import XCTest

/// The Swift rig must place every joint exactly where content/src/rig3d.js
/// does — the same maths the content tests check for planted feet and
/// nothing through the floor. `rigGoldenSamples` is generated by that file.
@MainActor
final class RigEngineTests: XCTestCase {
    func testMatchesTheContentPipelinesJointPositions() {
        XCTAssertFalse(rigGoldenSamples.isEmpty)
        for sample in rigGoldenSamples {
            guard let pattern = posePatternsBySlug[sample.pattern] else {
                XCTFail("unknown pattern \(sample.pattern)")
                continue
            }
            let playback = RigPlaybackCache.playback(for: pattern)
            let s = sample.time == true ? playback.frame(atTime: sample.t, loop: playback.loopSeconds) : playback.frame(at: sample.t)
            let points = [s.pelvis, s.head, s.L.ankle, s.R.toe, s.L.wrist, s.R.elbow, s.L.knee].flatMap { [$0.x, $0.y, $0.z] }
            for (index, (swift, js)) in zip(points, sample.points).enumerated() {
                XCTAssertEqual(swift, js, accuracy: 0.05, "\(sample.pattern) t=\(sample.t) value \(index)")
            }
            if let jsBall = sample.ball {
                guard let ball = s.ball else { XCTFail("\(sample.pattern) t=\(sample.t): Swift lost the ball"); continue }
                for (swift, js) in zip([ball.x, ball.y, ball.z], jsBall) { XCTAssertEqual(swift, js, accuracy: 0.05, "\(sample.pattern) ball") }
            } else {
                XCTAssertNil(s.ball, "\(sample.pattern) t=\(sample.t): ball should be out of play")
            }
        }
    }

    func testEveryCatalogueItemAnimatesARealPattern() {
        let catalogue = CatalogueLoader.load(from: AppConfig.packsDirectory())
        for item in catalogue.itemsBySlug.values {
            XCTAssertNotNil(item.posePattern, "\(item.slug) → \(item.startPose)")
        }
    }

    func testTheAppKnowsEveryItemsPatternEvenFromOldPacks() {
        XCTAssertGreaterThan(posePatternForItem.count, 900)
        for (item, name) in posePatternForItem { XCTAssertNotNil(posePatternsBySlug[name], "\(item) → \(name)") }
        for (old, name) in legacyPosePatterns { XCTAssertNotNil(posePatternsBySlug[name], "\(old) → \(name)") }
    }

    func testEveryPatternDrawsWithoutDegenerateShapes() {
        for pattern in posePatterns {
            let playback = RigPlaybackCache.playback(for: pattern)
            for n in 0..<6 {
                let shapes = RigShapes.shapes(playback.frame(at: Double(n) / 6), playback: playback, glow: ["chest": 1, "thighFront": 1], palette: .forScheme(.light))
                XCTAssertFalse(shapes.isEmpty, pattern.id)
                for shape in shapes {
                    for p in shape.points { XCTAssertTrue(p.x.isFinite && p.y.isFinite, "\(pattern.id) has a non-finite point") }
                }
            }
        }
    }
}
