/** Item slug → pose pattern slug: road cycling, mountain biking, BMX. */
export const BIKE_POSES = {
  'cycling-threshold-intervals': 'road-ride',
  'cycling-standing-sprints': 'standing-sprint',
  'cycling-hill-climb-repeats': 'seated-climb',
  'cycling-high-cadence-spin-ups': 'high-cadence-spin',
  'cycling-single-leg-pedaling': 'single-leg-pedaling',
  'cycling-endurance-ride': 'road-ride',
  'cycling-standing-climb-bursts': 'standing-climb',
  'mountain-biking-attack-position-drill': 'mtb-attack-descent',
  'mountain-biking-switchback-cornering': 'mtb-switchback',
  'mountain-biking-trackstand-balance': 'mtb-trackstand',
  'mountain-biking-climbing-intervals-mtb': 'seated-climb-low',
  'mountain-biking-pacing-race-loop': 'ride-loop',
  'mountain-biking-wheel-lift-drill': 'mtb-wheel-lift',
  'mountain-biking-long-trail-ride': 'road-ride',
  'bmx-gate-start-reaction': 'bmx-gate-start',
  'bmx-pump-track-laps': 'bmx-pump-track',
  'bmx-manual-drill': 'bmx-manual',
  'bmx-straight-sprints': 'bmx-sprint',
  'bmx-jump-absorb-landing': 'bmx-jump',
  'bmx-bmx-leg-power-jumps': 'box-jump',
  'bmx-berm-cornering': 'bmx-berm',
};
