/** Item slug → pose pattern slug: wrestling, judo, fencing. */
export const COMBAT_POSES = {
  'wrestling-stance-and-motion': 'wrestling-motion',
  'wrestling-penetration-step-shots': 'wrestling-pen-step',
  'wrestling-sprawl-reaction': 'wrestling-sprawl',
  'wrestling-hand-fighting-ties': 'wrestling-hand-fighting',
  'wrestling-towel-grip-hangs': 'towel-hang',
  'wrestling-bridge-and-turn': 'wrestling-bridge-turn',
  'wrestling-stand-up-from-bottom': 'wrestling-stand-up',
  'wrestling-shark-bait-scrambles': 'wrestling-hand-fighting',
  'wrestling-double-leg-finish': 'wrestling-double-leg',
  'wrestling-hip-heist-series': 'hip-heist',
  'wrestling-mat-returns': 'wrestling-mat-return',
  'wrestling-sprawl-and-shoot-intervals': 'wrestling-sprawl-and-shoot',
  'judo-ukemi-breakfalls': 'judo-breakfall',
  'judo-uchikomi-entries': 'judo-uchikomi',
  'judo-kuzushi-pull-drill': 'judo-kuzushi',
  'judo-gi-grip-pull-ups': 'towel-pull-up',
  'judo-newaza-transitions': 'judo-newaza',
  'judo-band-throw-rotations': 'band-throw-rotation',
  'judo-randori-intervals': 'judo-grip-fight',
  'fencing-advance-retreat-ladder': 'fence-ladder',
  'fencing-lunge-to-target': 'fence-lunge-target',
  'fencing-reaction-light-drill': 'fence-reaction',
  'fencing-point-control-circles': 'fence-point-circles',
  'fencing-fleche-starts': 'fence-fleche',
  'fencing-mirror-distance-game': 'fence-mirror-distance',
  'fencing-split-squat-endurance': 'fence-lunge-pulse',
  'fencing-feint-disengage-drill': 'fence-feint-disengage',
  'fencing-bout-footwork-intervals': 'fence-footwork-loop',
  'fencing-parry-riposte-reps': 'fence-parry-riposte',
  'fencing-lateral-bound-legs': 'fence-bound-lunge',
  'fencing-hip-mobility-flow': 'fence-hip-flow',
};
