/** Item slug → pose pattern slug: goalball, orienteering, triathlon, duathlon, para-track extras. */
export const ENDURANCE_POSES = {
  'goalball-full-extension-block': 'goalball-block',
  'goalball-sound-tracking-reps': 'goalball-sound-tracking',
  'goalball-spin-throw-power': 'goalball-spin-throw',
  'goalball-lateral-coverage-slides': 'goalball-slide',
  'goalball-core-extension-holds': 'side-plank',
  'goalball-orientation-return': 'goalball-orientation',
  'goalball-med-ball-rotational-throws': 'rotational-throw',
  'para-track-seated-med-ball-chest-pass': 'seated-chest-pass',
  'para-track-band-pull-rows-for-pushers': 'band-row',
  'orienteering-trail-hill-intervals': 'hill-run-up',
  'orienteering-uneven-ground-hops': 'single-leg-hops-directions',
  'orienteering-map-and-run-intervals': 'map-run',
  'orienteering-single-leg-balance-reach': 'star-excursion',
  'orienteering-long-easy-trail-run': 'jog',
  'orienteering-downhill-footwork': 'hill-run-down',
  'orienteering-control-punch-sprints': 'control-punch',
  'triathlon-brick-bike-to-run': 'bike-to-run',
  'triathlon-t1-transition-practice': 'transition-t1',
  'triathlon-open-water-sighting': 'swim-sighting-freestyle',
  'triathlon-aerobic-swim-set': 'swim-freestyle',
  'triathlon-steady-state-ride': 'road-ride',
  'triathlon-tempo-run-off-bike': 'tempo-run',
  'triathlon-duathlon-run-bike-brick': 'run-to-bike',
  'triathlon-duathlon-bike-run-brick': 'bike-to-run',
  'triathlon-duathlon-transition-rehearsal': 'bike-to-run',
  'triathlon-duathlon-negative-split-run': 'tempo-run',
  'triathlon-duathlon-run-form-strides': 'sprint',
  'triathlon-duathlon-bike-cadence-drill': 'high-cadence-spin',
  'triathlon-duathlon-calf-raise-durability': 'calf-raise-step',
};
