/** Item slug → pose pattern slug (general exercises, conditioning and mobility). */
export const EXERCISE_POSES = {
  'acceleration-wall-drill': 'acceleration-wall-drill',
  'acceleration-march': 'march',
  'sled-push': 'sled-push',
  'flying-sprint': 'sprint',
  'lateral-shuffle-cone-drill': 'lateral-shuffle',
  '5-10-5-shuttle': 'shuttle-turn',
  'lateral-bound': 'skater-bound',
  'deceleration-drop-stick': 'deceleration-stop',
  'countermovement-jump': 'vertical-jump',
  'weighted-jump-squat': 'jump-squat-dumbbells',
  'broad-jump': 'broad-jump',
  'rotational-step-through-throw': 'rotational-throw',
  'med-ball-rotational-throw': 'rotational-throw-wall',
  'explosive-wall-reach-jump': 'vertical-jump-wall',
  'med-ball-overhead-throw': 'overhead-throw-medball',
  'pogo-hop': 'pogo',
  'trap-bar-deadlift': 'deadlift-trapbar',
  'goblet-squat': 'goblet-squat',
  'barbell-back-squat': 'back-squat',
  'bulgarian-split-squat': 'bulgarian-split-squat',
  'split-squat': 'split-squat',
  'nordic-hamstring-curl': 'nordic-curl',
  'bodyweight-squat': 'squat-bodyweight',
  'push-up': 'push-up',
  'bench-press': 'bench-press',
  'incline-push-up': 'incline-push-up',
  'pull-up': 'pull-up',
  'band-assisted-pull-up': 'pull-up-band',
  'inverted-row': 'inverted-row',
  'prone-y-t-w-raise': 'prone-ytw',
  'band-pull-apart': 'band-pull-apart',
  'plank-shoulder-tap': 'plank-shoulder-tap',
  'pallof-press': 'pallof-press',
  'bear-crawl-hold': 'bear-hold',
  'farmers-carry': 'farmers-carry',
  'continuous-easy-run': 'jog',
  'hill-sprint-repeats': 'acceleration-start',
  'shuttle-repeat-sprints': 'shuttle-turn',
  'tempo-run': 'jog',
  'single-leg-balance-reach': 'star-excursion',
  'single-leg-rdl': 'single-leg-rdl',
  '90-90-hip-switch': 'hip-90-90',
  'mobility-flow-series': 'worlds-greatest-stretch',
  'scapular-wall-slide': 'wall-slide',
  'single-leg-ankle-hop': 'single-leg-pogo',
  'drop-landing-stick': 'drop-landing',
  'shadow-cutting-drill': 'cut-45',
  'in-place-suicide-sprints': 'shuttle-turn',
};

/** exercisesExtra.js */
Object.assign(EXERCISE_POSES, {
  'a-skip': 'a-skip', 'b-skip': 'b-skip', 'straight-leg-bound': 'bound', 'falling-start': 'falling-start',
  'sprint-from-push-up-start': 'burpee', 'resisted-band-sprint': 'acceleration-start', 'wicket-runs': 'wicket-runs', 'build-up-strides': 'sprint',
  'hill-bounds': 'bound', 't-drill': 'lateral-shuffle', 'l-drill': 'cut-45', 'pro-agility-plant-hold': 'deceleration-stop',
  'reactive-mirror-drill': 'lateral-shuffle', 'crossover-run-drill': 'crossover-run', 'backpedal-to-sprint': 'backpedal', 'eccentric-step-down': 'step-down',
  'box-jump': 'box-jump', 'depth-jump': 'depth-jump', 'tuck-jump': 'tuck-jump', 'hurdle-hops': 'hurdle-hops', 'skater-hops': 'skater-bound',
  'single-leg-hop-and-hold': 'single-leg-hop-stick', 'split-squat-jump': 'split-squat-jump', 'lateral-line-hops': 'lateral-line-hops',
  'jump-rope-intervals': 'jump-rope', 'broad-jump-to-sprint': 'broad-jump', 'med-ball-scoop-toss': 'rotational-scoop-wall', 'med-ball-shotput-throw': 'shot-put-throw-wall',
  'med-ball-slam': 'medball-slam', 'med-ball-chest-pass': 'chest-pass-wall', 'band-woodchop': 'woodchop-band', 'landmine-rotation': 'landmine-rotation',
  'barbell-front-squat': 'front-squat', 'romanian-deadlift': 'rdl', 'hip-thrust': 'hip-thrust', 'step-up': 'step-up-dumbbells', 'reverse-lunge': 'reverse-lunge-dumbbells',
  'lateral-lunge': 'lateral-lunge', 'cossack-squat': 'cossack-squat', 'wall-sit': 'wall-sit', 'spanish-squat': 'spanish-squat',
  'sissy-squat-assisted': 'sissy-squat', 'hamstring-slider-curl': 'hamstring-slider-curl', 'leg-curl-machine': 'prone-leg-curl',
  'kettlebell-swing': 'kettlebell-swing', 'single-leg-glute-bridge': 'single-leg-glute-bridge', 'dumbbell-bench-press': 'dumbbell-bench-press',
  'overhead-press-dumbbell': 'overhead-press-dumbbells', 'landmine-press': 'landmine-press', 'dips-parallel': 'bench-dip', 'pike-push-up': 'pike-push-up',
  'plyo-push-up': 'plyo-push-up', 'tempo-push-up': 'push-up', 'dumbbell-row': 'dumbbell-row', 'lat-pulldown': 'lat-pulldown', 'chin-up': 'pull-up',
  'seated-cable-row': 'seated-cable-row', 'face-pull': 'face-pull-band', 'towel-row': 'inverted-row', 'scap-pull-up': 'scapular-pull-up',
  'band-external-rotation': 'band-external-rotation', 'sleeper-stretch': 'sleeper-stretch', 'serratus-wall-slide': 'wall-slide', 'prone-i-raise': 'prone-ytw',
  'dumbbell-curl': 'biceps-curl', 'triceps-extension-band': 'triceps-pressdown', 'dead-hang': 'dead-hang', 'suitcase-carry': 'suitcase-carry-kettlebell',
  'overhead-carry': 'overhead-carry-single', 'plate-pinch': 'plate-pinch-hold', 'wrist-roller': 'wrist-roller', 'band-wrist-extension': 'wrist-curl-band',
  'dead-bug': 'dead-bug', 'bird-dog': 'bird-dog', 'side-plank': 'side-plank', 'hollow-hold': 'hollow-hold', 'ab-wheel-rollout': 'ab-rollout',
  'half-kneeling-chop': 'half-kneeling-lift', 'hanging-knee-raise': 'hanging-knee-raise', 'stir-the-pot': 'plank', 'back-extension': 'back-extension',
  'superman-hold': 'superman', 'copenhagen-plank': 'copenhagen-plank', 'adductor-squeeze': 'adductor-squeeze', 'tibialis-raise': 'tibialis-raise',
  'standing-calf-raise': 'calf-raise-step-straight', 'bent-knee-calf-raise': 'seated-calf-raise', 'ankle-alphabet': 'breathing-seated', 'short-foot-drill': 'single-leg-balance',
  'towel-toe-curls': 'breathing-seated', 'single-leg-balance-eyes-closed': 'single-leg-balance', 'star-excursion-reach': 'star-excursion',
  'lateral-band-walk': 'lateral-band-walk', 'clamshell': 'clamshell', 'reverse-nordic': 'reverse-nordic', 'neck-isometrics': 'neck-isometric',
  'band-neck-extension': 'neck-isometric', 'chin-tuck': 'chin-tuck', 'worlds-greatest-stretch': 'worlds-greatest-stretch', 'couch-stretch': 'couch-stretch',
  'deep-squat-hold': 'squat-hold', 'pigeon-stretch': 'pigeon-stretch', 'hamstring-floss': 'hamstring-floss-band', 'thoracic-open-book': 'open-book',
  'cat-camel': 'cat-camel', 'ankle-knee-to-wall': 'knee-to-wall', 'foam-roll-quads-calves': 'foam-roll', 'hip-circles-standing': 'hip-circles',
  'shoulder-dislocates-band': 'shoulder-pass-through', 'bike-intervals': 'cycling', 'burpee': 'burpee', 'mountain-climbers': 'mountain-climber',
  '30-15-intermittent-run': 'jog', 'fartlek-run': 'jog', 'sled-drag-backward': 'sled-drag', 'battle-rope-waves': 'battle-ropes', 'stair-runs': 'stair-runs',
  'rowing-machine-intervals': 'rowing-erg', 'hang-power-clean': 'hang-clean', 'clean-pull-dumbbell': 'high-pull-dumbbells', 'push-press': 'push-press',
  'barbell-bent-over-row': 'bent-over-row', 'barbell-deadlift': 'deadlift', 'barbell-overhead-squat-pvc': 'overhead-squat-pvc', 'lateral-box-jump': 'lateral-box-jump',
  'single-leg-box-jump': 'single-leg-box-jump', 'triple-broad-jump': 'broad-jump', 'medball-overhead-backward-toss': 'backward-overhead-toss',
  'medball-side-toss-lateral-step': 'rotational-throw-wall', 'dumbbell-snatch-single-arm': 'dumbbell-snatch', 'repeat-shuttle-10m': 'shuttle-turn',
  'tempo-200s': 'jog', 'long-easy-run': 'jog', 'box-step-over-conditioning': 'step-up', 'goblet-lateral-squat': 'goblet-lateral-squat',
  'split-squat-bottom-hold': 'split-squat', 'kickstand-rdl': 'single-leg-rdl', 'inverted-row-feet-elevated': 'inverted-row', 'push-up-plus': 'push-up',
  'bear-crawl-forward': 'bear-crawl', 'turkish-get-up': 'turkish-get-up', 'pallof-hold-split-stance': 'pallof-press', 'farmers-march': 'farmers-march',
  'nordic-assisted-band': 'nordic-curl', 'hip-airplane': 'hip-airplane', 'lateral-hop-to-stick': 'skater-bound', 'drop-squat': 'squat-bodyweight',
  'sprint-arm-drill': 'seated-arm-swing', 'curtsy-lunge': 'curtsy-lunge', 'dumbbell-incline-press': 'incline-dumbbell-press',
  'reverse-fly-dumbbell': 'reverse-fly', 'breathing-90-90': 'breathing-90-90-wall',
});
