/** Item slug → pose pattern slug: weightlifting, powerlifting, CrossFit-style conditioning. */
export const STRENGTH_SPORT_POSES = {
  'weightlifting-pvc-snatch-progression': 'pvc-snatch-progression',
  'weightlifting-overhead-squat-stability': 'overhead-squat',
  'weightlifting-hang-power-clean-technique': 'hang-clean',
  'weightlifting-front-squat-technique': 'front-squat',
  'weightlifting-snatch-grip-pull': 'snatch-grip-pull',
  'weightlifting-push-press-drive': 'push-press',
  'weightlifting-mobility-complex': 'stick-mobility-complex',
  'powerlifting-bracing-practice': 'stand-breathe',
  'powerlifting-competition-squat-technique': 'back-squat',
  'powerlifting-bench-press-technique': 'bench-press',
  'powerlifting-deadlift-technique': 'deadlift',
  'powerlifting-paused-squat': 'goblet-squat-pause',
  'powerlifting-dumbbell-floor-press': 'floor-press',
  'powerlifting-romanian-deadlift': 'rdl-dumbbells',
  'crossfit-style-conditioning-movement-quality-screen': 'movement-screen',
  'crossfit-style-conditioning-emom-bodyweight': 'emom-squat-pushup-situp',
  'crossfit-style-conditioning-kettlebell-swing-intervals': 'kettlebell-swing',
  'crossfit-style-conditioning-farmer-carry-medley': 'farmers-carry',
  'crossfit-style-conditioning-row-burpee-chipper': 'burpee',
  'crossfit-style-conditioning-goblet-squat-strength': 'goblet-squat',
  'crossfit-style-conditioning-pull-up-progression': 'pull-up',
};
