/**
 * Sport drills — track and field, cross country, unified and para track,
 * orienteering, triathlon, duathlon, cycling, mountain biking, BMX, rowing,
 * swimming and diving, adapted swimming, water polo. Written from standard
 * coaching practice for each sport (the drills coaches and national
 * federations teach): setup, execution, the cues a coach shouts, and the
 * mistake that ruins each one.
 *
 * Bikes, rowing machines, racing chairs and pools have no equipment tag of
 * their own: an athlete in these sports already has the sport's own gear, so
 * those drills list only the extra kit they need (often `none`).
 */

import { contacts, dist, reps, sportDrills, time } from '../drillKit.js';

const RUN_LEGS = { 'gluteus-maximus': 0.6, 'biceps-femoris': 0.6, 'gastrocnemius': 0.5, 'soleus': 0.5 };
const SWIM = { 'latissimus-dorsi': 0.7, 'triceps-brachii': 0.5, 'deltoid-posterior': 0.5, 'rectus-abdominis': 0.4 };
const ROW = { 'latissimus-dorsi': 0.6, 'gluteus-maximus': 0.6, 'vastus-lateralis': 0.6, 'erector-spinae': 0.5, 'rhomboids': 0.5 };
const BIKE = { 'vastus-lateralis': 0.7, 'rectus-femoris': 0.6, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.4 };

const TRACK = sportDrills('track-and-field', [
  {
    slug: 'a-skip-b-skip-series', name: 'A-Skips and B-Skips', skills: ['max-velocity-mechanics'],
    qualities: { 'max-velocity': 0.7, 'reactive-strength': 0.6, 'ankle-stiffness': 0.5 },
    muscles: { 'iliopsoas': 0.6, 'gastrocnemius': 0.6, 'biceps-femoris': 0.5 },
    equipment: ['none'], surface: 'track',
    setup: ["20 metres of straight track after a jog warm-up."],
    execution: ["A-skip: drive one knee to hip height with the toe pulled up, strike the ground under the hip, skip rhythmically for 20 m.", "B-skip: same, but extend the lower leg out and paw it back down under the hip like a pulling claw."],
    cues: ["Toe up, knee up, heel up", "Hit the ground under your hips"],
    mistakes: ["Reaching the foot out in front and landing on the heel, which brakes every step."],
    defaultDose: dist(4, 20), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'flying-30s', name: 'Flying 30s', skills: ['max-velocity-mechanics'],
    qualities: { 'max-velocity': 1.0, 'reactive-strength': 0.6, 'acceleration': 0.4 },
    muscles: RUN_LEGS, equipment: ['cones'], surface: 'track',
    setup: ["Cones at 0, 20 and 50 m: a 20 m build-up zone then a 30 m fly zone."],
    execution: ["Build smoothly through the first 20 m and hit top speed as you cross the second cone.", "Hold top speed, relaxed, for 30 m, then decelerate gradually. Walk back for full recovery."],
    cues: ["Tall hips, relaxed face", "Fast, not forced"],
    mistakes: ["Straining with a clenched jaw and shoulders, which makes you slower, not faster."],
    defaultDose: reps(4, 1), restSeconds: 240, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'three-point-starts', name: 'Three-Point Acceleration Starts', skills: ['block-start'],
    qualities: { 'acceleration': 1.0, 'horizontal-power': 0.7, 'lower-body-strength': 0.4 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['cones'], surface: 'track',
    setup: ["A start line and a cone at 20 m; practise before moving into blocks."],
    execution: ["Set up with one hand down, front knee bent, weight forward.", "Push hard off both feet on your own signal and drive out with a steady forward lean for 20 m, rising gradually."],
    cues: ["Push, don't pop up", "Big arm swing out of the start"],
    mistakes: ["Standing upright in the first three steps, which throws away the acceleration."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'block-clearance-10m', name: 'Block Clearance to 10 m', skills: ['block-start'],
    qualities: { 'acceleration': 1.0, 'horizontal-power': 0.8 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-medialis': 0.6, 'gastrocnemius': 0.6 },
    equipment: ['blocks'], prop: 'blocks', surface: 'track',
    setup: ["Blocks set with the front pedal about two foot-lengths behind the line, back pedal about one more."],
    execution: ["On your marks, set with hips just above shoulders, then react to the clap or gun.", "Drive both feet into the pedals, punch the back knee forward low, and cover 10 m with low, powerful steps."],
    cues: ["Push both pedals, not just one", "Shin angles low for the first steps"],
    mistakes: ["Setting the hips too high, which makes the first step a jump up rather than a push forward."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'curve-sprints', name: 'Curve Running 60s', skills: ['curve-running'],
    qualities: { 'max-velocity': 0.8, 'single-leg-stability': 0.5, 'ankle-stiffness': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'peroneals': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['none'], surface: 'track',
    setup: ["Start at the beginning of the bend in lane 3 or 4."],
    execution: ["Sprint 60 m around the curve at 90–95% effort, running the inside of your lane.", "Lean the whole body in from the ankles; the right arm swings slightly across the body."],
    cues: ["Lean from the ankles, not the waist", "Hug the inside line"],
    mistakes: ["Drifting to the outside of the lane, which adds distance to every step."],
    defaultDose: reps(4, 1), restSeconds: 180, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'hurdle-walkovers', name: 'Hurdle Walkovers', skills: ['hurdle-clearance'],
    qualities: { 'hip-mobility': 0.9, 'single-leg-stability': 0.6 },
    muscles: { 'iliopsoas': 0.6, 'adductors': 0.6, 'gluteus-medius': 0.5 },
    equipment: ['hurdle'], prop: 'hurdle', surface: 'track',
    setup: ["Six low hurdles in a line, about one metre apart."],
    execution: ["Walk down the line stepping over each hurdle with the lead leg, then the trail leg, staying tall.", "Trail leg lifts out to the side with the knee high and the foot turned out, pulling through to the front."],
    cues: ["Knee up, toe up", "Stay tall — don't lean back"],
    mistakes: ["Dropping the trail knee so the foot drags over the bar."],
    defaultDose: reps(3, 6), restSeconds: 30, startPose: 'mobility-flow', endPose: 'lunge',
  },
  {
    slug: 'three-step-hurdle-rhythm', name: 'Three-Step Hurdle Rhythm', skills: ['hurdle-clearance', 'approach-consistency'],
    qualities: { 'max-velocity': 0.7, 'hip-mobility': 0.6, 'reactive-strength': 0.6 },
    muscles: { 'iliopsoas': 0.6, 'biceps-femoris': 0.6, 'adductors': 0.4 },
    equipment: ['hurdle', 'cones'], prop: 'hurdle', surface: 'track', minAge: 14,
    setup: ["Three to five hurdles at a lowered height and a shortened spacing so three steps between them feels easy."],
    execution: ["Accelerate to the first hurdle, attack it with the lead leg, and take exactly three steps between each hurdle.", "Move the spacing out and the height up only when the rhythm is automatic."],
    cues: ["Attack the hurdle, don't jump it", "One-two-three-over"],
    mistakes: ["Floating high over the hurdle, which kills speed between barriers."],
    defaultDose: reps(5, 1), restSeconds: 120, startPose: 'sprint-cycle', endPose: 'bound',
  },
  {
    slug: 'long-jump-short-approach', name: 'Short-Approach Long Jump', skills: ['jump-takeoff-power', 'approach-consistency'],
    qualities: { 'horizontal-power': 0.9, 'reactive-strength': 0.7, 'landing-mechanics': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'rectus-femoris': 0.6, 'gastrocnemius': 0.6 },
    equipment: ['none'], surface: 'track',
    setup: ["Mark a six-stride approach to the board or a take-off line on a sand pit."],
    execution: ["Run the six strides, keep the last two quick and flat, and drive the take-off leg down into the board.", "Drive the free knee up, hold a tall position in the air, and bring the feet forward to land."],
    cues: ["Tall at take-off", "Hit the board, don't reach for it"],
    mistakes: ["Stuttering or over-striding the last steps to hit the board."],
    defaultDose: contacts(3, 4), restSeconds: 120, startPose: 'bound', endPose: 'landing',
  },
  {
    slug: 'approach-run-check-marks', name: 'Approach Run With Check Marks', skills: ['approach-consistency'],
    qualities: { 'acceleration': 0.7, 'max-velocity': 0.6 },
    muscles: RUN_LEGS, equipment: ['cones'], surface: 'track',
    setup: ["A coach or partner watches the 6th-stride and last-stride marks on your full jump approach."],
    execution: ["Run through your full approach without jumping, hitting the same start mark every time.", "Partner notes where the 6th step and the last step land; adjust the start mark until they are consistent."],
    cues: ["Same start every time", "Accelerate smoothly to the board"],
    mistakes: ["Changing effort run to run so the steps never line up."],
    defaultDose: reps(6, 1), restSeconds: 90, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'standing-throws', name: 'Standing Shot/Med-Ball Throws', skills: ['throwing-release-speed'],
    qualities: { 'rotational-power': 0.8, 'overhead-power': 0.7, 'lower-body-strength': 0.4 },
    muscles: { 'obliques-external': 0.6, 'triceps-brachii': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['med-ball'], prop: 'implement-throw', surface: 'field',
    setup: ["Stand side-on in the throwing position with a medicine ball or a light shot."],
    execution: ["Bend the back leg, turn the hips toward the throw, then the chest, and punch the implement up and out at about 40 degrees.", "Finish with the arm long and the fingers flicking through."],
    cues: ["Legs, hips, chest, arm", "Punch it high"],
    mistakes: ["Throwing with the arm only while the hips stay square."],
    defaultDose: reps(3, 6, 'light implement'), restSeconds: 90, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'relay-exchange-zones', name: 'Relay Exchange Zone Practice', skills: ['relay-exchange'],
    qualities: { 'acceleration': 0.8, 'max-velocity': 0.6 },
    muscles: RUN_LEGS, equipment: ['partner', 'cones'], surface: 'track',
    setup: ["A 30 m exchange zone marked with cones and a go-mark for the outgoing runner."],
    execution: ["Outgoing runner starts sprinting when the incoming runner hits the go-mark.", "Incoming runner calls \"hand\" and the pass is made at full speed in the second half of the zone."],
    cues: ["Go on the mark, not the call", "Hand back, palm steady"],
    mistakes: ["The outgoing runner looking back or slowing down during the pass."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'pace-400-splits', name: '400 m Pace Splits', skills: ['pacing-strategy'],
    qualities: { 'anaerobic-capacity': 0.8, 'aerobic-base': 0.6 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'track',
    setup: ["A watch and your target race pace per 200 m."],
    execution: ["Run 200 m at exact goal pace, walk 200 m.", "Hit the split within one second each time; the goal is feel, not speed."],
    cues: ["Even pace beats a fast start", "Check the split at the 100"],
    mistakes: ["Going out too fast and fading every rep."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'bounding-series', name: 'Bounding Series', skills: ['jump-takeoff-power'],
    qualities: { 'horizontal-power': 0.9, 'reactive-strength': 0.8 },
    muscles: { 'gluteus-maximus': 0.7, 'gastrocnemius': 0.6, 'rectus-femoris': 0.5 },
    equipment: ['none'], surface: 'track', minAge: 14,
    setup: ["30 m of grass or track."],
    execution: ["Bound from one leg to the other, driving the knee up and covering as much ground as possible per contact.", "Land on the ball of the foot under the hip and push off immediately."],
    cues: ["Hang in the air", "Quick off the ground"],
    mistakes: ["Landing flat-footed with a long ground contact."],
    defaultDose: contacts(3, 12), restSeconds: 120, startPose: 'bound', endPose: 'bound',
  },
]);

const XC = sportDrills('cross-country', [
  {
    slug: 'tempo-run', name: 'Tempo Run', skills: ['aerobic-threshold-pace'],
    qualities: { 'aerobic-base': 1.0, 'anaerobic-capacity': 0.4 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A 10-minute easy warm-up jog on a loop or trail."],
    execution: ["Run 15–20 minutes at comfortably hard: you can speak a few words, not a sentence.", "Cool down with 10 minutes easy."],
    cues: ["Comfortably hard, not racing", "Relax the shoulders"],
    mistakes: ["Turning the tempo into a race and finishing exhausted."],
    defaultDose: time(1, 1200), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'fartlek-30-90', name: 'Fartlek 90/90', skills: ['race-tactics', 'aerobic-threshold-pace'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A trail or park loop after a warm-up."],
    execution: ["Alternate 90 seconds hard (5K race effort) with 90 seconds easy running — never walking.", "Surge like you would to pass someone in a race."],
    cues: ["Keep running on the easy parts", "Surge with arms"],
    mistakes: ["Walking the recoveries, which turns it into a different workout."],
    defaultDose: reps(8, 1), restSeconds: 90, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'hill-repeats', name: 'Hill Repeats', skills: ['hill-running-economy'],
    qualities: { 'anaerobic-capacity': 0.8, 'lower-body-strength': 0.5, 'aerobic-base': 0.5 },
    muscles: { 'gluteus-maximus': 0.7, 'gastrocnemius': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A 60–90 second hill of moderate grade."],
    execution: ["Run up at a strong 5K effort with short steps and a slight forward lean.", "Jog back down easily as recovery."],
    cues: ["Short steps, strong arms", "Look up the hill, not at your feet"],
    mistakes: ["Over-striding uphill, which wastes energy."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'strides', name: 'Strides', skills: ['running-economy', 'finishing-kick'],
    qualities: { 'max-velocity': 0.6, 'reactive-strength': 0.5, 'aerobic-base': 0.3 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["100 m of flat grass or track after an easy run."],
    execution: ["Build smoothly to about 90% speed over 100 m, holding good form.", "Walk back for full recovery."],
    cues: ["Smooth and fast", "Quick feet, relaxed hands"],
    mistakes: ["Sprinting all-out so form breaks down."],
    defaultDose: reps(6, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'kick-finish-200s', name: 'Finishing-Kick 200s', skills: ['finishing-kick', 'race-tactics'],
    qualities: { 'anaerobic-capacity': 0.9, 'max-velocity': 0.6 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'track',
    setup: ["On a track after a threshold run or at the end of a steady run."],
    execution: ["Run 200 m, with the first 100 at race pace and the last 100 as a hard kick.", "Walk or jog 200 m between reps."],
    cues: ["Change gears at the 100", "Pump the arms to kick"],
    mistakes: ["Starting the kick too early and dying before the line."],
    defaultDose: reps(5, 1), restSeconds: 150, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'cadence-drill', name: 'Cadence Count Drill', skills: ['cadence', 'running-economy'],
    qualities: { 'reactive-strength': 0.6, 'aerobic-base': 0.5 },
    muscles: { 'gastrocnemius': 0.6, 'soleus': 0.6, 'iliopsoas': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["An easy run with a watch."],
    execution: ["Count right-foot strikes for 30 seconds and double it for your cadence.", "Run one minute trying to add 3–5 steps per minute with shorter, lighter steps, then return to normal."],
    cues: ["Light and quick", "Land under your hips"],
    mistakes: ["Over-striding, landing on the heel in front of your body."],
    defaultDose: reps(5, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'even-pace-mile-repeats', name: 'Even-Pace Mile Repeats', skills: ['pacing-discipline'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.5 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'track',
    setup: ["A track and your goal 5K pace per lap."],
    execution: ["Run a mile at goal 5K pace, checking every lap split.", "Jog 3 minutes between reps. Every lap should be within two seconds of the others."],
    cues: ["Lap splits, not feelings", "Negative-split the last rep"],
    mistakes: ["Running the first lap five seconds fast because you feel fresh."],
    defaultDose: reps(3, 1), restSeconds: 180, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'easy-recovery-run', name: 'Easy Recovery Run', skills: ['recovery-between-hard-days'],
    qualities: { 'aerobic-base': 0.8 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A soft surface — grass or trail — the day after a hard workout."],
    execution: ["Run 20–30 minutes at conversational pace; you should be able to talk in full sentences.", "Finish with light stretching."],
    cues: ["Easy means easy", "Talk test the whole way"],
    mistakes: ["Running recovery days too fast, which ruins the next hard day."],
    defaultDose: time(1, 1500), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'surge-and-settle', name: 'Surge-and-Settle Tempo', skills: ['race-tactics', 'pacing-discipline'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A loop course after a warm-up."],
    execution: ["Run tempo pace, and every third minute surge hard for 20 seconds as if breaking away from a pack.", "Settle straight back into tempo pace — don't slow below it."],
    cues: ["Surge, then settle", "Don't let the pace drop after"],
    mistakes: ["Slowing to a jog after each surge."],
    defaultDose: time(1, 1080), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'downhill-running', name: 'Controlled Downhill Running', skills: ['hill-running-economy'],
    qualities: { 'deceleration': 0.6, 'reactive-strength': 0.5, 'aerobic-base': 0.4 },
    muscles: { 'vastus-medialis': 0.6, 'rectus-femoris': 0.6, 'tibialis-anterior': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A gentle grassy downhill of 60–100 m."],
    execution: ["Run down with a slight forward lean, quick light steps, and arms a little wider for balance.", "Walk back up."],
    cues: ["Lean with the slope", "Quick feet, no braking"],
    mistakes: ["Leaning back and braking hard with each step."],
    defaultDose: reps(5, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'running-form-drills', name: 'Running Form Drill Circuit', skills: ['running-economy', 'cadence'],
    qualities: { 'reactive-strength': 0.6, 'ankle-stiffness': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'iliopsoas': 0.5, 'tibialis-anterior': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["20 m of flat ground."],
    execution: ["Ankling, high knees, butt kicks and straight-leg bounds, 20 m each.", "Jog back between drills."],
    cues: ["Stiff ankles, quick contacts", "Tall posture"],
    mistakes: ["Rushing drills sloppily instead of crisp and precise."],
    defaultDose: dist(4, 20), restSeconds: 30, startPose: 'pogo', endPose: 'sprint-cycle',
  },
  {
    slug: 'long-run', name: 'Weekly Long Run', skills: ['aerobic-threshold-pace', 'pacing-discipline'],
    qualities: { 'aerobic-base': 1.0 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A route about 25% of your weekly running volume."],
    execution: ["Run the whole distance at an easy, conversational effort.", "Carry water on hot days and walk briefly if needed."],
    cues: ["Slow enough to chat", "Finish feeling like you had more"],
    mistakes: ["Racing the long run."],
    defaultDose: time(1, 2700), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
]);

const UNIFIED_TRACK = sportDrills('unified-track', [
  {
    slug: 'partner-sprint-starts', name: 'Partner Sprint Starts', skills: ['sprint-technique'],
    qualities: { 'acceleration': 0.8, 'horizontal-power': 0.5 },
    muscles: RUN_LEGS, equipment: ['partner', 'cones'], surface: 'track',
    setup: ["Two partners side by side at a line with a cone 20 m away."],
    execution: ["One partner gives \"ready, set, go\"; both lean forward and sprint to the cone.", "Walk back together and swap who calls the start."],
    cues: ["Lean forward to start", "Pump your arms"],
    mistakes: ["Standing straight up at the start."],
    defaultDose: reps(5, 1), restSeconds: 90, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'arm-swing-drill', name: 'Seated or Standing Arm Swing', skills: ['sprint-technique'],
    qualities: { 'max-velocity': 0.5, 'shoulder-stability': 0.5 },
    muscles: { 'deltoid-anterior': 0.5, 'deltoid-posterior': 0.5, 'rectus-abdominis': 0.3 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["Sit tall or stand with elbows bent at about 90 degrees."],
    execution: ["Swing the arms from the shoulder: hand to cheek height in front, hand back past the hip.", "Speed up for 10 seconds, then slow down."],
    cues: ["Cheek to pocket", "Keep the shoulders down"],
    mistakes: ["Swinging the arms across the body."],
    defaultDose: time(3, 20), restSeconds: 30, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'standing-long-jump-practice', name: 'Standing Long Jump Practice', skills: ['jump-technique'],
    qualities: { 'horizontal-power': 0.8, 'landing-mechanics': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'rectus-femoris': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['none'], surface: 'track',
    setup: ["A sand pit or soft mat and a take-off line."],
    execution: ["Swing the arms back, bend the knees, then swing forward and jump as far as you can.", "Land on both feet with bent knees; a partner marks the distance."],
    cues: ["Swing and jump", "Land soft"],
    mistakes: ["Landing with straight legs."],
    defaultDose: contacts(3, 5), restSeconds: 60, startPose: 'broad-jump', endPose: 'landing',
  },
  {
    slug: 'softball-throw-practice', name: 'Softball Throw Practice', skills: ['throw-technique'],
    qualities: { 'overhead-power': 0.7, 'rotational-power': 0.6 },
    muscles: { 'latissimus-dorsi': 0.5, 'triceps-brachii': 0.5, 'obliques-external': 0.5 },
    equipment: ['ball'], prop: 'ball-round', surface: 'field',
    setup: ["A softball or tennis ball and a throwing line."],
    execution: ["Stand side-on, step toward the target with the opposite foot, and throw overhand.", "Follow through across the body."],
    cues: ["Step and throw", "Point at the target first"],
    mistakes: ["Throwing without stepping."],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'buddy-pacing-laps', name: 'Buddy Pacing Laps', skills: ['pacing'],
    qualities: { 'aerobic-base': 0.8 },
    muscles: RUN_LEGS, equipment: ['partner'], surface: 'track',
    setup: ["A partner and a lap of the track."],
    execution: ["Run or walk-run one lap side by side at a speed where you can both talk.", "Try to finish each lap in about the same time."],
    cues: ["Talk while you run", "Same speed start to finish"],
    mistakes: ["Starting fast and having to stop."],
    defaultDose: reps(3, 1), restSeconds: 120, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'hop-and-stick', name: 'Hop and Stick', skills: ['jump-technique'],
    qualities: { 'landing-mechanics': 0.8, 'single-leg-stability': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'vastus-medialis': 0.5, 'peroneals': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A flat spot; hold a partner's hand or a wall if needed."],
    execution: ["Hop forward a small distance on one foot and hold the landing for three seconds.", "Switch legs."],
    cues: ["Freeze on landing", "Knee over toes"],
    mistakes: ["Knee caving in on landing."],
    defaultDose: contacts(2, 6), restSeconds: 45, startPose: 'single-leg-balance', endPose: 'landing',
  },
  {
    slug: 'relay-handoff-walkthrough', name: 'Relay Hand-Off Walk-Through', skills: ['sprint-technique', 'pacing'],
    qualities: { 'acceleration': 0.6, 'reactive-strength': 0.4 },
    muscles: RUN_LEGS, equipment: ['partner'], surface: 'track',
    setup: ["Two partners and a baton (or any stick) in an exchange zone."],
    execution: ["Walk, then jog, the hand-off: incoming partner calls \"stick\", outgoing reaches back with an open hand.", "Build to running speed as the pass becomes easy."],
    cues: ["Call it loud", "Open hand, steady arm"],
    mistakes: ["Looking back and slowing down."],
    defaultDose: reps(6, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
]);

const PARA_TRACK = sportDrills('para-track', [
  {
    slug: 'racing-chair-push-starts', name: 'Racing-Chair Push Starts', skills: ['start-technique', 'upper-body-power'],
    qualities: { 'acceleration': 0.8, 'upper-body-push': 0.7, 'overhead-power': 0.4 },
    muscles: { 'triceps-brachii': 0.7, 'deltoid-anterior': 0.6, 'pectoralis-major': 0.6 },
    equipment: ['none'], surface: 'track',
    setup: ["In a racing chair on the start line; hands at the top of the push rims."],
    execution: ["Explode with short, fast pushes for the first 5–6 strokes, then lengthen each stroke.", "Drive for 20 m and coast to a stop."],
    cues: ["Short and fast, then long", "Chest low over the knees"],
    mistakes: ["Taking full-length strokes from a standstill, which wastes the first metres."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'push-rim-technique', name: 'Push-Rim Technique Laps', skills: ['technique-efficiency'],
    qualities: { 'aerobic-base': 0.6, 'upper-body-push': 0.5, 'shoulder-stability': 0.5 },
    muscles: { 'triceps-brachii': 0.6, 'deltoid-anterior': 0.5, 'latissimus-dorsi': 0.4 },
    equipment: ['none'], surface: 'track',
    setup: ["Racing chair on the track at easy effort."],
    execution: ["Focus on striking the push rim at the top and following through all the way to the bottom.", "Recover the hands in a smooth circle, not a jerky return."],
    cues: ["Hit, drive, release", "Smooth circular recovery"],
    mistakes: ["Short, choppy strokes that only use the top of the rim."],
    defaultDose: dist(4, 400), restSeconds: 90, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'guide-runner-tether-drills', name: 'Guide-Runner Tether Drills', skills: ['technique-efficiency', 'start-technique'],
    qualities: { 'acceleration': 0.6, 'max-velocity': 0.6 },
    muscles: RUN_LEGS, equipment: ['partner'], surface: 'track',
    setup: ["A visually impaired runner and a guide joined by a short tether at the hands."],
    execution: ["Practise matching arm swing and cadence, starting from walking to strides over 60 m.", "Add starts with the guide calling \"set\" and \"go\"."],
    cues: ["Match arms, match steps", "Guide talks early"],
    mistakes: ["The guide pulling on the tether instead of running in rhythm."],
    defaultDose: reps(6, 1), restSeconds: 90, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'seated-med-ball-chest-pass', name: 'Seated Med-Ball Chest Throws', skills: ['upper-body-power'],
    qualities: { 'upper-body-push': 0.8, 'overhead-power': 0.6 },
    muscles: { 'pectoralis-major': 0.7, 'triceps-brachii': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['med-ball', 'partner'], prop: 'ball-round', surface: 'anywhere',
    setup: ["Seated tall in your chair, a partner or a wall 3 m away."],
    execution: ["Hold a light medicine ball at the chest and throw it explosively to your partner.", "Catch, reset and repeat."],
    cues: ["Punch it out fast", "Sit tall, brace the trunk"],
    mistakes: ["Rounding the back as you throw."],
    defaultDose: reps(3, 8, 'light med ball'), restSeconds: 60, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'even-pace-intervals', name: 'Even-Pace Intervals', skills: ['pacing'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.5 },
    muscles: { 'triceps-brachii': 0.5, 'deltoid-anterior': 0.5, 'latissimus-dorsi': 0.4 },
    equipment: ['none'], surface: 'track',
    setup: ["A track and a target split per 200 m for your event."],
    execution: ["Cover 200 m at race pace, recover 2 minutes.", "Every rep within two seconds of the target."],
    cues: ["Same split every time", "Relax the shoulders"],
    mistakes: ["Going out too hard and fading."],
    defaultDose: reps(6, 1), restSeconds: 120, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'prosthetic-strides', name: 'Running-Blade Strides', skills: ['technique-efficiency', 'pacing'],
    qualities: { 'max-velocity': 0.6, 'single-leg-stability': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'gluteus-maximus': 0.5, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'track', minAge: 14,
    setup: ["On a running prosthesis on a straight, with your prosthetist's fitting approved."],
    execution: ["Build over 60 m to about 85% speed, focusing on equal stride length on both sides.", "Walk back for full recovery."],
    cues: ["Even rhythm left and right", "Hips tall"],
    mistakes: ["Overstriding on the sound side to compensate."],
    defaultDose: reps(5, 1), restSeconds: 90, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'band-pull-rows-for-pushers', name: 'Band Rows for Shoulder Balance', skills: ['upper-body-power', 'technique-efficiency'],
    qualities: { 'upper-body-pull': 0.8, 'shoulder-stability': 0.7 },
    muscles: { 'rhomboids': 0.7, 'trapezius-middle': 0.6, 'deltoid-posterior': 0.6 },
    equipment: ['band'], surface: 'anywhere',
    setup: ["A band anchored at chest height; seated or standing."],
    execution: ["Pull the band to the ribs, squeezing the shoulder blades together.", "Return slowly. Balances all the pushing work of racing."],
    cues: ["Squeeze the blades", "Slow on the way back"],
    mistakes: ["Shrugging the shoulders up toward the ears."],
    defaultDose: reps(3, 12, 'light band'), restSeconds: 45, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
]);

const ORIENTEERING = sportDrills('orienteering', [
  {
    slug: 'trail-hill-intervals', name: 'Trail Hill Intervals', skills: ['trail-running-economy', 'endurance'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A forest trail with rolling climbs."],
    execution: ["Run hard up every climb, easy on the flats and descents, for the whole loop.", "Keep the eyes scanning ahead as you would in a race."],
    cues: ["Short steps on climbs", "Eyes ahead"],
    mistakes: ["Staring at your feet instead of reading the terrain."],
    defaultDose: time(1, 1500), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'uneven-ground-hops', name: 'Uneven-Ground Ankle Hops', skills: ['uneven-terrain-stability'],
    qualities: { 'ankle-stiffness': 0.8, 'single-leg-stability': 0.6 },
    muscles: { 'peroneals': 0.6, 'gastrocnemius': 0.5, 'tibialis-anterior': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A grassy area with small bumps."],
    execution: ["Hop on one foot in different directions over the uneven ground, landing softly each time.", "Switch legs."],
    cues: ["Quiet landings", "Ankle strong, not floppy"],
    mistakes: ["Landing with the ankle rolled out."],
    defaultDose: contacts(3, 10), restSeconds: 45, startPose: 'pogo', endPose: 'single-leg-balance',
  },
  {
    slug: 'map-and-run-intervals', name: 'Map-Reading Run Intervals', skills: ['pacing-under-navigation-load'],
    qualities: { 'aerobic-base': 0.7, 'anaerobic-capacity': 0.5 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A park map with 8–10 marked controls."],
    execution: ["Run between controls at race effort, reading the map while jogging.", "Slow down only at the control, not while running between them."],
    cues: ["Plan the next leg as you run", "Thumb on your position"],
    mistakes: ["Stopping dead to read the map every minute."],
    defaultDose: time(1, 1500), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'single-leg-balance-reach', name: 'Single-Leg Balance Reach', skills: ['uneven-terrain-stability'],
    qualities: { 'single-leg-stability': 0.9, 'ankle-stiffness': 0.5 },
    muscles: { 'gluteus-medius': 0.7, 'peroneals': 0.5, 'foot-intrinsics': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["Stand on one leg on flat ground."],
    execution: ["Reach the free foot forward, to the side and behind, touching lightly each time.", "Keep the standing knee over the toes."],
    cues: ["Hip level", "Soft knee"],
    mistakes: ["Letting the standing knee cave inward."],
    defaultDose: reps(3, 8), restSeconds: 30, startPose: 'single-leg-balance', endPose: 'single-leg-rdl',
  },
  {
    slug: 'long-easy-trail-run', name: 'Long Easy Trail Run', skills: ['endurance', 'trail-running-economy'],
    qualities: { 'aerobic-base': 1.0 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A varied trail route."],
    execution: ["Run 40–60 minutes at conversational pace over mixed terrain.", "Walk steep climbs briskly."],
    cues: ["Easy talk pace", "Light feet on roots and rocks"],
    mistakes: ["Pushing the pace on every climb."],
    defaultDose: time(1, 2700), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'downhill-footwork', name: 'Technical Downhill Footwork', skills: ['uneven-terrain-stability', 'trail-running-economy'],
    qualities: { 'deceleration': 0.6, 'reactive-strength': 0.6, 'ankle-stiffness': 0.5 },
    muscles: { 'vastus-medialis': 0.6, 'tibialis-anterior': 0.5, 'peroneals': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A rocky or rooty downhill section of trail."],
    execution: ["Run down with quick, short steps, choosing each foot placement a few steps ahead.", "Walk back up."],
    cues: ["Look three steps ahead", "Quick feet"],
    mistakes: ["Long braking strides."],
    defaultDose: reps(5, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'control-punch-sprints', name: 'Control-Punch Sprints', skills: ['pacing-under-navigation-load'],
    qualities: { 'acceleration': 0.6, 'deceleration': 0.6, 'repeat-sprint': 0.6 },
    muscles: RUN_LEGS, equipment: ['cones'], surface: 'anywhere',
    setup: ["Cones as controls 30–50 m apart in a zig-zag."],
    execution: ["Sprint to each control, decelerate, touch it as if punching, and accelerate away.", "Complete the whole course without stopping."],
    cues: ["Slow down late, speed up early", "Leave the control fast"],
    mistakes: ["Loitering at each control."],
    defaultDose: reps(3, 1), restSeconds: 120, startPose: 'deceleration-plant', endPose: 'sprint-cycle',
  },
]);

const TRIATHLON = sportDrills('triathlon', [
  {
    slug: 'brick-bike-to-run', name: 'Brick: Bike to Run', skills: ['bike-to-run-transition'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.4 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["Your bike and running shoes set up for a quick change."],
    execution: ["Ride 20 minutes at race effort, change quickly, and run 10 minutes at race pace.", "Focus on short, quick steps for the first minute off the bike."],
    cues: ["Quick cadence off the bike", "Settle, then build"],
    mistakes: ["Sprinting the first run minute and blowing up."],
    defaultDose: time(1, 1800), restSeconds: 0, startPose: 'squat', endPose: 'sprint-cycle',
  },
  {
    slug: 't1-transition-practice', name: 'T1 Transition Practice', skills: ['swim-to-bike-transition'],
    qualities: { 'acceleration': 0.5, 'aerobic-base': 0.5 },
    muscles: { 'gluteus-maximus': 0.5, 'rectus-femoris': 0.5, 'deltoid-anterior': 0.3 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["Your transition set-up laid out: helmet, glasses, shoes, bike."],
    execution: ["Jog in as if from the swim, remove goggles and cap, helmet on and buckled, run the bike to the mount line.", "Time each rehearsal and repeat to shave seconds."],
    cues: ["Helmet on before touching the bike", "Same order every time"],
    mistakes: ["Touching the bike before the helmet is buckled — a penalty in races."],
    defaultDose: reps(5, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'squat',
  },
  {
    slug: 'open-water-sighting', name: 'Sighting Every Six Strokes', skills: ['open-water-sighting'],
    qualities: { 'aerobic-base': 0.7, 'trunk-anti-rotation': 0.5 },
    muscles: { ...SWIM, 'neck-extensors': 0.4 }, equipment: ['none'], surface: 'pool',
    setup: ["A pool lane with a target (a bottle or cone) on the deck at the far end."],
    execution: ["Swim freestyle; every six strokes lift the eyes just above the water to spot the target, then breathe to the side.", "Keep the kick going as you sight."],
    cues: ["Crocodile eyes, not a full head lift", "Sight then breathe"],
    mistakes: ["Lifting the whole head up, which drops the hips."],
    defaultDose: dist(6, 50), restSeconds: 20, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'aerobic-swim-set', name: 'Aerobic Swim Set', skills: ['aerobic-pacing'],
    qualities: { 'aerobic-base': 0.9 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pool and a pace clock."],
    execution: ["Swim 100 m repeats at a steady, sustainable race pace with short rests.", "Each 100 should finish within two seconds of the others."],
    cues: ["Long strokes, steady breathing", "Same time every rep"],
    mistakes: ["Starting fast and fading through the set."],
    defaultDose: dist(8, 100), restSeconds: 20, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'steady-state-ride', name: 'Steady-State Ride', skills: ['aerobic-pacing'],
    qualities: { 'aerobic-base': 1.0 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A bike or trainer and a route without many stops."],
    execution: ["Ride 45–60 minutes at a steady effort you could hold all day.", "Keep a smooth cadence of 85–95 rpm."],
    cues: ["Steady, not surging", "Eat and drink on schedule"],
    mistakes: ["Chasing every rider who passes you."],
    defaultDose: time(1, 2700), restSeconds: 0, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'wetsuit-exit-drill', name: 'Swim-Exit Run-Up', skills: ['swim-to-bike-transition', 'open-water-sighting'],
    qualities: { 'acceleration': 0.5, 'anaerobic-capacity': 0.5 },
    muscles: { 'gluteus-maximus': 0.5, 'gastrocnemius': 0.5, 'latissimus-dorsi': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Pool with shallow end steps or ladder."],
    execution: ["Swim a hard 50 m, climb out, and jog 20 m on deck (carefully) peeling the cap and goggles.", "Walk back and repeat."],
    cues: ["Kick hard the last 10 m", "Stand up tall, then jog"],
    mistakes: ["Standing up too quickly and getting dizzy."],
    defaultDose: reps(4, 1), restSeconds: 90, startPose: 'overhead-throw', endPose: 'sprint-cycle',
  },
  {
    slug: 'tempo-run-off-bike', name: 'Tempo Run Pacing', skills: ['aerobic-pacing', 'bike-to-run-transition'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.4 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["A flat running route."],
    execution: ["Run 15 minutes at your planned race run pace.", "Check pace every kilometre and correct gently."],
    cues: ["Race pace, not faster", "Relaxed arms"],
    mistakes: ["Running the first kilometre way too fast."],
    defaultDose: time(1, 900), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
]);

const DUATHLON = sportDrills('triathlon-duathlon', [
  {
    slug: 'run-bike-brick', name: 'Run-to-Bike Brick', skills: ['run-to-bike-transition'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.4 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["Bike racked with helmet ready, running route starting beside it."],
    execution: ["Run 10 minutes at race pace, transition quickly, and ride 20 minutes at race effort.", "Spin an easy gear for the first minute to settle the legs."],
    cues: ["Easy gear first", "Helmet then bike"],
    mistakes: ["Mashing a big gear straight out of transition."],
    defaultDose: time(1, 1800), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'squat',
  },
  {
    slug: 'bike-run-brick', name: 'Bike-to-Run Brick', skills: ['bike-to-run-transition'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.4 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["Bike and running shoes set up together."],
    execution: ["Ride 20 minutes, change quickly and run 10 minutes at race pace.", "Short, quick steps for the first minute."],
    cues: ["Quick feet off the bike", "Build into pace"],
    mistakes: ["Starting the run at sprint pace."],
    defaultDose: time(1, 1800), restSeconds: 0, startPose: 'squat', endPose: 'sprint-cycle',
  },
  {
    slug: 'transition-rehearsal', name: 'Transition Rehearsal', skills: ['run-to-bike-transition', 'bike-to-run-transition'],
    qualities: { 'acceleration': 0.5, 'aerobic-base': 0.5 },
    muscles: { 'gluteus-maximus': 0.5, 'rectus-femoris': 0.5, 'gastrocnemius': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A mock transition area with your gear."],
    execution: ["Practise both transitions at race speed with a stopwatch.", "Repeat until each change is under a minute with nothing forgotten."],
    cues: ["Same order every time", "Walk through it in your head first"],
    mistakes: ["Changing your routine on race day."],
    defaultDose: reps(4, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'squat',
  },
  {
    slug: 'negative-split-run', name: 'Negative-Split Run', skills: ['pacing'],
    qualities: { 'aerobic-base': 0.9 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["An out-and-back route."],
    execution: ["Run out 15 minutes easy, then come back faster so the return is at least a minute quicker.", "Build gradually, not with a sudden sprint."],
    cues: ["Patient on the way out", "Build, don't burst"],
    mistakes: ["Running out too fast so you can't come back quicker."],
    defaultDose: time(1, 1800), restSeconds: 0, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'run-form-strides', name: 'Run Economy Strides', skills: ['running-economy'],
    qualities: { 'max-velocity': 0.5, 'reactive-strength': 0.5 },
    muscles: RUN_LEGS, equipment: ['none'], surface: 'anywhere',
    setup: ["100 m of flat ground after an easy run."],
    execution: ["Accelerate smoothly to about 85% speed, holding tall posture and quick cadence.", "Walk back to the start for full recovery before the next one."],
    cues: ["Tall and light", "Quick cadence"],
    mistakes: ["Straining to sprint all-out."],
    defaultDose: reps(6, 1), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'bike-cadence-drill', name: 'Bike Cadence Ladder', skills: ['pacing'],
    qualities: { 'aerobic-base': 0.7, 'reactive-strength': 0.3 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A bike on a trainer or a quiet flat road."],
    execution: ["Ride two minutes each at 80, 90, 100, then 110 rpm in an easy gear.", "Stay smooth in the saddle — no bouncing."],
    cues: ["Pedal circles, not squares", "Still hips"],
    mistakes: ["Bouncing on the saddle at high cadence."],
    defaultDose: time(2, 480), restSeconds: 120, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'calf-raise-durability', name: 'Calf Raise Durability', skills: ['running-economy'],
    qualities: { 'ankle-stiffness': 0.7, 'lower-body-strength': 0.5 },
    muscles: { 'gastrocnemius': 0.8, 'soleus': 0.7 },
    equipment: ['step'], surface: 'anywhere',
    setup: ["Stand on the edge of a step, holding a rail."],
    execution: ["Rise onto the toes, then lower slowly for three seconds below step level.", "Do both straight-knee and bent-knee versions."],
    cues: ["Slow down", "Full range"],
    mistakes: ["Bouncing at the bottom."],
    defaultDose: reps(3, 15), restSeconds: 45, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
]);

const CYCLING = sportDrills('cycling', [
  {
    slug: 'threshold-intervals', name: 'Threshold Intervals', skills: ['ftp-power'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.5 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A bike on a trainer or a steady road/climb after a 15-minute warm-up."],
    execution: ["Ride 8 minutes at the hardest effort you could hold for about an hour.", "Recover 4 minutes easy between efforts."],
    cues: ["Hard but controlled", "Steady cadence 85–95"],
    mistakes: ["Starting each interval too hard and fading."],
    defaultDose: reps(3, 1), restSeconds: 240, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'standing-sprints', name: 'Standing Sprints', skills: ['sprint-power'],
    qualities: { 'acceleration': 0.8, 'anaerobic-capacity': 0.7 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A safe flat road or a trainer; start at about 20 km/h in a medium gear."],
    execution: ["Stand and sprint all-out for 10–12 seconds, rocking the bike under you.", "Recover fully (3–5 minutes) between efforts."],
    cues: ["Explode, don't build", "Pull on the bars"],
    mistakes: ["Starting in a gear so hard you can't get the pedals turning."],
    defaultDose: reps(6, 1), restSeconds: 240, startPose: 'squat', endPose: 'lunge',
  },
  {
    slug: 'hill-climb-repeats', name: 'Seated Hill Climb Repeats', skills: ['climbing-power-to-weight'],
    qualities: { 'aerobic-base': 0.7, 'lower-body-strength': 0.5, 'anaerobic-capacity': 0.5 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A 3–5 minute climb."],
    execution: ["Climb seated at a strong, steady effort, shifting to keep cadence around 75–85.", "Roll back down easy."],
    cues: ["Stay seated, stay smooth", "Relax your grip"],
    mistakes: ["Grinding a big gear at 50 rpm."],
    defaultDose: reps(5, 1), restSeconds: 240, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'high-cadence-spin-ups', name: 'High-Cadence Spin-Ups', skills: ['cadence-efficiency'],
    qualities: { 'aerobic-base': 0.6, 'reactive-strength': 0.4 },
    muscles: { 'rectus-femoris': 0.6, 'iliopsoas': 0.5, 'biceps-femoris': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["An easy gear on a trainer or flat road."],
    execution: ["Over 30 seconds, build cadence as high as you can without bouncing, hold 10 seconds, then ease off.", "Ride 90 seconds easy between."],
    cues: ["Quiet upper body", "Pull through the bottom of the stroke"],
    mistakes: ["Bouncing in the saddle."],
    defaultDose: reps(6, 1), restSeconds: 90, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'single-leg-pedaling', name: 'Single-Leg Pedalling', skills: ['cadence-efficiency'],
    qualities: { 'single-leg-stability': 0.5, 'aerobic-base': 0.5 },
    muscles: { 'iliopsoas': 0.6, 'rectus-femoris': 0.6, 'biceps-femoris': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A bike on a trainer; unclip one foot and rest it on a stool."],
    execution: ["Pedal with one leg for 30 seconds in an easy gear, smoothing out the dead spots.", "Switch legs."],
    cues: ["Scrape the mud off the shoe", "Smooth circles"],
    mistakes: ["Clunky strokes with a dead spot at the top."],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'endurance-ride', name: 'Long Endurance Ride', skills: ['ftp-power', 'climbing-power-to-weight'],
    qualities: { 'aerobic-base': 1.0 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A 1.5–2 hour route, food and water."],
    execution: ["Ride at conversational effort the whole way.", "Eat something every 30–45 minutes."],
    cues: ["Chat pace", "Eat before you're hungry"],
    mistakes: ["Riding too hard early and running out of energy."],
    defaultDose: time(1, 5400), restSeconds: 0, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'standing-climb-bursts', name: 'Standing Climb Bursts', skills: ['climbing-power-to-weight', 'sprint-power'],
    qualities: { 'anaerobic-capacity': 0.7, 'lower-body-strength': 0.5 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A moderate climb."],
    execution: ["Climb seated, and every minute stand for 15 seconds of hard acceleration.", "Sit back down and settle."],
    cues: ["Shift up one gear before standing", "Smooth transition back to seated"],
    mistakes: ["Losing all speed when sitting back down."],
    defaultDose: time(3, 300), restSeconds: 240, startPose: 'squat', endPose: 'lunge',
  },
]);

const MTB = sportDrills('mountain-biking', [
  {
    slug: 'attack-position-drill', name: 'Attack-Position Descents', skills: ['technical-descending'],
    qualities: { 'single-leg-stability': 0.5, 'trunk-anti-rotation': 0.6, 'lower-body-strength': 0.4 },
    muscles: { 'gluteus-maximus': 0.6, 'vastus-lateralis': 0.5, 'triceps-brachii': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A short, smooth downhill section with a helmet on."],
    execution: ["Descend standing with level pedals, knees and elbows bent, hips back over the saddle.", "Look far down the trail and let the bike move under you."],
    cues: ["Heavy feet, light hands", "Eyes up the trail"],
    mistakes: ["Stiff arms and legs, which bounce you off line."],
    defaultDose: reps(6, 1), restSeconds: 90, startPose: 'hinge', endPose: 'hinge',
  },
  {
    slug: 'switchback-cornering', name: 'Switchback Cornering Practice', skills: ['bike-handling', 'technical-descending'],
    qualities: { 'single-leg-stability': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-medius': 0.5, 'obliques-external': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['cones'], surface: 'anywhere',
    setup: ["Cones marking a tight turn on grass or dirt."],
    execution: ["Brake before the turn, look through the exit, lean the bike (not your body) and roll through.", "Outside pedal down, weight on it."],
    cues: ["Brake before, not in", "Look where you want to go"],
    mistakes: ["Braking in the middle of the corner."],
    defaultDose: reps(8, 1), restSeconds: 45, startPose: 'hinge', endPose: 'trunk-rotation',
  },
  {
    slug: 'trackstand-balance', name: 'Trackstand Balance', skills: ['bike-handling'],
    qualities: { 'single-leg-stability': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-medius': 0.5, 'rectus-abdominis': 0.4, 'forearm-flexors': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A flat spot with a slight uphill."],
    execution: ["Roll slowly, stop pedalling with the pedals level, and balance in place using small pedal pressure and steering.", "Build from 3 to 30 seconds."],
    cues: ["Pedals level, eyes ahead", "Tiny corrections"],
    mistakes: ["Staring at the front wheel."],
    defaultDose: time(5, 20), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'climbing-intervals-mtb', name: 'Technical Climbing Intervals', skills: ['climbing-power'],
    qualities: { 'anaerobic-capacity': 0.7, 'lower-body-strength': 0.5, 'aerobic-base': 0.5 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A loose or rocky 2–4 minute climb."],
    execution: ["Climb seated with the chest low toward the bars to keep the front wheel down.", "Ride easy back down."],
    cues: ["Nose over the stem", "Steady power, no stomping"],
    mistakes: ["Sitting upright so the front wheel lifts."],
    defaultDose: reps(5, 1), restSeconds: 240, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'pacing-race-loop', name: 'Race-Loop Pacing', skills: ['endurance-pacing'],
    qualities: { 'aerobic-base': 0.9, 'anaerobic-capacity': 0.4 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["Your race loop or a similar trail."],
    execution: ["Ride three laps with the goal of every lap within 30 seconds of the others.", "Eat and drink on the smooth sections."],
    cues: ["Even laps", "Recover on the descents"],
    mistakes: ["Going all-out on lap one."],
    defaultDose: reps(3, 1), restSeconds: 120, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'wheel-lift-drill', name: 'Front-Wheel Lift Drill', skills: ['bike-handling', 'technical-descending'],
    qualities: { 'upper-body-pull': 0.5, 'horizontal-power': 0.5 },
    muscles: { 'latissimus-dorsi': 0.5, 'gluteus-maximus': 0.5, 'forearm-flexors': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A flat grass area at walking speed."],
    execution: ["Compress down into the bike, then push the hips back and lift the front wheel a few centimetres.", "Build toward lifting over a small stick."],
    cues: ["Down, then back", "Hips drive it, not arms"],
    mistakes: ["Yanking the bars with straight arms."],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'hinge', endPose: 'horizontal-pull',
  },
  {
    slug: 'long-trail-ride', name: 'Long Trail Ride', skills: ['endurance-pacing', 'climbing-power'],
    qualities: { 'aerobic-base': 1.0 },
    muscles: BIKE, equipment: ['none'], surface: 'anywhere',
    setup: ["A 1.5-hour trail route with water and food."],
    execution: ["Ride at a steady, sustainable effort, walking anything beyond your skill level.", "Eat every 45 minutes."],
    cues: ["Steady pace", "Walk it if in doubt"],
    mistakes: ["Riding over your head when tired."],
    defaultDose: time(1, 5400), restSeconds: 0, startPose: 'squat', endPose: 'squat',
  },
]);

const BMX = sportDrills('bmx', [
  {
    slug: 'gate-start-reaction', name: 'Gate-Start Reaction', skills: ['gate-start-power'],
    qualities: { 'acceleration': 0.9, 'reactive-strength': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'latissimus-dorsi': 0.4 },
    equipment: ['none'], surface: 'track',
    setup: ["Gate (or a curb) with the lead pedal at about 2 o'clock, helmet and gloves on."],
    execution: ["Balance against the gate; on the cadence or lights, snap the hips forward and drive the first pedal stroke.", "Sprint hard for 5 pedal strokes."],
    cues: ["Hips over the bars, then snap", "First pedal is everything"],
    mistakes: ["Leaning back as the gate drops."],
    defaultDose: reps(8, 1), restSeconds: 90, startPose: 'sprint-start', endPose: 'squat',
  },
  {
    slug: 'pump-track-laps', name: 'Pump-Track Laps', skills: ['bike-handling', 'jump-technique'],
    qualities: { 'anaerobic-capacity': 0.6, 'lower-body-strength': 0.4, 'upper-body-push': 0.4 },
    muscles: { 'gluteus-maximus': 0.6, 'triceps-brachii': 0.5, 'vastus-lateralis': 0.5 },
    equipment: ['none'], surface: 'track',
    setup: ["A pump track or roller section."],
    execution: ["Ride laps without pedalling, pushing the bike down the backsides of rollers to gain speed.", "Unweight the bike on the way up each roller."],
    cues: ["Push down the back side", "Light on the way up"],
    mistakes: ["Pedalling instead of pumping."],
    defaultDose: time(6, 30), restSeconds: 60, startPose: 'hinge', endPose: 'squat',
  },
  {
    slug: 'manual-drill', name: 'Manual Balance Drill', skills: ['bike-handling', 'jump-technique'],
    qualities: { 'trunk-anti-rotation': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'gluteus-maximus': 0.5, 'rectus-abdominis': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["A flat area at slow rolling speed."],
    execution: ["Shift the hips back over the rear wheel to lift the front without pedalling, balancing with the hips and rear brake.", "Hold for longer each attempt."],
    cues: ["Arms straight, hips back", "Cover the rear brake"],
    mistakes: ["Pulling with bent arms."],
    defaultDose: reps(8, 1), restSeconds: 30, startPose: 'hinge', endPose: 'hinge',
  },
  {
    slug: 'straight-sprints', name: 'Straight-Line Sprints', skills: ['sprint-power', 'gate-start-power'],
    qualities: { 'acceleration': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: BIKE, equipment: ['none'], surface: 'track',
    setup: ["A straight 60–80 m section."],
    execution: ["Sprint from a rolling start all-out to the end, staying low over the bars.", "Roll back slowly for full recovery."],
    cues: ["Pull the bars as you push", "Stay low"],
    mistakes: ["Sitting down mid-sprint."],
    defaultDose: reps(6, 1), restSeconds: 180, startPose: 'squat', endPose: 'lunge',
  },
  {
    slug: 'jump-absorb-landing', name: 'Jump and Absorb', skills: ['jump-technique'],
    qualities: { 'landing-mechanics': 0.7, 'lower-body-strength': 0.4 },
    muscles: { 'vastus-lateralis': 0.6, 'gluteus-maximus': 0.5, 'triceps-brachii': 0.4 },
    equipment: ['none'], surface: 'track', minAge: 14,
    setup: ["A small tabletop jump you already ride comfortably."],
    execution: ["Pump the lip, stay neutral in the air, and land both wheels together.", "Absorb the landing with bent legs and arms."],
    cues: ["Neutral in the air", "Soak up the landing"],
    mistakes: ["Stiff legs on landing."],
    defaultDose: reps(6, 1), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'bmx-leg-power-jumps', name: 'Box Jumps for Gate Power', skills: ['gate-start-power', 'sprint-power'],
    qualities: { 'vertical-power': 0.8, 'lower-body-strength': 0.4 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['box'], surface: 'gym',
    setup: ["A box at knee height."],
    execution: ["Jump explosively onto the box, landing soft and quiet.", "Step down and reset."],
    cues: ["Explode up", "Step down, never jump down"],
    mistakes: ["Choosing a box so high you land in a deep squat."],
    defaultDose: contacts(3, 5), restSeconds: 90, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'berm-cornering', name: 'Berm Cornering', skills: ['bike-handling'],
    qualities: { 'single-leg-stability': 0.5, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-medius': 0.5, 'obliques-external': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['none'], surface: 'track',
    setup: ["A berm on a BMX or pump track."],
    execution: ["Enter high, look through the turn and pump the exit to carry speed.", "Try the low line and compare exit speed."],
    cues: ["Look through the turn", "Pump the exit"],
    mistakes: ["Braking in the berm."],
    defaultDose: reps(8, 1), restSeconds: 45, startPose: 'hinge', endPose: 'trunk-rotation',
  },
]);

const ROWING = sportDrills('rowing', [
  {
    slug: 'erg-2k-pace-pieces', name: '2K-Pace Erg Pieces', skills: ['2k-erg-pace'],
    qualities: { 'anaerobic-capacity': 0.9, 'aerobic-base': 0.6 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["A rowing machine after a 10-minute warm-up; know your target 2K split."],
    execution: ["Row 500 m at goal 2K split, rating 30–32 strokes per minute.", "Rest 3 minutes easy between pieces."],
    cues: ["Hold the split, not the rate", "Legs, body, arms"],
    mistakes: ["Starting each piece far below the target split and dying."],
    defaultDose: reps(4, 1), restSeconds: 180, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'pick-drill', name: 'Pick Drill (Arms, Body, Legs)', skills: ['boat-feel-timing', 'core-transfer'],
    qualities: { 'trunk-anti-rotation': 0.6, 'upper-body-pull': 0.5 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["On the erg or in the boat at light pressure."],
    execution: ["Row arms only for 10 strokes, then arms and body, then half slide, then full strokes.", "Keep the sequence identical as the stroke lengthens."],
    cues: ["Arms, body, then slide", "Same order back to the catch"],
    mistakes: ["Bending the arms before the legs have finished driving."],
    defaultDose: reps(3, 30), restSeconds: 60, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'pause-at-body-over', name: 'Pause Drill at Body-Over', skills: ['recovery-timing'],
    qualities: { 'trunk-anti-rotation': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'erector-spinae': 0.5, 'rectus-abdominis': 0.5, 'iliopsoas': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ["On the erg or in the boat at light pressure."],
    execution: ["After each finish, extend the arms, pivot the body forward from the hips, and pause for one count.", "Then slide slowly to the catch."],
    cues: ["Hands away, body over, then slide", "Slow slide"],
    mistakes: ["Rushing up the slide, which checks the boat."],
    defaultDose: reps(3, 30), restSeconds: 60, startPose: 'hinge', endPose: 'squat',
  },
  {
    slug: 'power-strokes', name: 'Power-10 Strokes', skills: ['power-per-stroke', 'leg-drive-power'],
    qualities: { 'horizontal-power': 0.8, 'lower-body-strength': 0.6 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["The erg or boat after a warm-up."],
    execution: ["Take 10 maximum-pressure strokes at rate 24, focusing on the leg drive.", "Row easy for a minute between sets."],
    cues: ["Push the floor away", "Hang on the handle"],
    mistakes: ["Yanking with the arms before the legs finish."],
    defaultDose: reps(6, 10), restSeconds: 60, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'rate-ladder', name: 'Rate Ladder', skills: ['stroke-rate-efficiency'],
    qualities: { 'aerobic-base': 0.7, 'anaerobic-capacity': 0.6 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["The erg with the stroke-rate display showing."],
    execution: ["Row one minute each at 20, 22, 24, 26 and 28 strokes per minute.", "Split should improve with each step while the stroke stays long."],
    cues: ["Rate comes from the recovery", "Keep the length"],
    mistakes: ["Shortening the stroke to rate up."],
    defaultDose: time(2, 300), restSeconds: 120, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'steady-state-erg', name: 'Steady-State Erg', skills: ['2k-erg-pace', 'stroke-rate-efficiency'],
    qualities: { 'aerobic-base': 1.0 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["The erg at an easy-moderate effort."],
    execution: ["Row 30 minutes at rate 18–20 at a pace you can talk at.", "Keep every stroke technically clean."],
    cues: ["Long and relaxed", "Breathe every stroke"],
    mistakes: ["Letting technique fall apart because it's easy."],
    defaultDose: time(1, 1800), restSeconds: 0, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'sprint-finish-pieces', name: 'Sprint-Finish Pieces', skills: ['sprint-finish-power'],
    qualities: { 'anaerobic-capacity': 0.9, 'horizontal-power': 0.6 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["The erg after a warm-up."],
    execution: ["Row 250 m at 2K pace, then take 20 strokes all-out at a raised rate.", "Rest 3 minutes."],
    cues: ["Raise the rate, keep the length", "Legs, legs, legs"],
    mistakes: ["Rushing so hard the stroke becomes short and choppy."],
    defaultDose: reps(4, 1), restSeconds: 180, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'legs-only-rowing', name: 'Legs-Only Rowing', skills: ['leg-drive-power'],
    qualities: { 'lower-body-strength': 0.6, 'horizontal-power': 0.6 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6, 'rectus-femoris': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ["On the erg with arms straight and body fixed at the forward angle."],
    execution: ["Drive with the legs only, keeping the arms long and the back still.", "Feel the handle move with the legs."],
    cues: ["Arms are ropes", "Drive through the heels"],
    mistakes: ["Opening the back early."],
    defaultDose: reps(3, 20), restSeconds: 60, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'catch-timing-drill', name: 'Square-Blade Catch Timing', skills: ['boat-feel-timing'],
    qualities: { 'shoulder-stability': 0.5, 'trunk-anti-rotation': 0.5 },
    muscles: { 'latissimus-dorsi': 0.5, 'deltoid-posterior': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ["In the boat at light pressure with a coach calling."],
    execution: ["Row with square blades the whole stroke, placing the blade at the catch together as a crew.", "Focus on a clean, splash-free entry."],
    cues: ["Blades in before the legs", "Together at the catch"],
    mistakes: ["Driving with the legs before the blade is buried."],
    defaultDose: reps(3, 30), restSeconds: 60, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'plank-row-hold', name: 'Plank to Row Hold', skills: ['core-transfer'],
    qualities: { 'trunk-anti-rotation': 0.8, 'upper-body-pull': 0.5 },
    muscles: { 'rectus-abdominis': 0.6, 'obliques-external': 0.5, 'latissimus-dorsi': 0.5 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ["High plank with hands on two light dumbbells, feet wide."],
    execution: ["Row one dumbbell to the ribs without twisting the hips, lower, then the other side.", "Hips stay square to the floor."],
    cues: ["Hips don't move", "Brace like you're about to be pushed"],
    mistakes: ["Rotating the hips to lift the weight."],
    defaultDose: reps(3, 8, 'light'), restSeconds: 60, startPose: 'isometric-hold', endPose: 'horizontal-pull',
  },
  {
    slug: 'erg-starts', name: 'Racing Starts on the Erg', skills: ['sprint-finish-power', 'power-per-stroke'],
    qualities: { 'acceleration': 0.7, 'horizontal-power': 0.8 },
    muscles: ROW, equipment: ['none'], surface: 'gym',
    setup: ["The erg from a stop."],
    execution: ["Half slide, three-quarter slide, then full slide strokes, then 10 high strokes at race rate.", "Settle to race pace for 10 more."],
    cues: ["Short, sharp, then long", "Settle smoothly"],
    mistakes: ["Staying at the start rate too long."],
    defaultDose: reps(5, 1), restSeconds: 120, startPose: 'squat', endPose: 'horizontal-pull',
  },
  {
    slug: 'feet-out-rowing', name: 'Feet-Out Rowing', skills: ['boat-feel-timing', 'recovery-timing'],
    qualities: { 'trunk-anti-rotation': 0.5, 'hip-mobility': 0.5 },
    muscles: { 'rectus-abdominis': 0.5, 'erector-spinae': 0.5, 'latissimus-dorsi': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ["Erg with the feet resting on top of the foot straps, not strapped in."],
    execution: ["Row at light pressure; you must finish the stroke with the handle drawn level to stay on.", "Any late or high finish lifts you off the foot plate."],
    cues: ["Draw the handle level", "Controlled finish"],
    mistakes: ["Pulling up to the chin and falling back."],
    defaultDose: reps(3, 20), restSeconds: 60, startPose: 'squat', endPose: 'horizontal-pull',
  },
]);

const SWIMMING = sportDrills('swimming-diving', [
  {
    slug: 'catch-up-freestyle', name: 'Catch-Up Freestyle', skills: ['stroke-rate', 'body-position'],
    qualities: { 'shoulder-stability': 0.6, 'aerobic-base': 0.5 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pool lane."],
    execution: ["Swim freestyle keeping one hand extended in front until the other hand touches it.", "Focus on a long reach and a full pull past the hip."],
    cues: ["Reach long", "Finish past the hip"],
    mistakes: ["Dropping the extended hand, which lets the hips sink."],
    defaultDose: dist(6, 50), restSeconds: 20, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'flip-turn-drill', name: 'Flip-Turn Repeats', skills: ['turn-speed'],
    qualities: { 'trunk-anti-rotation': 0.5, 'horizontal-power': 0.6 },
    muscles: { 'rectus-abdominis': 0.6, 'gluteus-maximus': 0.5, 'vastus-lateralis': 0.5 },
    equipment: ['none'], surface: 'pool',
    setup: ["Start 10 m from the wall."],
    execution: ["Swim fast into the wall, tuck and flip without breathing on the last stroke, plant the feet and push off on your back, rotating to your front.", "Streamline to 5 m before the first stroke."],
    cues: ["No breath into the wall", "Tight tuck, fast push"],
    mistakes: ["Gliding into the wall and losing speed."],
    defaultDose: reps(8, 1), restSeconds: 30, startPose: 'trunk-flexion', endPose: 'broad-jump',
  },
  {
    slug: 'streamline-kick', name: 'Streamline Dolphin Kick', skills: ['underwater-dolphin-kick', 'body-position'],
    qualities: { 'trunk-anti-rotation': 0.6, 'aerobic-base': 0.4, 'shoulder-stability': 0.5 },
    muscles: { 'rectus-abdominis': 0.6, 'erector-spinae': 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Push off the wall in a tight streamline."],
    execution: ["Hold streamline underwater and dolphin kick from the chest, not the knees, for 10–15 m.", "Surface and swim easy to the end."],
    cues: ["Squeeze the ears with the arms", "Kick from the chest"],
    mistakes: ["Big knee bends, which create drag."],
    defaultDose: reps(8, 1), restSeconds: 30, startPose: 'vertical-push', endPose: 'vertical-push',
  },
  {
    slug: 'dive-start-practice', name: 'Track Start Practice', skills: ['start-power', 'entry-technique'],
    qualities: { 'horizontal-power': 0.8, 'reactive-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['none'], surface: 'pool', minAge: 14,
    setup: ["On the starting block in water at least 2 m deep, supervised."],
    execution: ["Take your mark with one foot at the front edge, react to the whistle and drive out, entering through one hole.", "Glide in streamline and break out with dolphin kicks."],
    cues: ["Drive out, not up", "One-hole entry"],
    mistakes: ["Entering flat, which slaps and stops you."],
    defaultDose: reps(6, 1), restSeconds: 60, startPose: 'sprint-start', endPose: 'vertical-push',
  },
  {
    slug: 'broken-200-pace', name: 'Broken 200 Pace Set', skills: ['pacing-strategy'],
    qualities: { 'anaerobic-capacity': 0.8, 'aerobic-base': 0.6 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pace clock and your goal 200 time."],
    execution: ["Swim 4 × 50 at goal 200 pace with 10 seconds rest between.", "Add the 50 splits — the total should match your goal."],
    cues: ["Hold the same split", "Don't go out too fast"],
    mistakes: ["First 50 far faster than the rest."],
    defaultDose: dist(4, 50), restSeconds: 10, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'stroke-count-50s', name: 'Stroke-Count 50s', skills: ['stroke-rate', 'body-position'],
    qualities: { 'aerobic-base': 0.6, 'shoulder-stability': 0.5 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A 25 m or 50 m pool."],
    execution: ["Count strokes per length at easy pace, then try to hold the same speed with one fewer stroke.", "Then hold the count and go faster."],
    cues: ["Longer, not harder", "Glide off each stroke"],
    mistakes: ["Gliding so long you slow down."],
    defaultDose: dist(8, 50), restSeconds: 20, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'scapular-band-routine', name: 'Swimmer Shoulder Band Routine', skills: ['shoulder-durability'],
    qualities: { 'shoulder-stability': 0.9, 'upper-body-pull': 0.5 },
    muscles: { 'infraspinatus': 0.7, 'trapezius-lower': 0.6, 'serratus-anterior': 0.5 },
    equipment: ['band'], surface: 'anywhere',
    setup: ["A light band before practice."],
    execution: ["External rotations, pull-aparts, and Y-T-W raises, each done slowly.", "Stop well before fatigue."],
    cues: ["Shoulders down and back", "Slow and controlled"],
    mistakes: ["Using a heavy band and shrugging."],
    defaultDose: reps(2, 12, 'light band'), restSeconds: 30, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
  {
    slug: 'sprint-25s', name: 'All-Out 25s', skills: ['stroke-rate', 'start-power'],
    qualities: { 'anaerobic-capacity': 0.8, 'acceleration': 0.6 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A push start or dive start with full rest."],
    execution: ["Sprint 25 m at maximum speed with few breaths.", "Swim easy 50 as recovery."],
    cues: ["Fast hands", "Breathe every 3rd or less"],
    mistakes: ["Losing technique to spin the arms."],
    defaultDose: dist(6, 25), restSeconds: 60, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'kick-set-board', name: 'Kick Set With Board', skills: ['body-position', 'underwater-dolphin-kick'],
    qualities: { 'aerobic-base': 0.7, 'hip-mobility': 0.4 },
    muscles: { 'rectus-femoris': 0.6, 'gluteus-maximus': 0.5, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'pool',
    setup: ["A kickboard held at arm's length."],
    execution: ["Flutter kick 50 m with small, fast kicks from the hips.", "Every other 50 kick on your side without the board."],
    cues: ["Kick from the hips", "Pointed toes"],
    mistakes: ["Bicycle kicking with big knee bends."],
    defaultDose: dist(6, 50), restSeconds: 20, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'dryland-diving-hurdle', name: 'Dryland Hurdle and Take-Off', skills: ['entry-technique'],
    qualities: { 'vertical-power': 0.7, 'landing-mechanics': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'gluteus-maximus': 0.5, 'rectus-abdominis': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ["A soft mat or trampoline area with a coach."],
    execution: ["Practise the approach and hurdle step, driving the knee and arms up into a tall take-off.", "Land on two feet on the mat in a tight vertical line."],
    cues: ["Arms and knee drive up", "Tall and tight"],
    mistakes: ["Leaning forward on the hurdle."],
    defaultDose: contacts(3, 6), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'descending-100s', name: 'Descending 100s', skills: ['pacing-strategy'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pace clock."],
    execution: ["Swim 4 × 100, each one 2–3 seconds faster than the last.", "Rest 20 seconds; repeat the round twice."],
    cues: ["Start controlled", "Finish fast"],
    mistakes: ["Starting the first 100 as the fastest."],
    defaultDose: dist(8, 100), restSeconds: 20, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'breakout-drill', name: 'Breakout Timing Drill', skills: ['underwater-dolphin-kick', 'turn-speed'],
    qualities: { 'acceleration': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'rectus-abdominis': 0.5, 'latissimus-dorsi': 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Push off the wall in streamline."],
    execution: ["Dolphin kick 4–6 times, then take the first stroke just before surfacing, keeping the head down for the first stroke.", "Swim hard to 15 m."],
    cues: ["Stroke before you surface", "No breath on the first stroke"],
    mistakes: ["Popping up and stopping before the first stroke."],
    defaultDose: reps(8, 1), restSeconds: 30, startPose: 'vertical-push', endPose: 'overhead-throw',
  },
]);

const ADAPTED_SWIMMING = sportDrills('adapted-swimming', [
  {
    slug: 'supported-body-position', name: 'Supported Floating Body Position', skills: ['stroke-technique'],
    qualities: { 'trunk-anti-rotation': 0.6, 'shoulder-stability': 0.4 },
    muscles: { 'rectus-abdominis': 0.5, 'erector-spinae': 0.5, 'gluteus-maximus': 0.3 },
    equipment: ['partner'], surface: 'pool',
    setup: ["Chest-deep water with a coach or partner supporting as needed; a noodle or float is fine."],
    execution: ["Float face-down (or on your back) with the body long and hips near the surface.", "Hold for 10 seconds, then add a gentle kick or arm action."],
    cues: ["Long and flat", "Relax into the water"],
    mistakes: ["Lifting the head, which sinks the legs."],
    defaultDose: time(5, 15), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'rhythmic-breathing', name: 'Rhythmic Breathing Bobs', skills: ['breathing-rhythm'],
    qualities: { 'aerobic-base': 0.6, 'trunk-anti-rotation': 0.3 },
    muscles: { 'rectus-abdominis': 0.4, 'neck-extensors': 0.3, 'latissimus-dorsi': 0.3 },
    equipment: ['none'], surface: 'pool',
    setup: ["Hold the pool edge in standing depth (or with a partner's support)."],
    execution: ["Breathe out steadily through the nose and mouth under water, then turn the head to the side to breathe in.", "Build to a relaxed rhythm of 10 breaths."],
    cues: ["Bubbles out under water", "Turn, don't lift"],
    mistakes: ["Holding the breath under water, which causes panic breaths."],
    defaultDose: reps(4, 10), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'arms-only-freestyle', name: 'Arms-Only Freestyle With Pull Buoy', skills: ['stroke-technique', 'endurance'],
    qualities: { 'aerobic-base': 0.6, 'upper-body-pull': 0.5 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pull buoy between the legs (or a float for limb-difference swimmers)."],
    execution: ["Swim freestyle using arms only, focusing on a long reach and full pull.", "Rest at each wall as needed."],
    cues: ["Reach and pull", "Breathe to both sides if you can"],
    mistakes: ["Short, fast strokes that don't finish."],
    defaultDose: dist(6, 25), restSeconds: 30, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'in-water-starts', name: 'In-Water Push Starts', skills: ['start-technique'],
    qualities: { 'horizontal-power': 0.6, 'acceleration': 0.5 },
    muscles: { 'gluteus-maximus': 0.5, 'latissimus-dorsi': 0.5, 'vastus-lateralis': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Start in the water holding the wall or starting grip, as allowed for your classification."],
    execution: ["On the whistle, push off hard into streamline (or your strongest body position).", "Glide, then begin your stroke."],
    cues: ["Push hard, stay long", "First stroke fast"],
    mistakes: ["Letting go of the wall before pushing."],
    defaultDose: reps(6, 1), restSeconds: 45, startPose: 'isometric-hold', endPose: 'vertical-push',
  },
  {
    slug: 'steady-endurance-swim', name: 'Steady Endurance Swim', skills: ['endurance', 'breathing-rhythm'],
    qualities: { 'aerobic-base': 0.9 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pool lane at an easy pace."],
    execution: ["Swim continuously for 5–10 minutes at a steady pace, resting briefly at the wall if needed.", "Build total time week by week."],
    cues: ["Steady breathing", "Easy pace"],
    mistakes: ["Sprinting and stopping."],
    defaultDose: time(2, 300), restSeconds: 60, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'kick-with-float', name: 'Kick With Float', skills: ['stroke-technique', 'endurance'],
    qualities: { 'aerobic-base': 0.6, 'hip-mobility': 0.4 },
    muscles: { 'rectus-femoris': 0.5, 'gluteus-maximus': 0.5, 'iliopsoas': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Hold a kickboard or noodle."],
    execution: ["Kick steadily from the hips for one length, keeping legs long.", "Rest and repeat."],
    cues: ["Kick from the hips", "Relaxed ankles"],
    mistakes: ["Bending the knees a lot."],
    defaultDose: dist(4, 25), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'dryland-shoulder-care', name: 'Dryland Shoulder Care', skills: ['stroke-technique'],
    qualities: { 'shoulder-stability': 0.8 },
    muscles: { 'infraspinatus': 0.6, 'trapezius-lower': 0.5, 'serratus-anterior': 0.5 },
    equipment: ['band'], surface: 'anywhere',
    setup: ["A light band, seated or standing."],
    execution: ["Slow external rotations and band pull-aparts.", "Stop before any discomfort."],
    cues: ["Slow and smooth", "Shoulders down"],
    mistakes: ["Rushing through the reps."],
    defaultDose: reps(2, 12, 'light band'), restSeconds: 30, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
]);

const WATER_POLO = sportDrills('water-polo', [
  {
    slug: 'eggbeater-holds', name: 'Eggbeater Holds', skills: ['eggbeater-endurance', 'treading-power'],
    qualities: { 'aerobic-base': 0.7, 'hip-mobility': 0.6, 'lower-body-strength': 0.4 },
    muscles: { 'adductors': 0.7, 'gluteus-medius': 0.6, 'rectus-femoris': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Deep water, away from the wall and lane lines."],
    execution: ["Eggbeater with the hands out of the water for 30 seconds, keeping the shoulders above the surface.", "Rest 15 seconds and repeat."],
    cues: ["Alternate circles", "Sit tall in the water"],
    mistakes: ["Scissor-kicking, which bobs you up and down."],
    defaultDose: time(6, 30), restSeconds: 15, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'vertical-lunge-jumps', name: 'Vertical Jumps Out of the Water', skills: ['vertical-power-out-of-water', 'shot-velocity'],
    qualities: { 'vertical-power': 0.8, 'hip-mobility': 0.5 },
    muscles: { 'adductors': 0.6, 'gluteus-maximus': 0.6, 'rectus-femoris': 0.5 },
    equipment: ['none'], surface: 'pool',
    setup: ["Deep water in the eggbeater position."],
    execution: ["Build the eggbeater, then explode up to get the hips as high out of the water as possible, arm raised.", "Settle back and repeat."],
    cues: ["Build, then burst", "Reach high"],
    mistakes: ["Jumping without building eggbeater speed first."],
    defaultDose: reps(4, 6), restSeconds: 45, startPose: 'squat', endPose: 'vertical-jump',
  },
  {
    slug: 'wall-passing', name: 'Dry-Pass Passing Series', skills: ['passing-accuracy'],
    qualities: { 'overhead-power': 0.6, 'shoulder-stability': 0.6 },
    muscles: { 'latissimus-dorsi': 0.5, 'triceps-brachii': 0.5, 'deltoid-anterior': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'pool',
    setup: ["Two players 5 m apart treading water."],
    execution: ["Pass the ball to your partner's raised hand without it touching the water (dry pass).", "Move to 8 m, then add a pass on the move."],
    cues: ["Hand high, target the hand", "Eggbeater up for every pass"],
    mistakes: ["Passing from low in the water, which is easy to intercept."],
    defaultDose: reps(3, 20), restSeconds: 30, startPose: 'vertical-push', endPose: 'overhead-throw',
  },
  {
    slug: 'shot-power-series', name: 'Shooting Power Series', skills: ['shot-velocity'],
    qualities: { 'overhead-power': 0.9, 'rotational-power': 0.7 },
    muscles: { 'latissimus-dorsi': 0.6, 'obliques-external': 0.6, 'triceps-brachii': 0.5 },
    equipment: ['ball', 'goal'], prop: 'ball-round', surface: 'pool',
    setup: ["5 m in front of goal with balls."],
    execution: ["Eggbeater up high, rotate the hips and chest, and shoot to a called corner.", "Recover to the vertical position after each shot."],
    cues: ["Rotate the body, not just the arm", "Get high first"],
    mistakes: ["Shooting flat in the water with no lift."],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'head-up-sprints', name: 'Head-Up Freestyle Sprints', skills: ['sprint-swim-speed'],
    qualities: { 'anaerobic-capacity': 0.8, 'acceleration': 0.6 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A 15–25 m sprint lane."],
    execution: ["Sprint with the head up, eyes forward, fast high-elbow strokes.", "Rest 30 seconds; repeat."],
    cues: ["Eyes on the play", "Fast hands"],
    mistakes: ["Dropping the head, losing sight of the ball."],
    defaultDose: dist(8, 15), restSeconds: 30, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'counterattack-swims', name: 'Counterattack Swims', skills: ['sprint-swim-speed', 'eggbeater-endurance'],
    qualities: { 'repeat-sprint': 0.8, 'anaerobic-capacity': 0.7 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["Start at one goal line."],
    execution: ["Sprint head-up to half court, turn to eggbeater for 5 seconds, then sprint the rest.", "Swim easy back and repeat."],
    cues: ["Sprint, stop, sprint", "Stay high on the stop"],
    mistakes: ["Coasting on the second sprint."],
    defaultDose: reps(6, 1), restSeconds: 60, startPose: 'vertical-pull', endPose: 'overhead-throw',
  },
  {
    slug: 'defensive-hold-position', name: 'Defensive Position Wrestling', skills: ['defensive-positioning-strength'],
    qualities: { 'trunk-anti-rotation': 0.7, 'lower-body-strength': 0.5 },
    muscles: { 'adductors': 0.6, 'rectus-abdominis': 0.5, 'latissimus-dorsi': 0.5 },
    equipment: ['partner'], surface: 'pool', minAge: 14,
    setup: ["Two players in a hole-set position near goal."],
    execution: ["Defender holds position behind the centre using legal body position and strong eggbeater for 20 seconds.", "Swap roles so both players defend and attack."],
    cues: ["Stay behind, stay high", "Legs do the work"],
    mistakes: ["Sinking and grabbing, which draws exclusions."],
    defaultDose: time(6, 20), restSeconds: 40, startPose: 'squat', endPose: 'isometric-hold',
  },
  {
    slug: 'band-shoulder-routine', name: 'Thrower Band Routine', skills: ['shoulder-durability'],
    qualities: { 'shoulder-stability': 0.9 },
    muscles: { 'infraspinatus': 0.7, 'teres-minor': 0.6, 'trapezius-lower': 0.5 },
    equipment: ['band'], surface: 'anywhere',
    setup: ["A light band before practice."],
    execution: ["External rotations at 0 and 90 degrees, pull-aparts, and slow throwing-motion pulls.", "Two controlled sets."],
    cues: ["Slow and controlled", "Elbow high"],
    mistakes: ["Heavy band, sloppy form."],
    defaultDose: reps(2, 12, 'light band'), restSeconds: 30, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
  {
    slug: 'weighted-eggbeater', name: 'Eggbeater With Hands Up', skills: ['treading-power', 'eggbeater-endurance'],
    qualities: { 'lower-body-strength': 0.6, 'aerobic-base': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'adductors': 0.7, 'gluteus-medius': 0.6, 'vastus-medialis': 0.4 },
    equipment: ['ball'], prop: 'ball-round', surface: 'pool',
    setup: ["Deep water, holding a ball overhead with both hands."],
    execution: ["Eggbeater with the ball overhead for 20 seconds, elbows out of the water.", "Rest and repeat."],
    cues: ["Keep the ball dry", "Fast, wide circles"],
    mistakes: ["Letting the elbows drop into the water."],
    defaultDose: time(5, 20), restSeconds: 30, startPose: 'squat', endPose: 'isometric-hold',
  },
  {
    slug: 'lateral-eggbeater-moves', name: 'Lateral Eggbeater Movement', skills: ['defensive-positioning-strength', 'treading-power'],
    qualities: { 'lateral-power': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'adductors': 0.6, 'gluteus-medius': 0.6, 'obliques-external': 0.4 },
    equipment: ['none'], surface: 'pool',
    setup: ["Deep water between two lane lines."],
    execution: ["Move side to side 3 m using eggbeater, staying upright and square.", "Change direction on the whistle."],
    cues: ["Stay square", "Lead with the hips"],
    mistakes: ["Tilting forward into a swim."],
    defaultDose: time(6, 20), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'catch-and-shoot', name: 'Catch-and-Shoot', skills: ['shot-velocity', 'passing-accuracy'],
    qualities: { 'overhead-power': 0.8, 'reactive-strength': 0.5 },
    muscles: { 'latissimus-dorsi': 0.6, 'triceps-brachii': 0.5, 'obliques-external': 0.5 },
    equipment: ['ball', 'goal', 'partner'], prop: 'ball-round', surface: 'pool',
    setup: ["Feeder at the side, shooter 5 m out."],
    execution: ["Catch the pass high and shoot in one motion without bringing the ball down.", "Alternate sides."],
    cues: ["Catch it high, keep it high", "One motion"],
    mistakes: ["Dropping the ball to the water before shooting."],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'vertical-push', endPose: 'overhead-throw',
  },
  {
    slug: 'water-polo-interval-set', name: 'Water-Polo Interval Set', skills: ['eggbeater-endurance', 'sprint-swim-speed'],
    qualities: { 'repeat-sprint': 0.8, 'aerobic-base': 0.6 },
    muscles: SWIM, equipment: ['none'], surface: 'pool',
    setup: ["A pool width or 25 m lane."],
    execution: ["Swim 25 m head-up sprint, then 20 seconds of eggbeater, back-to-back for 5 rounds.", "Rest two minutes; repeat."],
    cues: ["No coasting", "High on the eggbeater"],
    mistakes: ["Sinking during the eggbeater recovery."],
    defaultDose: reps(2, 5), restSeconds: 120, startPose: 'vertical-pull', endPose: 'squat',
  },
]);

export const ENDURANCE_DRILLS = [
  ...TRACK, ...XC, ...UNIFIED_TRACK, ...PARA_TRACK, ...ORIENTEERING, ...TRIATHLON, ...DUATHLON,
  ...CYCLING, ...MTB, ...BMX, ...ROWING, ...SWIMMING, ...ADAPTED_SWIMMING, ...WATER_POLO,
];
