/**
 * Sport drills — soccer, football, basketball, baseball, softball, flag
 * football. Written from standard coaching practice for each sport (the
 * progressions coaches and national federations teach), not scraped or
 * imported: every drill states its setup, the actual execution, cues a
 * coach would shout, and the mistake that ruins it.
 */

import { contacts, dist, reps, sportDrills, time } from '../drillKit.js';

const SOCCER = sportDrills('soccer', [
  {
    slug: 'driven-pass-gates', name: 'Driven Pass Through Gates', skills: ['passing-range'],
    qualities: { 'rotational-power': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'rectus-femoris': 0.6, 'adductors': 0.5, 'gluteus-medius': 0.4 },
    equipment: ['ball', 'cones', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['Two players 25–35 yards apart with a two-yard cone gate halfway between them.'],
    execution: ['Strike a driven pass along the ground through the gate to your partner.', 'Partner receives, sets the ball, and returns through the gate; move the gate further off-centre as accuracy improves.'],
    cues: ['Toe down, laces through the middle', 'Land on the kicking foot'],
    mistakes: ['Leaning back so the ball lifts off the ground and over the gate.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'instep-strike', endPose: 'instep-strike', constraintAxes: ['touches'],
  },
  {
    slug: 'first-touch-wall-rebounds', name: 'First-Touch Wall Rebounds', skills: ['first-touch'],
    qualities: { 'single-leg-stability': 0.6, 'ankle-stiffness': 0.5, 'reactive-strength': 0.5 },
    muscles: { 'tibialis-anterior': 0.5, 'gluteus-medius': 0.5, 'adductors': 0.4 },
    equipment: ['ball', 'wall'], prop: 'ball-round', surface: 'anywhere',
    setup: ['Stand 5–8 yards from a solid wall with one ball.'],
    execution: ['Pass firmly into the wall and control the rebound with one touch into space, away from an imaginary defender.', 'Alternate inside foot, outside foot and sole; step further back to make the ball arrive faster.'],
    cues: ['Open your body before the ball arrives', 'Cushion — give with the foot on contact'],
    mistakes: ['Stopping the ball dead under your feet instead of taking it into the next action.'],
    defaultDose: time(4, 45), restSeconds: 45, startPose: 'single-leg-balance', endPose: 'instep-strike', constraintAxes: ['movement'],
  },
  {
    slug: 'cone-dribble-slalom', name: 'Cone Dribble Slalom', skills: ['dribbling', 'agility'],
    qualities: { 'change-of-direction': 0.8, 'lateral-power': 0.5, 'acceleration': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'adductors': 0.5, 'gastrocnemius': 0.4 },
    equipment: ['ball', 'cones'], prop: 'ball-round', surface: 'field',
    setup: ['Six cones in a line, one and a half yards apart.'],
    execution: ['Dribble through the cones using the inside and outside of the same foot, keeping the ball within a stride.', 'Accelerate hard for five yards after the last cone; walk back and repeat with the other foot.'],
    cues: ['Small touches, head up between touches', 'Stay low through the cones'],
    mistakes: ['Big touches that force you to reach for the ball at every cone.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'cut', endPose: 'sprint-cycle', constraintAxes: ['opposition'],
  },
  {
    slug: 'one-v-one-channel', name: '1v1 Attacking Channel', skills: ['dribbling', 'one-v-one-defending'],
    qualities: { 'change-of-direction': 0.9, 'deceleration': 0.8, 'acceleration': 0.7, 'anaerobic-capacity': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'biceps-femoris': 0.5, 'vastus-medialis': 0.5 },
    equipment: ['ball', 'cones', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['A channel 10 yards wide and 20 long with a small cone goal at each end.'],
    execution: ['Attacker starts with the ball and tries to beat the defender to dribble through the far goal.', 'Defender stays side-on, delays, and forces the attacker onto their weaker foot; swap roles every rep.'],
    cues: ['Defender: bent knees, don\'t dive in', 'Attacker: change speed, not just direction'],
    mistakes: ['Defender squaring up flat-footed, which lets the attacker go either way.'],
    defaultDose: reps(4, 6), restSeconds: 60, startPose: 'lateral-shuffle', endPose: 'cut',
  },
  {
    slug: 'heading-toss-and-attack', name: 'Heading Toss-and-Attack', skills: ['heading'],
    qualities: { 'vertical-power': 0.8, 'trunk-anti-rotation': 0.6, 'landing-mechanics': 0.5 },
    muscles: { 'neck-extensors': 0.6, 'rectus-abdominis': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field', minAge: 14,
    setup: ['Partner stands 4 yards away with a soft, properly inflated ball. Keep total heading volume low — quality over quantity.'],
    execution: ['Partner lobs the ball; take a short run, jump off one foot and attack the ball with the forehead, eyes open, mouth closed.', 'Land on two feet, balanced; walk back and reset. Stop at the prescribed reps.'],
    cues: ['Forehead, not the top of the head', 'Brace the neck and drive through the ball'],
    mistakes: ['Letting the ball hit you instead of attacking it, which is less controlled and less effective.'],
    defaultDose: reps(2, 5), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'crossing-from-wide', name: 'Crossing From the Wide Channel', skills: ['crossing', 'passing-range'],
    qualities: { 'rotational-power': 0.8, 'hip-mobility': 0.6, 'acceleration': 0.5 },
    muscles: { 'iliopsoas': 0.6, 'rectus-femoris': 0.6, 'adductors': 0.5 },
    equipment: ['ball', 'cones', 'goal'], prop: 'ball-round', surface: 'field',
    setup: ['Place balls in the wide channel 25 yards from goal; mark near-post, penalty spot and back-post target zones with cones.'],
    execution: ['Dribble at pace down the line, take a setting touch and whip the ball into a named zone.', 'Alternate driven crosses, lofted back-post balls and cut-backs.'],
    cues: ['Wrap the foot around the ball for bend', 'Look up before the setting touch'],
    mistakes: ['Crossing without looking, so the ball goes to the keeper instead of a zone.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'instep-strike', constraintAxes: ['movement'],
  },
  {
    slug: 'finishing-under-fatigue', name: 'Finishing Under Fatigue', skills: ['shooting-accuracy', 'shooting-power'],
    qualities: { 'repeat-sprint': 0.7, 'rotational-power': 0.7, 'deceleration': 0.6 },
    muscles: { 'rectus-femoris': 0.6, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.4 },
    equipment: ['ball', 'goal', 'cones'], prop: 'ball-round', surface: 'field',
    setup: ['Balls on the edge of the box; a cone 20 yards back from them.'],
    execution: ['Sprint from the cone to the ball, plant, and shoot to a named corner.', 'Jog back to the cone and go again immediately — the point is clean technique while tired, like late in a game.'],
    cues: ['Pick the corner before you arrive', 'Composure: last step shorter, then strike'],
    mistakes: ['Blasting every shot as hard as possible and losing accuracy as fatigue builds.'],
    defaultDose: reps(3, 6), restSeconds: 90, startPose: 'sprint-cycle', endPose: 'instep-strike',
  },
  {
    slug: 'target-corner-shooting', name: 'Target-Corner Shooting', skills: ['shooting-accuracy'],
    qualities: { 'single-leg-stability': 0.7, 'hip-mobility': 0.5, 'rotational-power': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'rectus-femoris': 0.5, 'adductors': 0.4 },
    equipment: ['ball', 'goal', 'cones'], prop: 'ball-round', surface: 'field',
    setup: ['Hang or place a target in each bottom corner of the goal (cones, bibs); balls 14–18 yards out.'],
    execution: ['Side-foot or instep-curl the ball into the corner a partner calls just before you strike.', 'Score one point per corner hit; track your score each week.'],
    cues: ['Placement beats power', 'Hips open for the far corner, closed for the near'],
    mistakes: ['Looking at the goal during contact instead of at the ball.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'instep-strike', endPose: 'instep-strike',
  },
  {
    slug: 'repeated-40-yard-sprints', name: 'Repeated 40-Yard Sprints', skills: ['sprint-speed'],
    qualities: { 'repeat-sprint': 0.9, 'acceleration': 0.7, 'max-velocity': 0.6 },
    muscles: { 'biceps-femoris': 0.7, 'gluteus-maximus': 0.7, 'gastrocnemius': 0.5 },
    equipment: ['cones'], surface: 'field',
    setup: ['Cones 40 yards apart after a full warm-up.'],
    execution: ['Sprint 40 yards at match speed, decelerate under control over 10 yards.', 'Walk back as recovery (about 30 seconds) and repeat.'],
    cues: ['Drive the arms, stay tall after 10 yards', 'Every rep near your best time'],
    mistakes: ['Pacing the reps so the last one is as fast as the first — each should be a real sprint.'],
    defaultDose: reps(2, 6), restSeconds: 120, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'arrowhead-agility', name: 'Arrowhead Agility Run', skills: ['agility'],
    qualities: { 'change-of-direction': 0.9, 'deceleration': 0.8, 'acceleration': 0.6 },
    muscles: { 'vastus-lateralis': 0.6, 'gluteus-medius': 0.6, 'peroneals': 0.4 },
    equipment: ['cones'], surface: 'field',
    setup: ['Arrowhead pattern: start line, a centre cone 10 m ahead, a side cone 5 m left and right of it, and a nose cone 5 m beyond centre.'],
    execution: ['Sprint to the centre cone, cut to the side cone, cut to the nose cone, then sprint back through the start.', 'Alternate left and right sides.'],
    cues: ['Plant outside foot, push away', 'Lower your hips before each cut'],
    mistakes: ['Rounding the cones instead of planting and changing direction sharply.'],
    defaultDose: reps(3, 4), restSeconds: 60, startPose: 'deceleration-plant', endPose: 'cut',
  },
]);

const FOOTBALL = sportDrills('football', [
  {
    slug: 'qb-drop-and-throw', name: 'Three-Step Drop and Throw', skills: ['throwing-velocity'],
    qualities: { 'rotational-power': 0.8, 'overhead-power': 0.8, 'shoulder-stability': 0.5 },
    muscles: { 'obliques-external': 0.6, 'latissimus-dorsi': 0.5, 'deltoid-anterior': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-oval', surface: 'field',
    setup: ['A receiver or target 10–15 yards downfield.'],
    execution: ['Take a three-step drop from under centre, plant on the third step, and throw on time.', 'Stride toward the target, rotate the hips before the shoulders and finish with the throwing hand to the opposite hip.'],
    cues: ['Hips lead, arm follows', 'Front foot points at the target'],
    mistakes: ['Throwing all arm with square hips, which costs velocity and strains the shoulder.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'catching-in-traffic', name: 'Catching Through Contact', skills: ['catching-in-traffic', 'ball-security'],
    qualities: { 'trunk-anti-rotation': 0.6, 'grip': 0.6, 'reactive-strength': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'rectus-abdominis': 0.5, 'biceps-brachii': 0.4 },
    equipment: ['ball', 'partner'], prop: 'ball-oval', surface: 'field',
    setup: ['A passer and a partner holding a pad or hand shield beside the catch point.'],
    execution: ['Run a short slant; as the ball arrives the partner bumps you with the pad.', 'Catch with the hands away from the body, then tuck the ball high and tight immediately.'],
    cues: ['Eyes on the ball into the hands', 'Catch, tuck, then turn upfield'],
    mistakes: ['Body-catching against the chest, which fails as soon as there is contact.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'isometric-hold', minAge: 14,
  },
  {
    slug: 'ball-security-gauntlet', name: 'Ball-Security Gauntlet', skills: ['ball-security'],
    qualities: { 'grip': 0.8, 'trunk-anti-rotation': 0.7, 'acceleration': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'biceps-brachii': 0.5, 'obliques-external': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-oval', surface: 'field',
    setup: ['Two lines of teammates two yards apart forming a 10-yard gauntlet.'],
    execution: ['Carry the ball high and tight through the gauntlet while teammates punch and rip at it.', 'Switch the ball to the outside arm and repeat.'],
    cues: ['Five points of pressure: fingers, forearm, bicep, chest, elbow', 'Cover up with the free hand in traffic'],
    mistakes: ['Letting the ball drift away from the body as you run.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'hand-fighting-shield', name: 'Hand-Fighting on the Shield', skills: ['hand-fighting', 'block-drive'],
    qualities: { 'upper-body-push': 0.8, 'reactive-strength': 0.6, 'grip': 0.5 },
    muscles: { 'triceps-brachii': 0.7, 'pectoralis-major': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['partner'], surface: 'field', minAge: 14,
    setup: ['Partner holds a hand shield at chest height in a good stance.'],
    execution: ['From a two-point stance, strike the shield with both hands inside, thumbs up, and lock out.', 'Partner swipes at your hands; re-fit inside and strike again for the full interval.'],
    cues: ['Inside hands win', 'Strike with the hips, not just the arms'],
    mistakes: ['Winding up the hands wide, which gives the defender your chest.'],
    defaultDose: time(4, 15), restSeconds: 45, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'first-step-get-off', name: 'Get-Off First-Step Starts', skills: ['first-step-quickness'],
    qualities: { 'acceleration': 0.9, 'horizontal-power': 0.8, 'reactive-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'gastrocnemius': 0.6 },
    equipment: ['cones'], surface: 'field',
    setup: ['Three-point stance at a line, a cone five yards ahead.'],
    execution: ['On a visual cue (ball movement or hand drop), explode out for five yards.', 'Your first step is short and powerful; stay low for the whole five yards.'],
    cues: ['Move on the ball, not the sound', 'Flat back, push the ground away'],
    mistakes: ['Standing straight up out of the stance on the first step.'],
    defaultDose: reps(4, 5), restSeconds: 45, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'w-drill-backpedal', name: 'W-Drill Backpedal Breaks', skills: ['lateral-agility'],
    qualities: { 'change-of-direction': 0.8, 'deceleration': 0.7, 'lateral-power': 0.6 },
    muscles: { 'vastus-medialis': 0.6, 'gluteus-medius': 0.6, 'adductors': 0.5 },
    equipment: ['cones'], surface: 'field',
    setup: ['Five cones in a W shape, 5 yards apart.'],
    execution: ['Backpedal to the first cone, break forward at 45 degrees to the next, backpedal again — through the whole W.', 'Stay in a low, balanced position with your weight over the balls of the feet.'],
    cues: ['Short, quick steps', 'Plant and drive — no rounded breaks'],
    mistakes: ['Popping up tall on every break, which slows the change of direction.'],
    defaultDose: reps(3, 4), restSeconds: 60, startPose: 'lateral-shuffle', endPose: 'cut',
  },
  {
    slug: 'sled-drive-blocking', name: 'Sled Drive', skills: ['block-drive'],
    qualities: { 'lower-body-strength': 0.9, 'horizontal-power': 0.8, 'upper-body-push': 0.5 },
    muscles: { 'gluteus-maximus': 0.8, 'vastus-lateralis': 0.7, 'gastrocnemius': 0.5 },
    equipment: ['sled'], surface: 'field', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Load a sled moderately so you can drive it continuously for 10 yards.'],
    execution: ['Fit your hands on the pad, drop the hips and drive with short, choppy steps.', 'Keep the back flat and the head up for the full distance.'],
    cues: ['Hips low, feet chopping', 'Push through the balls of the feet'],
    mistakes: ['Overloading so the steps become long lunges instead of driving steps.'],
    defaultDose: dist(4, 10), restSeconds: 90, startPose: 'horizontal-push', endPose: 'sprint-cycle',
  },
  {
    slug: 'kicking-approach-and-strike', name: 'Kicking Approach and Strike', skills: ['kicking-power'],
    qualities: { 'rotational-power': 0.8, 'hip-mobility': 0.7, 'single-leg-stability': 0.6 },
    muscles: { 'iliopsoas': 0.7, 'rectus-femoris': 0.7, 'adductors': 0.5 },
    equipment: ['ball'], prop: 'ball-oval', surface: 'field',
    setup: ['Ball on a tee, your usual approach steps marked.'],
    execution: ['Take your approach, plant beside the ball and swing through from the hip.', 'Follow through toward the target and land on the kicking foot.'],
    cues: ['Lock the ankle', 'Plant foot points at the target'],
    mistakes: ['Over-striding into the plant, which kills the hip swing.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'instep-strike', endPose: 'instep-strike',
  },
]);

const BASKETBALL = sportDrills('basketball', [
  {
    slug: 'form-shooting-ladder', name: 'Form Shooting Ladder', skills: ['shooting-mechanics', 'free-throw-consistency'],
    qualities: { 'shoulder-stability': 0.6, 'vertical-power': 0.5, 'single-leg-stability': 0.4 },
    muscles: { 'triceps-brachii': 0.6, 'deltoid-anterior': 0.5, 'forearm-flexors': 0.5 },
    equipment: ['ball'], prop: 'ball-round', surface: 'court',
    setup: ['Start one step in front of the rim, directly in line with it.'],
    execution: ['One-hand form shots: elbow under the ball, snap the wrist, hold the follow-through.', 'Make five in a row before taking a step back; work out to the free-throw line.'],
    cues: ['Elbow in, eyes on the rim', 'Hand in the cookie jar'],
    mistakes: ['Moving back before the short shots are automatic, which grooves bad form at range.'],
    defaultDose: reps(3, 15), restSeconds: 30, startPose: 'squat', endPose: 'vertical-push',
  },
  {
    slug: 'free-throw-routine', name: 'Free-Throw Routine Under Fatigue', skills: ['free-throw-consistency'],
    qualities: { 'aerobic-base': 0.5, 'shoulder-stability': 0.5 },
    muscles: { 'triceps-brachii': 0.5, 'forearm-flexors': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['ball'], prop: 'ball-round', surface: 'court',
    setup: ['A ball at the free-throw line.'],
    execution: ['Sprint baseline to baseline twice, then shoot two free throws using your full pre-shot routine.', 'Record makes; the goal is the same routine every time, tired or not.'],
    cues: ['Same routine, every time', 'Breathe out before the shot'],
    mistakes: ['Rushing the routine because you are out of breath.'],
    defaultDose: reps(5, 2), restSeconds: 20, startPose: 'sprint-cycle', endPose: 'vertical-push',
  },
  {
    slug: 'two-ball-dribbling', name: 'Two-Ball Dribbling Series', skills: ['ball-handling'],
    qualities: { 'grip': 0.5, 'reactive-strength': 0.5, 'trunk-anti-rotation': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'forearm-extensors': 0.6, 'deltoid-anterior': 0.4 },
    equipment: ['ball'], prop: 'ball-round', surface: 'court',
    setup: ['Two basketballs, in an athletic stance.'],
    execution: ['30 seconds each: simultaneous pounds, alternating pounds, crossovers in front, then walk forward and back.', 'Keep your eyes up on a spot on the wall throughout.'],
    cues: ['Pound it hard — below the knee', 'Eyes up'],
    mistakes: ['Watching the balls, which trains a habit you cannot use in a game.'],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'defensive-slide-closeouts', name: 'Defensive Slides and Closeouts', skills: ['lateral-quickness'],
    qualities: { 'lateral-power': 0.9, 'deceleration': 0.7, 'change-of-direction': 0.6 },
    muscles: { 'gluteus-medius': 0.7, 'adductors': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['cones'], surface: 'court',
    setup: ['Two cones 4 yards apart on the lane line.'],
    execution: ['Slide cone to cone without crossing the feet, touching each cone.', 'On the coach\'s call, sprint out and close out with short choppy steps and a high hand.'],
    cues: ['Push with the trail foot', 'Chop, chop — don\'t fly by'],
    mistakes: ['Bringing the feet together or crossing them mid-slide.'],
    defaultDose: time(4, 20), restSeconds: 40, startPose: 'lateral-shuffle', endPose: 'deceleration-plant',
  },
  {
    slug: 'mikan-drill', name: 'Mikan Finishing Drill', skills: ['finishing-at-rim'],
    qualities: { 'vertical-power': 0.6, 'reactive-strength': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'gastrocnemius': 0.6, 'gluteus-maximus': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['ball'], prop: 'ball-round', surface: 'court',
    setup: ['Stand under the rim with the ball.'],
    execution: ['Right-hand layup off the left foot, catch it before it lands, step across and finish left-handed off the right foot.', 'Continuous rhythm, never letting the ball hit the floor.'],
    cues: ['Ball high — never below the chin', 'Use the backboard'],
    mistakes: ['Bringing the ball down to the waist between reps where defenders strip it.'],
    defaultDose: time(3, 30), restSeconds: 30, startPose: 'vertical-jump', endPose: 'vertical-push', constraintAxes: ['opposition'],
  },
  {
    slug: 'rebound-tip-series', name: 'Rebound Tip Series', skills: ['rebounding-timing', 'vertical-jump'],
    qualities: { 'reactive-strength': 0.9, 'vertical-power': 0.8, 'landing-mechanics': 0.5 },
    muscles: { 'gastrocnemius': 0.7, 'soleus': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['ball'], prop: 'ball-round', surface: 'court',
    setup: ['Stand beside the backboard with the ball.'],
    execution: ['Toss the ball against the board and tip it back up with two hands on consecutive jumps.', 'On the last jump, rebound it strongly with two hands and land in a wide, balanced stance.'],
    cues: ['Quick off the floor', 'Chin the ball on the landing'],
    mistakes: ['Landing on one foot or with knees caving in after the final rebound.'],
    defaultDose: contacts(3, 8), restSeconds: 60, startPose: 'pogo', endPose: 'landing',
  },
  {
    slug: 'change-of-pace-dribble', name: 'Change-of-Pace Dribble Attacks', skills: ['change-of-pace', 'ball-handling'],
    qualities: { 'acceleration': 0.8, 'deceleration': 0.7, 'change-of-direction': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'biceps-femoris': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['ball', 'cones'], prop: 'ball-round', surface: 'court',
    setup: ['Cones at half court, the wing and the elbow.'],
    execution: ['Dribble at half speed to the first cone, hesitate, then explode past it at full speed.', 'Repeat at each cone and finish at the rim.'],
    cues: ['Sell the slow, then go', 'Push the ball out in front on the burst'],
    mistakes: ['Playing at one speed, which is easy to guard.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'deceleration-plant', endPose: 'sprint-cycle',
  },
]);

const BASEBALL = sportDrills('baseball', [
  {
    slug: 'long-toss-progression', name: 'Long-Toss Progression', skills: ['throwing-velocity', 'arm-care'],
    qualities: { 'overhead-power': 0.8, 'rotational-power': 0.7, 'shoulder-stability': 0.6 },
    muscles: { 'latissimus-dorsi': 0.6, 'obliques-external': 0.6, 'infraspinatus': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['After a full arm warm-up, start 30 feet from a partner.'],
    execution: ['Throw with a relaxed arc, moving back 10–15 feet every few throws as the arm feels loose.', 'Stop when your throws lose their line, then work back in with firm, on-a-line throws.'],
    cues: ['Stay relaxed — arc the ball on the way out', 'Step and turn the hips to throw'],
    mistakes: ['Throwing max-effort before the arm is warm.'],
    defaultDose: reps(1, 30), restSeconds: 60, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'band-arm-care', name: 'Band Arm-Care Routine', skills: ['arm-care'],
    qualities: { 'shoulder-stability': 0.9, 'upper-body-pull': 0.5 },
    muscles: { 'infraspinatus': 0.8, 'teres-minor': 0.7, 'trapezius-lower': 0.6 },
    equipment: ['band'], surface: 'anywhere',
    setup: ['A light resistance band anchored at elbow height.'],
    execution: ['Complete external rotations, internal rotations, pull-aparts and "Y" raises back to back.', 'Move slowly with control — 2 seconds out, 2 seconds back.'],
    cues: ['Elbow pinned to your side on rotations', 'Squeeze the shoulder blades together'],
    mistakes: ['Using a heavy band and swinging the body to move it.'],
    defaultDose: reps(2, 15, 'light band'), restSeconds: 30, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
  {
    slug: 'front-toss-hitting', name: 'Front Toss Line Drives', skills: ['exit-velocity', 'bat-speed'],
    qualities: { 'rotational-power': 0.9, 'horizontal-power': 0.5, 'grip': 0.5 },
    muscles: { 'obliques-external': 0.7, 'gluteus-maximus': 0.6, 'forearm-flexors': 0.5 },
    equipment: ['bat', 'ball', 'partner', 'net'], prop: 'bat', surface: 'field',
    setup: ['Partner tosses underhand from behind a screen 15 feet in front.'],
    execution: ['Load, stride and drive the ball back up the middle on a line.', 'Mix locations: inside pitches pulled, outside pitches driven the other way.'],
    cues: ['Knob to the ball', 'Back hip drives through'],
    mistakes: ['Casting the hands away from the body, which slows the bat and weakens contact.'],
    defaultDose: reps(4, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'overload-underload-swings', name: 'Heavy/Light Bat Swings', skills: ['bat-speed'],
    qualities: { 'rotational-power': 0.9, 'grip': 0.5, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-internal': 0.7, 'forearm-flexors': 0.6, 'latissimus-dorsi': 0.5 },
    equipment: ['bat'], prop: 'bat', surface: 'anywhere', minAge: 14,
    setup: ['A slightly heavier bat (or a donut) and your game bat.'],
    execution: ['Take five max-intent dry swings with the heavier bat, then five with your game bat.', 'Every swing is at full intent with full rest between sets.'],
    cues: ['Every swing is game speed', 'Stay balanced on the finish'],
    mistakes: ['Using a bat so heavy that your swing path changes.'],
    defaultDose: reps(3, 10), restSeconds: 60, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'hip-shoulder-separation-drill', name: 'Hip-Shoulder Separation Drill', skills: ['rotational-sequencing', 'pitching-mechanics'],
    qualities: { 'hip-mobility': 0.8, 'trunk-anti-rotation': 0.6, 'rotational-power': 0.6 },
    muscles: { 'obliques-external': 0.7, 'deep-hip-rotators': 0.6, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Stand in your stride position, arms across the chest.'],
    execution: ['Rotate the hips toward the target while keeping the shoulders closed, hold for one second.', 'Then let the shoulders follow; repeat slowly, then at game speed.'],
    cues: ['Hips first, shoulders later', 'Stay tall through the spine'],
    mistakes: ['Hips and shoulders turning together as one block.'],
    defaultDose: reps(3, 8), restSeconds: 30, startPose: 'swing-stride', endPose: 'trunk-rotation',
  },
  {
    slug: 'base-running-turns', name: 'Home-to-Second Base Running', skills: ['base-running-speed'],
    qualities: { 'acceleration': 0.8, 'max-velocity': 0.7, 'change-of-direction': 0.5 },
    muscles: { 'biceps-femoris': 0.7, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['cones'], surface: 'field',
    setup: ['A diamond or cones set at 90-foot intervals.'],
    execution: ['Swing from the box, run through a banana turn at first and hit the inside corner of the bag.', 'Accelerate hard to second and slide or pull up.'],
    cues: ['Bow out early, then run straight at the bag', 'Lean into the turn'],
    mistakes: ['Running straight to first and making a wide turn at the bag.'],
    defaultDose: reps(4, 3), restSeconds: 90, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
]);

const SOFTBALL = sportDrills('softball', [
  {
    slug: 'windmill-k-drill', name: 'Windmill K-Drill', skills: ['windmill-pitch-velocity'],
    qualities: { 'overhead-power': 0.7, 'rotational-power': 0.7, 'shoulder-stability': 0.6 },
    muscles: { 'deltoid-anterior': 0.6, 'pectoralis-major': 0.5, 'triceps-brachii': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['Stand in the stride position, a catcher 20 feet away.'],
    execution: ['Start with the ball at the top of the circle (the K position) and whip it down through the release.', 'Finish with a strong brush of the forearm past the hip.'],
    cues: ['Loose arm, fast circle', 'Brush the hip at release'],
    mistakes: ['Muscling the arm around instead of letting it whip.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'tee-work-power', name: 'Tee Work for Exit Velocity', skills: ['exit-velocity', 'bat-speed'],
    qualities: { 'rotational-power': 0.9, 'grip': 0.5, 'horizontal-power': 0.5 },
    muscles: { 'obliques-external': 0.7, 'gluteus-maximus': 0.6, 'forearm-flexors': 0.5 },
    equipment: ['bat', 'ball', 'net'], prop: 'bat', surface: 'anywhere',
    setup: ['Tee at belly-button height, ball placed just in front of home plate.'],
    execution: ['Drive the ball into the back of the net on a line.', 'Move the tee inside and outside every five swings.'],
    cues: ['Stay through the ball', 'Knob down, barrel up'],
    mistakes: ['Pulling the front shoulder off the ball early.'],
    defaultDose: reps(4, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'slap-footwork', name: 'Slap-Hitting Footwork', skills: ['slap-hitting-speed', 'base-running-speed'],
    qualities: { 'acceleration': 0.8, 'rotational-power': 0.5, 'change-of-direction': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'gastrocnemius': 0.6, 'biceps-femoris': 0.5 },
    equipment: ['bat', 'ball'], prop: 'bat', surface: 'field',
    setup: ['Left-handed batter\'s box, a ball on a tee or soft toss.'],
    execution: ['Crossover step toward the pitcher, make contact while moving, and sprint out of the box to first.', 'Keep the bat head above the hands and slap the ball on the ground.'],
    cues: ['Crossover, then contact', 'Run through the ball'],
    mistakes: ['Stopping the feet at contact, which loses the head start.'],
    defaultDose: reps(4, 5), restSeconds: 60, startPose: 'crossover-stride', endPose: 'sprint-cycle',
  },
  {
    slug: 'infield-reaction-grounders', name: 'Infield Reaction Grounders', skills: ['first-step-quickness', 'throwing-velocity'],
    qualities: { 'reactive-strength': 0.7, 'lateral-power': 0.7, 'acceleration': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'adductors': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['Ready position at shortstop; a partner rolls or hits grounders left and right.'],
    execution: ['React with a quick first step, field the ball out front and come up throwing to first.', 'Alternate backhands and forehands.'],
    cues: ['Get low early', 'Field it in front of your body'],
    mistakes: ['Flat-footed start — be on the balls of your feet before the pitch.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'overhead-throw',
  },
  {
    slug: 'hip-lead-dry-swings', name: 'Hip-Lead Dry Swings', skills: ['rotational-sequencing', 'bat-speed'],
    qualities: { 'rotational-power': 0.8, 'hip-mobility': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-external': 0.7, 'deep-hip-rotators': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['bat'], prop: 'bat', surface: 'anywhere',
    setup: ['Stance in front of a mirror or phone camera with your game bat.'],
    execution: ['Stride and hold for a count with the hands back, then fire the back hip first and let the hands follow.', 'Freeze at contact and check: belly button facing the pitcher, hands still inside the ball, head still.'],
    cues: ['Hips, then shoulders, then hands', 'Stay tall through the turn'],
    mistakes: ['Hands and hips firing together, which spins the body off the ball.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'med-ball-scoop-toss', name: 'Med-Ball Scoop Toss', skills: ['rotational-sequencing', 'exit-velocity'],
    qualities: { 'rotational-power': 0.9, 'horizontal-power': 0.5, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-internal': 0.7, 'gluteus-maximus': 0.6, 'latissimus-dorsi': 0.4 },
    equipment: ['med-ball', 'wall'], prop: 'ball-round', surface: 'anywhere',
    setup: ['Stand side-on to a solid wall, an arm\'s length plus a step away, holding a 2–4 kg ball at the back hip.'],
    execution: ['Load into the back hip, then rotate hard and release the ball into the wall at chest height.', 'Catch the rebound, reset fully, and repeat; switch sides to stay balanced.'],
    cues: ['Throw it through the wall', 'Back foot turns like a swing'],
    mistakes: ['Arm-throwing the ball instead of letting the hips turn it.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'rotational-throw', endPose: 'rotational-throw',
  },
  {
    slug: 'outfield-crow-hop-throws', name: 'Outfield Crow-Hop Throws', skills: ['throwing-velocity'],
    qualities: { 'overhead-power': 0.8, 'rotational-power': 0.6, 'shoulder-stability': 0.5 },
    muscles: { 'latissimus-dorsi': 0.6, 'deltoid-anterior': 0.5, 'obliques-external': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['After a full arm warm-up, a partner 45–60 feet away at the relay spot.'],
    execution: ['Field a rolled ball moving forward, crow-hop to gain momentum, and throw on a line to the partner\'s chest.', 'Every throw should arrive on one hop or less.'],
    cues: ['Hop, then throw — one motion', 'Point the glove shoulder at the target'],
    mistakes: ['Throwing flat-footed after the catch, which loses all the run-up.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'overhead-throw',
  },
]);

const FLAG = sportDrills('flag-football', [
  {
    slug: 'flag-pull-mirror', name: 'Flag-Pull Mirror Drill', skills: ['flag-pull-reaction', 'lateral-agility'],
    qualities: { 'lateral-power': 0.8, 'reactive-strength': 0.7, 'deceleration': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'adductors': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['cones', 'partner'], surface: 'field',
    setup: ['A 5-yard-wide box; the ball carrier wears flags.'],
    execution: ['The carrier jukes side to side trying to escape the box; the defender mirrors and pulls a flag.', 'Swap roles every rep.'],
    cues: ['Watch the hips, not the feet', 'Break down before you reach'],
    mistakes: ['Lunging at the flag and over-running the carrier.'],
    defaultDose: reps(4, 5), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'cut',
  },
  {
    slug: 'route-tree-sprints', name: 'Route-Tree Sprints', skills: ['route-running', 'deceleration-and-cut', 'sprint-speed'],
    qualities: { 'deceleration': 0.8, 'change-of-direction': 0.8, 'acceleration': 0.7 },
    muscles: { 'vastus-medialis': 0.6, 'biceps-femoris': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['cones', 'ball'], prop: 'ball-oval', surface: 'field',
    setup: ['Mark a 10-yard stem with cones.'],
    execution: ['Run slant, out, curl and post routes at full speed, sinking the hips at the break.', 'Catch a pass out of each break.'],
    cues: ['Sell vertical first', 'Three quick steps into the break'],
    mistakes: ['Rounding the break so the defender stays on your hip.'],
    defaultDose: reps(4, 4), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'cut',
  },
  {
    slug: 'one-hand-catch-series', name: 'One-Handed Catch Series', skills: ['one-handed-catching'],
    qualities: { 'reactive-strength': 0.5, 'grip': 0.5, 'shoulder-stability': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'deltoid-anterior': 0.4, 'biceps-brachii': 0.4 },
    equipment: ['ball', 'partner'], prop: 'ball-oval', surface: 'field',
    setup: ['Partner 8 yards away.'],
    execution: ['Catch 10 balls with the right hand, 10 with the left, bringing each one straight to the chest.', 'Then add a jog so you catch on the move.'],
    cues: ['Soft hand — give with the ball', 'Look it all the way in'],
    mistakes: ['Snatching at the ball with a stiff hand.'],
    defaultDose: reps(2, 20), restSeconds: 30, startPose: 'vertical-push', endPose: 'isometric-hold',
  },
  {
    slug: 'quick-release-accuracy', name: 'Quick-Release Accuracy Throws', skills: ['throwing-accuracy'],
    qualities: { 'overhead-power': 0.6, 'rotational-power': 0.6, 'shoulder-stability': 0.5 },
    muscles: { 'latissimus-dorsi': 0.5, 'obliques-external': 0.5, 'triceps-brachii': 0.5 },
    equipment: ['ball', 'cones'], prop: 'ball-oval', surface: 'field',
    setup: ['Targets (a hoop, a bin, a partner\'s hands) at 10, 15 and 20 yards.'],
    execution: ['Catch a snap, set your feet in two steps and throw to the called target.', 'Score hits; keep release time under two seconds.'],
    cues: ['Eyes to the target first', 'Throw from the ear'],
    mistakes: ['Aiming the ball with a slow, pushed release.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'hesitation-burst', name: 'Hesitation and Burst', skills: ['change-of-pace', 'deceleration-and-cut'],
    qualities: { 'acceleration': 0.8, 'deceleration': 0.8, 'change-of-direction': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'vastus-medialis': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['cones', 'ball'], prop: 'ball-oval', surface: 'field',
    setup: ['A 20-yard lane with a cone at 8 yards where a defender stands.'],
    execution: ['Carry the ball at three-quarter speed, chop the feet into a hesitation at the cone, then explode past.', 'Alternate going left and right; add a live flag-puller when the timing is sharp.'],
    cues: ['Slow down to speed up', 'Eyes up, hips square in the hesitation'],
    mistakes: ['Stopping completely — a hesitation keeps the feet moving.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'deceleration-plant', endPose: 'sprint-cycle', constraintAxes: ['opposition'],
  },
  {
    slug: 'flying-20s', name: 'Flying 20s', skills: ['sprint-speed', 'change-of-pace'],
    qualities: { 'max-velocity': 0.9, 'acceleration': 0.6, 'repeat-sprint': 0.5 },
    muscles: { 'biceps-femoris': 0.7, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['cones'], surface: 'field',
    setup: ['Cones at 0, 20 and 40 yards after a full warm-up.'],
    execution: ['Build up over the first 20 yards, then sprint the next 20 at true top speed.', 'Walk back for full recovery between reps.'],
    cues: ['Tall hips, quick feet', 'Relax the face and shoulders'],
    mistakes: ['Running the build-up zone flat out, so there is nothing left for the fast zone.'],
    defaultDose: reps(1, 5), restSeconds: 120, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'flag-defense-angle-pursuit', name: 'Angle Pursuit and Pull', skills: ['flag-pull-reaction', 'lateral-agility'],
    qualities: { 'acceleration': 0.8, 'change-of-direction': 0.7, 'reactive-strength': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'biceps-femoris': 0.5, 'adductors': 0.5 },
    equipment: ['cones', 'partner'], surface: 'field',
    setup: ['A ball carrier starts 10 yards wide of the defender; both run toward a sideline cone 20 yards ahead.'],
    execution: ['Defender takes an angle to cut the carrier off before the cone rather than chasing from behind.', 'Break down within two yards and pull the flag on the near hip.'],
    cues: ['Aim at where they will be, not where they are', 'Break down, then reach'],
    mistakes: ['Chasing the carrier\'s back and never catching up.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'cut',
  },
]);


/** Written for goalkeepers only (`positions`): outfield plans never get them. */
const SOCCER_KEEPER = sportDrills('soccer', [
  {
    slug: 'goalkeeper-set-and-shuffle', name: 'Keeper Set Position and Shuffle', positions: ['goalkeeper'],
    qualities: { 'lateral-power': 0.8, 'reactive-strength': 0.6, 'deceleration': 0.5 },
    muscles: { 'gluteus-medius': 0.7, 'adductors': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['cones'], prop: 'ball-round', surface: 'field',
    setup: ['Two cones on the goal line, one at each post.'],
    execution: ['Shuffle post to post in the set position — feet shoulder-width, knees bent, weight on the balls of the feet, hands up in front.', 'Stop and set (a small hop to plant both feet) at each post and in the middle before moving again.'],
    cues: ['Feet never cross', 'Hands stay up and in front'],
    mistakes: ['Standing up tall between steps, so you are late to the next shot.'],
    defaultDose: time(4, 30), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'goalkeeper-low-diving-saves', name: 'Keeper Low Diving Saves', positions: ['goalkeeper'],
    qualities: { 'lateral-power': 0.8, 'landing-mechanics': 0.7, 'reactive-strength': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'obliques-external': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['On grass or a mat; a partner rolls or pushes balls just out of reach to either side.'],
    execution: ['From the set position, step toward the ball and dive sideways, catching it with the bottom hand behind and the top hand on top.', 'Land on your side (never on the elbow), pull the ball in, and get back up to set.'],
    cues: ['Step, then dive — never fall', 'Land on the side of the body, not the elbow'],
    mistakes: ['Diving back toward the goal instead of forward to the ball.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'lateral-bound', endPose: 'landing',
  },
  {
    slug: 'goalkeeper-high-catch', name: 'Keeper High Catch (W Catch)', positions: ['goalkeeper'],
    qualities: { 'vertical-power': 0.9, 'reactive-strength': 0.6, 'landing-mechanics': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'gastrocnemius': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field',
    setup: ['A partner lobs balls high toward you from about 10 yards.'],
    execution: ['Take off from one leg with the other knee driving up for protection and catch the ball at the highest point.', 'Hands make a W behind the ball; bring it down into the chest and land balanced.'],
    cues: ['Catch it in front of your head, not above it', 'Knee up, eyes on the ball'],
    mistakes: ['Waiting on the ground and letting the ball drop onto you.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'goalkeeper-reaction-saves', name: 'Keeper Reaction Saves', positions: ['goalkeeper'],
    qualities: { 'reactive-strength': 0.9, 'lateral-power': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'deltoid-anterior': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['ball', 'partner', 'goal'], prop: 'ball-round', surface: 'field',
    setup: ['In goal; a partner shoots firmly from 8–10 yards.'],
    execution: ['Set as the shooter plants, then react and save the shot to the hands, behind the ball.', 'Get back to set before the next shot; the partner varies height and side.'],
    cues: ['Set — small hop — as they strike', 'Get your body behind the ball'],
    mistakes: ['Still moving when the ball is struck.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'athletic-stance', endPose: 'athletic-stance',
  },
  {
    slug: 'goalkeeper-overarm-distribution', name: 'Keeper Overarm Throw', positions: ['goalkeeper'],
    qualities: { 'rotational-power': 0.7, 'shoulder-stability': 0.6 },
    muscles: { 'latissimus-dorsi': 0.6, 'pectoralis-major': 0.5, 'obliques-external': 0.5 },
    equipment: ['ball', 'cones'], prop: 'ball-round', surface: 'field',
    setup: ['A target cone 25–35 yards away.'],
    execution: ['Step toward the target, bring the ball back with a straight arm and bowl it over the top.', 'Release so the ball skims low and fast to the target; switch to a rolled pass for short range.'],
    cues: ['Straight arm over the top', 'Point the front shoulder at the target'],
    mistakes: ['Throwing it high and slow so the receiver has to wait.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'overhead-throw', endPose: 'overhead-throw',
  },
  {
    slug: 'goalkeeper-punt-distribution', name: 'Keeper Punts', positions: ['goalkeeper'],
    qualities: { 'rotational-power': 0.6, 'single-leg-stability': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'rectus-femoris': 0.7, 'iliopsoas': 0.6, 'gluteus-medius': 0.4 },
    equipment: ['ball'], prop: 'ball-round', surface: 'field',
    setup: ['In the penalty area with a pile of balls.'],
    execution: ['Hold the ball out in front, drop it and volley it with the laces as it falls.', 'Aim for distance with a flat, driven flight; land on the kicking foot.'],
    cues: ['Drop it, don\'t throw it up', 'Toe down, lock the ankle'],
    mistakes: ['Tossing the ball up so the timing changes every kick.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'instep-strike', endPose: 'instep-strike',
  },
]);

export const FIELD_AND_COURT_DRILLS = [...SOCCER, ...SOCCER_KEEPER, ...FOOTBALL, ...BASKETBALL, ...BASEBALL, ...SOFTBALL, ...FLAG];
