/**
 * Sport drills — wrestling, judo, fencing, weightlifting, powerlifting,
 * strength & conditioning team, gymnastics, competitive spirit, sideline
 * cheer, competitive dance, step team, color guard and marching band.
 * Written from the standard progressions coaches in each sport teach — the
 * setup, the execution, what a coach shouts, and the mistake that ruins it.
 * Every barbell technique drill is COACHED and 15+, with light, technique
 * loads and youth-envelope doses (§2).
 */

import { contacts, dist, reps, formatDrills, sportDrills, time } from '../drillKit.js';

const WRESTLING = sportDrills('wrestling', [
  {
    slug: 'stance-and-motion', name: 'Stance and Motion', skills: ['mat-awareness', 'hand-control'],
    qualities: { 'lateral-power': 0.6, 'single-leg-stability': 0.5, 'anaerobic-capacity': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'vastus-lateralis': 0.5, 'erector-spinae': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['Square or staggered stance in the centre of the mat, elbows in, hands in front of the knees.'],
    execution: ['Circle, step, and change levels on the coach\'s whistle without ever bringing the feet together.', 'Keep hands active in front of you — fight for an imaginary inside tie while you move.'],
    cues: ['Head up, hips down', 'Never cross your feet'],
    mistakes: ['Standing tall between level changes, which gives the opponent a free shot.'],
    defaultDose: time(4, 45), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'penetration-step-shots', name: 'Penetration Step Shots', skills: ['takedown-power', 'hip-explosiveness'],
    qualities: { 'horizontal-power': 0.9, 'lower-body-strength': 0.6, 'acceleration': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'rectus-femoris': 0.6, 'vastus-medialis': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Start in stance on a mat with room to travel forward three or four yards.'],
    execution: ['Change levels, drive the lead knee to the mat just past an imaginary opponent\'s feet, then step the trail leg up and finish.', 'Return to stance and shoot again; alternate lead legs every set.'],
    cues: ['Level change before you shoot', 'Head up, back straight on the knee'],
    mistakes: ['Reaching with the arms instead of penetrating with the hips.'],
    defaultDose: reps(4, 8), restSeconds: 45, startPose: 'lunge', endPose: 'split-squat',
  },
  {
    slug: 'sprawl-reaction', name: 'Sprawl Reaction Drill', skills: ['sprawl-speed', 'scrambling-endurance'],
    qualities: { 'reactive-strength': 0.8, 'hip-mobility': 0.6, 'anaerobic-capacity': 0.6 },
    muscles: { 'iliopsoas': 0.5, 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Face a partner in stance; the partner fakes and shoots at the legs.'],
    execution: ['As soon as the partner changes level, throw the legs back and drive the hips down to the mat.', 'Crossface, circle to the back and return to stance before the next shot.'],
    cues: ['Hips heavy on the mat', 'Legs back, not out to the sides'],
    mistakes: ['Sprawling with the hips up, which lets the shooter finish anyway.'],
    defaultDose: reps(4, 8), restSeconds: 40, startPose: 'lateral-shuffle', endPose: 'isometric-hold',
  },
  {
    slug: 'hand-fighting-ties', name: 'Hand-Fighting Ties', skills: ['hand-control', 'grip-strength'],
    qualities: { 'grip': 0.8, 'upper-body-pull': 0.6, 'anaerobic-capacity': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'biceps-brachii': 0.5, 'latissimus-dorsi': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Partners in stance, collar ties and wrist control allowed, no shots.'],
    execution: ['Fight for inside control: collar tie, wrist control, two-on-one, clearing the opponent\'s hands.', 'Score a point each time you snap the partner\'s head down or win a two-on-one.'],
    cues: ['Inside hands win', 'Snap, then move your feet'],
    mistakes: ['Standing flat-footed while hand fighting — the feet must stay in motion.'],
    defaultDose: time(4, 60), restSeconds: 45, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
  {
    slug: 'towel-grip-hangs', name: 'Towel Grip Hangs', skills: ['grip-strength'],
    qualities: { 'grip': 0.9, 'upper-body-pull': 0.5 },
    muscles: { 'forearm-flexors': 0.8, 'latissimus-dorsi': 0.5, 'brachioradialis': 0.5 },
    equipment: ['pull-up-bar'], surface: 'gym',
    setup: ['Loop two towels over a pull-up bar, shoulder width apart.'],
    execution: ['Grip a towel in each hand and hang with the shoulders engaged, not relaxed.', 'Step down before the grip fails completely; rest and repeat.'],
    cues: ['Squeeze like you are wringing it out', 'Shoulders pulled down from your ears'],
    mistakes: ['Hanging passively on the shoulder joints with no tension.'],
    defaultDose: time(3, 30), restSeconds: 60, startPose: 'vertical-pull', endPose: 'isometric-hold',
  },
  {
    slug: 'bridge-and-turn', name: 'Bridge and Turn', skills: ['bridging-strength', 'scrambling-endurance'],
    qualities: { 'trunk-anti-rotation': 0.6, 'hip-mobility': 0.6, 'lower-body-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'neck-extensors': 0.6, 'erector-spinae': 0.5 },
    equipment: ['none'], surface: 'gym', minAge: 14,
    setup: ['Lie on your back on a mat, knees bent, feet flat. Build up from a hip bridge before any neck bridge.'],
    execution: ['Drive the hips high into a bridge, then turn onto the shoulder and hip, coming up to the knees facing the other way.', 'Alternate sides; keep weight on the feet and shoulders, never all on the head.'],
    cues: ['Hips high first, then turn', 'Look where you are turning'],
    mistakes: ['Collapsing onto the top of the head instead of bridging with the hips.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'hinge', endPose: 'trunk-rotation',
  },
  {
    slug: 'stand-up-from-bottom', name: 'Stand-Up From Bottom', skills: ['hip-explosiveness', 'mat-awareness'],
    qualities: { 'lower-body-strength': 0.6, 'vertical-power': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'vastus-lateralis': 0.5, 'obliques-external': 0.4 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Bottom referee position with a partner on top applying light pressure.'],
    execution: ['On the whistle, post the outside leg, drive the back up into the partner, and clear the hands off your waist.', 'Turn to face and return to stance.'],
    cues: ['Back pressure into them', 'Hand control before you turn'],
    mistakes: ['Standing up leaning forward, which lets the top man ride you back down.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'squat', endPose: 'vertical-jump',
  },
  {
    slug: 'shark-bait-scrambles', name: 'Shark-Bait Scrambles', skills: ['scrambling-endurance', 'mat-awareness'],
    qualities: { 'anaerobic-capacity': 0.9, 'repeat-sprint': 0.6, 'grip': 0.5 },
    muscles: { 'gluteus-maximus': 0.5, 'rectus-abdominis': 0.5, 'forearm-flexors': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['One wrestler in the centre; fresh partners take turns rotating in every 20 seconds.'],
    execution: ['Wrestle live from neutral against each fresh partner for the whole interval.', 'Focus on staying in good position when tired — it is a position drill, not a brawl.'],
    cues: ['Good position when tired', 'Keep scoring, keep moving'],
    mistakes: ['Giving up position and flattening out once fatigue hits.'],
    defaultDose: time(3, 90), restSeconds: 120, startPose: 'lateral-shuffle', endPose: 'isometric-hold',
  },
  {
    slug: 'double-leg-finish', name: 'Double-Leg Finish Drill', skills: ['takedown-power'],
    qualities: { 'horizontal-power': 0.8, 'lower-body-strength': 0.7, 'grip': 0.5 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'erector-spinae': 0.5 },
    equipment: ['partner'], surface: 'gym', minAge: 14,
    setup: ['Partner stands in stance and lets you get in on a double leg.'],
    execution: ['Penetrate, lock the hands behind the knees, drive through with the head on the side and turn the corner.', 'Finish on top in control, then reset. Partner gives light resistance only.'],
    cues: ['Head on the side, drive through', 'Turn the corner, don\'t lift straight up'],
    mistakes: ['Lifting with a rounded back instead of driving with the legs.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'lunge', endPose: 'horizontal-push',
  },
  {
    slug: 'hip-heist-series', name: 'Hip-Heist Series', skills: ['hip-explosiveness', 'scrambling-endurance'],
    qualities: { 'hip-mobility': 0.7, 'trunk-anti-rotation': 0.5, 'reactive-strength': 0.5 },
    muscles: { 'obliques-internal': 0.6, 'gluteus-medius': 0.5, 'deltoid-lateral': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['Sit on the mat with both hands and feet down, hips off the floor.'],
    execution: ['Thread one leg under the body and kick it through to switch to face the other way, finishing on hands and feet.', 'Continue side to side quickly without letting the hips drop.'],
    cues: ['Hips off the mat the whole time', 'Snap the leg through'],
    mistakes: ['Sitting down between switches, which slows everything.'],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'mobility-flow', endPose: 'trunk-rotation',
  },
  {
    slug: 'mat-returns', name: 'Mat Returns', skills: ['hand-control', 'takedown-power'],
    qualities: { 'lower-body-strength': 0.6, 'grip': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'forearm-flexors': 0.5, 'erector-spinae': 0.5 },
    equipment: ['partner'], surface: 'gym', minAge: 15,
    setup: ['Partner stands up from bottom position; you are behind with a waist lock.'],
    execution: ['Lock the hands, step to the side, and return the partner to the mat by sweeping the far leg — not by slamming.', 'Follow them down and establish a ride.'],
    cues: ['Hips close, hands locked tight', 'Sweep, never lift and slam'],
    mistakes: ['Lifting the partner high, which is illegal in competition.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'hinge', endPose: 'squat',
  },
  {
    slug: 'sprawl-and-shoot-intervals', name: 'Sprawl-and-Shoot Intervals', skills: ['sprawl-speed', 'scrambling-endurance', 'takedown-power'],
    qualities: { 'anaerobic-capacity': 0.8, 'reactive-strength': 0.6, 'horizontal-power': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5, 'rectus-femoris': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Stance in open mat space; match-length intervals (a period is two minutes).'],
    execution: ['On each whistle, alternate a sprawl and a penetration step, returning to stance each time.', 'Keep going for the whole interval, with clean positions every rep.'],
    cues: ['Snap back to stance', 'Every rep is match speed'],
    mistakes: ['Losing stance between reps as you tire.'],
    defaultDose: time(3, 60), restSeconds: 60, startPose: 'lunge', endPose: 'isometric-hold',
  },
]);

const JUDO = sportDrills('judo', [
  {
    slug: 'ukemi-breakfalls', name: 'Ukemi Breakfall Progression', skills: ['fall-safety'],
    qualities: { 'landing-mechanics': 0.9, 'trunk-anti-rotation': 0.5 },
    muscles: { 'rectus-abdominis': 0.5, 'neck-extensors': 0.5, 'latissimus-dorsi': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['Soft mats; start sitting, then squatting, then standing as each level is clean.'],
    execution: ['Back breakfall: roll back with the chin tucked and slap the mat with both arms at 45 degrees.', 'Progress to side breakfalls both sides, then forward rolling breakfalls.'],
    cues: ['Chin tucked to the chest', 'Slap the mat with the whole arm'],
    mistakes: ['Posting a hand out to catch yourself, which is how wrists get hurt.'],
    defaultDose: reps(3, 8), restSeconds: 30, startPose: 'squat', endPose: 'landing',
  },
  {
    slug: 'uchikomi-entries', name: 'Uchikomi Throw Entries', skills: ['throw-power', 'off-balancing-timing'],
    qualities: { 'rotational-power': 0.8, 'hip-mobility': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'obliques-external': 0.6, 'gluteus-maximus': 0.6, 'latissimus-dorsi': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Partner stands in a natural posture; you take a standard sleeve-lapel grip.'],
    execution: ['Pull to off-balance (kuzushi), turn in for your throw, load the partner on the hips — but do not throw.', 'Step back out and repeat quickly and smoothly.'],
    cues: ['Break balance first, then turn in', 'Hips lower than theirs'],
    mistakes: ['Turning in without breaking balance, so the partner is still standing solid.'],
    defaultDose: reps(4, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'kuzushi-pull-drill', name: 'Kuzushi Off-Balancing Drill', skills: ['off-balancing-timing', 'grip-strength'],
    qualities: { 'upper-body-pull': 0.7, 'grip': 0.7, 'reactive-strength': 0.5 },
    muscles: { 'latissimus-dorsi': 0.7, 'forearm-flexors': 0.6, 'rhomboids': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Standard grip with a partner who moves around the mat.'],
    execution: ['As the partner steps, pull them onto their toes in the direction they are moving.', 'Name the direction (front, back, corner) each time you break their balance.'],
    cues: ['Pull like opening a window', 'Time it with their step'],
    mistakes: ['Pulling against their movement instead of with it.'],
    defaultDose: time(4, 45), restSeconds: 30, startPose: 'horizontal-pull', endPose: 'horizontal-pull',
  },
  {
    slug: 'gi-grip-pull-ups', name: 'Gi Grip Pull-Ups', skills: ['grip-strength'],
    qualities: { 'upper-body-pull': 0.95, 'grip': 0.8 },
    muscles: { 'latissimus-dorsi': 0.8, 'forearm-flexors': 0.7, 'biceps-brachii': 0.6 },
    equipment: ['pull-up-bar'], surface: 'gym',
    setup: ['Drape a judo jacket or two towels over a pull-up bar.'],
    execution: ['Grip the fabric and pull the chest toward the bar under control.', 'Lower slowly; use a band or bent-leg negatives if you can\'t yet do full reps.'],
    cues: ['Crush the fabric', 'Chest to the bar'],
    mistakes: ['Kipping — the grip, not momentum, is the point.'],
    defaultDose: reps(3, 6), restSeconds: 90, startPose: 'vertical-pull', endPose: 'vertical-pull',
  },
  {
    slug: 'newaza-transitions', name: 'Newaza Transition Flow', skills: ['groundwork-transitions'],
    qualities: { 'hip-mobility': 0.7, 'anaerobic-capacity': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-internal': 0.6, 'gluteus-medius': 0.5, 'rectus-abdominis': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Start on the ground with the partner in a defensive turtle position.'],
    execution: ['Flow through a turnover into a hold-down, then transition to a second hold-down as the partner resists lightly.', 'Switch roles every round.'],
    cues: ['Chest-to-chest pressure', 'Move from one control to the next'],
    mistakes: ['Losing contact between positions, which lets the partner escape.'],
    defaultDose: time(4, 60), restSeconds: 60, startPose: 'mobility-flow', endPose: 'isometric-hold',
  },
  {
    slug: 'band-throw-rotations', name: 'Band Throw Rotations', skills: ['throw-power'],
    qualities: { 'rotational-power': 0.8, 'trunk-anti-rotation': 0.6 },
    muscles: { 'obliques-external': 0.7, 'gluteus-maximus': 0.5, 'latissimus-dorsi': 0.5 },
    equipment: ['band'], surface: 'anywhere',
    setup: ['Anchor a band at chest height and hold it with both hands like a sleeve and lapel grip.'],
    execution: ['Step in and rotate powerfully as if turning in for a throw, finishing with the hips through.', 'Return under control and repeat both sides.'],
    cues: ['Feet turn, hips turn, then shoulders', 'Finish looking over the far shoulder'],
    mistakes: ['Rotating only the arms while the hips stay square.'],
    defaultDose: reps(3, 10, 'medium band'), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'randori-intervals', name: 'Randori Rounds', skills: ['throw-power', 'off-balancing-timing', 'groundwork-transitions'],
    qualities: { 'anaerobic-capacity': 0.9, 'grip': 0.6, 'rotational-power': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'gluteus-maximus': 0.5, 'latissimus-dorsi': 0.5 },
    equipment: ['partner'], surface: 'gym', minAge: 14,
    setup: ['Supervised free practice with a similar-sized partner; clean breakfalls only.'],
    execution: ['Standing practice at controlled intensity, attempting your throws and combinations.', 'Stop immediately if a throw goes wrong; reset from grips.'],
    cues: ['Attack, then attack again', 'Breakfall every time'],
    mistakes: ['Stiff-arming the whole round, which trains nothing.'],
    defaultDose: time(4, 120), restSeconds: 90, startPose: 'lateral-shuffle', endPose: 'rotational-throw',
  },
]);

const FENCING = sportDrills('fencing', [
  {
    slug: 'advance-retreat-ladder', name: 'Advance-Retreat Footwork Ladder', skills: ['advance-retreat-speed', 'footwork-endurance'],
    qualities: { 'acceleration': 0.7, 'deceleration': 0.7, 'ankle-stiffness': 0.5 },
    muscles: { 'vastus-lateralis': 0.6, 'gastrocnemius': 0.6, 'gluteus-medius': 0.5 },
    equipment: ['cones'], surface: 'gym',
    setup: ['A marked piste strip (or a line of cones) 7 metres long.'],
    execution: ['Advance, advance, retreat, advance-lunge down the strip on the coach\'s calls, staying in en-garde.', 'Recover to en-garde after every lunge.'],
    cues: ['Front toe lifts first', 'Stay the same height'],
    mistakes: ['Bobbing up and down, which telegraphs every action.'],
    defaultDose: time(5, 45), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'lunge',
  },
  {
    slug: 'lunge-to-target', name: 'Lunge to Target', skills: ['lunge-power', 'distance-judgement'],
    qualities: { 'horizontal-power': 0.9, 'hip-mobility': 0.5, 'single-leg-stability': 0.5 },
    muscles: { 'rectus-femoris': 0.7, 'gluteus-maximus': 0.6, 'vastus-medialis': 0.5 },
    equipment: ['wall'], surface: 'gym',
    setup: ['A wall target or target pad at chest height, starting at lunge distance.'],
    execution: ['Extend the arm first, then drive the back leg to lunge and touch the target.', 'Recover forward or backward to en-garde; vary the start distance so you judge it each time.'],
    cues: ['Arm before foot', 'Back leg drives straight'],
    mistakes: ['Leading with the front foot and dropping the arm, which is too slow and gets hit.'],
    defaultDose: reps(4, 8), restSeconds: 45, startPose: 'lunge', endPose: 'split-squat',
  },
  {
    slug: 'reaction-light-drill', name: 'Reaction Cue Drill', skills: ['reaction-time'],
    qualities: { 'reactive-strength': 0.8, 'acceleration': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'rectus-femoris': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['partner'], surface: 'gym',
    setup: ['En-garde facing a partner who holds a glove or target in each hand.'],
    execution: ['When the partner opens a hand or drops the glove, react with an extension or lunge to that target.', 'Partner varies timing so you cannot anticipate.'],
    cues: ['Relaxed until the cue', 'Explode, don\'t tense'],
    mistakes: ['Guessing the cue and moving early.'],
    defaultDose: reps(4, 8), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'lunge',
  },
  {
    slug: 'point-control-circles', name: 'Point-Control Circles', skills: ['blade-hand-speed', 'feint-timing'],
    qualities: { 'grip': 0.6, 'shoulder-stability': 0.6 },
    muscles: { 'forearm-flexors': 0.6, 'forearm-extensors': 0.6, 'deltoid-anterior': 0.4 },
    equipment: ['wall'], surface: 'gym',
    setup: ['Your weapon (or a stick) and a small target on the wall.'],
    execution: ['Draw small circles and figure eights around the target using only the fingers and wrist.', 'Finish each set by landing the point on the centre.'],
    cues: ['Fingers do the work', 'Small, precise circles'],
    mistakes: ['Moving the whole arm from the shoulder.'],
    defaultDose: time(4, 30), restSeconds: 20, startPose: 'isometric-hold', endPose: 'horizontal-push',
  },
  {
    slug: 'fleche-starts', name: 'Flèche Starts', skills: ['lunge-power'],
    qualities: { 'acceleration': 0.8, 'horizontal-power': 0.8 },
    muscles: { 'gastrocnemius': 0.6, 'gluteus-maximus': 0.6, 'rectus-femoris': 0.5 },
    equipment: ['none'], surface: 'gym', minAge: 14,
    setup: ['En-garde with open space ahead (épée/foil only).'],
    execution: ['Extend the arm, tip the weight forward off the front foot and run past the target.', 'Decelerate under control and return.'],
    cues: ['Arm extends first', 'Fall forward, then run'],
    mistakes: ['Jumping up instead of driving forward.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'mirror-distance-game', name: 'Mirror Distance Game', skills: ['distance-judgement', 'advance-retreat-speed'],
    qualities: { 'deceleration': 0.7, 'reactive-strength': 0.6, 'anaerobic-capacity': 0.5 },
    muscles: { 'vastus-medialis': 0.6, 'gastrocnemius': 0.5, 'gluteus-medius': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Two fencers in en-garde at lunge distance.'],
    execution: ['The leader advances and retreats unpredictably; the follower keeps the exact same distance.', 'The leader may lunge at any time — the follower must be out of reach.'],
    cues: ['Match their first move', 'Keep your distance, not your position'],
    mistakes: ['Watching the feet instead of the whole body.'],
    defaultDose: time(4, 60), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'split-squat-endurance', name: 'En-Garde Split-Squat Holds', skills: ['lower-body-endurance'],
    qualities: { 'lower-body-strength': 0.7, 'single-leg-stability': 0.6, 'aerobic-base': 0.5 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6, 'adductors': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Take a deep en-garde position.'],
    execution: ['Hold the position, then pulse down and up 2–3 cm for the interval.', 'Switch to a lunge-and-recover every 15 seconds.'],
    cues: ['Knees track over toes', 'Torso upright'],
    mistakes: ['Letting the front knee collapse inward as you tire.'],
    defaultDose: time(3, 45), restSeconds: 45, startPose: 'split-squat', endPose: 'isometric-hold',
  },
  {
    slug: 'feint-disengage-drill', name: 'Feint-Disengage Drill', skills: ['feint-timing', 'blade-hand-speed'],
    qualities: { 'reactive-strength': 0.6, 'shoulder-stability': 0.5, 'horizontal-power': 0.5 },
    muscles: { 'forearm-extensors': 0.5, 'deltoid-anterior': 0.5, 'rectus-femoris': 0.5 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Partner holds a steady parry position.'],
    execution: ['Feint to one line; as the partner reacts, disengage under the blade and lunge to the open line.', 'Partner varies whether they react so you learn to read it.'],
    cues: ['Make the feint believable', 'Disengage small and fast'],
    mistakes: ['A lazy feint that draws no reaction.'],
    defaultDose: reps(4, 8), restSeconds: 30, startPose: 'horizontal-push', endPose: 'lunge',
  },
  {
    slug: 'bout-footwork-intervals', name: 'Bout-Length Footwork Intervals', skills: ['footwork-endurance', 'lower-body-endurance'],
    qualities: { 'anaerobic-capacity': 0.8, 'repeat-sprint': 0.6, 'ankle-stiffness': 0.5 },
    muscles: { 'gastrocnemius': 0.6, 'vastus-lateralis': 0.6, 'soleus': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['A strip or line; a timer set to three-minute periods.'],
    execution: ['Continuous footwork — advances, retreats, lunges and recoveries — at bout intensity for the interval.', 'Keep form quality high even in the final minute.'],
    cues: ['Stay low all period', 'Sharp at the end, like the final touch'],
    mistakes: ['Standing up to rest mid-interval.'],
    defaultDose: time(3, 180), restSeconds: 60, startPose: 'lateral-shuffle', endPose: 'lunge',
  },
  {
    slug: 'parry-riposte-reps', name: 'Parry-Riposte Reps', skills: ['reaction-time', 'blade-hand-speed'],
    qualities: { 'reactive-strength': 0.7, 'shoulder-stability': 0.5 },
    muscles: { 'forearm-flexors': 0.5, 'deltoid-anterior': 0.5, 'infraspinatus': 0.4 },
    equipment: ['partner'], surface: 'gym',
    setup: ['Partner attacks slowly in a named line; build speed as it is clean.'],
    execution: ['Parry with a small, blade-only movement and riposte immediately to the target.', 'Rotate through parries 4, 6 and 8.'],
    cues: ['Parry small', 'Riposte straight'],
    mistakes: ['Big sweeping parries that leave you open.'],
    defaultDose: reps(4, 10), restSeconds: 30, startPose: 'isometric-hold', endPose: 'horizontal-push',
  },
  {
    slug: 'lateral-bound-legs', name: 'Lunge Leg Bounds', skills: ['lunge-power'],
    qualities: { 'horizontal-power': 0.8, 'reactive-strength': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'gastrocnemius': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Clear space; a full warm-up first.'],
    execution: ['Explosive forward bounds off the back leg into a lunge landing, holding for one second.', 'Walk back and repeat; count ground contacts.'],
    cues: ['Drive through the back heel', 'Stick the landing'],
    mistakes: ['Landing with the front knee caving in.'],
    defaultDose: contacts(3, 8), restSeconds: 60, startPose: 'bound', endPose: 'lunge',
  },
  {
    slug: 'hip-mobility-flow', name: 'Fencer Hip Mobility Flow', skills: ['lower-body-endurance', 'footwork-endurance'],
    qualities: { 'hip-mobility': 0.9, 'single-leg-stability': 0.5 },
    muscles: { 'iliopsoas': 0.6, 'adductors': 0.6, 'deep-hip-rotators': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['A mat or clear floor space.'],
    execution: ['Flow through a deep lunge with rotation, a lateral lunge, and a 90/90 hip switch on each side.', 'Move slowly and breathe out into each position.'],
    cues: ['Slow and controlled', 'Breathe into the stretch'],
    mistakes: ['Bouncing into end range.'],
    defaultDose: time(2, 90), restSeconds: 20, startPose: 'mobility-flow', endPose: 'lunge',
  },
]);

const WEIGHTLIFTING = sportDrills('weightlifting', [
  {
    slug: 'pvc-snatch-progression', name: 'PVC Snatch Progression', skills: ['bar-path-consistency', 'overhead-stability'],
    qualities: { 'shoulder-stability': 0.7, 'hip-mobility': 0.6, 'vertical-power': 0.5 },
    muscles: { 'trapezius-upper': 0.5, 'deltoid-lateral': 0.5, 'gluteus-maximus': 0.5 },
    equipment: ['stick'], prop: 'bar-barbell', surface: 'gym',
    setup: ['A PVC pipe or broomstick with a wide snatch grip.'],
    execution: ['Work down the progression: overhead squat, snatch balance, high hang snatch, hang snatch, full snatch from mid-shin.', 'Five clean reps of each before moving on.'],
    cues: ['Bar stays close', 'Punch up and sit under'],
    mistakes: ['Swinging the bar out in front of the body.'],
    defaultDose: reps(3, 5, 'PVC only'), restSeconds: 45, startPose: 'hinge', endPose: 'vertical-push',
  },
  {
    slug: 'overhead-squat-stability', name: 'Overhead Squat', skills: ['overhead-stability', 'hip-mobility', 'squat-strength'],
    qualities: { 'shoulder-stability': 0.8, 'hip-mobility': 0.7, 'lower-body-strength': 0.6 },
    muscles: { 'trapezius-lower': 0.6, 'vastus-lateralis': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['barbell'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Empty bar or technique bar, snatch-width grip, locked out overhead.'],
    execution: ['Squat to full depth with the bar over the middle of the feet and the arms locked.', 'Stand up without the bar drifting forward.'],
    cues: ['Push the bar up to the ceiling', 'Armpits forward'],
    mistakes: ['Soft elbows, which let the bar fall forward.'],
    defaultDose: reps(3, 6, 'light, technique'), restSeconds: 90, startPose: 'squat', endPose: 'vertical-push',
  },
  {
    slug: 'hang-power-clean-technique', name: 'Hang Power Clean Technique', skills: ['bar-path-consistency'],
    qualities: { 'vertical-power': 0.9, 'lower-body-strength': 0.5, 'grip': 0.5 },
    muscles: { 'gluteus-maximus': 0.7, 'trapezius-upper': 0.6, 'biceps-femoris': 0.5 },
    equipment: ['barbell', 'bumper-plates'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Start at the hang (bar above the knees), clean grip, light technique load.'],
    execution: ['Hinge to the hang, jump the bar up with the legs, shrug and pull under into a front rack.', 'Catch with fast elbows and stand; reset every rep.'],
    cues: ['Jump, shrug, elbows fast', 'Bar brushes the thighs'],
    mistakes: ['Pulling early with the arms instead of finishing the jump.'],
    defaultDose: reps(3, 6, 'light, technique'), restSeconds: 90, startPose: 'hinge', endPose: 'squat',
  },
  {
    slug: 'front-squat-technique', name: 'Front Squat Technique', skills: ['squat-strength'],
    qualities: { 'lower-body-strength': 0.95, 'trunk-anti-rotation': 0.6 },
    muscles: { 'vastus-lateralis': 0.8, 'vastus-medialis': 0.7, 'erector-spinae': 0.5 },
    equipment: ['barbell', 'rack'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Bar in the front rack from a squat rack, elbows high.'],
    execution: ['Squat straight down between the heels to full depth, keeping the chest tall.', 'Drive up with the elbows leading.'],
    cues: ['Elbows up', 'Sit between your heels'],
    mistakes: ['Dropping the elbows so the bar rolls forward.'],
    defaultDose: reps(3, 8, 'moderate, technique first'), restSeconds: 120, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'snatch-grip-pull', name: 'Snatch-Grip Pull', skills: ['bar-path-consistency'],
    qualities: { 'vertical-power': 0.7, 'grip': 0.6, 'lower-body-strength': 0.6 },
    muscles: { 'trapezius-upper': 0.6, 'gluteus-maximus': 0.6, 'erector-spinae': 0.5 },
    equipment: ['barbell', 'bumper-plates'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Bar on the floor, snatch grip, shoulders over the bar.'],
    execution: ['Push the floor away, keep the bar close past the knees, and finish tall with a shrug.', 'Lower under control; no pulling under.'],
    cues: ['Chest up off the floor', 'Stay over the bar'],
    mistakes: ['Hips shooting up first so the back does the work.'],
    defaultDose: reps(3, 6, 'light, technique'), restSeconds: 90, startPose: 'hinge', endPose: 'vertical-jump',
  },
  {
    slug: 'push-press-drive', name: 'Push Press', skills: ['overhead-stability'],
    qualities: { 'overhead-power': 0.8, 'shoulder-stability': 0.6 },
    muscles: { 'deltoid-anterior': 0.7, 'triceps-brachii': 0.6, 'gluteus-maximus': 0.4 },
    equipment: ['barbell', 'rack'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Bar in the front rack, feet hip width.'],
    execution: ['Dip straight down a few inches, drive up with the legs and press the bar overhead to lockout.', 'Head through the window at the top.'],
    cues: ['Dip straight, drive fast', 'Lock it out'],
    mistakes: ['Dipping forward onto the toes.'],
    defaultDose: reps(3, 6, 'light, technique'), restSeconds: 90, startPose: 'squat', endPose: 'vertical-push',
  },
  {
    slug: 'mobility-complex', name: 'Lifter Mobility Complex', skills: ['hip-mobility', 'overhead-stability'],
    qualities: { 'hip-mobility': 0.8, 'shoulder-stability': 0.6, 'ankle-stiffness': 0.4 },
    muscles: { 'adductors': 0.5, 'latissimus-dorsi': 0.5, 'soleus': 0.5 },
    equipment: ['stick'], surface: 'anywhere',
    setup: ['A stick and clear floor space.'],
    execution: ['Deep goblet-style squat holds, stick pass-throughs, and ankle rocks in sequence.', 'Finish with a paused overhead squat with the stick.'],
    cues: ['Heels down', 'Breathe into the bottom'],
    mistakes: ['Rushing through end range instead of owning it.'],
    defaultDose: time(2, 90), restSeconds: 20, startPose: 'mobility-flow', endPose: 'squat',
  },
]);

const POWERLIFTING = sportDrills('powerlifting', [
  {
    slug: 'bracing-practice', name: 'Bracing Practice', skills: ['bracing-technique'],
    qualities: { 'trunk-anti-rotation': 0.9 },
    muscles: { 'transverse-abdominis': 0.8, 'obliques-internal': 0.6, 'erector-spinae': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Stand tall with hands around the waist.'],
    execution: ['Breathe in through the nose into the belly and sides, then brace as if about to be punched.', 'Hold the brace for five seconds while breathing shallowly, then relax.'],
    cues: ['360-degree breath', 'Ribs down, belly tight'],
    mistakes: ['Breathing into the chest and shrugging the shoulders.'],
    defaultDose: reps(3, 8), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'competition-squat-technique', name: 'Competition Squat Technique', skills: ['squat-strength', 'bracing-technique'],
    qualities: { 'lower-body-strength': 0.95, 'trunk-anti-rotation': 0.6 },
    muscles: { 'vastus-lateralis': 0.8, 'gluteus-maximus': 0.7, 'erector-spinae': 0.5 },
    equipment: ['barbell', 'rack'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Squat rack with safeties set just below depth; light technique load.'],
    execution: ['Brace, sit down and back until the hip crease is below the knee, then stand up.', 'Wait for the coach\'s "rack" command before re-racking.'],
    cues: ['Brace before you move', 'Knees out, chest proud'],
    mistakes: ['Losing the brace at the bottom and rounding forward.'],
    defaultDose: reps(3, 8, 'light, technique'), restSeconds: 120, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'bench-press-technique', name: 'Bench Press Technique', skills: ['bench-press-strength'],
    qualities: { 'upper-body-push': 0.95, 'shoulder-stability': 0.6 },
    muscles: { 'pectoralis-major': 0.8, 'triceps-brachii': 0.7, 'deltoid-anterior': 0.5 },
    equipment: ['barbell', 'bench', 'rack'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Bench with a spotter; shoulder blades pinned, feet flat.'],
    execution: ['Lower the bar to the lower chest with control, pause briefly, and press up and slightly back.', 'Keep glutes on the bench and feet on the floor throughout.'],
    cues: ['Bend the bar', 'Pause, then press'],
    mistakes: ['Bouncing the bar off the chest.'],
    defaultDose: reps(3, 8, 'light, technique'), restSeconds: 120, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'deadlift-technique', name: 'Deadlift Technique', skills: ['deadlift-strength', 'bracing-technique'],
    qualities: { 'lower-body-strength': 0.95, 'grip': 0.6 },
    muscles: { 'gluteus-maximus': 0.8, 'biceps-femoris': 0.7, 'erector-spinae': 0.6 },
    equipment: ['barbell', 'bumper-plates'], prop: 'bar-barbell', surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Bar over mid-foot, shins close, hands just outside the legs.'],
    execution: ['Brace, pull the slack out of the bar, and push the floor away until standing tall.', 'Lower by hinging back first, then bending the knees.'],
    cues: ['Pull the slack out', 'Push the floor away'],
    mistakes: ['Jerking the bar off the floor with a rounded back.'],
    defaultDose: reps(3, 6, 'light, technique'), restSeconds: 150, startPose: 'hinge', endPose: 'hinge',
  },
  {
    slug: 'paused-squat', name: 'Paused Goblet Squat', skills: ['squat-strength'],
    qualities: { 'lower-body-strength': 0.95, 'hip-mobility': 0.5 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6, 'adductors': 0.5 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ['Hold a dumbbell at the chest.'],
    execution: ['Squat to depth and pause for two seconds without relaxing.', 'Drive up hard out of the pause.'],
    cues: ['Stay tight in the hole', 'Elbows inside the knees'],
    mistakes: ['Relaxing at the bottom and bouncing out.'],
    defaultDose: reps(3, 8, 'moderate'), restSeconds: 90, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'dumbbell-floor-press', name: 'Dumbbell Floor Press', skills: ['bench-press-strength'],
    qualities: { 'upper-body-push': 0.95, 'shoulder-stability': 0.5 },
    muscles: { 'triceps-brachii': 0.7, 'pectoralis-major': 0.7, 'deltoid-anterior': 0.4 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ['Lie on the floor with knees bent, dumbbells over the chest.'],
    execution: ['Lower until the upper arms touch the floor, pause, then press up.', 'Elbows at about 45 degrees from the body.'],
    cues: ['Pause on the floor', 'Press to lockout'],
    mistakes: ['Flaring the elbows straight out to the side.'],
    defaultDose: reps(3, 10, 'moderate'), restSeconds: 90, startPose: 'horizontal-push', endPose: 'horizontal-push',
  },
  {
    slug: 'romanian-deadlift', name: 'Romanian Deadlift', skills: ['deadlift-strength'],
    qualities: { 'lower-body-strength': 0.95, 'hip-mobility': 0.5 },
    muscles: { 'biceps-femoris': 0.8, 'semitendinosus': 0.7, 'gluteus-maximus': 0.6 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ['Stand holding two dumbbells in front of the thighs.'],
    execution: ['Push the hips back with soft knees, sliding the weights down the legs until the hamstrings are loaded.', 'Drive the hips forward to stand.'],
    cues: ['Hips back, not down', 'Weights stay close'],
    mistakes: ['Rounding the back to reach lower.'],
    defaultDose: reps(3, 10, 'moderate'), restSeconds: 90, startPose: 'hinge', endPose: 'hinge',
  },
]);

const CONDITIONING = sportDrills('crossfit-style-conditioning', [
  {
    slug: 'movement-quality-screen', name: 'Movement Quality Flow', skills: ['movement-quality'],
    qualities: { 'hip-mobility': 0.7, 'shoulder-stability': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'gluteus-medius': 0.5, 'trapezius-lower': 0.5, 'adductors': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Clear floor space before any intense work.'],
    execution: ['Air squats, inchworms, lunges with reach and bear crawls, done slowly with perfect positions.', 'Film one round and compare it to the last.'],
    cues: ['Own every position', 'Slow is smooth'],
    mistakes: ['Racing through the flow and skipping the positions.'],
    defaultDose: time(2, 120), restSeconds: 30, startPose: 'mobility-flow', endPose: 'squat',
  },
  {
    slug: 'emom-bodyweight', name: 'EMOM Bodyweight Circuit', skills: ['work-capacity', 'mixed-modal-conditioning'],
    qualities: { 'anaerobic-capacity': 0.8, 'aerobic-base': 0.6, 'lower-body-strength': 0.4 },
    muscles: { 'vastus-lateralis': 0.5, 'pectoralis-major': 0.5, 'rectus-abdominis': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['A timer beeping every minute.'],
    execution: ['Minute 1: 10 air squats. Minute 2: 8 push-ups. Minute 3: 12 sit-ups. Repeat for the set.', 'Rest for whatever is left of each minute.'],
    cues: ['Quality reps, then rest', 'Same pace every round'],
    mistakes: ['Going out too fast and failing the later minutes.'],
    defaultDose: time(1, 720), restSeconds: 120, startPose: 'squat', endPose: 'horizontal-push',
  },
  {
    slug: 'kettlebell-swing-intervals', name: 'Kettlebell Swing Intervals', skills: ['work-capacity', 'general-strength'],
    qualities: { 'horizontal-power': 0.7, 'anaerobic-capacity': 0.6, 'grip': 0.5 },
    muscles: { 'gluteus-maximus': 0.8, 'biceps-femoris': 0.6, 'erector-spinae': 0.5 },
    equipment: ['kettlebell'], surface: 'gym', minAge: 14,
    setup: ['A moderate kettlebell a foot in front of you.'],
    execution: ['Hike the bell back, snap the hips forward and float it to chest height.', 'Work 20 seconds, rest 40, for the full set.'],
    cues: ['Hinge, don\'t squat', 'Snap the hips'],
    mistakes: ['Lifting with the arms instead of the hips.'],
    defaultDose: time(8, 20), restSeconds: 40, startPose: 'hinge', endPose: 'isometric-hold',
  },
  {
    slug: 'farmer-carry-medley', name: 'Carry Medley', skills: ['general-strength', 'work-capacity'],
    qualities: { 'grip': 0.9, 'trunk-anti-rotation': 0.7 },
    muscles: { 'forearm-flexors': 0.8, 'trapezius-upper': 0.6, 'obliques-internal': 0.5 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ['Two heavy dumbbells or kettlebells and 20 metres of space.'],
    execution: ['Farmer carry 20 m, suitcase carry (one side) 20 m, then switch sides.', 'Walk tall with short, quick steps.'],
    cues: ['Walk tall', 'Don\'t let the weight tip you'],
    mistakes: ['Leaning toward the loaded side on the suitcase carry.'],
    defaultDose: dist(3, 60), restSeconds: 90, startPose: 'carry', endPose: 'carry',
  },
  {
    slug: 'row-burpee-chipper', name: 'Burpee Ladder', skills: ['mixed-modal-conditioning', 'work-capacity'],
    qualities: { 'anaerobic-capacity': 0.9, 'vertical-power': 0.5 },
    muscles: { 'pectoralis-major': 0.5, 'rectus-femoris': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Open floor and a clock.'],
    execution: ['Do 1 burpee in the first minute, 2 in the second, 3 in the third and so on.', 'Stop when you can no longer finish the round inside its minute.'],
    cues: ['Chest to floor, jump at the top', 'Breathe on the way up'],
    mistakes: ['Sagging hips in the push-up portion.'],
    defaultDose: time(1, 600), restSeconds: 120, startPose: 'horizontal-push', endPose: 'vertical-jump',
  },
  {
    slug: 'goblet-squat-strength', name: 'Goblet Squat Strength', skills: ['general-strength', 'movement-quality'],
    qualities: { 'lower-body-strength': 0.95, 'trunk-anti-rotation': 0.5 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6, 'adductors': 0.5 },
    equipment: ['kettlebell'], surface: 'gym',
    setup: ['Hold a kettlebell by the horns at the chest.'],
    execution: ['Squat to depth with the elbows inside the knees and the chest up.', 'Stand up by driving through the whole foot.'],
    cues: ['Chest up', 'Push knees out'],
    mistakes: ['Heels lifting as you go down.'],
    defaultDose: reps(3, 10, 'moderate'), restSeconds: 90, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'pull-up-progression', name: 'Pull-Up Progression', skills: ['general-strength'],
    qualities: { 'upper-body-pull': 0.95, 'grip': 0.6 },
    muscles: { 'latissimus-dorsi': 0.8, 'biceps-brachii': 0.6, 'rhomboids': 0.5 },
    equipment: ['pull-up-bar', 'band'], surface: 'gym',
    setup: ['A pull-up bar and a band for assistance if needed.'],
    execution: ['Hang with the shoulders engaged, pull until the chin clears the bar, lower slowly.', 'Use a band or jumping negatives until strict reps are possible.'],
    cues: ['Shoulders down first', 'Three-second lower'],
    mistakes: ['Kipping before strict pull-ups are strong.'],
    defaultDose: reps(3, 6), restSeconds: 90, startPose: 'vertical-pull', endPose: 'vertical-pull',
  },
]);

const GYMNASTICS = sportDrills('gymnastics', [
  {
    slug: 'hollow-body-holds', name: 'Hollow Body Holds and Rocks', skills: ['core-hollow-hold'],
    qualities: { 'trunk-anti-rotation': 0.9 },
    muscles: { 'rectus-abdominis': 0.8, 'transverse-abdominis': 0.7, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Lie on your back on a mat.'],
    execution: ['Press the lower back into the floor and lift arms and legs into a banana shape; hold.', 'Progress to small rocks without losing the shape.'],
    cues: ['Low back glued down', 'Squeeze everything'],
    mistakes: ['Arching the lower back off the floor.'],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'trunk-flexion', endPose: 'isometric-hold',
  },
  {
    slug: 'round-off-rebound', name: 'Round-Off Rebound', skills: ['tumbling-power', 'landing-control'],
    qualities: { 'reactive-strength': 0.9, 'vertical-power': 0.7, 'landing-mechanics': 0.6 },
    muscles: { 'gastrocnemius': 0.7, 'soleus': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['none'], surface: 'gym', minAge: 13,
    setup: ['Tumbling strip or sprung floor; a coach spotting the first reps.'],
    execution: ['Hurdle, round-off, snap the feet down together and rebound straight up with arms by the ears.', 'Land in a controlled, soft finish.'],
    cues: ['Snap down fast', 'Stiff legs, quick feet'],
    mistakes: ['Landing with bent knees, which kills the rebound.'],
    defaultDose: contacts(3, 6), restSeconds: 60, startPose: 'pogo', endPose: 'landing',
  },
  {
    slug: 'stick-landing-drops', name: 'Stick-Landing Drops', skills: ['landing-control'],
    qualities: { 'landing-mechanics': 0.9, 'lower-body-strength': 0.5 },
    muscles: { 'vastus-medialis': 0.6, 'gluteus-maximus': 0.5, 'soleus': 0.5 },
    equipment: ['box'], surface: 'gym',
    setup: ['Step off a low box (30–45 cm) onto a mat.'],
    execution: ['Land on two feet with hips back, knees over toes, arms forward, and freeze for three seconds.', 'Progress the height only when every landing is silent and still.'],
    cues: ['Land quiet', 'Freeze — no step'],
    mistakes: ['Knees caving inward on landing.'],
    defaultDose: contacts(3, 8), restSeconds: 45, startPose: 'landing', endPose: 'squat',
  },
  {
    slug: 'kip-swing-drill', name: 'Tap-Swing Drill', skills: ['bar-swing-strength'],
    qualities: { 'upper-body-pull': 0.7, 'grip': 0.7, 'trunk-anti-rotation': 0.6 },
    muscles: { 'latissimus-dorsi': 0.7, 'forearm-flexors': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['pull-up-bar'], surface: 'gym',
    setup: ['Hang from a bar with an overhand grip, shoulders engaged.'],
    execution: ['Alternate hollow and arch positions to create a swing, "tapping" the feet at the front.', 'Keep the arms straight and the grip active.'],
    cues: ['Swing from the shoulders', 'Hollow, arch, hollow'],
    mistakes: ['Bending the arms and pulling instead of swinging.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'vertical-pull', endPose: 'vertical-pull',
  },
  {
    slug: 'beam-balance-walks', name: 'Beam Balance Walks', skills: ['beam-balance'],
    qualities: { 'single-leg-stability': 0.9, 'ankle-stiffness': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'peroneals': 0.6, 'foot-intrinsics': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['A line on the floor, then a low beam as balance improves.'],
    execution: ['Walk the length on relevé with arms in position, then add half turns and holds on one leg.', 'Finish with a controlled arabesque hold.'],
    cues: ['Eyes on the end of the beam', 'Squeeze the standing leg'],
    mistakes: ['Looking down at the feet.'],
    defaultDose: reps(3, 4), restSeconds: 30, startPose: 'single-leg-balance', endPose: 'single-leg-balance',
  },
  {
    slug: 'active-flexibility-kicks', name: 'Active Flexibility Kicks', skills: ['flexibility'],
    qualities: { 'hip-mobility': 0.9 },
    muscles: { 'iliopsoas': 0.6, 'biceps-femoris': 0.5, 'adductors': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Stand beside a wall or barre for balance.'],
    execution: ['Controlled front, side and back kicks, lifting as high as possible with a straight leg and holding at the top.', 'No swinging — the leg is lifted by the muscles.'],
    cues: ['Lift, don\'t swing', 'Tall standing leg'],
    mistakes: ['Throwing the leg with momentum.'],
    defaultDose: reps(2, 10), restSeconds: 30, startPose: 'single-leg-balance', endPose: 'mobility-flow',
  },
  {
    slug: 'vault-board-punches', name: 'Board Punch Drill', skills: ['vault-block-power'],
    qualities: { 'reactive-strength': 0.9, 'acceleration': 0.6 },
    muscles: { 'gastrocnemius': 0.7, 'soleus': 0.6, 'rectus-femoris': 0.5 },
    equipment: ['box'], surface: 'gym',
    setup: ['A springboard or low box after a short run-up.'],
    execution: ['Run, hurdle onto the board with both feet and punch up and forward to a stuck landing on a mat.', 'Arms swing from behind to overhead on the punch.'],
    cues: ['Punch through the toes', 'Short contact'],
    mistakes: ['Sinking into the board with soft knees.'],
    defaultDose: contacts(3, 6), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'vertical-jump',
  },
  {
    slug: 'handstand-shoulder-blocks', name: 'Handstand Shoulder Blocks', skills: ['vault-block-power', 'shoulder-durability'],
    qualities: { 'shoulder-stability': 0.8, 'overhead-power': 0.6 },
    muscles: { 'deltoid-anterior': 0.7, 'trapezius-upper': 0.6, 'serratus-anterior': 0.6 },
    equipment: ['wall'], surface: 'gym', minAge: 14,
    setup: ['Handstand facing the wall, hands shoulder width.'],
    execution: ['Shrug the shoulders up to the ears, pushing the body higher, then lower slightly.', 'Keep the body hollow and the arms locked.'],
    cues: ['Push the floor away', 'Arms by your ears'],
    mistakes: ['Bending the elbows to create the movement.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'vertical-push', endPose: 'vertical-push',
  },
  {
    slug: 'band-shoulder-prehab', name: 'Gymnast Shoulder Prehab', skills: ['shoulder-durability'],
    qualities: { 'shoulder-stability': 0.9 },
    muscles: { 'infraspinatus': 0.7, 'trapezius-lower': 0.6, 'serratus-anterior': 0.5 },
    equipment: ['band'], surface: 'anywhere',
    setup: ['Light band; complete before every bar and floor session.'],
    execution: ['External rotations, Y-raises, and scapular push-ups back to back.', 'Slow tempo — two seconds each way.'],
    cues: ['Slow and controlled', 'Blades down and back'],
    mistakes: ['Using a band so heavy that the neck shrugs up.'],
    defaultDose: reps(2, 12, 'light band'), restSeconds: 20, startPose: 'horizontal-pull', endPose: 'vertical-push',
  },
  {
    slug: 'straddle-press-prep', name: 'Straddle Press Prep', skills: ['core-hollow-hold', 'flexibility'],
    qualities: { 'hip-mobility': 0.7, 'trunk-anti-rotation': 0.6, 'shoulder-stability': 0.5 },
    muscles: { 'iliopsoas': 0.6, 'rectus-abdominis': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Sit in a wide straddle with hands on the floor in front.'],
    execution: ['Lean the shoulders forward and lift the legs off the floor using the hip flexors and core.', 'Hold one second each lift.'],
    cues: ['Shoulders over hands', 'Lift the legs, don\'t swing'],
    mistakes: ['Bending the knees to get the legs up.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'trunk-flexion', endPose: 'isometric-hold',
  },
  {
    slug: 'tuck-jump-series', name: 'Tuck Jump Series', skills: ['tumbling-power'],
    qualities: { 'vertical-power': 0.9, 'reactive-strength': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'iliopsoas': 0.6, 'rectus-femoris': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Sprung floor or mat.'],
    execution: ['Jump straight up and pull the knees to the chest at the top, then open for the landing.', 'Rebound into the next jump.'],
    cues: ['Knees to chest', 'Land soft, rebound fast'],
    mistakes: ['Kicking the feet back instead of pulling the knees up.'],
    defaultDose: contacts(3, 8), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'split-flexibility', name: 'Split Flexibility Progression', skills: ['flexibility'],
    qualities: { 'hip-mobility': 0.9 },
    muscles: { 'iliopsoas': 0.6, 'biceps-femoris': 0.6, 'adductors': 0.5 },
    equipment: ['blocks'], surface: 'gym',
    setup: ['Two yoga blocks beside the hips; fully warm first.'],
    execution: ['Lower into front splits supported on the blocks, holding each side for the interval.', 'Finish with middle splits; never bounce.'],
    cues: ['Square the hips', 'Breathe out to go lower'],
    mistakes: ['Twisting the back hip open to go lower.'],
    defaultDose: time(3, 45), restSeconds: 20, startPose: 'mobility-flow', endPose: 'split-squat',
  },
]);

const SPIRIT = sportDrills('competitive-spirit', [
  {
    slug: 'toe-touch-jump-drill', name: 'Toe-Touch Jump Drill', skills: ['jump-height', 'flexibility'],
    qualities: { 'vertical-power': 0.9, 'hip-mobility': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'iliopsoas': 0.6, 'adductors': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Sprung floor, a partner to count.'],
    execution: ['Whip the arms, jump, and snap the legs up into a toe touch at the peak, bringing the feet together to land.', 'Rest a few seconds between jumps.'],
    cues: ['Legs up, not chest down', 'Snap the feet together'],
    mistakes: ['Leaning forward to reach the toes.'],
    defaultDose: contacts(3, 8), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'standing-back-tuck-prep', name: 'Back Tuck Prep', skills: ['tumbling-power'],
    qualities: { 'vertical-power': 0.8, 'reactive-strength': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['box'], surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Coach spotting, a stacked mat or incline behind you.'],
    execution: ['Set the arms, jump up tall first, then pull the knees in and rotate onto the stacked mat.', 'Progress only as the coach clears each step.'],
    cues: ['Jump up, then tuck', 'Eyes on the ceiling'],
    mistakes: ['Throwing the head back before getting height.'],
    defaultDose: contacts(3, 5), restSeconds: 90, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'base-press-strength', name: 'Base Press Strength', skills: ['base-strength', 'stunt-stability'],
    qualities: { 'overhead-power': 0.7, 'lower-body-strength': 0.6, 'shoulder-stability': 0.6 },
    muscles: { 'deltoid-anterior': 0.6, 'triceps-brachii': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ['Two dumbbells at the shoulders, feet shoulder width.'],
    execution: ['Dip with the legs and drive the weights overhead together, like pressing a flyer to extension.', 'Lower to the shoulders under control.'],
    cues: ['Legs first, then arms', 'Lock out overhead'],
    mistakes: ['Pressing with arms only while the legs stay locked.'],
    defaultDose: reps(3, 8, 'moderate'), restSeconds: 90, startPose: 'squat', endPose: 'vertical-push',
  },
  {
    slug: 'flyer-balance-holds', name: 'Flyer Balance Holds', skills: ['flyer-core-control', 'stunt-stability'],
    qualities: { 'single-leg-stability': 0.8, 'trunk-anti-rotation': 0.7 },
    muscles: { 'gluteus-medius': 0.6, 'transverse-abdominis': 0.6, 'peroneals': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Stand on one foot on the floor, then on a foam pad.'],
    execution: ['Pull into a liberty position (knee up, arms high) and hold with everything locked.', 'Progress to closing the eyes briefly.'],
    cues: ['Squeeze the standing leg', 'Ribs down, stay tight'],
    mistakes: ['Loose core, which a base feels as a wobble.'],
    defaultDose: time(4, 20), restSeconds: 20, startPose: 'single-leg-balance', endPose: 'isometric-hold',
  },
  {
    slug: 'hollow-to-arch-rocks', name: 'Hollow-to-Arch Rocks', skills: ['flyer-core-control'],
    qualities: { 'trunk-anti-rotation': 0.9 },
    muscles: { 'rectus-abdominis': 0.7, 'erector-spinae': 0.6, 'gluteus-maximus': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['On a mat, lying on your back.'],
    execution: ['Hold a hollow for 15 seconds, roll to an arch (superman) for 15 seconds.', 'Keep the body as one tight piece throughout.'],
    cues: ['One solid piece', 'Squeeze the glutes in the arch'],
    mistakes: ['Bending at the hips instead of staying rigid.'],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'trunk-flexion', endPose: 'isometric-hold',
  },
  {
    slug: 'stunt-timing-counts', name: 'Stunt Timing on Counts', skills: ['timing-synchronisation', 'stunt-stability'],
    qualities: { 'lower-body-strength': 0.6, 'reactive-strength': 0.5, 'shoulder-stability': 0.5 },
    muscles: { 'vastus-lateralis': 0.5, 'deltoid-anterior': 0.5, 'gluteus-maximus': 0.5 },
    equipment: ['partner'], surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Stunt group with a coach; start from prep level only.'],
    execution: ['Dip and drive together on the same count, holding the prep for four counts.', 'Cradle or step down on count as the coach calls it.'],
    cues: ['Dip together, drive together', 'Eyes on the flyer'],
    mistakes: ['One base driving early, which tips the flyer.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'squat', endPose: 'vertical-push',
  },
  {
    slug: 'jump-landing-drill', name: 'Jump Landing Drill', skills: ['landing-control'],
    qualities: { 'landing-mechanics': 0.9, 'single-leg-stability': 0.5 },
    muscles: { 'vastus-medialis': 0.6, 'gluteus-medius': 0.5, 'soleus': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Mat or sprung floor.'],
    execution: ['Small jumps to a soft, silent landing, freezing for two seconds each time.', 'Then land on one foot; keep the knee over the toes.'],
    cues: ['Quiet feet', 'Knees over toes'],
    mistakes: ['Straight-legged landings.'],
    defaultDose: contacts(3, 10), restSeconds: 45, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'tumbling-pass-conditioning', name: 'Tumbling-Pass Conditioning', skills: ['tumbling-power'],
    qualities: { 'anaerobic-capacity': 0.8, 'reactive-strength': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'deltoid-anterior': 0.5, 'rectus-abdominis': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Full routine length on a timer.'],
    execution: ['Run the routine\'s jumps, motions and dance sections back to back, marking the tumbling.', 'Rest one minute, then repeat.'],
    cues: ['Full energy all the way through', 'Sharp motions even when tired'],
    mistakes: ['Saving energy early and fading at the end.'],
    defaultDose: time(3, 150), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'motion-sharpness', name: 'Arm Motion Sharpness', skills: ['timing-synchronisation'],
    qualities: { 'shoulder-stability': 0.7 },
    muscles: { 'deltoid-lateral': 0.6, 'deltoid-anterior': 0.5, 'trapezius-middle': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Face a mirror or teammate, a count going.'],
    execution: ['Hit high V, low V, T, touchdown and daggers on each count, stopping each one dead.', 'Double the tempo for the second half.'],
    cues: ['Hit and stop', 'Fists tight, wrists straight'],
    mistakes: ['Floating through motions instead of hitting them.'],
    defaultDose: time(3, 60), restSeconds: 20, startPose: 'isometric-hold', endPose: 'vertical-push',
  },
  {
    slug: 'split-and-straddle-stretch', name: 'Split and Straddle Stretch', skills: ['flexibility'],
    qualities: { 'hip-mobility': 0.9 },
    muscles: { 'adductors': 0.6, 'biceps-femoris': 0.6, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['After practice, when fully warm.'],
    execution: ['Hold right split, left split, then middle split for the interval each.', 'Breathe out and relax a little deeper each hold.'],
    cues: ['Breathe out, sink in', 'Square hips'],
    mistakes: ['Stretching cold before practice.'],
    defaultDose: time(3, 40), restSeconds: 10, startPose: 'mobility-flow', endPose: 'split-squat',
  },
  {
    slug: 'base-squat-strength', name: 'Base Goblet Squat', skills: ['base-strength'],
    qualities: { 'lower-body-strength': 0.95, 'trunk-anti-rotation': 0.5 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6, 'erector-spinae': 0.4 },
    equipment: ['dumbbell'], surface: 'gym',
    setup: ['A dumbbell held at the chest.'],
    execution: ['Squat to depth with the chest up, drive up fast.', 'Pause one second at the bottom on the last two reps.'],
    cues: ['Chest up', 'Drive fast'],
    mistakes: ['Rounding forward at the bottom.'],
    defaultDose: reps(3, 10, 'moderate'), restSeconds: 90, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'approach-tumbling-drills', name: 'Round-Off Back-Handspring Drills', skills: ['tumbling-power', 'landing-control'],
    qualities: { 'reactive-strength': 0.8, 'shoulder-stability': 0.6, 'vertical-power': 0.6 },
    muscles: { 'deltoid-anterior': 0.6, 'gastrocnemius': 0.6, 'triceps-brachii': 0.5 },
    equipment: ['box'], surface: 'gym', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Coach spotting, a barrel or incline mat.'],
    execution: ['Sit back and swing the arms into a back handspring over the barrel, pushing through the shoulders.', 'Snap down to the feet; progress as the coach clears it.'],
    cues: ['Sit like a chair', 'Push through the shoulders'],
    mistakes: ['Throwing the head back early without sitting.'],
    defaultDose: contacts(3, 5), restSeconds: 90, startPose: 'squat', endPose: 'landing',
  },
]);

const SIDELINE = formatDrills('competitive-spirit', 'cheerleading-sideline', 'sideline', [
  {
    slug: 'jump-series', name: 'Sideline Jump Series', skills: ['jump-height'],
    qualities: { 'vertical-power': 0.9, 'hip-mobility': 0.5 },
    muscles: { 'gastrocnemius': 0.6, 'gluteus-maximus': 0.5, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'field',
    setup: ['On grass or the track after a warm-up.'],
    execution: ['Toe touch, herkie and pike jumps in sequence with full arm whips.', 'Walk back between sets.'],
    cues: ['Height first, then shape', 'Land together'],
    mistakes: ['Skipping the arm whip that drives height.'],
    defaultDose: contacts(3, 9), restSeconds: 60, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'voice-projection-breath', name: 'Projection Breathing', skills: ['projection-and-voice-endurance'],
    qualities: { 'trunk-anti-rotation': 0.6, 'aerobic-base': 0.5 },
    muscles: { 'transverse-abdominis': 0.6, 'obliques-internal': 0.5, 'rectus-abdominis': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Stand tall; one hand on your belly.'],
    execution: ['Breathe in low into the belly, then project a chant from the diaphragm — not the throat.', 'Repeat the chant during a light jog to build endurance.'],
    cues: ['Breathe from the belly', 'Open throat, loud from the core'],
    mistakes: ['Yelling from the throat, which goes hoarse by halftime.'],
    defaultDose: time(4, 45), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'stunt-hold-endurance', name: 'Prep Hold Endurance', skills: ['stunt-stability'],
    qualities: { 'shoulder-stability': 0.8, 'lower-body-strength': 0.5 },
    muscles: { 'deltoid-anterior': 0.6, 'trapezius-upper': 0.5, 'vastus-lateralis': 0.4 },
    equipment: ['dumbbell'], surface: 'anywhere',
    setup: ['Two light dumbbells held at shoulder height, elbows under hands.'],
    execution: ['Hold in a quarter squat like a base under a prep for the interval.', 'Keep the hands level and the core tight.'],
    cues: ['Hands level', 'Elbows under hands'],
    mistakes: ['Letting the elbows flare wide.'],
    defaultDose: time(3, 30), restSeconds: 45, startPose: 'squat', endPose: 'isometric-hold',
  },
  {
    slug: 'game-length-circuit', name: 'Game-Length Stamina Circuit', skills: ['routine-stamina'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'deltoid-lateral': 0.5, 'rectus-femoris': 0.4 },
    equipment: ['none'], surface: 'field',
    setup: ['A timer for quarter-length intervals.'],
    execution: ['Cycle chant with motions, eight jumps, and a light jog for the interval.', 'Repeat for four "quarters" with a short break.'],
    cues: ['Same energy in Q4 as Q1', 'Sharp motions'],
    mistakes: ['Going all out in the first round and fading.'],
    defaultDose: time(4, 180), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'vertical-jump',
  },
  {
    slug: 'herkie-drill', name: 'Herkie Technique Drill', skills: ['jump-height'],
    qualities: { 'vertical-power': 0.8, 'hip-mobility': 0.6 },
    muscles: { 'iliopsoas': 0.6, 'biceps-femoris': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Stand facing a partner who checks leg height.'],
    execution: ['Lying on your back, kick the jump leg to shape 10 times; then perform standing herkies.', 'Focus on the straight leg reaching high.'],
    cues: ['Straight leg, pointed toe', 'Chest up'],
    mistakes: ['Bending the jump leg.'],
    defaultDose: contacts(3, 6), restSeconds: 45, startPose: 'mobility-flow', endPose: 'vertical-jump',
  },
  {
    slug: 'shoulder-endurance-motions', name: 'Motion Endurance Sets', skills: ['routine-stamina'],
    qualities: { 'shoulder-stability': 0.7, 'aerobic-base': 0.5 },
    muscles: { 'deltoid-lateral': 0.7, 'trapezius-upper': 0.5, 'deltoid-anterior': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Stand tall with fists clenched.'],
    execution: ['Hold motions (high V, T) for eight counts each, cycling continuously.', 'Keep the arms locked at the exact angle.'],
    cues: ['Lock the angle', 'Shoulders down'],
    mistakes: ['Arms drifting lower as fatigue builds.'],
    defaultDose: time(3, 60), restSeconds: 30, startPose: 'isometric-hold', endPose: 'vertical-push',
  },
  {
    slug: 'balance-for-stunts', name: 'Single-Leg Balance for Stunts', skills: ['stunt-stability'],
    qualities: { 'single-leg-stability': 0.9 },
    muscles: { 'gluteus-medius': 0.6, 'peroneals': 0.5, 'transverse-abdominis': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Barefoot on a firm floor.'],
    execution: ['Hold a liberty position for 20 seconds, then pass the knee to the heel stretch position.', 'Switch legs.'],
    cues: ['Lock the standing knee', 'Tight core'],
    mistakes: ['Hip dropping on the lifted side.'],
    defaultDose: time(3, 20), restSeconds: 20, startPose: 'single-leg-balance', endPose: 'isometric-hold',
  },
]);

const DANCE = sportDrills('competitive-dance', [
  {
    slug: 'grand-jete-progression', name: 'Grand Jeté Progression', skills: ['leap-height', 'flexibility'],
    qualities: { 'horizontal-power': 0.7, 'vertical-power': 0.7, 'hip-mobility': 0.7 },
    muscles: { 'iliopsoas': 0.6, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['A diagonal across the studio floor.'],
    execution: ['Run, run, leap — brush the front leg straight up and push off the back leg into a split in the air.', 'Land through the foot softly into a plié.'],
    cues: ['Brush, don\'t kick', 'Hang at the top'],
    mistakes: ['Landing on a straight leg.'],
    defaultDose: contacts(3, 6), restSeconds: 45, startPose: 'bound', endPose: 'landing',
  },
  {
    slug: 'pirouette-spot-drill', name: 'Pirouette Spotting Drill', skills: ['turn-control'],
    qualities: { 'single-leg-stability': 0.9, 'ankle-stiffness': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gastrocnemius': 0.6, 'gluteus-medius': 0.5, 'transverse-abdominis': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Pick a spot at eye level.'],
    execution: ['Relevé passé balance for four counts, then single pirouettes whipping the head to the spot.', 'Finish each turn in a controlled fourth position.'],
    cues: ['Head leaves last, arrives first', 'Pull up out of the hips'],
    mistakes: ['Dropping the heel mid-turn.'],
    defaultDose: reps(3, 6), restSeconds: 30, startPose: 'single-leg-balance', endPose: 'single-leg-balance',
  },
  {
    slug: 'calf-releve-strength', name: 'Relevé Calf Strength', skills: ['turn-control', 'landing-control'],
    qualities: { 'ankle-stiffness': 0.8, 'single-leg-stability': 0.6 },
    muscles: { 'gastrocnemius': 0.7, 'soleus': 0.7, 'foot-intrinsics': 0.5 },
    equipment: ['step'], surface: 'anywhere',
    setup: ['Stand on the edge of a step with heels hanging off.'],
    execution: ['Rise to high relevé, hold one second, lower slowly below the step.', 'Progress to single-leg reps.'],
    cues: ['Straight up through the big toe', 'Slow down'],
    mistakes: ['Rolling onto the outside of the foot.'],
    defaultDose: reps(3, 12), restSeconds: 30, startPose: 'pogo', endPose: 'isometric-hold',
  },
  {
    slug: 'across-the-floor-stamina', name: 'Across-the-Floor Stamina', skills: ['routine-stamina'],
    qualities: { 'aerobic-base': 0.7, 'anaerobic-capacity': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'rectus-femoris': 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['A set of combinations across the floor, music on.'],
    execution: ['Chassé, leap, turn combinations back and forth continuously for routine length.', 'Technique stays clean on the last pass.'],
    cues: ['Clean on the last pass', 'Breathe with the music'],
    mistakes: ['Losing turnout and pointed feet as you tire.'],
    defaultDose: time(3, 150), restSeconds: 60, startPose: 'bound', endPose: 'landing',
  },
  {
    slug: 'active-extensions', name: 'Active Extensions', skills: ['flexibility', 'leap-height'],
    qualities: { 'hip-mobility': 0.9, 'trunk-anti-rotation': 0.5 },
    muscles: { 'iliopsoas': 0.7, 'rectus-femoris': 0.5, 'adductors': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['At the barre or a wall.'],
    execution: ['Développé to the front, side and back, holding each extension at its highest for three seconds.', 'Lower slowly without dropping.'],
    cues: ['Lift from underneath', 'Standing hip level'],
    mistakes: ['Hiking the hip to get the leg higher.'],
    defaultDose: reps(2, 8), restSeconds: 30, startPose: 'single-leg-balance', endPose: 'mobility-flow',
  },
  {
    slug: 'plie-landing-drill', name: 'Plié Landing Drill', skills: ['landing-control'],
    qualities: { 'landing-mechanics': 0.9, 'ankle-stiffness': 0.5 },
    muscles: { 'soleus': 0.6, 'vastus-medialis': 0.6, 'gluteus-medius': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Studio floor.'],
    execution: ['Sauté jumps in first position, landing toe-ball-heel into a deep, quiet plié.', 'Progress to changements and single-leg landings.'],
    cues: ['Toe, ball, heel', 'Knees over toes'],
    mistakes: ['Landing flat-footed with a thud.'],
    defaultDose: contacts(3, 12), restSeconds: 45, startPose: 'pogo', endPose: 'landing',
  },
  {
    slug: 'fouette-prep', name: 'Fouetté Prep', skills: ['turn-control', 'routine-stamina'],
    qualities: { 'single-leg-stability': 0.8, 'hip-mobility': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'iliopsoas': 0.5, 'gastrocnemius': 0.5 },
    equipment: ['none'], surface: 'gym', minAge: 14,
    setup: ['Facing a spot, from fourth position.'],
    execution: ['Plié, relevé, extend the working leg front and whip it to the side and into passé without turning first.', 'Add single turns once the leg action is clean.'],
    cues: ['Plié every time', 'Whip from the hip'],
    mistakes: ['Skipping the plié and losing momentum.'],
    defaultDose: reps(3, 8), restSeconds: 30, startPose: 'single-leg-balance', endPose: 'trunk-rotation',
  },
]);

const STEP = sportDrills('step-team', [
  {
    slug: 'rhythm-stomp-clap', name: 'Rhythm Stomp-Clap Patterns', skills: ['rhythmic-precision'],
    qualities: { 'reactive-strength': 0.6, 'aerobic-base': 0.5 },
    muscles: { 'gastrocnemius': 0.5, 'rectus-femoris': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['A metronome app at 90 bpm.'],
    execution: ['Stomp-stomp-clap patterns exactly on the beat for eight counts, then add body slaps.', 'Raise the tempo 5 bpm when clean.'],
    cues: ['Land on the beat', 'Sharp sounds'],
    mistakes: ['Rushing ahead of the beat.'],
    defaultDose: time(4, 60), restSeconds: 30, startPose: 'pogo', endPose: 'isometric-hold',
  },
  {
    slug: 'power-stomp-jumps', name: 'Power Stomp Jumps', skills: ['jump-power'],
    qualities: { 'vertical-power': 0.8, 'reactive-strength': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'gluteus-maximus': 0.5, 'vastus-lateralis': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['Clear space in formation.'],
    execution: ['Jump and land with a hard, loud stomp in time, then rebound immediately into the next.', 'Keep landings loud but controlled.'],
    cues: ['Loud, not sloppy', 'Rebound fast'],
    mistakes: ['Landing with locked knees.'],
    defaultDose: contacts(3, 12), restSeconds: 45, startPose: 'vertical-jump', endPose: 'landing',
  },
  {
    slug: 'routine-run-throughs', name: 'Full Routine Run-Throughs', skills: ['routine-endurance', 'rhythmic-precision'],
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'deltoid-lateral': 0.5, 'rectus-femoris': 0.4 },
    equipment: ['none'], surface: 'gym',
    setup: ['Full team in formation.'],
    execution: ['Run the complete show start to finish at performance energy.', 'Rest, then run it again, fixing one section.'],
    cues: ['Performance energy every time', 'Stay in formation'],
    mistakes: ['Marking the hard sections in practice.'],
    defaultDose: time(3, 240), restSeconds: 120, startPose: 'pogo', endPose: 'vertical-jump',
  },
  {
    slug: 'hamstring-mobility', name: 'Step Team Mobility', skills: ['flexibility'],
    qualities: { 'hip-mobility': 0.9 },
    muscles: { 'biceps-femoris': 0.6, 'iliopsoas': 0.5, 'adductors': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['After practice.'],
    execution: ['Hamstring, hip-flexor and adductor stretches, 30 seconds each side.', 'Breathe slowly through each.'],
    cues: ['Breathe out into it', 'No bouncing'],
    mistakes: ['Skipping it when practice runs late.'],
    defaultDose: time(2, 120), restSeconds: 10, startPose: 'mobility-flow', endPose: 'lunge',
  },
  {
    slug: 'body-percussion-endurance', name: 'Body Percussion Endurance', skills: ['routine-endurance'],
    qualities: { 'anaerobic-capacity': 0.7, 'shoulder-stability': 0.5 },
    muscles: { 'deltoid-anterior': 0.5, 'pectoralis-major': 0.4, 'rectus-abdominis': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Metronome at your performance tempo.'],
    execution: ['Continuous chest, thigh and hand slaps with stomps on every fourth count for the interval.', 'Stay exactly on the beat.'],
    cues: ['Crisp sounds', 'Stay on tempo'],
    mistakes: ['Slapping softer as you tire.'],
    defaultDose: time(4, 45), restSeconds: 30, startPose: 'isometric-hold', endPose: 'pogo',
  },
  {
    slug: 'split-squat-power', name: 'Split-Squat Jumps', skills: ['jump-power'],
    qualities: { 'vertical-power': 0.7, 'single-leg-stability': 0.6 },
    muscles: { 'gluteus-maximus': 0.6, 'rectus-femoris': 0.6, 'gastrocnemius': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Split stance.'],
    execution: ['Jump and switch legs in the air, landing in the opposite split stance.', 'Pause one beat between jumps to control the landing.'],
    cues: ['Tall torso', 'Soft landing'],
    mistakes: ['Front knee caving inward.'],
    defaultDose: contacts(3, 10), restSeconds: 45, startPose: 'split-squat', endPose: 'split-squat',
  },
  {
    slug: 'formation-transitions', name: 'Formation Transitions on Count', skills: ['rhythmic-precision'],
    qualities: { 'acceleration': 0.5, 'change-of-direction': 0.5 },
    muscles: { 'gastrocnemius': 0.5, 'gluteus-medius': 0.4, 'rectus-femoris': 0.4 },
    equipment: ['cones'], surface: 'gym',
    setup: ['Floor marks (cones) for two formations.'],
    execution: ['Switch formations in exactly eight counts, arriving and stomping on count eight.', 'Repeat both directions.'],
    cues: ['Arrive on eight', 'Stay in lines'],
    mistakes: ['Arriving early and waiting.'],
    defaultDose: reps(3, 6), restSeconds: 30, startPose: 'sprint-cycle', endPose: 'pogo',
  },
]);

const GUARD = sportDrills('color-guard', [
  {
    slug: 'flag-spin-drills', name: 'Flag Spin Fundamentals', skills: ['equipment-control'],
    qualities: { 'grip': 0.7, 'shoulder-stability': 0.7 },
    muscles: { 'forearm-flexors': 0.6, 'deltoid-anterior': 0.5, 'forearm-extensors': 0.5 },
    equipment: ['stick'], surface: 'field',
    setup: ['A flag or pole, arms-length clearance all round.'],
    execution: ['Drop spins, flat spins and carving spins on counts, keeping the pole in one plane.', 'Switch hands every eight counts.'],
    cues: ['Right hand guides, left hand drives', 'Stay in the plane'],
    mistakes: ['The pole drifting out of plane and wobbling.'],
    defaultDose: time(4, 60), restSeconds: 30, startPose: 'isometric-hold', endPose: 'trunk-rotation',
  },
  {
    slug: 'toss-and-catch-counts', name: 'Toss-and-Catch on Counts', skills: ['toss-catch-timing'],
    qualities: { 'overhead-power': 0.6, 'shoulder-stability': 0.6, 'reactive-strength': 0.5 },
    muscles: { 'deltoid-anterior': 0.6, 'triceps-brachii': 0.5, 'forearm-flexors': 0.5 },
    equipment: ['stick'], surface: 'field',
    setup: ['A flag or rifle, open space, counts called out.'],
    execution: ['Single toss on count one, catch on count four; progress to double and triple tosses.', 'Catch in the same spot every time.'],
    cues: ['Toss straight up', 'Eyes on the rotation'],
    mistakes: ['Tossing forward, which makes you chase the catch.'],
    defaultDose: reps(4, 8), restSeconds: 30, startPose: 'vertical-push', endPose: 'vertical-push',
  },
  {
    slug: 'shoulder-endurance-holds', name: 'Pole Holds for Shoulder Endurance', skills: ['shoulder-endurance'],
    qualities: { 'shoulder-stability': 0.9 },
    muscles: { 'deltoid-lateral': 0.7, 'trapezius-upper': 0.5, 'infraspinatus': 0.5 },
    equipment: ['stick'], surface: 'anywhere',
    setup: ['Hold the pole horizontally at shoulder height.'],
    execution: ['Hold the pole out, overhead, and at a 45-degree present for 20 seconds each without dipping.', 'Cycle through for the interval.'],
    cues: ['Lock the angle', 'Shoulders down'],
    mistakes: ['Shrugging to hold the weight.'],
    defaultDose: time(3, 60), restSeconds: 45, startPose: 'isometric-hold', endPose: 'vertical-push',
  },
  {
    slug: 'across-the-floor-guard', name: 'Across-the-Floor Movement', skills: ['routine-precision'],
    qualities: { 'single-leg-stability': 0.6, 'hip-mobility': 0.6 },
    muscles: { 'gluteus-medius': 0.5, 'gastrocnemius': 0.5, 'iliopsoas': 0.5 },
    equipment: ['none'], surface: 'gym',
    setup: ['A diagonal across the floor.'],
    execution: ['Jazz runs, chaînés and leaps across the floor on counts.', 'Hold a pose at the end of each pass.'],
    cues: ['Pointed feet', 'Finish the pose'],
    mistakes: ['Losing the count halfway across.'],
    defaultDose: reps(3, 6), restSeconds: 30, startPose: 'bound', endPose: 'single-leg-balance',
  },
  {
    slug: 'wrist-forearm-strength', name: 'Wrist and Forearm Strength', skills: ['equipment-control', 'shoulder-endurance'],
    qualities: { 'grip': 0.9 },
    muscles: { 'forearm-flexors': 0.7, 'forearm-extensors': 0.7, 'brachioradialis': 0.5 },
    equipment: ['dumbbell'], surface: 'anywhere',
    setup: ['A light dumbbell, forearm resting on the thigh.'],
    execution: ['Wrist curls, reverse wrist curls and rotations, slow and controlled.', 'Finish with a 20-second grip squeeze.'],
    cues: ['Slow up, slower down', 'Full range'],
    mistakes: ['Using too much weight and jerking it.'],
    defaultDose: reps(3, 12, 'light'), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'show-run-endurance', name: 'Show Run-Through', skills: ['routine-precision', 'shoulder-endurance'],
    qualities: { 'aerobic-base': 0.8, 'shoulder-stability': 0.5 },
    muscles: { 'deltoid-lateral': 0.5, 'gastrocnemius': 0.5, 'rectus-femoris': 0.4 },
    equipment: ['stick'], surface: 'field',
    setup: ['Full show with equipment.'],
    execution: ['Perform the show at full effort, recording drops.', 'Rerun the section with the most drops.'],
    cues: ['Every toss is a performance', 'Recover drops instantly'],
    mistakes: ['Only practising sections, never the full show.'],
    defaultDose: time(3, 300), restSeconds: 120, startPose: 'bound', endPose: 'vertical-push',
  },
  {
    slug: 'balance-poses', name: 'Balance Pose Holds', skills: ['routine-precision'],
    qualities: { 'single-leg-stability': 0.8 },
    muscles: { 'gluteus-medius': 0.6, 'peroneals': 0.5, 'transverse-abdominis': 0.5 },
    equipment: ['stick'], surface: 'anywhere',
    setup: ['Holding your equipment.'],
    execution: ['Hold arabesque and passé poses on each leg with the equipment at a set angle.', 'Hold eight counts per pose.'],
    cues: ['Still equipment, still body', 'Tall spine'],
    mistakes: ['Equipment angle drifting as you balance.'],
    defaultDose: time(3, 40), restSeconds: 20, startPose: 'single-leg-balance', endPose: 'isometric-hold',
  },
]);

const BAND = sportDrills('marching-band-athletics', [
  {
    slug: 'eight-to-five-drill', name: 'Eight-to-Five Marching Drill', skills: ['marching-endurance', 'postural-control-while-playing'],
    qualities: { 'aerobic-base': 0.8, 'single-leg-stability': 0.5 },
    muscles: { 'tibialis-anterior': 0.6, 'gastrocnemius': 0.5, 'erector-spinae': 0.4 },
    equipment: ['cones'], surface: 'field',
    setup: ['Yard lines on a field; instrument or a stand-in held in playing position.'],
    execution: ['March eight steps per five yards with a smooth roll step, upper body perfectly still.', 'Continue for multiple yard lines, then backward march.'],
    cues: ['Roll heel to toe', 'Glide — head doesn\'t bob'],
    mistakes: ['Bouncing, which shows in the sound.'],
    defaultDose: time(4, 120), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'isometric-hold',
  },
  {
    slug: 'breathing-gym', name: 'Breathing Gym', skills: ['breath-support'],
    qualities: { 'trunk-anti-rotation': 0.6, 'aerobic-base': 0.5 },
    muscles: { 'transverse-abdominis': 0.6, 'obliques-internal': 0.5, 'rectus-abdominis': 0.4 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Stand tall with relaxed shoulders.'],
    execution: ['Inhale for 4 counts, exhale for 8; then inhale 4, exhale 12; then 4 in, 16 out.', 'Keep the shoulders relaxed and the air low in the body.'],
    cues: ['Low, full breath', 'Steady air'],
    mistakes: ['Lifting the shoulders when breathing in.'],
    defaultDose: time(3, 90), restSeconds: 20, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'posture-holds-with-instrument', name: 'Playing-Position Posture Holds', skills: ['postural-control-while-playing'],
    qualities: { 'shoulder-stability': 0.7, 'trunk-anti-rotation': 0.6 },
    muscles: { 'trapezius-middle': 0.6, 'erector-spinae': 0.6, 'deltoid-anterior': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Horn up (or arms in position) at set.'],
    execution: ['Hold the playing position with a tall spine for the interval, then march in place.', 'Keep the instrument angle fixed.'],
    cues: ['Tall spine, horn up', 'Shoulders down'],
    mistakes: ['Slumping as the arms tire.'],
    defaultDose: time(3, 60), restSeconds: 30, startPose: 'isometric-hold', endPose: 'isometric-hold',
  },
  {
    slug: 'heat-acclimation-run', name: 'Progressive Heat Conditioning', skills: ['heat-tolerance-conditioning', 'marching-endurance'],
    qualities: { 'aerobic-base': 0.9 },
    muscles: { 'gastrocnemius': 0.5, 'rectus-femoris': 0.5, 'soleus': 0.4 },
    equipment: ['none'], surface: 'field',
    setup: ['Early in camp, in the cooler part of the day; water available at all times.'],
    execution: ['Easy continuous marching or jogging, adding a few minutes each day over the first two weeks.', 'Drink water regularly and stop if you feel dizzy or sick — tell a director.'],
    cues: ['Build up gradually', 'Drink before you\'re thirsty'],
    mistakes: ['Going full intensity on day one in the heat.'],
    defaultDose: time(1, 900), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'backward-march-control', name: 'Backward March Control', skills: ['marching-endurance'],
    qualities: { 'ankle-stiffness': 0.6, 'single-leg-stability': 0.6 },
    muscles: { 'gastrocnemius': 0.6, 'soleus': 0.6, 'tibialis-anterior': 0.4 },
    equipment: ['cones'], surface: 'field',
    setup: ['Yard lines for spacing.'],
    execution: ['March backward on the balls of the feet with heels off the ground, keeping the upper body still.', 'Keep exact step size.'],
    cues: ['Stay on your toes', 'Even steps'],
    mistakes: ['Heels dropping, which causes a bounce.'],
    defaultDose: time(3, 60), restSeconds: 30, startPose: 'pogo', endPose: 'isometric-hold',
  },
  {
    slug: 'core-for-carry', name: 'Instrument Carry Core', skills: ['postural-control-while-playing'],
    qualities: { 'trunk-anti-rotation': 0.8, 'grip': 0.5 },
    muscles: { 'obliques-internal': 0.6, 'erector-spinae': 0.6, 'transverse-abdominis': 0.5 },
    equipment: ['dumbbell'], surface: 'anywhere',
    setup: ['A dumbbell of similar weight to your instrument.'],
    execution: ['Hold it in front at chest height and walk 20 m, then hold on one side and walk back.', 'Stay perfectly upright.'],
    cues: ['Tall and still', 'Brace the core'],
    mistakes: ['Leaning back to balance the weight.'],
    defaultDose: dist(3, 40), restSeconds: 45, startPose: 'carry', endPose: 'carry',
  },
  {
    slug: 'play-while-marching-intervals', name: 'Play-While-Marching Intervals', skills: ['breath-support', 'marching-endurance'],
    qualities: { 'aerobic-base': 0.8, 'trunk-anti-rotation': 0.5 },
    muscles: { 'transverse-abdominis': 0.5, 'gastrocnemius': 0.5, 'tibialis-anterior': 0.4 },
    equipment: ['none'], surface: 'field',
    setup: ['Your instrument, a tempo track.'],
    execution: ['March a set while playing long tones, then move to your show music.', 'Track whether the sound stays steady while moving.'],
    cues: ['Steady air while moving', 'Smooth feet, smooth sound'],
    mistakes: ['Breath control failing on direction changes.'],
    defaultDose: time(4, 120), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'isometric-hold',
  },
]);

export const INDIVIDUAL_DRILLS = [
  ...WRESTLING, ...JUDO, ...FENCING, ...WEIGHTLIFTING, ...POWERLIFTING, ...CONDITIONING,
  ...GYMNASTICS, ...SPIRIT, ...SIDELINE, ...DANCE, ...STEP, ...GUARD, ...BAND,
];
