/**
 * Sport drills — ice hockey, inline hockey, field hockey (field players and
 * goalkeepers), lacrosse (field and box), adapted floor hockey. Written from
 * standard club and high-school coaching practice for each sport: every
 * drill states its setup, the execution, the cues a coach shouts, and the
 * mistake that ruins it.
 */

import { contacts, dist, reps, sportDrills, time } from '../drillKit.js';

const ICE_HOCKEY = sportDrills('ice-hockey', [
  {
    slug: 'slap-shot-weight-transfer', name: 'Slap-Shot Weight Transfer', skills: ['shooting-power'],
    qualities: { 'rotational-power': 0.9, 'lateral-power': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'obliques-external': 0.7, 'latissimus-dorsi': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['stick', 'puck', 'skates', 'goal'], prop: 'stick-hockey', surface: 'ice',
    setup: ['A row of pucks 25 feet out from the net, shooter stationary and side-on to the target.'],
    execution: ['Load weight onto the back leg with the stick back to shoulder height.', 'Transfer the weight onto the front leg as the blade strikes the ice just behind the puck, flexing the shaft, and follow through low to the target.'],
    cues: ['Hit the ice first', 'Weight back to front'],
    mistakes: ['Hitting the puck clean without touching the ice first, which never loads the shaft.'],
    defaultDose: reps(4, 8), restSeconds: 60, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'quick-release-snap-shots', name: 'Quick-Release Snap Shots', skills: ['shot-release-quickness', 'shooting-power'],
    qualities: { 'rotational-power': 0.8, 'grip': 0.5, 'reactive-strength': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'obliques-external': 0.6, 'triceps-brachii': 0.4 },
    equipment: ['stick', 'puck', 'goal', 'partner'], prop: 'stick-hockey', surface: 'ice',
    setup: ['Shooter in the slot, a partner feeding passes from the half-wall.'],
    execution: ['Receive the pass and release a snap shot within one second — no stickhandling first.', 'Change the angle of the feed every five reps so the catch-and-release adapts.'],
    cues: ['Catch it in shooting position', 'Snap the wrists, point the toe of the blade'],
    mistakes: ['Pulling the puck across the body to get comfortable, which gives the goalie time to set.'],
    defaultDose: reps(4, 8), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw', constraintAxes: ['touches'],
  },
  {
    slug: 'blue-line-sprints', name: 'Blue-Line Stop-Start Sprints', skills: ['skating-speed', 'shift-endurance'],
    qualities: { 'acceleration': 0.9, 'repeat-sprint': 0.7, 'deceleration': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.7, 'adductors': 0.5 },
    equipment: ['skates'], surface: 'ice',
    setup: ['Start on the goal line in a ready stance.'],
    execution: ['Sprint to the near blue line, two-foot hockey stop, sprint back to the goal line, stop, then sprint to the far blue line.', 'Every stop faces the same wall so both edges get work across sets.'],
    cues: ['Short, choppy first three strides', 'Full extension after that'],
    mistakes: ['Gliding into the stops instead of skating hard all the way to the line.'],
    defaultDose: reps(3, 4), restSeconds: 90, startPose: 'sprint-start', endPose: 'skating-stride',
  },
  {
    slug: 'shift-length-intervals', name: 'Shift-Length Intervals', skills: ['shift-endurance'],
    qualities: { 'anaerobic-capacity': 0.9, 'repeat-sprint': 0.7, 'aerobic-base': 0.5 },
    muscles: { 'vastus-lateralis': 0.6, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.4 },
    equipment: ['skates'], surface: 'ice',
    setup: ['Full sheet of ice, a timer visible from the bench.'],
    execution: ['Skate hard laps for 40 seconds, mixing crossovers in the corners and straight-line bursts.', 'Rest on the bench for about two minutes — a real game rhythm — then go again.'],
    cues: ['Last ten seconds as hard as the first', 'Recover with slow breathing on the bench'],
    mistakes: ['Pacing the shift like a jog, which trains the wrong energy system.'],
    defaultDose: time(6, 40), restSeconds: 120, startPose: 'skating-stride', endPose: 'crossover-stride',
  },
  {
    slug: 'tight-turns-circles', name: 'Tight Turns Around the Circles', skills: ['edge-work'],
    qualities: { 'single-leg-stability': 0.8, 'change-of-direction': 0.7, 'hip-mobility': 0.5 },
    muscles: { 'gluteus-medius': 0.7, 'adductors': 0.6, 'peroneals': 0.4 },
    equipment: ['skates', 'stick', 'puck'], prop: 'stick-hockey', surface: 'ice',
    setup: ['Use the five face-off circles; puck on the stick.'],
    execution: ['Skate around each circle on your inside edges with the knees bent and the stick on the ice.', 'Finish each circle with a tight turn around the dot before sprinting to the next.'],
    cues: ['Lean in, knee over toe', 'Head up, puck on the blade'],
    mistakes: ['Standing up tall through the turn, which lets the edge slip out.'],
    defaultDose: reps(3, 2), restSeconds: 60, startPose: 'crossover-stride', endPose: 'skating-stride',
  },
  {
    slug: 'mohawk-transitions', name: 'Mohawk Forward-to-Backward Transitions', skills: ['edge-work', 'crossover-acceleration'],
    qualities: { 'hip-mobility': 0.8, 'change-of-direction': 0.7, 'single-leg-stability': 0.6 },
    muscles: { 'deep-hip-rotators': 0.7, 'gluteus-medius': 0.6, 'adductors': 0.5 },
    equipment: ['skates', 'cones'], surface: 'ice',
    setup: ['A line of cones down the middle of the rink, 10 feet apart.'],
    execution: ['Skate forward to each cone, open the hips with heels facing each other and pivot to backward skating without stopping.', 'Pivot back to forward at the next cone, alternating the side you open to.'],
    cues: ['Open the hips, not the shoulders', 'Keep your speed through the pivot'],
    mistakes: ['Hopping the turn instead of rolling the edges round.'],
    defaultDose: reps(3, 4), restSeconds: 60, startPose: 'skating-stride', endPose: 'crossover-stride',
  },
  {
    slug: 'toe-drag-stickhandling', name: 'Toe-Drag Stickhandling Lane', skills: ['puck-handling'],
    qualities: { 'grip': 0.6, 'change-of-direction': 0.6, 'reactive-strength': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'forearm-extensors': 0.6, 'deltoid-anterior': 0.4 },
    equipment: ['stick', 'puck', 'cones'], prop: 'stick-hockey', surface: 'ice',
    setup: ['Six cones in a staggered lane across the neutral zone.'],
    execution: ['Skate through the lane, pulling the puck around each cone with a toe drag.', 'Alternate forehand and backhand toe drags, then shoot on net at the end.'],
    cues: ['Cup the puck with the toe', 'Eyes up between cones'],
    mistakes: ['Pushing the puck too far out so you reach and lose it.'],
    defaultDose: reps(4, 3), restSeconds: 45, startPose: 'skating-stride', endPose: 'swing-stride', constraintAxes: ['opposition'],
  },
  {
    slug: 'dryland-stickhandling-ball', name: 'Dryland Stickhandling With a Ball', skills: ['puck-handling'],
    qualities: { 'grip': 0.6, 'reactive-strength': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'forearm-extensors': 0.6, 'brachioradialis': 0.4 },
    equipment: ['stick', 'ball'], prop: 'stick-hockey', surface: 'anywhere',
    setup: ['A hockey stick and a golf ball or dangle ball on a smooth floor.'],
    execution: ['Stickhandle side to side in front of your feet for the interval, keeping soft hands.', 'Rotate through narrow dribbles, wide dribbles and figure-eights around your feet.'],
    cues: ['Top hand does the work', 'Quiet, fast hands'],
    mistakes: ['Squeezing the stick with the bottom hand so the movement gets stiff.'],
    defaultDose: time(5, 30), restSeconds: 30, startPose: 'squat', endPose: 'squat',
  },
  {
    slug: 'crossover-starts', name: 'Crossover Starts From the Dot', skills: ['crossover-acceleration', 'skating-speed'],
    qualities: { 'acceleration': 0.8, 'lateral-power': 0.8, 'horizontal-power': 0.5 },
    muscles: { 'adductors': 0.7, 'gluteus-medius': 0.6, 'vastus-lateralis': 0.6 },
    equipment: ['skates'], surface: 'ice',
    setup: ['Stand side-on at a face-off dot.'],
    execution: ['Open the lead foot and drive two hard crossovers, then sprint 30 feet straight ahead.', 'Alternate the side you start from each rep.'],
    cues: ['Push under, not over', 'Stay low through the first strides'],
    mistakes: ['Stepping over with the crossover leg without pushing underneath.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'crossover-stride', endPose: 'skating-stride',
  },
  {
    slug: 'board-battle-body-position', name: 'Board-Battle Body Position', skills: ['checking-strength'],
    qualities: { 'lower-body-strength': 0.7, 'trunk-anti-rotation': 0.7, 'lateral-power': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'obliques-internal': 0.6, 'adductors': 0.5 },
    equipment: ['skates', 'partner', 'puck'], surface: 'ice', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['Two players along the boards with a puck between them; a coach supervises.'],
    execution: ['Both players fight for inside position with a wide base, hips low and stick on the ice.', 'Win the puck out to a support player within 10 seconds, then swap.'],
    cues: ['Low hips win the wall', 'Legs moving the whole time'],
    mistakes: ['Leaning on the opponent with straight legs, which gets you spun off the puck.'],
    defaultDose: time(4, 10), restSeconds: 60, startPose: 'lateral-shuffle', endPose: 'horizontal-push',
  },
  {
    slug: 'lateral-skater-bounds', name: 'Lateral Skater Bounds', skills: ['skating-speed', 'crossover-acceleration'],
    qualities: { 'lateral-power': 0.9, 'single-leg-stability': 0.6, 'landing-mechanics': 0.5 },
    muscles: { 'gluteus-medius': 0.7, 'gluteus-maximus': 0.6, 'adductors': 0.5 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Off-ice, a clear lane about 5 metres wide.'],
    execution: ['Push off one leg and bound sideways, landing softly on the other leg in a skating posture.', 'Stick each landing for a count of one before bounding back.'],
    cues: ['Push through the whole foot', 'Land quiet, knee over toes'],
    mistakes: ['Knee collapsing inward on the landing leg.'],
    defaultDose: contacts(3, 12), restSeconds: 60, startPose: 'lateral-bound', endPose: 'single-leg-balance',
  },
  {
    slug: 'one-timer-reps', name: 'One-Timer Reps From the Circle', skills: ['shooting-power', 'shot-release-quickness'],
    qualities: { 'rotational-power': 0.9, 'reactive-strength': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'obliques-external': 0.7, 'latissimus-dorsi': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['stick', 'puck', 'goal', 'partner'], prop: 'stick-hockey', surface: 'ice',
    setup: ['Shooter at the top of the circle on the off-side; passer below the goal line.'],
    execution: ['Open up to the passer, stick loaded, and shoot the pass directly without stopping it.', 'Aim for the far side, then switch sides.'],
    cues: ['Face the passer, open the blade', 'Timing over power'],
    mistakes: ['Winding up too early so the puck arrives behind you.'],
    defaultDose: reps(4, 6), restSeconds: 60, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
]);

const INLINE_HOCKEY = sportDrills('inline-hockey', [
  {
    slug: 'wrist-shot-release', name: 'Wrist-Shot Release on Wheels', skills: ['shooting-power'],
    qualities: { 'rotational-power': 0.8, 'grip': 0.5, 'single-leg-stability': 0.5 },
    muscles: { 'obliques-external': 0.6, 'forearm-flexors': 0.6, 'latissimus-dorsi': 0.5 },
    equipment: ['stick', 'puck', 'skates', 'goal'], prop: 'stick-hockey', surface: 'court',
    setup: ['A row of pucks 20 feet from the net on a sport-court surface.'],
    execution: ['Cup the puck on the heel of the blade and sweep it forward, rolling the wrists at release.', 'Transfer weight onto the front skate and point the blade at the target on the finish.'],
    cues: ['Heel to toe roll', 'Finish pointing at the corner'],
    mistakes: ['Flicking only from the wrists with no weight transfer.'],
    defaultDose: reps(4, 8), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'full-rink-sprints', name: 'Full-Rink Sprints', skills: ['skating-speed'],
    qualities: { 'acceleration': 0.8, 'max-velocity': 0.7, 'repeat-sprint': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6, 'adductors': 0.5 },
    equipment: ['skates'], surface: 'court',
    setup: ['Start behind one goal line.'],
    execution: ['Sprint the full length with full stride extension and a powerstop at the far end.', 'Walk or glide back slowly as recovery.'],
    cues: ['Push to the side, not back', 'Swing the arms front to back'],
    mistakes: ['Short, choppy strides the whole way, which never reach top speed.'],
    defaultDose: reps(3, 5), restSeconds: 75, startPose: 'sprint-start', endPose: 'skating-stride',
  },
  {
    slug: 'figure-eight-stickhandling', name: 'Figure-Eight Stickhandling Around Cones', skills: ['stick-handling'],
    qualities: { 'grip': 0.6, 'change-of-direction': 0.6 },
    muscles: { 'forearm-flexors': 0.7, 'forearm-extensors': 0.5, 'gluteus-medius': 0.4 },
    equipment: ['stick', 'puck', 'cones', 'skates'], prop: 'stick-hockey', surface: 'court',
    setup: ['Two cones 12 feet apart.'],
    execution: ['Skate figure-eights around the cones while stickhandling the puck.', 'Keep the puck on the forehand going one way and the backhand the other.'],
    cues: ['Soft hands, head up', 'Tight around the cones'],
    mistakes: ['Watching the puck the whole time.'],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'crossover-stride', endPose: 'skating-stride',
  },
  {
    slug: 'crossover-circles', name: 'Crossover Circles', skills: ['edge-work', 'skating-speed'],
    qualities: { 'lateral-power': 0.7, 'single-leg-stability': 0.7, 'hip-mobility': 0.5 },
    muscles: { 'adductors': 0.7, 'gluteus-medius': 0.6, 'peroneals': 0.4 },
    equipment: ['skates', 'cones'], surface: 'court',
    setup: ['A circle marked with four cones, about 20 feet across.'],
    execution: ['Skate continuous crossovers around the circle, pushing under with the inside leg.', 'Switch direction every lap.'],
    cues: ['Shoulders level', 'Push under with the inside leg'],
    mistakes: ['Leaning the upper body in so the wheels wash out.'],
    defaultDose: reps(3, 4), restSeconds: 45, startPose: 'crossover-stride', endPose: 'crossover-stride',
  },
  {
    slug: 'powerslide-stops', name: 'Powerslide Stops', skills: ['edge-work'],
    qualities: { 'deceleration': 0.8, 'single-leg-stability': 0.6, 'ankle-stiffness': 0.5 },
    muscles: { 'vastus-medialis': 0.6, 'gluteus-medius': 0.6, 'peroneals': 0.5 },
    equipment: ['skates'], surface: 'court',
    setup: ['A clear straight lane about 30 metres long.'],
    execution: ['Build speed, turn the back skate perpendicular and slide it out while bending the front knee.', 'Come to a full stop and sprint back the other way.'],
    cues: ['Weight on the front leg', 'Low and wide'],
    mistakes: ['Putting weight on the sliding skate, which spins you out.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'skating-stride', endPose: 'deceleration-plant',
  },
  {
    slug: 'give-and-go-passing', name: 'Give-and-Go Passing Lanes', skills: ['stick-handling', 'shooting-power'],
    qualities: { 'acceleration': 0.6, 'rotational-power': 0.5, 'grip': 0.4 },
    muscles: { 'forearm-flexors': 0.6, 'obliques-external': 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['stick', 'puck', 'skates', 'partner', 'goal'], prop: 'stick-hockey', surface: 'court',
    setup: ['Two players at the far end, one net at the other.'],
    execution: ['Pass to your partner, sprint into space, and receive the return pass in stride.', 'Finish with a shot on goal; alternate roles.'],
    cues: ['Pass and move — never stand still', 'Receive in stride'],
    mistakes: ['Stopping after the pass so the return pass has nowhere to go.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'skating-stride', endPose: 'rotational-throw', constraintAxes: ['opposition'],
  },
  {
    slug: 'backward-c-cuts', name: 'Backward C-Cuts', skills: ['edge-work', 'skating-speed'],
    qualities: { 'hip-mobility': 0.6, 'lateral-power': 0.6, 'single-leg-stability': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'adductors': 0.6, 'vastus-lateralis': 0.4 },
    equipment: ['skates'], surface: 'court',
    setup: ['Start at one goal line facing the goal.'],
    execution: ['Skate backward the length of the rink using alternating C-cuts from each skate.', 'Keep the knees bent and the chest up the whole way.'],
    cues: ['Sit in a chair', 'Push with the inside edge'],
    mistakes: ['Bending at the waist instead of the knees.'],
    defaultDose: reps(3, 3), restSeconds: 45, startPose: 'squat', endPose: 'crossover-stride',
  },
]);

const FIELD_HOCKEY = sportDrills('field-hockey', [
  {
    slug: 'drag-flick-progression', name: 'Drag-Flick Progression', skills: ['drag-flick-power'],
    qualities: { 'rotational-power': 0.9, 'lateral-power': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'obliques-external': 0.7, 'gluteus-maximus': 0.6, 'latissimus-dorsi': 0.5 },
    equipment: ['stick', 'ball', 'goal'], prop: 'stick-hockey', surface: 'field', minAge: 14,
    setup: ['Balls at the penalty-corner injection spot; flicker starts at the top of the circle.'],
    execution: ['Take a low, wide run-in, drop the body with the ball at the heel of the stick behind the front foot.', 'Drag the ball forward along the ground and sling it upward toward the goal, rotating the hips through.'],
    cues: ['Get low early', 'Long drag, then sling'],
    mistakes: ['Standing up during the drag, which loses both power and control.'],
    defaultDose: reps(4, 6), restSeconds: 75, startPose: 'lunge', endPose: 'rotational-throw',
  },
  {
    slug: 'repeat-25-yard-sprints', name: 'Repeat 25-Yard Sprints', skills: ['sprint-speed'],
    qualities: { 'acceleration': 0.9, 'repeat-sprint': 0.8, 'max-velocity': 0.5 },
    muscles: { 'biceps-femoris': 0.7, 'gluteus-maximus': 0.7, 'gastrocnemius': 0.5 },
    equipment: ['cones'], surface: 'field',
    setup: ['Cones 25 yards apart after a full warm-up.'],
    execution: ['Sprint 25 yards from a standing start carrying your stick.', 'Walk back as recovery and repeat.'],
    cues: ['Drive the knees', 'Carry the stick without flapping it'],
    mistakes: ['Easing off after 15 yards.'],
    defaultDose: reps(2, 6), restSeconds: 90, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'indian-dribble-lane', name: 'Indian-Dribble Lane', skills: ['stick-handling', 'reverse-stick-control'],
    qualities: { 'grip': 0.6, 'change-of-direction': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'forearm-extensors': 0.6, 'gluteus-medius': 0.4 },
    equipment: ['stick', 'ball', 'cones'], prop: 'stick-hockey', surface: 'field',
    setup: ['A 20-yard lane marked with cones.'],
    execution: ['Pull the ball side to side between open stick and reverse stick while moving down the lane.', 'Accelerate out of the last dribble and pass to a cone target.'],
    cues: ['Left hand turns the stick', 'Ball in front of the feet'],
    mistakes: ['Dragging the ball too wide so you can\'t get the reverse back in time.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'sprint-cycle', constraintAxes: ['opposition'],
  },
  {
    slug: 'push-pass-gates', name: 'Push-Pass Through Gates', skills: ['passing-accuracy'],
    qualities: { 'rotational-power': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'obliques-external': 0.5, 'triceps-brachii': 0.5, 'gluteus-medius': 0.4 },
    equipment: ['stick', 'ball', 'cones', 'partner'], prop: 'stick-hockey', surface: 'field',
    setup: ['Two players 15 yards apart with a small cone gate between them.'],
    execution: ['Push-pass through the gate keeping the stick in contact with the ball the whole way.', 'Receive, set and return; move the gate off-centre as accuracy improves.'],
    cues: ['Push, don\'t hit', 'Follow through to the target'],
    mistakes: ['Lifting the stick off the ball so the push becomes a scrappy slap.'],
    defaultDose: reps(3, 12), restSeconds: 30, startPose: 'lunge', endPose: 'swing-stride', constraintAxes: ['touches'],
  },
  {
    slug: 'hit-pass-accuracy', name: 'Hit-Pass Accuracy to Targets', skills: ['passing-accuracy'],
    qualities: { 'rotational-power': 0.7, 'grip': 0.5, 'single-leg-stability': 0.4 },
    muscles: { 'obliques-external': 0.6, 'latissimus-dorsi': 0.5, 'forearm-flexors': 0.5 },
    equipment: ['stick', 'ball', 'cones'], prop: 'stick-hockey', surface: 'field',
    setup: ['Three cone targets at 20, 30 and 40 yards.'],
    execution: ['Hands together at the top of the stick, swing through and hit to the called target.', 'Hit on the move after five stationary reps.'],
    cues: ['Hands together, short backswing', 'Head over the ball'],
    mistakes: ['A huge backswing that sends the ball in the air and off line.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'low-stance-shadow-defending', name: 'Low-Stance Shadow Defending', skills: ['low-athletic-stance', 'tackling-timing'],
    qualities: { 'lateral-power': 0.7, 'hip-mobility': 0.6, 'lower-body-strength': 0.5 },
    muscles: { 'gluteus-medius': 0.7, 'adductors': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['stick', 'cones', 'partner'], prop: 'stick-hockey', surface: 'field',
    setup: ['A 10-yard channel; attacker dribbles, defender faces them.'],
    execution: ['Defender stays low with the stick down on the left-hand side, shadowing the attacker backward.', 'Only tackle when the attacker\'s ball is off the stick; hold the channel for 10 seconds.'],
    cues: ['Stick down, stay low', 'Be patient — wait for the loose touch'],
    mistakes: ['Lunging in early and being beaten on the reverse side.'],
    defaultDose: reps(4, 5), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'lunge',
  },
  {
    slug: 'block-tackle-timing', name: 'Block-Tackle Timing', skills: ['tackling-timing'],
    qualities: { 'deceleration': 0.7, 'lateral-power': 0.6, 'grip': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'vastus-medialis': 0.5, 'gluteus-maximus': 0.5 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-hockey', surface: 'field',
    setup: ['Attacker dribbles slowly toward the defender from 10 yards.'],
    execution: ['Defender closes down, slows, and puts the stick flat on the ground in front of the ball as the attacker pushes it forward.', 'Win the ball cleanly and play it away.'],
    cues: ['Close fast, arrive slow', 'Stick flat and firm'],
    mistakes: ['Hacking at the ball, which gives away free hits.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'deceleration-plant', endPose: 'lunge',
  },
  {
    slug: 'reverse-stick-receiving', name: 'Reverse-Stick Receiving', skills: ['reverse-stick-control'],
    qualities: { 'grip': 0.6, 'single-leg-stability': 0.5, 'hip-mobility': 0.5 },
    muscles: { 'forearm-extensors': 0.6, 'forearm-flexors': 0.5, 'obliques-external': 0.4 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-hockey', surface: 'field',
    setup: ['A partner passes to your left side from 15 yards.'],
    execution: ['Receive on the reverse stick with the stick angled down so the ball doesn\'t pop up.', 'Transfer to open stick in one movement and pass back.'],
    cues: ['Angle the stick over the ball', 'Soft hands on receipt'],
    mistakes: ['Holding the stick upright so the ball bounces off and away.'],
    defaultDose: reps(3, 10), restSeconds: 30, startPose: 'lunge', endPose: 'swing-stride', constraintAxes: ['movement'],
  },
  {
    slug: 't-drill-agility', name: 'T-Drill With Stick', skills: ['agility', 'low-athletic-stance'],
    qualities: { 'change-of-direction': 0.9, 'deceleration': 0.7, 'lateral-power': 0.6 },
    muscles: { 'vastus-lateralis': 0.6, 'gluteus-medius': 0.6, 'adductors': 0.5 },
    equipment: ['cones', 'stick'], surface: 'field',
    setup: ['A T of cones: 10 yards forward, then 5 yards left and right of the top cone.'],
    execution: ['Sprint forward, shuffle left, shuffle right across, shuffle back to centre, backpedal to start.', 'Carry the stick in both hands the whole way.'],
    cues: ['Touch every cone low', 'Never cross the feet on the shuffle'],
    mistakes: ['Standing up tall on the shuffle.'],
    defaultDose: reps(3, 4), restSeconds: 60, startPose: 'lateral-shuffle', endPose: 'cut',
  },
  {
    slug: 'circle-entry-finishing', name: 'Circle-Entry Finishing', skills: ['passing-accuracy', 'sprint-speed'],
    qualities: { 'acceleration': 0.7, 'rotational-power': 0.6, 'change-of-direction': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'obliques-external': 0.5, 'biceps-femoris': 0.5 },
    equipment: ['stick', 'ball', 'goal', 'partner'], prop: 'stick-hockey', surface: 'field',
    setup: ['A feeder at the 25-yard line, attacker at the top of the circle.'],
    execution: ['Lead into the circle, receive the pass on the move and finish with a quick shot or deflection.', 'Alternate far-post and near-post finishes.'],
    cues: ['Lead, then receive', 'Shoot early in the circle'],
    mistakes: ['Receiving flat-footed so the keeper has time to set.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'rotational-throw',
  },
  {
    slug: 'aerial-lift-and-trap', name: 'Lift and Trap Control', skills: ['stick-handling', 'passing-accuracy'],
    qualities: { 'grip': 0.6, 'single-leg-stability': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'deltoid-anterior': 0.4, 'gluteus-medius': 0.4 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-hockey', surface: 'field', minAge: 14,
    setup: ['Two players 10 yards apart in open space away from others.'],
    execution: ['Scoop the ball gently over a low cone to your partner.', 'Partner traps it dead with an angled stick and returns the same way.'],
    cues: ['Scoop, don\'t hit', 'Cushion the trap'],
    mistakes: ['Lifting too high or too hard — this is a control drill, not a power one.'],
    defaultDose: reps(3, 10), restSeconds: 30, startPose: 'lunge', endPose: 'isometric-hold',
  },
  {
    slug: 'split-stance-hold', name: 'Low Split-Stance Holds', skills: ['low-athletic-stance'],
    qualities: { 'hip-mobility': 0.7, 'single-leg-stability': 0.6, 'lower-body-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'vastus-lateralis': 0.6, 'iliopsoas': 0.5 },
    equipment: ['stick'], surface: 'anywhere',
    setup: ['Stick in both hands, feet wide in a lunge position.'],
    execution: ['Sink into a deep, low split stance with the stick on the ground and hold.', 'Switch the lead leg every set.'],
    cues: ['Flat back, chest over the knee', 'Stick head on the ground'],
    mistakes: ['Bending at the waist instead of the knees and hips.'],
    defaultDose: time(3, 30), restSeconds: 30, startPose: 'split-squat', endPose: 'isometric-hold',
  },
]);

const FIELD_HOCKEY_GK = sportDrills('field-hockey-goalkeeping', [
  {
    slug: 'reaction-ball-saves', name: 'Reaction Saves off a Rebounder', skills: ['reaction-save-speed'],
    qualities: { 'reactive-strength': 0.8, 'lateral-power': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'gluteus-medius': 0.5, 'adductors': 0.4 },
    equipment: ['ball', 'goal', 'partner'], prop: 'ball-round', surface: 'field', minAge: 14,
    setup: ['Keeper in full kit on the line; a partner hits balls off a rebound board 8 yards out.'],
    execution: ['React to each rebound, saving with the kickers, pads or stick.', 'Recover to the set position before the next ball.'],
    cues: ['Weight forward, hands out front', 'Set before every ball'],
    mistakes: ['Sitting back on the heels so every save is late.'],
    defaultDose: reps(3, 10), restSeconds: 60, startPose: 'squat', endPose: 'lateral-bound',
  },
  {
    slug: 'lateral-kick-saves', name: 'Lateral Kick-Save Shuffles', skills: ['lateral-explosiveness', 'reaction-save-speed'],
    qualities: { 'lateral-power': 0.9, 'single-leg-stability': 0.6, 'deceleration': 0.5 },
    muscles: { 'gluteus-medius': 0.7, 'adductors': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['cones'], surface: 'field',
    setup: ['Two cones 3 yards apart on the goal line.'],
    execution: ['Shuffle cone to cone and kick out at each cone as if saving a ball to that post.', 'Reset into the set position after every kick.'],
    cues: ['Push off the far leg', 'Kick through the ball, not at it'],
    mistakes: ['Crossing the feet, which leaves you off balance for the second save.'],
    defaultDose: time(4, 20), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'lateral-bound',
  },
  {
    slug: 'hip-opener-flow', name: 'Keeper Hip-Opener Flow', skills: ['low-block-mobility'],
    qualities: { 'hip-mobility': 0.9, 'single-leg-stability': 0.5 },
    muscles: { 'adductors': 0.7, 'iliopsoas': 0.6, 'deep-hip-rotators': 0.6 },
    equipment: ['none'], surface: 'anywhere',
    setup: ['Open space on grass or a mat, before training.'],
    execution: ['Move slowly through a deep lateral lunge, a 90/90 hip switch and a low squat with elbows pushing the knees out.', 'Hold each position for two breaths and flow into the next.'],
    cues: ['Breathe into the stretch', 'Slow and smooth'],
    mistakes: ['Bouncing into the end range.'],
    defaultDose: time(3, 60), restSeconds: 20, startPose: 'mobility-flow', endPose: 'squat',
  },
  {
    slug: 'low-block-slides', name: 'Low-Block Slides', skills: ['low-block-mobility', 'lateral-explosiveness'],
    qualities: { 'lateral-power': 0.7, 'hip-mobility': 0.7, 'landing-mechanics': 0.5 },
    muscles: { 'adductors': 0.7, 'gluteus-medius': 0.6, 'obliques-external': 0.4 },
    equipment: ['ball', 'goal', 'partner'], prop: 'ball-round', surface: 'field', minAge: 14,
    setup: ['In full kit; a partner pushes balls toward either post along the ground.'],
    execution: ['Drop into a sideways block, sliding the pads along the ground to cover the post.', 'Hands stay up and in front to deny a deflection.'],
    cues: ['Pads sealed together', 'Hands up even on the ground'],
    mistakes: ['Leaving a gap between the pads that the ball rolls through.'],
    defaultDose: reps(3, 6), restSeconds: 60, startPose: 'lateral-bound', endPose: 'landing',
  },
  {
    slug: 'get-up-drill', name: 'Save-and-Get-Up Drill', skills: ['recovery-to-feet'],
    qualities: { 'reactive-strength': 0.6, 'hip-mobility': 0.5, 'lower-body-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5, 'vastus-lateralis': 0.5 },
    equipment: ['ball', 'goal', 'partner'], prop: 'ball-round', surface: 'field', minAge: 14,
    setup: ['In full kit; a partner with balls at the top of the circle.'],
    execution: ['Make a low block save, then get back to your feet and set as fast as possible.', 'The partner shoots the second ball as soon as you are up.'],
    cues: ['Up through one knee', 'Set before the second shot'],
    mistakes: ['Rolling around on the ground instead of getting straight up.'],
    defaultDose: reps(3, 5), restSeconds: 60, startPose: 'landing', endPose: 'squat',
  },
  {
    slug: 'angle-positioning-walk', name: 'Angle-Positioning Arc Walk', skills: ['reaction-save-speed'],
    qualities: { 'single-leg-stability': 0.6, 'lateral-power': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'vastus-medialis': 0.4, 'adductors': 0.4 },
    equipment: ['cones', 'goal'], surface: 'field',
    setup: ['Five cones spread around the edge of the circle, representing shooters.'],
    execution: ['The coach points to a cone; move along your arc to square up to that shooter.', 'Set in a ready stance at each position before the next call.'],
    cues: ['Square to the ball, not the goal', 'Small steps along the arc'],
    mistakes: ['Drifting off your line so the near post opens up.'],
    defaultDose: time(3, 45), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'squat',
  },
  {
    slug: 'kicker-clearances', name: 'Kicker Clearances', skills: ['lateral-explosiveness'],
    qualities: { 'rotational-power': 0.6, 'single-leg-stability': 0.6 },
    muscles: { 'rectus-femoris': 0.6, 'adductors': 0.5, 'gluteus-medius': 0.5 },
    equipment: ['ball', 'partner'], prop: 'ball-round', surface: 'field', minAge: 14,
    setup: ['In kickers and pads; a partner rolls balls in from the edge of the circle.'],
    execution: ['Meet the ball with the inside of the kicker and clear it wide to a target cone.', 'Alternate clearing left and right.'],
    cues: ['Clear wide, never central', 'Step into it'],
    mistakes: ['Clearing straight back to the middle of the circle.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'instep-strike', endPose: 'instep-strike',
  },
]);

const LACROSSE = sportDrills('lacrosse', [
  {
    slug: 'overhand-shot-step-down', name: 'Overhand Shot With Step-Down', skills: ['shot-velocity'],
    qualities: { 'rotational-power': 0.9, 'overhead-power': 0.7, 'horizontal-power': 0.5 },
    muscles: { 'obliques-external': 0.7, 'latissimus-dorsi': 0.6, 'triceps-brachii': 0.5 },
    equipment: ['stick', 'ball', 'goal'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['A line of balls 10–12 yards from goal.'],
    execution: ['Crow-hop or step down with the front foot, hands back and away from the body.', 'Rotate the hips then shoulders and snap the top hand through, finishing across the body.'],
    cues: ['Hands away from your ear', 'Hips before hands'],
    mistakes: ['Pushing the stick like a spear with no rotation.'],
    defaultDose: reps(4, 8), restSeconds: 60, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'wall-ball-routine', name: 'Wall-Ball Routine', skills: ['cradling-under-pressure', 'field-vision'],
    qualities: { 'grip': 0.6, 'reactive-strength': 0.5, 'shoulder-stability': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'deltoid-anterior': 0.5, 'triceps-brachii': 0.4 },
    equipment: ['stick', 'ball', 'wall'], prop: 'stick-lacrosse', surface: 'anywhere',
    setup: ['Stand 5 yards from a brick wall.'],
    execution: ['Throw and catch 25 reps each: right hand, left hand, quick-stick, and cross-hand.', 'Move closer for quick sticks and further back for long throws.'],
    cues: ['Soft hands on the catch', 'Throw to one brick'],
    mistakes: ['Only working your strong hand.'],
    defaultDose: reps(4, 25), restSeconds: 30, startPose: 'overhead-throw', endPose: 'overhead-throw',
  },
  {
    slug: 'split-dodge-cones', name: 'Split Dodge Through Cones', skills: ['dodging-quickness'],
    qualities: { 'change-of-direction': 0.9, 'deceleration': 0.7, 'acceleration': 0.7 },
    muscles: { 'gluteus-medius': 0.6, 'vastus-medialis': 0.6, 'adductors': 0.5 },
    equipment: ['stick', 'ball', 'cones'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['Three cones staggered 5 yards apart toward goal.'],
    execution: ['Approach each cone, plant hard and split, switching hands and exploding past it.', 'Finish with a shot on goal.'],
    cues: ['Sell with the eyes and shoulders', 'Explode out of the switch'],
    mistakes: ['Rounding the dodge instead of a sharp plant-and-go.'],
    defaultDose: reps(4, 4), restSeconds: 45, startPose: 'deceleration-plant', endPose: 'cut', constraintAxes: ['opposition'],
  },
  {
    slug: 'roll-dodge-drill', name: 'Roll Dodge Drill', skills: ['dodging-quickness', 'stick-protection'],
    qualities: { 'change-of-direction': 0.8, 'trunk-anti-rotation': 0.6, 'lateral-power': 0.5 },
    muscles: { 'obliques-internal': 0.6, 'gluteus-medius': 0.5, 'adductors': 0.5 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['A defender holds a stationary pad or stick in front of you.'],
    execution: ['Drive into the defender, plant the lead foot, and roll off them with your back to the defender.', 'Keep the stick protected on the far side through the whole roll.'],
    cues: ['Back to the defender', 'Stick tight to your ear'],
    mistakes: ['Swinging the stick wide during the roll where it gets checked.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'cut', endPose: 'sprint-cycle',
  },
  {
    slug: 'ground-ball-scoop-and-go', name: 'Ground Ball Scoop-and-Go', skills: ['ground-ball-speed'],
    qualities: { 'acceleration': 0.8, 'deceleration': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'gluteus-maximus': 0.6, 'biceps-femoris': 0.5, 'vastus-lateralis': 0.5 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['A coach rolls balls out from the side 10 yards ahead of the player.'],
    execution: ['Sprint through the ball, get low with the knees bent, and scoop with hands low on the stick.', 'Protect the ball and accelerate away five yards before passing.'],
    cues: ['Knees bent, back hand low', 'Scoop through, don\'t stop at the ball'],
    mistakes: ['Bending at the waist and reaching, which fumbles the ball.'],
    defaultDose: reps(4, 6), restSeconds: 45, startPose: 'sprint-cycle', endPose: 'squat', constraintAxes: ['opposition'],
  },
  {
    slug: 'face-off-clamp-reps', name: 'Face-Off Clamp Reps', skills: ['face-off-power'],
    qualities: { 'reactive-strength': 0.8, 'grip': 0.7, 'lateral-power': 0.5 },
    muscles: { 'forearm-flexors': 0.7, 'triceps-brachii': 0.5, 'gluteus-maximus': 0.5 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-lacrosse', surface: 'field', minAge: 14,
    setup: ['Ball on the ground at the X; a partner gives the whistle.'],
    execution: ['On the whistle, clamp the ball with the back of the stick head, then pop it out to your side and scoop.', 'Reset after each rep; count the reps where you win the clamp cleanly.'],
    cues: ['React to the sound, not the movement', 'Hands and hips move together'],
    mistakes: ['Leaning too far over the ball before the whistle, which gets called for a violation.'],
    defaultDose: reps(4, 6), restSeconds: 45, startPose: 'squat', endPose: 'lateral-bound',
  },
  {
    slug: 'cradle-under-pressure', name: 'Cradle Under Pressure Box', skills: ['cradling-under-pressure', 'stick-protection'],
    qualities: { 'trunk-anti-rotation': 0.7, 'grip': 0.6, 'change-of-direction': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'obliques-internal': 0.6, 'gluteus-medius': 0.4 },
    equipment: ['stick', 'ball', 'cones', 'partner'], prop: 'stick-lacrosse', surface: 'field', minAge: 14,
    setup: ['A 10-yard box; one ball carrier, one defender throwing legal checks.'],
    execution: ['Keep possession for 15 seconds, cradling and turning your body between the defender and the stick.', 'Swap roles every rep.'],
    cues: ['Body between the ball and the stick', 'Short, tight cradles'],
    mistakes: ['Holding the stick out in front where it gets knocked free.'],
    defaultDose: time(4, 15), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'isometric-hold',
  },
  {
    slug: 'fast-break-4v3', name: 'Fast-Break 4v3', skills: ['transition-speed', 'field-vision'],
    qualities: { 'anaerobic-capacity': 0.7, 'acceleration': 0.6, 'repeat-sprint': 0.6 },
    muscles: { 'gluteus-maximus': 0.5, 'biceps-femoris': 0.5, 'gastrocnemius': 0.4 },
    equipment: ['stick', 'ball', 'goal', 'partner'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['Four attackers start at midfield, three defenders set in front of goal.'],
    execution: ['Attack the defence at full speed, moving the ball quickly to find the open player.', 'Take the best shot within 10 seconds; the defenders then clear the ball back.'],
    cues: ['Ball moves faster than feet', 'Hands ready, look early'],
    mistakes: ['Dodging into a slid defender instead of moving the ball on.'],
    defaultDose: reps(4, 4), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'overhead-throw',
  },
  {
    slug: 'midfield-clear-sprints', name: 'Midfield Clearing Sprints', skills: ['transition-speed'],
    qualities: { 'repeat-sprint': 0.8, 'acceleration': 0.7, 'max-velocity': 0.5 },
    muscles: { 'biceps-femoris': 0.7, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['stick', 'cones'], surface: 'field',
    setup: ['Cones at the defensive restraining line and the far restraining line.'],
    execution: ['Sprint carrying your stick from one restraining line to the other.', 'Jog back as recovery and repeat.'],
    cues: ['Stick up, ready to catch', 'Eyes up the field'],
    mistakes: ['Dragging the stick at your side instead of carrying it ready to receive.'],
    defaultDose: reps(2, 6), restSeconds: 90, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'heads-up-passing-triangle', name: 'Heads-Up Passing Triangle', skills: ['field-vision'],
    qualities: { 'overhead-power': 0.5, 'reactive-strength': 0.5, 'shoulder-stability': 0.4 },
    muscles: { 'deltoid-anterior': 0.5, 'triceps-brachii': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['Three players in a triangle 12 yards apart.'],
    execution: ['Catch, look to the called player and pass, keeping the head up before every pass.', 'Add a fourth player moving through the middle to track.'],
    cues: ['Look, then pass', 'Catch with the stick in the box'],
    mistakes: ['Staring at your stick head while catching.'],
    defaultDose: time(4, 60), restSeconds: 30, startPose: 'overhead-throw', endPose: 'overhead-throw', constraintAxes: ['touches'],
  },
  {
    slug: 'sidearm-shot-reps', name: 'Sidearm Shot Reps', skills: ['shot-velocity'],
    qualities: { 'rotational-power': 0.9, 'hip-mobility': 0.5, 'single-leg-stability': 0.5 },
    muscles: { 'obliques-external': 0.7, 'gluteus-maximus': 0.5, 'latissimus-dorsi': 0.5 },
    equipment: ['stick', 'ball', 'goal'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['Balls 10 yards out, slightly off-centre.'],
    execution: ['Drop the stick to hip height and rotate through the shot, aiming low corners.', 'Alternate sidearm and underhand release angles.'],
    cues: ['Rotate, don\'t push', 'Aim low and away'],
    mistakes: ['Keeping the feet square so only the arms move.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'rotational-med-ball-shot', name: 'Rotational Throw Shot Prep', skills: ['shot-velocity', 'face-off-power'],
    qualities: { 'rotational-power': 0.9, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-external': 0.7, 'obliques-internal': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['med-ball', 'wall'], surface: 'anywhere',
    setup: ['Side-on to a sturdy wall, 3 metres away, with a light med ball.'],
    execution: ['Load the back hip and throw the ball into the wall with a fast hip-then-shoulder rotation.', 'Catch the rebound and repeat; switch sides every set.'],
    cues: ['Load the back hip', 'Throw through the wall'],
    mistakes: ['Throwing with the arms while the hips stay still.'],
    defaultDose: reps(3, 8, 'light med ball'), restSeconds: 60, startPose: 'rotational-throw', endPose: 'rotational-throw',
  },
]);

const LACROSSE_BOX = sportDrills('lacrosse-box', [
  {
    slug: 'tight-space-shooting', name: 'Tight-Space Shooting', skills: ['shot-velocity'],
    qualities: { 'rotational-power': 0.8, 'reactive-strength': 0.5, 'grip': 0.5 },
    muscles: { 'obliques-external': 0.6, 'forearm-flexors': 0.6, 'triceps-brachii': 0.5 },
    equipment: ['stick', 'ball', 'goal'], prop: 'stick-lacrosse', surface: 'court',
    setup: ['Balls 6–8 yards from the smaller box net.'],
    execution: ['Shoot with a short, compact wind-up — box goalies fill the net, so pick corners.', 'Alternate overhand and sidearm releases.'],
    cues: ['Short wind-up, fast hands', 'Shoot to the corners'],
    mistakes: ['A long field-lacrosse wind-up that gets checked in the box.'],
    defaultDose: reps(4, 8), restSeconds: 45, startPose: 'swing-stride', endPose: 'overhead-throw',
  },
  {
    slug: 'pick-and-roll-dodges', name: 'Pick-and-Roll Dodges', skills: ['dodging-quickness'],
    qualities: { 'change-of-direction': 0.8, 'acceleration': 0.6, 'deceleration': 0.6 },
    muscles: { 'gluteus-medius': 0.6, 'vastus-medialis': 0.5, 'adductors': 0.5 },
    equipment: ['stick', 'ball', 'partner'], prop: 'stick-lacrosse', surface: 'court',
    setup: ['A ball carrier and a screener on the wing.'],
    execution: ['Use the screen by driving hard off your teammate\'s hip, then attack the net.', 'The screener rolls to goal for a pass if the defence switches.'],
    cues: ['Run shoulder to shoulder off the pick', 'Read the switch'],
    mistakes: ['Leaving a gap between you and the screener so the defender slides through.'],
    defaultDose: reps(4, 5), restSeconds: 45, startPose: 'cut', endPose: 'sprint-cycle', constraintAxes: ['opposition'],
  },
  {
    slug: 'cross-check-absorb', name: 'Cross-Check Absorb and Drive', skills: ['checking-strength'],
    qualities: { 'trunk-anti-rotation': 0.8, 'lower-body-strength': 0.6, 'upper-body-push': 0.5 },
    muscles: { 'obliques-internal': 0.6, 'gluteus-maximus': 0.6, 'triceps-brachii': 0.5 },
    equipment: ['stick', 'partner'], prop: 'stick-lacrosse', surface: 'court', minAge: 15, supervisionLevel: 'COACHED',
    setup: ['A partner holds a stick across your back numbers at controlled pressure; coach supervises.'],
    execution: ['Keep a wide, low base and drive forward against the pressure for five seconds.', 'Then pivot and seal the partner off with your body, holding position.'],
    cues: ['Wide base, low hips', 'Brace the trunk before contact'],
    mistakes: ['Standing tall with feet together so you get pushed off your spot.'],
    defaultDose: time(4, 10), restSeconds: 60, startPose: 'horizontal-push', endPose: 'isometric-hold',
  },
  {
    slug: 'box-transition-sprints', name: 'Floor-Length Transition Sprints', skills: ['transition-speed'],
    qualities: { 'repeat-sprint': 0.8, 'acceleration': 0.7 },
    muscles: { 'biceps-femoris': 0.6, 'gluteus-maximus': 0.6, 'gastrocnemius': 0.5 },
    equipment: ['stick'], surface: 'court',
    setup: ['Start at one end of the box floor.'],
    execution: ['Sprint the length of the floor with the stick up ready to receive, then jog back.', 'Repeat on a 30-second clock.'],
    cues: ['Stick up to receive', 'First three steps hard'],
    mistakes: ['Jogging the first few steps of each rep.'],
    defaultDose: reps(2, 6), restSeconds: 30, startPose: 'sprint-start', endPose: 'sprint-cycle',
  },
  {
    slug: 'inside-roll-finish', name: 'Inside Roll and Finish', skills: ['dodging-quickness', 'shot-velocity'],
    qualities: { 'change-of-direction': 0.7, 'rotational-power': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-external': 0.6, 'gluteus-medius': 0.5, 'forearm-flexors': 0.4 },
    equipment: ['stick', 'ball', 'goal', 'partner'], prop: 'stick-lacrosse', surface: 'court',
    setup: ['Attacker on the crease side with a passive defender.'],
    execution: ['Drive the defender, roll inside off their hip and shoot within one step.', 'Keep the stick protected through the roll.'],
    cues: ['Roll tight to the defender', 'Shoot off the roll'],
    mistakes: ['Taking extra steps after the roll so the goalie resets.'],
    defaultDose: reps(3, 6), restSeconds: 45, startPose: 'cut', endPose: 'rotational-throw',
  },
  {
    slug: 'defensive-stick-positioning', name: 'Defensive Stick Positioning', skills: ['checking-strength'],
    qualities: { 'lateral-power': 0.6, 'trunk-anti-rotation': 0.6, 'deceleration': 0.5 },
    muscles: { 'gluteus-medius': 0.6, 'obliques-internal': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['stick', 'partner'], prop: 'stick-lacrosse', surface: 'court', minAge: 14,
    setup: ['A ball carrier works the wing; you defend from the ball-side.'],
    execution: ['Shuffle with the carrier, stick on their gloves and body square, pushing them away from the middle.', 'Hold them to the outside for 10 seconds.'],
    cues: ['Push them to the wall', 'Stick on the hands'],
    mistakes: ['Swinging for the stick and losing body position.'],
    defaultDose: time(4, 10), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'horizontal-push',
  },
  {
    slug: 'quick-stick-crease', name: 'Quick-Stick Crease Finishes', skills: ['shot-velocity'],
    qualities: { 'reactive-strength': 0.7, 'grip': 0.5, 'rotational-power': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'triceps-brachii': 0.5, 'obliques-external': 0.4 },
    equipment: ['stick', 'ball', 'goal', 'partner'], prop: 'stick-lacrosse', surface: 'court',
    setup: ['A feeder behind the net, finisher on the crease.'],
    execution: ['Catch the feed and redirect it into the net in one motion without cradling.', 'Feeder varies the angle every few reps.'],
    cues: ['Catch and release in one', 'Stick head ready at the ear'],
    mistakes: ['Cradling after the catch so the goalie closes the angle.'],
    defaultDose: reps(4, 6), restSeconds: 45, startPose: 'overhead-throw', endPose: 'overhead-throw', constraintAxes: ['touches'],
  },
]);

const ADAPTED_FLOOR_HOCKEY = sportDrills('adapted-floor-hockey', [
  {
    slug: 'stick-handling-lane', name: 'Stick-Handling Lane', skills: ['stick-handling'],
    qualities: { 'grip': 0.6, 'change-of-direction': 0.5 },
    muscles: { 'forearm-flexors': 0.6, 'forearm-extensors': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['stick', 'puck', 'cones'], prop: 'stick-hockey', surface: 'court',
    setup: ['Four cones in a line two metres apart on a gym floor.'],
    execution: ['Move the puck around each cone at a comfortable pace, keeping it close to the stick.', 'Walk back and go again, a little faster each time you are in control.'],
    cues: ['Puck close to the stick', 'Look up between cones'],
    mistakes: ['Pushing the puck too far ahead so it is lost.'],
    defaultDose: reps(3, 4), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'target-shooting', name: 'Target Shooting', skills: ['shot-accuracy'],
    qualities: { 'rotational-power': 0.6, 'single-leg-stability': 0.4 },
    muscles: { 'obliques-external': 0.5, 'forearm-flexors': 0.5, 'deltoid-anterior': 0.4 },
    equipment: ['stick', 'puck', 'goal', 'cones'], prop: 'stick-hockey', surface: 'court',
    setup: ['A goal with cone targets in each corner; pucks 4–5 metres out.'],
    execution: ['Aim at the corner a partner calls and push or sweep the puck toward it.', 'Keep score of corners hit.'],
    cues: ['Eyes on the target, then the puck', 'Follow through to the target'],
    mistakes: ['Rushing the shot before setting the feet.'],
    defaultDose: reps(3, 8), restSeconds: 45, startPose: 'swing-stride', endPose: 'rotational-throw',
  },
  {
    slug: 'passing-pairs', name: 'Passing in Pairs', skills: ['stick-handling', 'positional-awareness'],
    qualities: { 'grip': 0.5, 'rotational-power': 0.5 },
    muscles: { 'forearm-flexors': 0.5, 'obliques-external': 0.4, 'deltoid-anterior': 0.4 },
    equipment: ['stick', 'puck', 'partner'], prop: 'stick-hockey', surface: 'court',
    setup: ['Two players four metres apart.'],
    execution: ['Pass the puck back and forth, stopping it each time before passing back.', 'Step further apart as passes get accurate.'],
    cues: ['Call your partner\'s name', 'Stop it, then pass'],
    mistakes: ['Hitting the puck too hard to control.'],
    defaultDose: time(4, 60), restSeconds: 30, startPose: 'swing-stride', endPose: 'swing-stride',
  },
  {
    slug: 'position-zones', name: 'Position Zone Game', skills: ['positional-awareness'],
    qualities: { 'aerobic-base': 0.6, 'change-of-direction': 0.5 },
    muscles: { 'gluteus-maximus': 0.4, 'gastrocnemius': 0.4, 'vastus-lateralis': 0.4 },
    equipment: ['cones', 'partner'], surface: 'court',
    setup: ['Mark three zones on the floor with cones — defence, centre and attack.'],
    execution: ['The coach calls a zone; move to your position in that zone and face the play.', 'Hold your spot until the next call.'],
    cues: ['Know your zone', 'Face the puck'],
    mistakes: ['Everyone chasing the puck and leaving zones empty.'],
    defaultDose: time(4, 90), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'sprint-cycle',
  },
  {
    slug: 'continuous-laps', name: 'Continuous Gym Laps', skills: ['endurance'],
    qualities: { 'aerobic-base': 0.9, 'repeat-sprint': 0.4 },
    muscles: { 'gastrocnemius': 0.5, 'vastus-lateralis': 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['cones'], surface: 'court',
    setup: ['Cones around the edge of the gym floor.'],
    execution: ['Move around the course at a steady pace you can talk at, for the full interval.', 'Add a short faster section on one side each lap.'],
    cues: ['Steady and relaxed', 'Breathe in rhythm'],
    mistakes: ['Starting too fast and stopping halfway.'],
    defaultDose: time(3, 120), restSeconds: 60, startPose: 'sprint-cycle', endPose: 'sprint-cycle',
  },
  {
    slug: 'defensive-shadowing', name: 'Defensive Shadowing', skills: ['positional-awareness', 'endurance'],
    qualities: { 'lateral-power': 0.6, 'aerobic-base': 0.5 },
    muscles: { 'gluteus-medius': 0.5, 'adductors': 0.5, 'gastrocnemius': 0.4 },
    equipment: ['partner', 'stick'], prop: 'stick-hockey', surface: 'court',
    setup: ['A partner moves slowly around a marked area; you defend.'],
    execution: ['Stay between your partner and the goal as they move, keeping your stick on the floor.', 'Swap roles every interval.'],
    cues: ['Stay goal-side', 'Stick on the floor'],
    mistakes: ['Following behind instead of staying between them and the goal.'],
    defaultDose: time(4, 30), restSeconds: 30, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'stop-and-go-puck', name: 'Stop-and-Go Puck Control', skills: ['stick-handling', 'endurance'],
    qualities: { 'acceleration': 0.5, 'deceleration': 0.5, 'grip': 0.4 },
    muscles: { 'forearm-flexors': 0.5, 'gluteus-maximus': 0.4, 'vastus-lateralis': 0.4 },
    equipment: ['stick', 'puck'], prop: 'stick-hockey', surface: 'court',
    setup: ['Open floor space; a coach with a whistle.'],
    execution: ['Move the puck around the floor; on the whistle, stop and trap the puck under control.', 'On the next whistle, go again in a new direction.'],
    cues: ['Trap it dead', 'Head up for the whistle'],
    mistakes: ['Letting the puck roll on after the stop.'],
    defaultDose: time(3, 60), restSeconds: 45, startPose: 'deceleration-plant', endPose: 'sprint-cycle',
  },
]);


/** Goaltender / goalie drills (`positions`): skaters' and attackers' plans never get them. */
const HOCKEY_GOALIE = sportDrills('ice-hockey', [
  {
    slug: 'goaltender-butterfly-slides', name: 'Goaltender Butterfly Slides', positions: ['goaltender'],
    qualities: { 'lateral-power': 0.8, 'hip-mobility': 0.7 },
    muscles: { 'adductors': 0.7, 'gluteus-medius': 0.6, 'obliques-external': 0.4 },
    equipment: ['skates', 'stick'], prop: 'stick-hockey', surface: 'anywhere',
    setup: ['In the crease, in your stance.'],
    execution: ['Drop into the butterfly — knees together, pads flared flat on the ice, stick covering the five-hole.', 'Push off the post-side leg and slide across in the butterfly to the other post; recover to your feet.'],
    cues: ['Chest up, gloves in front', 'Push, then lead with the knee'],
    mistakes: ['Leaning back so the pads open a gap under you.'],
    defaultDose: reps(3, 8), restSeconds: 60, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
  {
    slug: 'goaltender-t-push-tracking', name: 'Goaltender T-Pushes', positions: ['goaltender'],
    qualities: { 'lateral-power': 0.8, 'deceleration': 0.6 },
    muscles: { 'gluteus-medius': 0.7, 'adductors': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['skates', 'stick'], prop: 'stick-hockey', surface: 'anywhere',
    setup: ['In the crease, facing the play.'],
    execution: ['Turn the lead skate toward where you are going, push hard off the back skate in a T, and glide across.', 'Stop square to the shooter in your stance, then T-push back.'],
    cues: ['Head and hands lead', 'Stop square, set, then go'],
    mistakes: ['Over-rotating the shoulders so you arrive facing the wrong way.'],
    defaultDose: reps(3, 10), restSeconds: 45, startPose: 'lateral-shuffle', endPose: 'lateral-shuffle',
  },
]);
const LACROSSE_GOALIE = sportDrills('lacrosse', [
  {
    slug: 'goalie-arc-step-saves', name: 'Goalie Step-to-Ball Saves', positions: ['goalie'],
    qualities: { 'reactive-strength': 0.8, 'lateral-power': 0.6 },
    muscles: { 'gastrocnemius': 0.5, 'deltoid-anterior': 0.5, 'forearm-flexors': 0.5 },
    equipment: ['stick', 'ball', 'partner', 'goal'], prop: 'stick-lacrosse', surface: 'field',
    setup: ['In goal, a partner shoots from 8–10 yards to all four corners.'],
    execution: ['From your stance (stick head up by the ear), step to the ball with the foot on its side and drive the stick head to it.', 'Top hand leads; step back to the arc before the next shot.'],
    cues: ['Step at the ball, not back into the goal', 'Watch it into the pocket'],
    mistakes: ['Only moving the stick and leaving the body behind.'],
    defaultDose: reps(3, 10), restSeconds: 60, startPose: 'athletic-stance', endPose: 'athletic-stance',
  },
]);

export const STICK_DRILLS = [
  ...HOCKEY_GOALIE, ...LACROSSE_GOALIE,
  ...ICE_HOCKEY,
  ...INLINE_HOCKEY,
  ...FIELD_HOCKEY,
  ...FIELD_HOCKEY_GK,
  ...LACROSSE,
  ...LACROSSE_BOX,
  ...ADAPTED_FLOOR_HOCKEY,
];
