/**
 * Placement of every drawable muscle onto the rig (rig.js) — the data the
 * generator in build.mjs turns into MuscleMapPaths.swift. Schematic, not
 * medically precise: the goal is "the right area of the body, distinguishable
 * from its neighbours," matching §9's "clean uniform-stroke line art," not an
 * anatomy-textbook dissection. One entry per (muscle, view) the muscle has in
 * muscles.js; left/right are generated by mirroring, not placed separately.
 *
 * `t0`/`t1`/`xInsetFrac`/`widthFrac` are for line segments (see
 * geometry.js#lineSegmentPatch); `dxFrac`/`dyFrac`/`radiusFrac` are for point
 * segments (geometry.js#pointSegmentPatch, the shoulder and hip caps).
 */

export const MUSCLE_REGIONS = {
  sternocleidomastoid: [{ view: 'front', segment: 'neck', t0: 0.1, t1: 0.8, xInsetFrac: 0.5, widthFrac: 0.5 }],
  'neck-extensors': [{ view: 'back', segment: 'neck', t0: 0.1, t1: 0.8, xInsetFrac: 0.3, widthFrac: 0.7 }],

  'deltoid-anterior': [{ view: 'front', segment: 'shoulderCap', dxFrac: -0.3, dyFrac: -0.3, radiusFrac: 0.55 }],
  'deltoid-lateral': [
    { view: 'front', segment: 'shoulderCap', dxFrac: 0.55, dyFrac: 0, radiusFrac: 0.5 },
    { view: 'back', segment: 'shoulderCap', dxFrac: 0.55, dyFrac: 0, radiusFrac: 0.5 },
  ],
  'deltoid-posterior': [{ view: 'back', segment: 'shoulderCap', dxFrac: -0.2, dyFrac: 0.4, radiusFrac: 0.5 }],
  supraspinatus: [{ view: 'back', segment: 'shoulderCap', dxFrac: 0, dyFrac: -0.65, radiusFrac: 0.4 }],
  infraspinatus: [{ view: 'back', segment: 'shoulderCap', dxFrac: -0.45, dyFrac: 0.05, radiusFrac: 0.45 }],
  'teres-minor': [{ view: 'back', segment: 'shoulderCap', dxFrac: -0.5, dyFrac: 0.35, radiusFrac: 0.35 }],
  'teres-major': [{ view: 'back', segment: 'trunk-upper', t0: 0.2, t1: 0.35, xInsetFrac: 0.75, widthFrac: 0.3 }],

  'pectoralis-major': [{ view: 'front', segment: 'trunk-upper', t0: 0.08, t1: 0.42, xInsetFrac: 0.35, widthFrac: 0.75 }],
  'serratus-anterior': [{ view: 'front', segment: 'trunk-upper', t0: 0.38, t1: 0.58, xInsetFrac: 0.65, widthFrac: 0.35 }],

  'trapezius-upper': [
    { view: 'front', segment: 'trunk-upper', t0: 0, t1: 0.15, xInsetFrac: 0.3, widthFrac: 0.5 },
    { view: 'back', segment: 'trunk-upper', t0: 0, t1: 0.15, xInsetFrac: 0.3, widthFrac: 0.55 },
  ],
  'trapezius-middle': [{ view: 'back', segment: 'trunk-upper', t0: 0.12, t1: 0.32, xInsetFrac: 0.4, widthFrac: 0.6 }],
  'trapezius-lower': [{ view: 'back', segment: 'trunk-upper', t0: 0.3, t1: 0.5, xInsetFrac: 0.2, widthFrac: 0.4 }],
  rhomboids: [{ view: 'back', segment: 'trunk-upper', t0: 0.15, t1: 0.32, xInsetFrac: 0.2, widthFrac: 0.3 }],
  'latissimus-dorsi': [{ view: 'back', segment: 'trunk-upper', t0: 0.3, t1: 0.62, xInsetFrac: 0.6, widthFrac: 0.5 }],
  'levator-scapulae': [{ view: 'back', segment: 'trunk-upper', t0: 0, t1: 0.15, xInsetFrac: 0.5, widthFrac: 0.25 }],

  'erector-spinae': [{ view: 'back', segment: 'trunk-lower', t0: 0, t1: 0.75, xInsetFrac: 0.15, widthFrac: 0.3 }],
  'quadratus-lumborum': [{ view: 'back', segment: 'trunk-lower', t0: 0, t1: 0.45, xInsetFrac: 0.45, widthFrac: 0.3 }],

  'biceps-brachii': [{ view: 'front', segment: 'upperArm', t0: 0.15, t1: 0.85, xInsetFrac: -0.2, widthFrac: 0.8 }],
  brachialis: [{ view: 'front', segment: 'upperArm', t0: 0.5, t1: 0.9, xInsetFrac: 0.3, widthFrac: 0.5 }],
  'triceps-brachii': [{ view: 'back', segment: 'upperArm', t0: 0.1, t1: 0.9, xInsetFrac: 0, widthFrac: 0.85 }],

  'forearm-flexors': [{ view: 'front', segment: 'forearm', t0: 0.05, t1: 0.9, xInsetFrac: -0.2, widthFrac: 0.75 }],
  'forearm-extensors': [{ view: 'back', segment: 'forearm', t0: 0.05, t1: 0.9, xInsetFrac: 0.1, widthFrac: 0.75 }],
  brachioradialis: [
    { view: 'front', segment: 'forearm', t0: 0, t1: 0.6, xInsetFrac: 0.6, widthFrac: 0.4 },
    { view: 'back', segment: 'forearm', t0: 0, t1: 0.6, xInsetFrac: 0.6, widthFrac: 0.4 },
  ],

  'rectus-abdominis': [{ view: 'front', segment: 'trunk-lower', t0: 0, t1: 0.85, xInsetFrac: 0.15, widthFrac: 0.3 }],
  'obliques-external': [{ view: 'front', segment: 'trunk-lower', t0: 0, t1: 0.7, xInsetFrac: 0.5, widthFrac: 0.4 }],

  'gluteus-maximus': [{ view: 'back', segment: 'hipCap', dxFrac: 0.1, dyFrac: 0.2, radiusFrac: 0.85 }],
  'gluteus-medius': [{ view: 'back', segment: 'hipCap', dxFrac: 0.3, dyFrac: -0.3, radiusFrac: 0.5 }],
  'tensor-fasciae-latae': [{ view: 'front', segment: 'hipCap', dxFrac: 0.4, dyFrac: -0.4, radiusFrac: 0.35 }],
  iliopsoas: [{ view: 'front', segment: 'hipCap', dxFrac: -0.1, dyFrac: -0.5, radiusFrac: 0.4 }],
  adductors: [{ view: 'front', segment: 'hipCap', dxFrac: -0.3, dyFrac: 0.3, radiusFrac: 0.55 }],

  'rectus-femoris': [{ view: 'front', segment: 'thigh', t0: 0.1, t1: 0.85, xInsetFrac: 0, widthFrac: 0.55 }],
  'vastus-lateralis': [{ view: 'front', segment: 'thigh', t0: 0.15, t1: 0.9, xInsetFrac: 0.55, widthFrac: 0.5 }],
  'vastus-medialis': [{ view: 'front', segment: 'thigh', t0: 0.4, t1: 0.95, xInsetFrac: -0.5, widthFrac: 0.4 }],
  sartorius: [{ view: 'front', segment: 'thigh', t0: 0.05, t1: 0.95, xInsetFrac: -0.15, widthFrac: 0.2 }],

  'biceps-femoris': [{ view: 'back', segment: 'thigh', t0: 0.15, t1: 0.9, xInsetFrac: 0.4, widthFrac: 0.5 }],
  semitendinosus: [{ view: 'back', segment: 'thigh', t0: 0.2, t1: 0.9, xInsetFrac: -0.35, widthFrac: 0.4 }],
  semimembranosus: [{ view: 'back', segment: 'thigh', t0: 0.3, t1: 0.85, xInsetFrac: -0.15, widthFrac: 0.35 }],

  gastrocnemius: [{ view: 'back', segment: 'shin', t0: 0.05, t1: 0.55, xInsetFrac: 0, widthFrac: 0.85 }],
  soleus: [{ view: 'back', segment: 'shin', t0: 0.45, t1: 0.85, xInsetFrac: 0, widthFrac: 0.6 }],
  'tibialis-anterior': [{ view: 'front', segment: 'shin', t0: 0.05, t1: 0.75, xInsetFrac: -0.2, widthFrac: 0.45 }],
  peroneals: [
    { view: 'front', segment: 'shin', t0: 0.15, t1: 0.8, xInsetFrac: 0.6, widthFrac: 0.3 },
    { view: 'back', segment: 'shin', t0: 0.15, t1: 0.8, xInsetFrac: 0.6, widthFrac: 0.3 },
  ],

  'foot-intrinsics': [{ view: 'front', segment: 'foot', t0: 0.1, t1: 0.9, xInsetFrac: 0, widthFrac: 0.7 }],
};
