/**
 * The static reference figure for §9 job 1 (the muscle map) — separate from
 * job 2 (the animated pose rig in poses.js). The muscle map is one fixed
 * front-view and one fixed back-view figure with ~90 coloured regions; the
 * pose animation is a live geometry computation from a [Joint: AngleDegrees]
 * dictionary at runtime in Swift, never pre-rendered art. Conflating the two
 * would mean baking a muscle-coloured image per pose, which is exactly the
 * "commissioned art" §9 rules out.
 *
 * Coordinates are in a fixed 100 (x) by 200 (y) canonical space, y increasing
 * downward, x=50 the body midline. Every point given here is for the RIGHT
 * side of the figure (viewer's right); the left side is generated by
 * mirroring x around the midline, so only one side of anatomy needs placing.
 */

export const RIG_WIDTH = 100;
export const RIG_HEIGHT = 200;
export const MIDLINE_X = 50;

/** Canonical (right-side) joint positions for the static reference pose. */
export const REST_POINTS = {
  headTop: { x: 50, y: 2 },
  headCenter: { x: 50, y: 12 },
  neckBase: { x: 50, y: 22 },
  // The classic muscle-chart A-pose: arms held clearly clear of the torso so
  // the two silhouettes read as distinct shapes rather than overlapping.
  shoulderR: { x: 75, y: 29 },
  chestCenter: { x: 50, y: 38 },
  elbowR: { x: 84, y: 54 },
  waist: { x: 50, y: 68 },
  wristR: { x: 89, y: 78 },
  pelvisCenter: { x: 50, y: 88 },
  hipR: { x: 60, y: 91 },
  kneeR: { x: 61, y: 130 },
  ankleR: { x: 61, y: 168 },
  footTipR: { x: 61, y: 177 },
};

export function mirrorX(x) {
  return 2 * MIDLINE_X - x;
}

/**
 * Segments the figure is built from. `kind: 'line'` runs between two named
 * points with a half-width; `kind: 'point'` is a small round region (deltoid,
 * glute cap) centred on one point. Every drawable muscle attaches to exactly
 * one segment.
 */
export const SEGMENTS = {
  neck: { kind: 'line', a: 'neckBase', b: 'headCenter', halfWidth: 5 },
  'trunk-upper': { kind: 'line', a: 'neckBase', b: 'waist', halfWidth: 17 },
  'trunk-lower': { kind: 'line', a: 'waist', b: 'pelvisCenter', halfWidth: 15 },
  shoulderCap: { kind: 'point', center: 'shoulderR', radius: 7.5 },
  upperArm: { kind: 'line', a: 'shoulderR', b: 'elbowR', halfWidth: 6 },
  forearm: { kind: 'line', a: 'elbowR', b: 'wristR', halfWidth: 5 },
  hipCap: { kind: 'point', center: 'hipR', radius: 9.5 },
  thigh: { kind: 'line', a: 'hipR', b: 'kneeR', halfWidth: 8.5 },
  shin: { kind: 'line', a: 'kneeR', b: 'ankleR', halfWidth: 6 },
  foot: { kind: 'line', a: 'ankleR', b: 'footTipR', halfWidth: 5 },
};

export const SEGMENT_IDS = Object.keys(SEGMENTS);
