/** Sport guides: individual and other sports. See guides/index.js for the shape. */
export const INDIVIDUAL = [
  {
    slug: 'wrestling',
    headline: 'Wrestling is strength, conditioning and technique in six minutes of all-out effort — and making weight the healthy way.',
    demands: [
      { label: 'Match', value: '3 periods, 6–7 minutes total' },
      { label: 'Energy', value: 'Very high intensity, both aerobic and anaerobic' },
      { label: 'Key qualities', value: 'Relative strength, grip, hip power, neck strength' },
      { label: 'Contact', value: 'Full contact the whole match' },
    ],
    succeed: [
      { title: 'Relative strength', body: 'Strength for your bodyweight matters in a weight-class sport. Pull-ups, squats, deadlifts and carries.' },
      { title: 'Conditioning that matches the match', body: 'Hard 1–2 minute efforts with short rest, plus live wrestling, build match fitness.' },
      { title: 'Grip and neck', body: 'Hand fighting and ties need grip; bridges and neck work protect the neck.' },
      { title: 'Make weight safely', body: 'Rapid weight cutting harms performance, health and growth. Pick a weight you can make by eating well — ask your coach about your certified minimum weight.' },
      { title: 'Skin hygiene', body: 'Shower right after practice, wash gear daily, and show any rash to your trainer — skin infections spread fast on the mat.' },
    ],
    season: {
      off: 'Strength and size phase, freestyle/Greco, conditioning base.',
      pre: 'Match-specific conditioning, technique, settle at your weight.',
      in: 'Short strength sessions; stay at your weight by eating well, not cutting.',
    },
    gym: {
      focus: ['Relative strength', 'Grip', 'Neck', 'Hip power', 'Anaerobic conditioning'],
      exercises: ['pull-up', 'trap-bar-deadlift', 'farmers-carry', 'towel-row', 'neck-isometrics', 'sled-push'],
    },
    injuries: [
      { area: 'Neck and head', body: 'Strong neck muscles and good technique protect you. Concussion: out the same day.', exercises: ['neck-isometrics', 'band-neck-extension', 'chin-tuck'] },
      { area: 'Shoulders and knees', body: 'Takedowns and scrambles; strengthen the cuff and legs.', exercises: ['band-external-rotation', 'push-up-plus', 'split-squat'] },
      { area: 'Dehydration and weight cutting', body: 'Saunas, sweat suits and skipping meals are dangerous. Plan your weight with your coach.', exercises: [] },
    ],
    positions: {},
    mindset: ['Wrestle every second — matches are won in the third period.', 'Focus on your position and your shots, not the scoreboard.'],
    fuel: 'Regular meals with protein and carbs keep you strong at your weight. Rehydrate and eat after weigh-ins.',
    sources: ['wrestlingWeight', 'concussion', 'youthStrength'],
    quiz: [
      { type: 'trueFalse', statement: 'Rapid weight cutting harms performance and growth.', answer: true, explain: 'The ACSM advises against it.' },
      { type: 'choice', prompt: 'What should you do with a skin rash?', options: ['Show your trainer before wrestling', 'Cover it and wrestle', 'Ignore it'], answer: 0, explain: 'Skin infections spread quickly on the mat.' },
      { type: 'choice', prompt: 'Which strength matters most in a weight-class sport?', options: ['Strength for your bodyweight', 'Only max bench press', 'Arm size'], answer: 0, explain: 'Relative strength wins.' },
      { type: 'trueFalse', statement: 'Neck training belongs in a wrestler\'s programme.', answer: true, explain: 'It protects the neck and head.' },
    ],
  },
  {
    slug: 'gymnastics',
    headline: 'Gymnastics needs huge strength for your size, flexibility, air awareness — and smart training to protect a growing body.',
    demands: [
      { label: 'Routines', value: 'About 30–90 seconds' },
      { label: 'Key qualities', value: 'Relative strength, power, flexibility, body control' },
      { label: 'Loads', value: 'Landing forces many times bodyweight; wrists bear weight' },
      { label: 'Training', value: 'Many hours a week, often from a young age' },
    ],
    succeed: [
      { title: 'Strength for your size', body: 'Hollow holds, pull-ups, dips and handstands build the base for every skill.' },
      { title: 'Active flexibility', body: 'Flexibility you can control with strength is more useful — and safer — than passive stretching alone.' },
      { title: 'Land well', body: 'Stick landings with bent knees and hips; land softly to protect knees, ankles and back.' },
      { title: 'Avoid overload', body: 'Young athletes who train more hours per week than their age have more serious overuse injuries. Rest days and variety matter.' },
      { title: 'Fuel for growth', body: 'Under-eating harms bones and growth (REDs). A healthy body is a strong body.' },
    ],
    season: {
      off: 'Build strength and new skills with lower routine volume.',
      pre: 'Full routines, consistency.',
      in: 'Maintain strength, reduce volume before meets.',
    },
    gym: {
      focus: ['Core (hollow and arch)', 'Upper-body pull and push', 'Wrist strength', 'Landing', 'Active flexibility'],
      exercises: ['hollow-hold', 'pull-up', 'dips-parallel', 'pike-push-up', 'band-wrist-extension', 'drop-landing-stick'],
    },
    injuries: [
      { area: 'Wrists', body: 'Weight bearing on hands. Build load gradually; wrist pain that lasts needs a check (growth plates).', exercises: ['band-wrist-extension', 'wrist-roller'] },
      { area: 'Lower back', body: 'Repeated arching (back walkovers) can cause stress fractures. Back pain that lasts over two weeks needs a doctor.', exercises: ['dead-bug', 'hollow-hold', 'bird-dog'] },
      { area: 'Ankles and knees', body: 'Landings: soft, controlled and on proper mats.', exercises: ['drop-landing-stick', 'single-leg-balance-reach', 'standing-calf-raise'] },
    ],
    positions: {},
    mindset: ['One skill at a time — visualise it before you go.', 'Fear is normal: break skills into steps and build confidence with spotting.'],
    fuel: 'Enough energy for growth and training: regular meals with protein, carbs and calcium-rich foods.',
    sources: ['reds', 'specialization', 'youthStrength'],
    quiz: [
      { type: 'trueFalse', statement: 'Back pain lasting over two weeks in a gymnast should be checked.', answer: true, explain: 'It can be a stress fracture from repeated arching.' },
      { type: 'choice', prompt: 'Which kind of flexibility is most useful?', options: ['Active — controlled with strength', 'Only passive stretching', 'None'], answer: 0, explain: 'Strength-controlled range is safer.' },
      { type: 'choice', prompt: 'What raised serious overuse injuries in young athletes?', options: ['More weekly hours than their age', 'Rest days', 'Free play'], answer: 0, explain: 'Found in a study of over 1,000 young athletes.' },
      { type: 'trueFalse', statement: 'Under-eating makes gymnasts stronger.', answer: false, explain: 'It harms bones, growth and performance.' },
    ],
  },
  {
    slug: 'competitive-spirit',
    headline: 'Competitive cheer and dance combine tumbling, stunting, jumps and choreography — power, flexibility and trust in your team.',
    demands: [
      { label: 'Routine', value: 'About 2.5 minutes, all-out' },
      { label: 'Key qualities', value: 'Power, flexibility, core, shoulder strength' },
      { label: 'Stunts', value: 'Bases lift and throw; flyers balance and land' },
      { label: 'Risk', value: 'Stunts on hard surfaces cause the most serious injuries' },
    ],
    succeed: [
      { title: 'Stunt safely', body: 'Stunts only with a trained coach, spotters and proper mats — never on hard floors.' },
      { title: 'Strength for bases', body: 'Squats, presses and core strength make lifts safer and cleaner.' },
      { title: 'Balance for flyers', body: 'Single-leg balance, core and body tension keep you stable in the air.' },
      { title: 'Routine fitness', body: 'Full-out routines are intense. Run full routines to build fitness, not only sections.' },
    ],
    season: {
      off: 'Strength, flexibility and tumbling progressions.',
      pre: 'Choreography, stunt progressions with spotters, full-out routine fitness.',
      in: 'Maintain strength; recover between competitions.',
    },
    gym: {
      focus: ['Leg and core strength', 'Shoulder stability', 'Jump power', 'Flexibility'],
      exercises: ['goblet-squat', 'push-press', 'hollow-hold', 'countermovement-jump', 'band-external-rotation', 'single-leg-balance-reach'],
    },
    injuries: [
      { area: 'Head and neck', body: 'Falls from stunts are the main serious risk. Spotters, mats and trained coaching every time.', exercises: ['neck-isometrics'] },
      { area: 'Ankles and knees', body: 'Tumbling and landing; balance and landing training help.', exercises: ['drop-landing-stick', 'single-leg-balance-reach', 'standing-calf-raise'] },
      { area: 'Wrists and back', body: 'Tumbling loads the wrists; bases load the back. Build strength gradually.', exercises: ['band-wrist-extension', 'bird-dog', 'dead-bug'] },
    ],
    positions: {},
    mindset: ['Trust your team — communicate on every stunt.', 'Nerves before a routine are normal: breathe, smile, hit it.'],
    fuel: 'Eat enough for long practices: snacks and water. Healthy bodies make strong flyers and bases.',
    sources: ['cheer', 'reds', 'concussion'],
    quiz: [
      { type: 'trueFalse', statement: 'Stunts should only happen on proper mats with spotters.', answer: true, explain: 'Hard surfaces raise the risk of serious injury.' },
      { type: 'choice', prompt: 'What helps flyers stay stable?', options: ['Balance and core strength', 'Longer hair', 'Holding their breath'], answer: 0, explain: 'Body tension and balance.' },
      { type: 'choice', prompt: 'Who should supervise stunts?', options: ['A trained coach', 'Nobody', 'The audience'], answer: 0, explain: 'Poorly trained supervision raises risk.' },
      { type: 'trueFalse', statement: 'Running full routines builds competition fitness.', answer: true, explain: 'Routines are short but all-out.' },
    ],
  },
  {
    slug: 'golf',
    headline: 'Golf is a power and precision sport: a fast, repeatable swing comes from mobile hips and upper back and a stable core.',
    demands: [
      { label: 'Round', value: '4–5 hours, 6–10 km of walking' },
      { label: 'Swing', value: 'About 1 second; club speed from rotation' },
      { label: 'Key qualities', value: 'Rotational power, mobility, focus' },
      { label: 'Practice', value: 'Hundreds of swings on the range' },
    ],
    succeed: [
      { title: 'Mobility where it matters', body: 'Hips and upper back should turn; the low back should stay stable. Mobility drills make a full turn possible without strain.' },
      { title: 'Strength and speed', body: 'Stronger legs and a powerful rotation mean more club-head speed. Med ball throws and jumps help.' },
      { title: 'Practise with purpose', body: 'Short game and putting are about half of your shots. Practise them with targets and scoring.' },
      { title: 'Warm up before you play', body: 'A short dynamic warm-up before hitting prepares the back and shoulders.' },
      { title: 'Course management', body: 'Play to your strengths, aim for the fat part of the green and take trouble out of play.' },
    ],
    season: {
      off: 'Strength, speed training and swing changes.',
      pre: 'Short-game volume and playing rounds.',
      in: 'Short strength and mobility sessions; manage range volume.',
    },
    gym: {
      focus: ['Rotational power', 'Hip and upper-back mobility', 'Core stability', 'Leg strength'],
      exercises: ['med-ball-rotational-throw', 'thoracic-open-book', '90-90-hip-switch', 'pallof-press', 'goblet-squat', 'countermovement-jump'],
    },
    injuries: [
      { area: 'Lower back', body: 'The most common golf injury. Turn from the hips and upper back, keep the core strong, and don\'t overdo range sessions.', exercises: ['bird-dog', 'side-plank', 'pallof-press', 'thoracic-open-book'] },
      { area: 'Wrists and elbows', body: 'Hitting fat shots and too many balls. Build range volume gradually.', exercises: ['band-wrist-extension', 'wrist-roller'] },
    ],
    positions: {},
    mindset: ['One shot at a time: a pre-shot routine resets your focus.', 'Accept bad shots — the next one is the only one you can control.'],
    fuel: 'Water and small snacks every few holes keep energy and focus up over 4–5 hours.',
    sources: ['youthStrength', 'sleep'],
    quiz: [
      { type: 'choice', prompt: 'Which parts of the body should turn most in a swing?', options: ['Hips and upper back', 'Low back only', 'Neck'], answer: 0, explain: 'The low back should stay stable.' },
      { type: 'trueFalse', statement: 'Short game and putting are about half of your shots.', answer: true, explain: 'Practise them with purpose.' },
      { type: 'choice', prompt: 'What is the most common golf injury?', options: ['Lower back', 'Ankle', 'Knee'], answer: 0, explain: 'Rotation and volume load the back.' },
      { type: 'trueFalse', statement: 'You should eat nothing during a round.', answer: false, explain: 'Small snacks keep energy and focus up.' },
    ],
  },
  {
    slug: 'bowling',
    headline: 'Bowling is precision and repetition: a consistent approach, a strong, healthy wrist and shoulder, and a calm mind.',
    demands: [
      { label: 'Games', value: '3–6+ per competition, often in a day' },
      { label: 'Ball', value: 'Up to 16 lb, swung hundreds of times' },
      { label: 'Key qualities', value: 'Consistency, balance, grip and wrist strength' },
      { label: 'Focus', value: 'Long periods of concentration' },
    ],
    succeed: [
      { title: 'Repeatable approach', body: 'The same steps, tempo and release every time. Balance at the finish shows a good shot.' },
      { title: 'Balance and leg strength', body: 'A stable slide and finish position need single-leg strength and balance.' },
      { title: 'Grip and wrist', body: 'Strong forearms and wrists help control the ball and protect the elbow.' },
      { title: 'Read the lanes', body: 'Oil patterns change during a session. Adjust your line early.' },
    ],
    season: {
      off: 'Strength (legs, grip, shoulder) and technique changes.',
      pre: 'Volume builds; practise spare shooting.',
      in: 'Short strength and mobility sessions; manage game volume.',
    },
    gym: {
      focus: ['Single-leg strength and balance', 'Grip and wrist', 'Shoulder stability', 'Hip mobility'],
      exercises: ['split-squat', 'single-leg-balance-reach', 'farmers-carry', 'wrist-roller', 'band-external-rotation', '90-90-hip-switch'],
    },
    injuries: [
      { area: 'Wrist, elbow and fingers', body: 'Heavy ball and many shots; build volume gradually and use the right ball weight and fit.', exercises: ['band-wrist-extension', 'wrist-roller', 'plate-pinch'] },
      { area: 'Knee and low back', body: 'The slide position loads the front knee and back.', exercises: ['eccentric-step-down', 'bird-dog', 'side-plank'] },
    ],
    positions: {},
    mindset: ['Same routine every shot: breathe, target, go.', 'Make your spares — consistency beats the occasional strike.'],
    fuel: 'Long sessions: water and steady snacks to keep your focus.',
    sources: ['youthStrength', 'sleep'],
    quiz: [
      { type: 'trueFalse', statement: 'Balance at the finish shows a good shot.', answer: true, explain: 'A stable finish means a controlled approach.' },
      { type: 'choice', prompt: 'What changes during a bowling session?', options: ['Oil patterns', 'Lane length', 'Pin count'], answer: 0, explain: 'Adjust your line as the oil moves.' },
      { type: 'choice', prompt: 'Which strength helps control the ball?', options: ['Grip and wrist', 'Neck', 'Calves'], answer: 0, explain: 'Strong forearms control the release.' },
      { type: 'trueFalse', statement: 'Spares don\'t matter much.', answer: false, explain: 'Consistent spare shooting wins games.' },
    ],
  },
  {
    slug: 'weightlifting',
    headline: 'Olympic weightlifting is speed and technique under a bar: the snatch and the clean & jerk reward power, mobility and patience.',
    demands: [
      { label: 'Lifts', value: 'Snatch and clean & jerk, 3 attempts each' },
      { label: 'Effort', value: 'A few seconds of maximum power' },
      { label: 'Key qualities', value: 'Power, technique, mobility, strength' },
      { label: 'Categories', value: 'Bodyweight classes' },
    ],
    succeed: [
      { title: 'Technique first', body: 'Learn the lifts with a PVC pipe or empty bar from a qualified coach. Load follows technique, never the other way round.' },
      { title: 'Supervised strength training is safe', body: 'An international consensus says supervised strength training is safe and effective for young people and lowers injury risk.' },
      { title: 'Mobility for positions', body: 'Ankles, hips, upper back and shoulders need to reach deep, stable positions.' },
      { title: 'Squat strength', body: 'Front and back squats build the legs to stand up from cleans and snatches.' },
      { title: 'Plan your attempts', body: 'Open with a weight you\'re sure of, then build. Six good lifts beat one miss.' },
    ],
    season: {
      off: 'Volume and strength phase, technique fixes.',
      pre: 'Heavier singles and doubles, competition practice.',
      in: 'Taper before meets; practise attempt selection.',
    },
    gym: {
      focus: ['Olympic lift technique', 'Squat strength', 'Pulling power', 'Overhead stability', 'Mobility'],
      exercises: ['barbell-overhead-squat-pvc', 'hang-power-clean', 'barbell-front-squat', 'push-press', 'romanian-deadlift', 'ankle-knee-to-wall'],
    },
    injuries: [
      { area: 'Lower back', body: 'Keep a neutral back on pulls; don\'t max out with poor positions.', exercises: ['back-extension', 'bird-dog', 'dead-bug'] },
      { area: 'Wrists and shoulders', body: 'Overhead lifts need mobile, stable shoulders and strong wrists.', exercises: ['shoulder-dislocates-band', 'band-external-rotation', 'band-wrist-extension'] },
      { area: 'Knees', body: 'Deep squats are fine with good technique; build load gradually.', exercises: ['spanish-squat', 'goblet-squat'] },
    ],
    positions: {},
    mindset: ['Commit to every lift — hesitation causes misses.', 'Record your lifts: video is your best coach between sessions.'],
    fuel: 'Protein at every meal and enough energy to recover; make weight by planning, not crash dieting.',
    sources: ['youthStrength', 'sleep'],
    quiz: [
      { type: 'trueFalse', statement: 'Supervised strength training is safe for young athletes.', answer: true, explain: 'An international consensus supports it.' },
      { type: 'choice', prompt: 'What should you learn the lifts with first?', options: ['A PVC pipe or empty bar', 'Your max weight', 'Dumbbells only'], answer: 0, explain: 'Technique first, load second.' },
      { type: 'choice', prompt: 'What makes a good opening attempt?', options: ['A weight you\'re sure of', 'Your all-time best', 'A new record'], answer: 0, explain: 'Build confidence and a total.' },
      { type: 'trueFalse', statement: 'Mobility doesn\'t matter in weightlifting.', answer: false, explain: 'Deep, stable positions need mobility.' },
    ],
  },
  {
    slug: 'mountain-biking',
    headline: 'Mountain biking needs a strong aerobic engine, powerful legs and the skills and confidence to ride technical trails.',
    demands: [
      { label: 'Race', value: 'Cross-country: 1–2 hours; downhill: a few minutes' },
      { label: 'Energy', value: 'Mostly aerobic, with hard climbs and sprints' },
      { label: 'Key qualities', value: 'Leg power, endurance, bike handling' },
      { label: 'Risk', value: 'Falls on rough terrain' },
    ],
    succeed: [
      { title: 'Aerobic engine', body: 'Long, steady rides build endurance; intervals build climbing power.' },
      { title: 'Skills on the bike', body: 'Cornering, braking and line choice save more time than fitness alone. Practise technical sections.' },
      { title: 'Strength off the bike', body: 'Squats, hinges and single-leg work add power and help you absorb rough terrain.' },
      { title: 'Protect your head', body: 'Always wear a helmet; add gloves and pads for technical riding.' },
    ],
    season: {
      off: 'Strength phase, cross-training, skills on easier trails.',
      pre: 'Intervals, longer rides and race-course practice.',
      in: 'Races and recovery; short strength sessions.',
    },
    gym: {
      focus: ['Leg strength', 'Hip hinge', 'Core and upper body for handling', 'Aerobic intervals'],
      exercises: ['goblet-squat', 'romanian-deadlift', 'bulgarian-split-squat', 'plank-shoulder-tap', 'push-up', 'bike-intervals'],
    },
    injuries: [
      { area: 'Head and collarbone', body: 'Falls: helmet on, learn to roll, and ride within your skill level.', exercises: ['neck-isometrics'] },
      { area: 'Knees and low back', body: 'Long hours in the saddle; get your bike fitted and keep hips mobile.', exercises: ['90-90-hip-switch', 'bird-dog', 'couch-stretch'] },
      { area: 'Wrists and hands', body: 'Vibration and falls; strong grip and relaxed hands.', exercises: ['band-wrist-extension', 'farmers-carry'] },
    ],
    positions: {},
    mindset: ['Look where you want to go, not at the rock you want to avoid.', 'Pre-ride technical sections and visualise your line.'],
    fuel: 'Carbohydrate before and during long rides; drink regularly; eat within an hour after.',
    sources: ['helmets', 'youthStrength'],
    quiz: [
      { type: 'choice', prompt: 'Where should you look on a technical trail?', options: ['Where you want to go', 'At the obstacle', 'At your front wheel'], answer: 0, explain: 'The bike follows your eyes.' },
      { type: 'trueFalse', statement: 'Bike handling skills can save more time than fitness alone.', answer: true, explain: 'Cornering and braking matter a lot.' },
      { type: 'choice', prompt: 'What should you eat during long rides?', options: ['Carbohydrate', 'Nothing', 'Only protein'], answer: 0, explain: 'Carbs keep energy up.' },
      { type: 'trueFalse', statement: 'A helmet is optional on easy trails.', answer: false, explain: 'Always wear one.' },
    ],
  },
  {
    slug: 'unified-sports',
    headline: 'Unified Sports bring athletes with and without intellectual disabilities onto the same team — skill, fitness and teamwork for everyone.',
    demands: [
      { label: 'Format', value: 'Mixed teams — basketball, soccer, track, bowling and more' },
      { label: 'Key qualities', value: 'Sport skills, fitness, teamwork' },
      { label: 'Focus', value: 'Meaningful involvement for every player' },
      { label: 'Levels', value: 'Recreation, player development, competitive' },
    ],
    succeed: [
      { title: 'Everyone plays a real role', body: 'Great Unified teams make sure every player touches the ball and contributes — that is the rule and the spirit.' },
      { title: 'Build all-round fitness', body: 'Strength, balance and aerobic fitness help every athlete play longer and safer.' },
      { title: 'Clear communication', body: 'Simple, positive cues and demonstrations help the whole team learn skills.' },
      { title: 'Celebrate progress', body: 'Personal bests and team goals keep everyone motivated.' },
    ],
    season: {
      off: 'General fitness, balance and fun movement.',
      pre: 'Sport skills and team practice.',
      in: 'Games, recovery and keeping fitness up.',
    },
    gym: {
      focus: ['Balance', 'General strength', 'Aerobic fitness', 'Coordination'],
      exercises: ['bodyweight-squat', 'push-up', 'single-leg-balance-reach', 'step-up', 'farmers-carry', 'jump-rope-intervals'],
    },
    injuries: [
      { area: 'Ankles and knees', body: 'Balance and landing drills protect every athlete.', exercises: ['single-leg-balance-reach', 'drop-landing-stick'] },
      { area: 'Heat and hydration', body: 'Drink water at every break and watch teammates on hot days.', exercises: [] },
    ],
    positions: {},
    mindset: ['Encourage every teammate — the team wins together.', 'Focus on your own progress, one skill at a time.'],
    fuel: 'Regular meals, water at every break, and a snack after practice.',
    sources: ['youthStrength', 'heat'],
    quiz: [
      { type: 'trueFalse', statement: 'In Unified Sports every player should have a real role.', answer: true, explain: 'Meaningful involvement is the heart of Unified.' },
      { type: 'choice', prompt: 'What helps a Unified team learn skills?', options: ['Simple cues and demonstrations', 'Long lectures', 'Only watching'], answer: 0, explain: 'Clear, positive communication.' },
      { type: 'choice', prompt: 'What protects ankles and knees?', options: ['Balance and landing drills', 'Longer shoelaces', 'Skipping warm-ups'], answer: 0, explain: 'They lower sprains for everyone.' },
      { type: 'trueFalse', statement: 'Only the best player should shoot.', answer: false, explain: 'Everyone contributes.' },
    ],
  },
];
