/** Sport guides: field team sports. See guides/index.js for the shape. */
export const TEAM_FIELD = [
  {
    slug: 'soccer',
    headline: 'Soccer is won by the player who can repeat hard sprints late in the game and still make good decisions with the ball.',
    demands: [
      { label: 'Distance per game', value: '7–11 km (high school to college)' },
      { label: 'Sprints', value: '20–40 short sprints, most under 20 m' },
      { label: 'Changes of direction', value: '600+ turns, cuts and stops' },
      { label: 'Energy', value: 'Aerobic base with repeated bursts' },
    ],
    succeed: [
      { title: 'Win the first three steps', body: 'Most decisive sprints are 5–15 m. Acceleration and braking decide who gets to the ball first, far more than top speed.' },
      { title: 'Build the engine to repeat it', body: 'A strong aerobic base lets you recover between sprints, so your 30th burst looks like your first. Small-sided games and intervals build it best.' },
      { title: 'Touch count matters', body: 'Players who get thousands of touches outside team practice — wall passes, juggling, both feet — are calmer on the ball under pressure.' },
      { title: 'Scan before you receive', body: 'Top midfielders check over their shoulder several times before the ball arrives. It turns a first touch into a decision.' },
      { title: 'Strong hamstrings and groins keep you playing', body: 'Hamstring and groin strains are the most common time-loss injuries. Two simple exercises prevent many of them (below).' },
    ],
    season: {
      off: 'Build strength (two to three gym days), aerobic base and sprint mechanics. This is when you get faster.',
      pre: 'Shift to speed, repeated sprints and game-like conditioning. Keep one or two short strength sessions. Build up running volume gradually.',
      in: 'Two short strength sessions a week, never the day before a game. Nordic curls and Copenhagen planks all season long.',
    },
    gym: {
      focus: ['Single-leg strength for sprinting, cutting and shooting', 'Eccentric hamstring strength', 'Adductor (groin) strength', 'Acceleration and deceleration drills', 'Hip mobility'],
      exercises: ['bulgarian-split-squat', 'nordic-hamstring-curl', 'copenhagen-plank', 'trap-bar-deadlift', 'acceleration-wall-drill', 'deceleration-drop-stick'],
    },
    injuries: [
      { area: 'Hamstrings', body: 'Strains happen while sprinting, often late in games. The Nordic curl cut hamstring injuries to about a third in amateur players.', exercises: ['nordic-hamstring-curl', 'single-leg-rdl'] },
      { area: 'Groin', body: 'Kicking and cutting load the adductors. One exercise done three times a week in pre-season and once a week in season cut groin problems by 41%.', exercises: ['copenhagen-plank', 'adductor-squeeze'] },
      { area: 'Knees and ankles', body: 'Landing, cutting and balance training — the FIFA 11+ warm-up — lowers severe and overuse injuries. Do it before every practice.', exercises: ['single-leg-balance-reach', 'drop-landing-stick', 'lateral-hop-to-stick'] },
    ],
    positions: {
      goalkeeper: 'Explosive jumps and lateral pushes, strong shoulders for landing on your side, and fast reactions.',
      defender: 'Braking and turning, heading duels, and staying compact while backpedalling.',
      midfielder: 'The biggest engine on the team: repeated sprints and constant scanning.',
      forward: 'Acceleration off the shoulder of the last defender and a powerful, repeatable strike.',
    },
    mindset: ['After a mistake, the next action matters more than the last one — use a reset word.', 'Talk constantly: communication is a skill coaches notice.'],
    fuel: 'A carb-rich meal 3–4 hours before, water and a little carbohydrate at half-time in the heat. Games burn a lot — eat properly afterwards.',
    sources: ['fifa11', 'nordic', 'copenhagen', 'acl'],
    quiz: [
      { type: 'choice', prompt: 'How long are most sprints in a soccer game?', options: ['Under 20 m', '40–60 m', 'Over 80 m'], answer: 0, explain: 'Most decisive sprints are short — acceleration wins them.' },
      { type: 'trueFalse', statement: 'The Nordic hamstring curl lowered hamstring injuries in amateur soccer players.', answer: true, explain: 'To about a third, in a randomised trial.' },
      { type: 'choice', prompt: 'Which exercise protects the groin?', options: ['Copenhagen plank', 'Bicep curl', 'Calf raise'], answer: 0, explain: 'It strengthens the adductors that cutting and kicking load.' },
      { type: 'trueFalse', statement: 'In season you should stop strength training so your legs stay fresh.', answer: false, explain: 'Two short sessions a week keep you strong; skip only the day before a game.' },
    ],
  },
  {
    slug: 'football',
    headline: 'Football is a sport of short, violent bursts: the players who are strongest and most explosive over 5–10 yards win most plays.',
    demands: [
      { label: 'Play length', value: 'About 5 seconds, then 30–40 s rest' },
      { label: 'Plays per game', value: '60–80 per team' },
      { label: 'Key qualities', value: 'Power, acceleration, strength' },
      { label: 'Contact', value: 'Full contact on almost every play' },
    ],
    succeed: [
      { title: 'Get strong first', body: 'Relative strength — how strong you are for your bodyweight — underpins speed, blocking and tackling. Squats, deadlifts, presses and rows are the base.' },
      { title: 'Turn strength into power', body: 'Jumps, throws and Olympic-style lifts teach you to use strength fast. Keep reps low and quality high.' },
      { title: 'Train like the game', body: 'Conditioning should match play length: 5–8 second efforts with 30–40 seconds rest, not long slow runs.' },
      { title: 'Protect the neck', body: 'A strong neck is linked to fewer and less severe head injuries. Neck work belongs in every week.' },
      { title: 'Know your assignment', body: 'Film and playbook study make you faster: the player who knows where to go reacts first.' },
    ],
    season: {
      off: 'Main strength phase: three to four lifting days, sprint technique, bodyweight goals (gain muscle if needed).',
      pre: 'Heat acclimatisation: the first 14 days build up slowly with helmets only, then pads. Speed and position-specific conditioning.',
      in: 'Two lifting days to keep strength. Recover from contact: sleep, food, mobility.',
    },
    gym: {
      focus: ['Lower-body strength (squat, hinge)', 'Upper-body push and pull', 'Explosive power', 'Neck strength', 'Acceleration over 10 yards'],
      exercises: ['barbell-back-squat', 'trap-bar-deadlift', 'bench-press', 'hang-power-clean', 'neck-isometrics', 'sled-push'],
    },
    injuries: [
      { area: 'Head and neck', body: 'Tackle with your head up and strengthen the neck. Any suspected concussion: out for the day, see a doctor, return step by step.', exercises: ['neck-isometrics', 'band-neck-extension', 'chin-tuck'] },
      { area: 'Knees', body: 'Landing and cutting drills lower non-contact knee injuries.', exercises: ['drop-landing-stick', 'lateral-hop-to-stick', 'eccentric-step-down'] },
      { area: 'Heat illness', body: 'Most dangerous in the first days of pre-season. Acclimatise over two weeks, drink, and tell someone if you feel dizzy or confused.', exercises: [] },
    ],
    positions: {
      quarterback: 'Rotational power, shoulder care and quick feet in the pocket.',
      lineman: 'Maximal strength, a powerful first step and strong hands — both sides of the ball.',
      skill: 'Receivers, backs and DBs: acceleration, top speed, sharp cuts and a backpedal that turns into a sprint.',
      linebacker: 'Reading and reacting, lateral speed and tackling power.',
    },
    mindset: ['Next play: reset between snaps in the 30 seconds you have.', 'Preparation builds confidence — know your job before you get to the field.'],
    fuel: 'Big days need big fuel: carbohydrate and protein at every meal, plus a snack after lifting. Hydrate across the day, not just at practice.',
    sources: ['heat', 'concussion', 'acl'],
    quiz: [
      { type: 'choice', prompt: 'How long does a typical football play last?', options: ['About 5 seconds', 'About 30 seconds', 'About 2 minutes'], answer: 0, explain: 'Short bursts — so conditioning should be short, fast efforts with rest.' },
      { type: 'trueFalse', statement: 'Long slow runs are the best conditioning for football.', answer: false, explain: 'Repeated 5–8 second efforts match the game better.' },
      { type: 'choice', prompt: 'When is heat illness most dangerous?', options: ['The first days of pre-season', 'The last game of the season', 'Winter workouts'], answer: 0, explain: 'Before your body has acclimatised to the heat.' },
      { type: 'trueFalse', statement: 'Neck strengthening belongs in a football player\'s week.', answer: true, explain: 'A strong neck is linked to fewer and less severe head injuries.' },
    ],
  },
  {
    slug: 'flag-football',
    headline: 'Flag football is a speed-and-agility game: no blocking, so the athlete who changes direction fastest wins.',
    demands: [
      { label: 'Play length', value: '4–8 seconds of full effort' },
      { label: 'Key qualities', value: 'Acceleration, cutting, hands' },
      { label: 'Contact', value: 'Limited — flag pulls, not tackles' },
      { label: 'Energy', value: 'Repeated sprints with short rest' },
    ],
    succeed: [
      { title: 'Cut on a dime', body: 'Sharp route breaks and evasive moves decide every play. Train braking and re-accelerating, not just straight-line speed.' },
      { title: 'Sure hands', body: 'Catch hundreds of balls a week from different angles — catching is a skill that improves with repetition.' },
      { title: 'Pull flags cleanly', body: 'Defence is about staying square and mirroring. Break down, keep your hips low, reach for the hip.' },
      { title: 'Repeat the sprint', body: 'Conditioning with 5–10 second efforts and short rest keeps you sharp in the second half.' },
    ],
    season: {
      off: 'Strength (single-leg and hinge), sprint technique, lots of catching.',
      pre: 'Agility and route running, repeated sprints.',
      in: 'Short strength sessions twice a week; keep hamstrings and ankles strong.',
    },
    gym: {
      focus: ['Braking and cutting', 'Acceleration', 'Hamstring strength', 'Ankle stability'],
      exercises: ['5-10-5-shuttle', 'lateral-bound', 'nordic-hamstring-curl', 'single-leg-rdl', 'single-leg-balance-reach', 'acceleration-wall-drill'],
    },
    injuries: [
      { area: 'Hamstrings', body: 'Sprinting injuries — keep eccentric hamstring strength up all season.', exercises: ['nordic-hamstring-curl', 'hamstring-slider-curl'] },
      { area: 'Ankles and knees', body: 'Cutting on grass or turf; balance and landing training lower the risk.', exercises: ['single-leg-balance-eyes-closed', 'lateral-hop-to-stick', 'drop-landing-stick'] },
    ],
    positions: {},
    mindset: ['Short memory: a dropped pass is gone — focus on the next route.', 'Communicate on defence; most big plays come from missed switches.'],
    fuel: 'A balanced meal a few hours before and water between games on tournament days, plus a small carb snack.',
    sources: ['nordic', 'balance', 'acl'],
    quiz: [
      { type: 'trueFalse', statement: 'Straight-line speed matters more than cutting in flag football.', answer: false, explain: 'Evasion and route breaks decide most plays.' },
      { type: 'choice', prompt: 'Which exercise best protects against hamstring strains?', options: ['Nordic hamstring curl', 'Leg extension', 'Crunch'], answer: 0, explain: 'Eccentric hamstring strength is the key protector.' },
      { type: 'choice', prompt: 'How long is a typical flag football play?', options: ['4–8 seconds', '1 minute', '3 minutes'], answer: 0, explain: 'Short bursts with rest in between.' },
      { type: 'trueFalse', statement: 'Balance training can lower ankle sprains.', answer: true, explain: 'It roughly halved them in high school athletes.' },
    ],
  },
  {
    slug: 'rugby',
    headline: 'Rugby asks for everything at once — strength for contact, speed for space and an engine for 60–80 minutes.',
    demands: [
      { label: 'Distance', value: '4–7 km per game' },
      { label: 'Collisions', value: '20–40+ tackles, rucks and carries (forwards more)' },
      { label: 'Key qualities', value: 'Strength, power, repeated efforts' },
      { label: 'Contact', value: 'Full contact' },
    ],
    succeed: [
      { title: 'Be strong in contact', body: 'Strength and body mass help you win collisions, but only if you can move them fast. Lift heavy and sprint.' },
      { title: 'Tackle technique first', body: 'Low, square tackles with your head on the correct side protect you and win the ball. Practise technique at walking speed before full contact.' },
      { title: 'Repeated high-intensity efforts', body: 'Get up, sprint, tackle, ruck, repeat. Conditioning should mix sprints with getting off the ground.' },
      { title: 'Neck and trunk', body: 'Scrums, rucks and tackles load the neck. Neck training is part of the programme, not optional.' },
      { title: 'Warm up with purpose', body: 'The Activate warm-up — balance, strength, jumps and landing — cut match injuries and concussions when teams did it three times a week.' },
    ],
    season: {
      off: 'Strength and size (if needed), speed, aerobic base.',
      pre: 'Contact conditioning, repeated efforts, tackle technique.',
      in: 'Two strength sessions, Activate before every practice, recovery after games.',
    },
    gym: {
      focus: ['Full-body strength', 'Neck strength', 'Power (jumps, throws, cleans)', 'Repeated sprint ability'],
      exercises: ['barbell-back-squat', 'trap-bar-deadlift', 'bench-press', 'neck-isometrics', 'hang-power-clean', 'sled-push'],
    },
    injuries: [
      { area: 'Head and neck', body: 'Tackle technique and neck strength matter. The Activate programme reduced concussions in schoolboy rugby.', exercises: ['neck-isometrics', 'band-neck-extension'] },
      { area: 'Shoulders', body: 'Tackling loads the shoulder; strengthen the cuff and upper back.', exercises: ['band-external-rotation', 'face-pull', 'push-up-plus'] },
      { area: 'Knees and ankles', body: 'Balance, landing and cutting drills from the Activate warm-up.', exercises: ['single-leg-balance-reach', 'drop-landing-stick'] },
    ],
    positions: {},
    mindset: ['Work rate is a choice: be the player who gets up first.', 'Stay composed under fatigue — decisions are what separate levels.'],
    fuel: 'Enough energy to hold or build muscle: protein at every meal and plenty of carbohydrate around training.',
    sources: ['rugbyActivate', 'concussion'],
    quiz: [
      { type: 'trueFalse', statement: 'A warm-up programme reduced concussions in schoolboy rugby.', answer: true, explain: 'Activate, done three times a week, lowered match injuries and concussions.' },
      { type: 'choice', prompt: 'What should you practise before full-contact tackling?', options: ['Technique at walking speed', 'Max-speed hits', 'Nothing — just tackle'], answer: 0, explain: 'Good technique protects you and wins the ball.' },
      { type: 'choice', prompt: 'Which body part does neck training protect?', options: ['Head and neck', 'Ankle', 'Wrist'], answer: 0, explain: 'A strong neck helps in tackles, rucks and scrums.' },
      { type: 'trueFalse', statement: 'Rugby conditioning should only be long, slow runs.', answer: false, explain: 'Repeated efforts — sprint, tackle, get up — match the game.' },
    ],
  },
  {
    slug: 'lacrosse',
    headline: 'Lacrosse rewards quick feet, quick hands and the fitness to keep running a transition game.',
    demands: [
      { label: 'Distance', value: '5–8 km for midfielders' },
      { label: 'Key qualities', value: 'Acceleration, change of direction, stick skills' },
      { label: 'Contact', value: 'Boys: body and stick checks; girls: limited' },
      { label: 'Energy', value: 'Repeated sprints, shifts' },
    ],
    succeed: [
      { title: 'Wall ball every day', body: 'The best players throw and catch thousands of balls against a wall, both hands. Stick skills are built alone, not just at practice.' },
      { title: 'Dodge and change direction', body: 'Beating a defender is about deceleration and a sharp first step. Train cutting and braking.' },
      { title: 'Shoot with the whole body', body: 'Shot speed comes from the hips and trunk turning, like a throw. Rotational power training helps.' },
      { title: 'Transition fitness', body: 'Midfielders run end to end; repeated sprint training keeps you fast in the fourth quarter.' },
    ],
    season: {
      off: 'Strength, rotational power, wall ball and aerobic base.',
      pre: 'Agility, repeated sprints, shooting volume.',
      in: 'Two short strength sessions; keep up knee and ankle prevention.',
    },
    gym: {
      focus: ['Rotational power', 'Single-leg strength and braking', 'Shoulder health', 'Knee injury prevention'],
      exercises: ['med-ball-rotational-throw', 'landmine-rotation', 'bulgarian-split-squat', 'lateral-bound', 'band-external-rotation', 'drop-landing-stick'],
    },
    injuries: [
      { area: 'Knees (ACL)', body: 'Cutting sports carry ACL risk, especially for girls. Prevention programmes cut non-contact ACL tears in girls by two-thirds.', exercises: ['drop-landing-stick', 'lateral-hop-to-stick', 'nordic-hamstring-curl'] },
      { area: 'Ankles', body: 'Balance training lowers sprains.', exercises: ['single-leg-balance-reach', 'single-leg-balance-eyes-closed'] },
      { area: 'Head', body: 'Stick and body contact cause concussions. Protective gear on, head up, and out the same day if in doubt.', exercises: ['neck-isometrics'] },
    ],
    positions: {
      attack: 'Dodging, quick release and shooting with both hands from tight angles.',
      midfield: 'The engine: transition sprints, face-off wins and shooting on the run.',
      defense: 'Footwork to stay in front, a patient stick and communication.',
      goalie: 'Reaction speed, stepping to the ball and a quick clearing pass.',
    },
    mindset: ['Be ready for ground balls — effort plays win possessions.', 'After a turnover, sprint back: the next play is yours.'],
    fuel: 'A carb-rich meal before games, fluids during, and a proper meal afterwards.',
    sources: ['acl', 'balance', 'concussion'],
    quiz: [
      { type: 'trueFalse', statement: 'Wall ball on your own is one of the best ways to improve stick skills.', answer: true, explain: 'Thousands of reps with both hands build the skill.' },
      { type: 'choice', prompt: 'Where does shot power mostly come from?', options: ['Hips and trunk turning', 'Wrists only', 'Standing still'], answer: 0, explain: 'Like a throw, the power comes from the body rotating.' },
      { type: 'choice', prompt: 'By how much did prevention programmes lower non-contact ACL tears in girls?', options: ['About two-thirds', 'Not at all', 'About 5%'], answer: 0, explain: 'A large combined analysis found a two-thirds reduction.' },
      { type: 'trueFalse', statement: 'Midfielders only need to be fast, not fit.', answer: false, explain: 'They run end to end; repeated sprint fitness matters.' },
    ],
  },
  {
    slug: 'field-hockey',
    headline: 'Field hockey is played bent over at speed — a strong low back, hips and legs let you stay low, fast and skilful.',
    demands: [
      { label: 'Distance', value: '6–9 km per game' },
      { label: 'Posture', value: 'Long periods in a crouched position' },
      { label: 'Key qualities', value: 'Repeated sprints, agility, trunk endurance' },
      { label: 'Contact', value: 'Limited' },
    ],
    succeed: [
      { title: 'Stay low for longer', body: 'The crouched posture tires the back and legs. Strong glutes, hamstrings and back muscles let you keep it without losing speed.' },
      { title: 'Stick skills at speed', body: 'Dribbling and receiving while running fast separate good from great. Practise with the ball at game speed.' },
      { title: 'Repeat sprints', body: 'Players sprint many times per game with rolling substitutions; interval training builds that.' },
      { title: 'Read the game', body: 'Scanning before receiving lets you pass forward quickly instead of turning back.' },
    ],
    season: {
      off: 'Strength (hinge, single-leg), back endurance, aerobic base.',
      pre: 'Speed, agility and repeated sprints; build up turf running slowly.',
      in: 'Two short strength sessions; back and hamstring care.',
    },
    gym: {
      focus: ['Hip hinge strength', 'Back endurance', 'Single-leg strength', 'Agility'],
      exercises: ['romanian-deadlift', 'back-extension', 'side-plank', 'bulgarian-split-squat', 't-drill', 'nordic-hamstring-curl'],
    },
    injuries: [
      { area: 'Lower back', body: 'The bent posture loads the back. Build back and trunk endurance and hip mobility.', exercises: ['back-extension', 'bird-dog', 'side-plank', '90-90-hip-switch'] },
      { area: 'Knees and ankles', body: 'Cutting on turf: landing and balance training lower the risk.', exercises: ['drop-landing-stick', 'single-leg-balance-reach'] },
    ],
    positions: {
      goalkeeper: 'Explosive lateral pushes and fast feet while wearing heavy kit — and courage on penalty corners.',
      defender: 'Tackling timing, jab tackles and long, accurate hits out of defence.',
      midfielder: 'The biggest engine: repeated sprints both ways and receiving under pressure.',
      forward: 'Quick first step in the circle, deflections and finishing from reverse stick.',
    },
    mindset: ['Stay switched on through rolling subs: be ready the moment you step on.', 'Short memory for mistakes, fast reaction to turnovers.'],
    fuel: 'Carbohydrate before games, fluids at breaks — turf gets hot.',
    sources: ['acl', 'balance'],
    quiz: [
      { type: 'trueFalse', statement: 'Back endurance training helps field hockey players stay low for longer.', answer: true, explain: 'The crouched posture tires the back and hips.' },
      { type: 'choice', prompt: 'Which exercise builds the hip hinge for staying low?', options: ['Romanian deadlift', 'Bicep curl', 'Chest fly'], answer: 0, explain: 'It strengthens hamstrings, glutes and back.' },
      { type: 'choice', prompt: 'What helps you pass forward quickly?', options: ['Scanning before receiving', 'Looking at the ball only', 'Standing still'], answer: 0, explain: 'Knowing what is around you before the ball arrives.' },
      { type: 'trueFalse', statement: 'Field hockey players never sprint.', answer: false, explain: 'They sprint many times per game.' },
    ],
  },
];
