/**
 * Base drills — §7: sport-specific technical or tactical work, requiring that
 * sport's equipment and surface. Four of the drills below are the exact
 * examples §7 itself names ("soccer instep-drive progression, hockey
 * edge-work figure eights, volleyball approach-and-swing footwork, sprint
 * block starts"); the rest fill out §8's worked "soccer · shooting power ·
 * game in 7 days" example, which names plant-and-strike, one-touch finishing
 * off a rolling ball, and weak-foot volume explicitly.
 */

export const DRILLS = [

  // ═══════════════════════════════════════════════════════════════════════
  // Soccer — §8's worked example: shooting-power maps to deceleration 1.0,
  // rotational-power 0.9, horizontal/vertical power 0.8, lower-body-strength
  // 0.7, ankle-stiffness/reactive-strength 0.7, hip-mobility 0.5,
  // single-leg-stability 0.5. Every drill below is tagged from that mapping.
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'soccer-instep-drive-progression',
    name: 'Instep-Drive Progression',
    kind: 'drill',
    sport: 'soccer',
    qualities: { 'rotational-power': 0.9, 'ankle-stiffness': 0.6, deceleration: 0.5 },
    muscles: { 'rectus-femoris': 0.8, 'gluteus-maximus': 0.6, 'tibialis-anterior': 0.4 },
    equipment: ['ball', 'goal'],
    prop: 'ball-round',
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set up 12 yards from the goal with a supply of balls.'],
    execution: [
      'Static ball, no run-up: strike through the middle of the ball with the instep, laces locked.',
      'Add a two-step approach once the static strike is consistent, planting the support foot beside the ball.',
    ],
    cues: ['Lock the ankle at contact — a loose ankle bleeds power.', 'Non-kicking foot plants level with the ball, not behind it.'],
    mistakes: ['Leaning back at contact, which sends the ball up rather than through the target.'],
    progressions: ['soccer-plant-and-strike'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'instep-strike',
    endPose: 'instep-strike',
    constraintAxes: ['movement'],
  },
  {
    slug: 'soccer-plant-and-strike',
    name: 'Plant-and-Strike Progression',
    kind: 'drill',
    sport: 'soccer',
    qualities: { deceleration: 0.9, 'rotational-power': 0.7, 'single-leg-stability': 0.5 },
    muscles: { 'biceps-femoris': 0.7, 'gluteus-maximus': 0.7, 'gluteus-medius': 0.5 },
    equipment: ['ball', 'goal'],
    prop: 'ball-round',
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set up 15 yards out with a ball supply and a marked approach line.'],
    execution: [
      'Jog in from an angle, decelerate hard over the last two steps into a firm plant beside the ball.',
      'Strike immediately off the plant — the braking and the strike are one continuous action, not two.',
    ],
    cues: ['The plant foot absorbs and stops almost all of the approach speed in one step.', 'Strike within a beat of planting — do not pause and re-set.'],
    mistakes: ['Taking an extra shuffle step to reset before striking, which defeats the point of training the plant-to-strike transfer.'],
    progressions: [],
    regressions: ['soccer-instep-drive-progression'],
    substitutes: ['soccer-instep-drive-progression'],
    defaultDose: { kind: 'reps', sets: 4, reps: 6, load: 'bodyweight' },
    restSeconds: 75,
    startPose: 'deceleration-plant',
    endPose: 'instep-strike',
    constraintAxes: ['opposition'],
  },
  {
    slug: 'soccer-one-touch-finishing',
    name: 'One-Touch Finishing Off a Rolling Ball',
    kind: 'drill',
    sport: 'soccer',
    qualities: { 'rotational-power': 0.7, 'reactive-strength': 0.5 },
    muscles: { 'rectus-femoris': 0.7, 'gluteus-maximus': 0.5 },
    equipment: ['ball', 'goal', 'partner'],
    prop: 'ball-round',
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['A partner or a wall feeds rolling balls across the front of goal from varying angles.'],
    execution: ['Strike the moving ball first time, without a controlling touch.', 'Reset for the next feed from a different angle.'],
    cues: ['Read the ball\'s pace and line early so the strike is not rushed.', 'Adjust the plant foot to the ball\'s speed, not a fixed spot.'],
    mistakes: ['Taking a controlling touch anyway out of habit, which defeats the drill.'],
    progressions: [],
    regressions: ['soccer-instep-drive-progression'],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'instep-strike',
    endPose: 'instep-strike',
    constraintAxes: ['touches'],
  },
  {
    slug: 'soccer-weak-foot-volume',
    name: 'Weak-Foot Striking Volume',
    kind: 'drill',
    sport: 'soccer',
    qualities: { 'rotational-power': 0.5, 'ankle-stiffness': 0.3 },
    muscles: { 'rectus-femoris': 0.5, 'tibialis-anterior': 0.4 },
    equipment: ['ball', 'goal'],
    prop: 'ball-round',
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set up as for the instep-drive progression, striking only with the non-dominant foot.'],
    execution: ['Static and light-approach strikes with the weaker foot, same mechanics as the dominant-foot version.', 'Prioritise clean contact over power at first.'],
    cues: ['Accept a lower power output than the dominant foot — consistency is the goal here, not maximal velocity.', 'Use the exact same plant and approach mechanics as the dominant foot.'],
    mistakes: ['Rushing the volume to "get it over with" instead of focusing on clean technique each rep.'],
    progressions: [],
    regressions: [],
    substitutes: ['soccer-instep-drive-progression'],
    defaultDose: { kind: 'reps', sets: 3, reps: 10, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'instep-strike',
    endPose: 'instep-strike',
    unilateralEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // §7's own named examples
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'hockey-edge-work-figure-eights',
    name: 'Edge-Work Figure Eights',
    kind: 'drill',
    sport: 'ice-hockey',
    qualities: { 'change-of-direction': 1.0, 'single-leg-stability': 0.7, 'lateral-power': 0.6 },
    muscles: { 'gluteus-medius': 0.9, 'adductors': 0.7, 'vastus-lateralis': 0.5 },
    equipment: ['skates'],
    prop: 'stick-hockey',
    surface: 'ice',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Mark two points 8-10 feet apart on the ice, or use existing faceoff dots.'],
    execution: [
      'Skate a figure-eight pattern around the two points using inside and outside edges, no stopping.',
      'Keep the pattern tight — the tighter the turn, the more edge control it demands.',
    ],
    cues: ['Stay low through the turns, knees bent.', 'Lead with the edge, not by turning the whole body first.'],
    mistakes: ['Slowing to a near-stop at each turn instead of carrying speed through with the edge.'],
    progressions: ['hockey-crossover-acceleration'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'time', sets: 4, seconds: 30, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'crossover-stride',
    endPose: 'crossover-stride',
    constraintAxes: ['movement'],
  },
  {
    slug: 'hockey-crossover-acceleration',
    name: 'Crossover Acceleration',
    kind: 'drill',
    sport: 'ice-hockey',
    qualities: { acceleration: 0.9, 'lateral-power': 0.8, 'single-leg-stability': 0.5 },
    muscles: { 'gluteus-medius': 0.8, 'gluteus-maximus': 0.7, 'adductors': 0.5 },
    equipment: ['skates'],
    prop: 'stick-hockey',
    surface: 'ice',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Start at the boards or a faceoff circle with open ice ahead.'],
    execution: ['Drive out of a stationary or near-stationary start using crossover steps rather than a straight stride.', 'Transition to a full stride once speed builds.'],
    cues: ['Push fully through each crossover step before the next.', 'Stay low out of the start; standing up early kills acceleration.'],
    mistakes: ['Switching to a straight stride too early, before the crossovers have built real speed.'],
    progressions: [],
    regressions: ['hockey-edge-work-figure-eights'],
    substitutes: ['hockey-edge-work-figure-eights'],
    defaultDose: { kind: 'reps', sets: 5, reps: 1, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'crossover-stride',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
  },
  {
    slug: 'hockey-wrist-shot-power',
    name: 'Wrist Shot Power',
    kind: 'drill',
    sport: 'ice-hockey',
    qualities: { 'rotational-power': 0.9, grip: 0.5, 'trunk-anti-rotation': 0.4 },
    muscles: { 'obliques-external': 0.8, 'forearm-flexors': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['stick', 'puck', 'goal'],
    prop: 'puck',
    surface: 'ice',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set up 15-20 feet from an empty net with a supply of pucks.'],
    execution: ['Load the stick by rolling the puck back, then drive forward transferring weight from back to front foot as the blade whips through the release.', 'Follow through toward the target.'],
    cues: ['The power comes from the weight transfer and stick flex, not the arms alone.', 'Follow-through points at the target every time.'],
    mistakes: ['Shooting entirely with the arms while the feet stay flat and square.'],
    progressions: [],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'rotational-throw',
    endPose: 'rotational-throw',
    unilateralEligible: false,
  },

  {
    slug: 'volleyball-approach-and-swing-footwork',
    name: 'Approach-and-Swing Footwork',
    kind: 'drill',
    sport: 'volleyball',
    qualities: { 'vertical-power': 0.8, 'change-of-direction': 0.6, 'overhead-power': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'deltoid-anterior': 0.6, 'vastus-lateralis': 0.6 },
    equipment: ['ball', 'net'],
    prop: 'ball-round',
    surface: 'court',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand at the approach spot, a few steps back from the net.'],
    execution: [
      'Perform the three- or four-step approach (small step, big step, close step) building speed into the plant.',
      'Plant both feet, swing the arms back-to-up, and jump into the swing motion at the top.',
    ],
    cues: ['The last two steps should be quick and low, converting horizontal speed into vertical lift.', 'Arms swing all the way back before driving up together at the plant.'],
    mistakes: ['A slow, even-tempo approach instead of building speed into the last two steps.'],
    progressions: [],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 6, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'vertical-jump',
    endPose: 'overhead-throw',
    constraintAxes: ['opposition'],
  },

  {
    slug: 'sprint-block-starts',
    name: 'Block Starts',
    kind: 'drill',
    sport: 'track-and-field',
    qualities: { acceleration: 1.0, 'horizontal-power': 0.6, 'reactive-strength': 0.4 },
    muscles: { 'gluteus-maximus': 0.9, 'vastus-lateralis': 0.7, gastrocnemius: 0.5 },
    equipment: ['blocks'],
    surface: 'track',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Set starting blocks at a comfortable pedal angle; take the "set" position with hips slightly above shoulder height.'],
    execution: ['On the start signal, drive out low and hard, first steps short and powerful.', 'Gradually rise to full sprint posture over the first 10-15 metres.'],
    cues: ['First step is short and punches straight back into the block, not up.', 'Stay low for the first several steps rather than standing up immediately.'],
    mistakes: ['Popping straight up out of the blocks instead of driving out at a low angle.'],
    progressions: [],
    regressions: ['acceleration-wall-drill'],
    substitutes: ['acceleration-wall-drill'],
    defaultDose: { kind: 'reps', sets: 5, reps: 1, load: 'bodyweight' },
    restSeconds: 120,
    startPose: 'sprint-start',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Basketball
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'basketball-first-step-attack',
    name: 'First-Step Attack',
    kind: 'drill',
    sport: 'basketball',
    qualities: { acceleration: 0.9, 'change-of-direction': 0.7, 'reactive-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.8, 'vastus-lateralis': 0.7, 'gluteus-medius': 0.5 },
    equipment: ['ball'],
    prop: 'ball-round',
    surface: 'court',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Start in a triple-threat stance with the ball, a cone or defender marker two steps away.'],
    execution: [
      'Push off the far foot explosively and take the first dribble low and out ahead of the body, not up.',
      'Accelerate hard for three steps past the marker before pulling up.',
    ],
    cues: ['The first step is the biggest, fastest step of the move — a small first step gives the defender time to recover.', 'Keep the dribble low so it cannot be poked away on the attack.'],
    mistakes: ['Standing tall and dribbling in place before actually attacking a direction.'],
    progressions: [],
    regressions: ['acceleration-wall-drill'],
    substitutes: ['acceleration-wall-drill'],
    defaultDose: { kind: 'reps', sets: 4, reps: 6, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'cut',
    endPose: 'sprint-cycle',
    constraintAxes: ['opposition'],
  },
  {
    slug: 'basketball-approach-and-finish',
    name: 'Approach and Finish at the Rim',
    kind: 'drill',
    sport: 'basketball',
    qualities: { 'vertical-power': 0.9, 'change-of-direction': 0.5, 'landing-mechanics': 0.5 },
    muscles: { 'gluteus-maximus': 0.8, 'vastus-lateralis': 0.8, gastrocnemius: 0.5 },
    equipment: ['ball', 'goal'],
    prop: 'ball-round',
    surface: 'court',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Start at the free-throw line with a ball.'],
    execution: ['Drive toward the basket, gathering the ball smoothly into the last two steps.', 'Take off explosively off one or two feet and finish at the rim.', 'Land balanced under control.'],
    cues: ['The gather happens early — do not palm the ball and take extra steps looking for it.', 'Full extension at takeoff, not a half-hearted jump.'],
    mistakes: ['Decelerating through the gather instead of carrying speed into the takeoff.'],
    progressions: [],
    regressions: ['countermovement-jump'],
    substitutes: ['countermovement-jump'],
    defaultDose: { kind: 'reps', sets: 4, reps: 5, load: 'bodyweight' },
    restSeconds: 75,
    startPose: 'vertical-jump',
    endPose: 'vertical-jump',
    constraintAxes: ['opposition'],
  },
  {
    slug: 'basketball-box-out-drill',
    name: 'Box-Out and Rebound',
    kind: 'drill',
    sport: 'basketball',
    qualities: { 'lower-body-strength': 0.6, 'vertical-power': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-maximus': 0.8, 'vastus-lateralis': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['ball', 'goal', 'partner'],
    prop: 'ball-round',
    surface: 'court',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Pair up facing the basket with a partner behind, ball tossed off the rim or backboard.'],
    execution: ['On the shot, pivot and make contact with the opponent, establishing a wide, low base between them and the basket.', 'Hold the position, then jump to secure the rebound.'],
    cues: ['Find contact first — locate the opponent before the ball ever arrives.', 'Wide stance, low centre of gravity, arms out for width.'],
    mistakes: ['Watching the ball and forgetting to make contact, which lets the opponent go around.'],
    progressions: [],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 5, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'isometric-hold',
    endPose: 'vertical-jump',
    unilateralEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Football
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'football-block-drive',
    name: 'Block Drive',
    kind: 'drill',
    sport: 'football',
    qualities: { 'horizontal-power': 0.9, 'lower-body-strength': 0.7, 'upper-body-push': 0.6 },
    muscles: { 'gluteus-maximus': 0.8, 'vastus-lateralis': 0.7, 'pectoralis-major': 0.5 },
    equipment: ['sled'],
    surface: 'field',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Line up in a three-point or two-point stance in front of a sled or blocking dummy.'],
    execution: ['Fire out low on the snap count, making contact with hands inside and hips low.', 'Drive the legs continuously through contact, keeping the feet moving.'],
    cues: ['Low hat, low pads — the lower player wins the leverage battle.', 'Feet never stop chopping through the drive.'],
    mistakes: ['Standing up out of the stance at contact, giving up all the leverage just gained.'],
    progressions: [],
    regressions: ['sled-push'],
    substitutes: ['sled-push'],
    defaultDose: { kind: 'reps', sets: 5, reps: 3, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'sprint-start',
    endPose: 'horizontal-push',
    unilateralEligible: false,
  },
  {
    slug: 'football-route-break',
    name: 'Route Break',
    kind: 'drill',
    sport: 'football',
    qualities: { 'change-of-direction': 0.9, deceleration: 0.7, acceleration: 0.6 },
    muscles: { 'gluteus-medius': 0.8, 'vastus-lateralis': 0.7, 'biceps-femoris': 0.5 },
    equipment: ['cones'],
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set a cone at the route\'s break point, 8-12 yards from the start.'],
    execution: ['Sprint to the cone at full speed.', 'Plant and cut sharply into the new route direction without rounding the turn.', 'Accelerate away from the break.'],
    cues: ['Attack the cone at full speed — a route run at half speed does not train the actual demand.', 'Plant on the outside foot for an out-cut, inside foot for an in-cut.'],
    mistakes: ['Slowing down well before the cone instead of decelerating hard right at the break point.'],
    progressions: [],
    regressions: ['5-10-5-shuttle'],
    substitutes: ['5-10-5-shuttle'],
    defaultDose: { kind: 'reps', sets: 5, reps: 1, load: 'bodyweight' },
    restSeconds: 75,
    startPose: 'cut',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
  },
  {
    slug: 'football-open-field-tackle',
    name: 'Open-Field Tackling Form',
    kind: 'drill',
    sport: 'football',
    qualities: { deceleration: 0.8, 'lower-body-strength': 0.6, 'trunk-anti-rotation': 0.5 },
    muscles: { 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.7, 'rectus-abdominis': 0.5 },
    equipment: ['partner'],
    surface: 'field',
    minAge: 15,
    supervisionLevel: 'COACHED',
    setup: ['Set up a marked lane with a partner or coach acting as a slow-moving ball carrier.'],
    execution: ['Close the distance under control, breaking down into a low, balanced position a step before contact.', 'Drive through with the shoulder across the near hip, wrapping the arms and finishing the feet through contact.'],
    cues: ['Break down before contact — do not arrive at full uncontrolled speed.', 'Eyes up, head across, not down and leading with the crown.'],
    mistakes: ['Lunging at the legs from too far away instead of breaking down and closing the distance under control.'],
    progressions: [],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 4, load: 'bodyweight, coached' },
    restSeconds: 90,
    startPose: 'deceleration-plant',
    endPose: 'isometric-hold',
    unilateralEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Baseball
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'baseball-tee-work-rotational-power',
    name: 'Tee Work for Rotational Power',
    kind: 'drill',
    sport: 'baseball',
    qualities: { 'rotational-power': 1.0, 'trunk-anti-rotation': 0.4 },
    muscles: { 'obliques-external': 0.9, 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['bat', 'ball'],
    prop: 'bat',
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set a batting tee at belt height in a normal batting stance.'],
    execution: ['Load by turning the hips and shoulders away from the tee.', 'Rotate explosively, driving the hips first and letting the hands follow, striking through the ball.'],
    cues: ['Hips open before the hands — a bat that starts moving before the hips do loses most of its power.', 'Finish the swing fully; do not decelerate through contact.'],
    mistakes: ['Swinging with the arms and shoulders while the hips stay closed and passive.'],
    progressions: [],
    regressions: ['rotational-step-through-throw'],
    substitutes: ['rotational-step-through-throw', 'med-ball-rotational-throw'],
    defaultDose: { kind: 'reps', sets: 4, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'swing-stride',
    endPose: 'swing-stride',
    unilateralEligible: false,
  },
  {
    slug: 'baseball-pitching-mound-mechanics',
    name: 'Pitching Mound Mechanics',
    kind: 'drill',
    sport: 'baseball',
    qualities: { 'overhead-power': 1.0, 'shoulder-stability': 0.8, 'hip-mobility': 0.5 },
    muscles: { 'deltoid-anterior': 0.7, 'obliques-external': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['ball'],
    surface: 'field',
    minAge: 15,
    supervisionLevel: 'COACHED',
    setup: ['Start from the pitching rubber or a flat-ground mark, ball in glove.'],
    execution: ['Leg lift and controlled stride toward the target, hips leading the throwing arm.', 'Sequence trunk rotation before arm acceleration, releasing out front and following through down the target line.'],
    cues: ['Stride length and direction stay consistent rep to rep — inconsistency here is where most control problems start.', 'Arm follows the body\'s rotation; it should never feel like it is racing ahead of the hips.'],
    mistakes: ['Rushing the stride so the arm has to catch up, which strips efficiency and adds arm stress.'],
    progressions: [],
    regressions: ['rotational-step-through-throw'],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 8, load: 'bodyweight, coached' },
    restSeconds: 60,
    startPose: 'overhead-throw',
    endPose: 'overhead-throw',
    unilateralEligible: false,
  },
  {
    slug: 'baseball-infield-first-step-reaction',
    name: 'Infield First-Step Reaction',
    kind: 'drill',
    sport: 'baseball',
    qualities: { 'reactive-strength': 0.8, acceleration: 0.7, 'single-leg-stability': 0.5 },
    muscles: { 'gluteus-medius': 0.8, 'vastus-lateralis': 0.6, 'gluteus-maximus': 0.6 },
    equipment: ['ball', 'partner'],
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Athletic ready position, a partner rolls or hits ground balls to either side without warning.'],
    execution: ['React to the ball\'s direction with an explosive first step and crossover.', 'Field the ball in a balanced position and reset to ready for the next rep.'],
    cues: ['The first movement is a push off the outside foot, not a false step in the wrong direction.', 'Stay light on the feet in the ready position — flat, heavy feet react slowly.'],
    mistakes: ['A false step away from the ball before redirecting, which costs valuable reaction time.'],
    progressions: [],
    regressions: [],
    substitutes: ['lateral-bound', 'shadow-cutting-drill'],
    defaultDose: { kind: 'reps', sets: 4, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'lateral-shuffle',
    endPose: 'lateral-shuffle',
    constraintAxes: ['movement'],
  },
];
