/**
 * Base exercises — §7: general physical preparation, sport-agnostic, selected
 * by quality. Hand-authored once each; `expand.js` derives equipment,
 * unilateral, and tempo variants from what is declared here.
 *
 * §7's completeness test requires every one of the 23 qualities to have at
 * least one bodyweight-only (equipment ['none']) item at weight ≥ 0.5. Most
 * items here get there via their own `equipmentChain` reaching a bodyweight
 * tier (the elegant case — one authored item, the bodyweight version is a
 * derivative); a handful of qualities have no meaningful loaded version at
 * all and are authored bodyweight-only outright (marked below).
 *
 * §2's NSCA-cited youth envelope governs every dose here: 1-3 sets, 6-15 reps
 * for strength work, technique before load, no COACHED item below minAge 15,
 * and `defaultDose.load` is always a plain description ("light", "moderate"),
 * never a percentage of 1RM.
 */

export const EXERCISES = [

  // ═══════════════════════════════════════════════════════════════════════
  // Speed
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'acceleration-wall-drill',
    name: 'Acceleration Wall Drill',
    kind: 'exercise',
    qualities: { acceleration: 1.0, 'ankle-stiffness': 0.5 },
    muscles: { 'gluteus-maximus': 0.8, gastrocnemius: 0.6, 'rectus-femoris': 0.5 },
    equipment: ['wall'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Lean into a wall at about 45 degrees, hands at shoulder height, body a straight line from head to back ankle.'],
    execution: [
      'Drive one knee up to hip height while the other leg stays extended behind, foot dorsiflexed.',
      'Switch legs with a sharp, piston-like action, keeping the front-side knee drive quick.',
    ],
    cues: ['Shin drives forward, not the foot kicking back.', 'Stay tall through the hips — no sagging at the waist.'],
    mistakes: ['Bending at the waist instead of leaning as one straight line from the wall.'],
    progressions: ['sled-push'],
    regressions: ['acceleration-march'],
    substitutes: ['acceleration-march'],
    defaultDose: { kind: 'time', sets: 3, seconds: 20, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'acceleration-march',
    name: 'Acceleration March',
    kind: 'exercise',
    qualities: { acceleration: 0.6, 'ankle-stiffness': 0.4 },
    muscles: { 'gluteus-maximus': 0.6, gastrocnemius: 0.5, 'rectus-femoris': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand tall in a slight forward lean from the ankles.'],
    execution: ['March forward driving the knee to hip height on each step, punching the foot down under the hip.', 'Keep the lean and rhythm consistent step to step.'],
    cues: ['Strike the ground under the hip, not out in front.', 'Stay tall through the torso rather than bending at the waist.'],
    mistakes: ['Reaching the foot out in front on landing, which brakes forward momentum instead of building it.'],
    progressions: ['acceleration-wall-drill'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'distance', sets: 3, metres: 15, load: 'bodyweight' },
    restSeconds: 45,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'sled-push',
    name: 'Sled Push',
    kind: 'exercise',
    qualities: { acceleration: 1.0, 'horizontal-power': 0.6, 'lower-body-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.9, 'vastus-lateralis': 0.7, gastrocnemius: 0.5 },
    equipment: ['sled'],
    surface: 'field',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Load the sled lightly. Set hands on the uprights, arms mostly extended, shoulders over hands.'],
    execution: ['Drive forward in short, powerful steps, staying low through the first 5-10 steps like a sprint start.', 'Accelerate over 15-20 metres.'],
    cues: ['Push the ground away, not just the sled.', 'Full extension at the back of each step.'],
    mistakes: ['Standing up too early and losing the forward lean.'],
    progressions: ['flying-sprint'],
    regressions: ['acceleration-wall-drill'],
    substitutes: ['broad-jump'],
    defaultDose: { kind: 'distance', sets: 4, metres: 20, load: 'light' },
    restSeconds: 90,
    startPose: 'sprint-start',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'flying-sprint',
    name: 'Flying Sprint',
    kind: 'exercise',
    qualities: { 'max-velocity': 1.0, 'reactive-strength': 0.5 },
    muscles: { 'biceps-femoris': 0.8, gastrocnemius: 0.7, 'gluteus-maximus': 0.7 },
    equipment: ['none'],
    surface: 'track',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Mark a 20-metre build-up zone and a 20-metre timed/effort zone.'],
    execution: ['Build up gradually over the first 20 metres to reach top speed exactly as you enter the effort zone.', 'Hold relaxed top-speed mechanics through the effort zone.'],
    cues: ['Relax the face and hands — tension anywhere slows you down.', 'Tall posture, quick ground contacts.'],
    mistakes: ['Trying to accelerate maximally from the very first step instead of building in.'],
    progressions: [],
    regressions: ['acceleration-wall-drill'],
    substitutes: [],
    defaultDose: { kind: 'distance', sets: 4, metres: 20, load: 'bodyweight' },
    restSeconds: 180,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'lateral-shuffle-cone-drill',
    name: 'Lateral Shuffle Cone Drill',
    kind: 'exercise',
    qualities: { 'change-of-direction': 1.0, 'lateral-power': 0.6 },
    muscles: { 'gluteus-medius': 0.8, 'adductors': 0.6, 'vastus-lateralis': 0.5 },
    equipment: ['cones'],
    surface: 'court',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set two cones 5 metres apart.'],
    execution: ['Shuffle laterally between the cones staying low, touching each cone with the outside hand.', 'Keep the chest facing forward the entire time.'],
    cues: ['Stay low — hips below shoulders.', 'Push off the trail leg, do not let the feet cross.'],
    mistakes: ['Standing up tall between reps, which slows the change of direction.'],
    progressions: ['5-10-5-shuttle'],
    regressions: [],
    substitutes: ['lateral-bound'],
    defaultDose: { kind: 'time', sets: 4, seconds: 15, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'lateral-shuffle',
    endPose: 'lateral-shuffle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: '5-10-5-shuttle',
    name: '5-10-5 Pro Agility Shuttle',
    kind: 'exercise',
    qualities: { 'change-of-direction': 1.0, deceleration: 0.7, acceleration: 0.5 },
    muscles: { 'gluteus-medius': 0.8, 'vastus-lateralis': 0.7, 'adductors': 0.5 },
    equipment: ['cones'],
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set three cones in a line, 5 yards apart.'],
    execution: ['From the middle cone, sprint 5 yards to one side and touch the line.', 'Sprint 10 yards to the far cone and touch.', 'Sprint 5 yards back through the start.'],
    cues: ['Plant hard and low on each direction change.', 'Keep the first step after the plant short and explosive.'],
    mistakes: ['Rounding the turns instead of planting sharply.'],
    progressions: [],
    regressions: ['lateral-shuffle-cone-drill'],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 1, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'cut',
    endPose: 'cut',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'lateral-bound',
    name: 'Lateral Bound',
    kind: 'exercise',
    qualities: { 'lateral-power': 1.0, 'single-leg-stability': 0.6, 'reactive-strength': 0.5 },
    muscles: { 'gluteus-medius': 0.9, 'vastus-lateralis': 0.6, 'gluteus-maximus': 0.6 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand on one leg, knee slightly bent.'],
    execution: ['Push explosively sideways off the stance leg.', 'Land softly on the opposite leg and stick the landing for a full second before the next rep.'],
    cues: ['Land quietly — absorb through the hip and knee.', 'Full stick before bounding back.'],
    mistakes: ['Landing stiff-legged, which sends the impact straight into the knee.'],
    progressions: ['5-10-5-shuttle'],
    regressions: ['lateral-shuffle-cone-drill'],
    substitutes: ['lateral-shuffle-cone-drill'],
    defaultDose: { kind: 'contacts', sets: 3, contacts: 6, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'lateral-bound',
    endPose: 'lateral-bound',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'deceleration-drop-stick',
    name: 'Deceleration Drop and Stick',
    kind: 'exercise',
    qualities: { deceleration: 1.0, 'landing-mechanics': 0.6, 'single-leg-stability': 0.4 },
    muscles: { 'vastus-lateralis': 0.8, 'gluteus-maximus': 0.7, 'biceps-femoris': 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Start in a light jog, three to five steps of run-up.'],
    execution: ['Accelerate for three steps, then decelerate as fast as possible over two steps to a dead stop.', 'Hold the stopped position for two full seconds.'],
    cues: ['Get low and wide on the last step — do not try to stop on tall legs.', 'Shins stay roughly vertical at the stop, not way out in front.'],
    mistakes: ['Taking too many steps to stop, which does not train the braking quality at all.'],
    progressions: ['shadow-cutting-drill'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 4, reps: 4, load: 'bodyweight' },
    restSeconds: 75,
    startPose: 'deceleration-plant',
    endPose: 'deceleration-plant',
    unilateralEligible: false,
    tempoEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Power
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'countermovement-jump',
    name: 'Countermovement Jump',
    kind: 'exercise',
    qualities: { 'vertical-power': 1.0, 'landing-mechanics': 0.5 },
    muscles: { 'gluteus-maximus': 0.9, 'vastus-lateralis': 0.8, gastrocnemius: 0.6 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand tall, feet hip-width.'],
    execution: ['Dip quickly to about a quarter squat, arms swinging back.', 'Reverse immediately and jump as high as possible, swinging the arms up.', 'Land softly with bent knees.'],
    cues: ['Minimise the pause at the bottom of the dip.', 'Reach tall in the air.'],
    mistakes: ['Pausing at the bottom, which turns a reactive jump into a slow squat jump.'],
    progressions: ['weighted-jump-squat'],
    regressions: [],
    substitutes: ['broad-jump'],
    defaultDose: { kind: 'reps', sets: 4, reps: 5, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'vertical-jump',
    endPose: 'vertical-jump',
    unilateralEligible: true,
    unilateralPosePattern: 'bound',
    unilateralStabilityQuality: 'single-leg-stability',
    tempoEligible: true,
  },
  {
    slug: 'weighted-jump-squat',
    name: 'Weighted Jump Squat',
    kind: 'exercise',
    qualities: { 'vertical-power': 1.0, 'lower-body-strength': 0.5 },
    muscles: { 'gluteus-maximus': 0.9, 'vastus-lateralis': 0.8 },
    equipment: ['dumbbell'],
    surface: 'gym',
    minAge: 15,
    supervisionLevel: 'SELF',
    setup: ['Hold a light dumbbell in each hand at the sides.'],
    execution: ['Squat to about a quarter depth.', 'Jump as high as possible, keeping the dumbbells at the sides throughout.', 'Land softly and reset.'],
    cues: ['Light load — this is about speed, not how much weight moves.', 'Keep the dumbbells pinned to the sides; do not let them swing forward.'],
    mistakes: ['Using so much load that the jump becomes slow; the whole point is bar (or dumbbell) speed.'],
    progressions: [],
    regressions: ['countermovement-jump'],
    substitutes: ['countermovement-jump'],
    defaultDose: { kind: 'reps', sets: 4, reps: 5, load: 'light' },
    restSeconds: 120,
    startPose: 'vertical-jump',
    endPose: 'vertical-jump',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'broad-jump',
    name: 'Standing Broad Jump',
    kind: 'exercise',
    qualities: { 'horizontal-power': 1.0, 'landing-mechanics': 0.5 },
    muscles: { 'gluteus-maximus': 0.9, 'biceps-femoris': 0.7, 'vastus-lateralis': 0.7 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand at a marked line, feet hip-width.'],
    execution: ['Swing the arms back and dip.', 'Drive forward and up explosively, extending fully at the hips.', 'Land with both feet together, absorbing through the hips and knees.'],
    cues: ['Full hip extension at takeoff — finish the jump tall.', 'Land in one piece, not falling forward.'],
    mistakes: ['Stopping the jump short by landing off-balance and stepping forward to catch yourself.'],
    progressions: ['flying-sprint'],
    regressions: [],
    substitutes: ['countermovement-jump'],
    defaultDose: { kind: 'reps', sets: 4, reps: 4, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'broad-jump',
    endPose: 'broad-jump',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'rotational-step-through-throw',
    name: 'Rotational Step-Through Throw',
    kind: 'exercise',
    qualities: { 'rotational-power': 1.0, 'trunk-anti-rotation': 0.4 },
    muscles: { 'obliques-external': 0.9, 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand side-on to the target direction, hands together at the hip.'],
    execution: ['Step through with the back foot, rotating the hips and torso together.', 'Drive the arms across the body explosively as if releasing a throw, finishing facing the target.'],
    cues: ['Hips lead, hands follow — the rotation starts at the ground.', 'Finish tall and facing the target, not falling sideways.'],
    mistakes: ['Rotating only the arms and shoulders while the hips stay square.'],
    progressions: ['med-ball-rotational-throw'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 3, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'rotational-throw',
    endPose: 'rotational-throw',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'med-ball-rotational-throw',
    name: 'Medicine Ball Rotational Throw',
    kind: 'exercise',
    qualities: { 'rotational-power': 1.0, 'trunk-anti-rotation': 0.5 },
    muscles: { 'obliques-external': 0.9, 'gluteus-maximus': 0.6, 'rectus-abdominis': 0.5 },
    equipment: ['med-ball', 'wall'],
    surface: 'gym',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand side-on to a solid wall, about an arm\'s length plus a stride away, holding a medicine ball at the hip.'],
    execution: ['Rotate away from the wall to load, then explosively rotate back and release the ball into the wall at chest-to-hip height.', 'Catch the rebound and reset.'],
    cues: ['Let the hips start the rotation before the arms.', 'Release at the same point in the rotation every rep for consistency.'],
    mistakes: ['Standing too square to the wall so the throw becomes a chest pass instead of a rotation.'],
    progressions: [],
    regressions: ['rotational-step-through-throw'],
    substitutes: ['rotational-step-through-throw'],
    defaultDose: { kind: 'reps', sets: 4, reps: 6, load: 'light' },
    restSeconds: 75,
    startPose: 'rotational-throw',
    endPose: 'rotational-throw',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'explosive-wall-reach-jump',
    name: 'Explosive Wall Reach Jump',
    kind: 'exercise',
    qualities: { 'overhead-power': 1.0, 'vertical-power': 0.6, 'shoulder-stability': 0.3 },
    muscles: { 'deltoid-anterior': 0.7, 'gluteus-maximus': 0.7, 'vastus-lateralis': 0.6 },
    equipment: ['wall'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand facing a wall with a visible mark or reach point above your highest standing reach.'],
    execution: ['Dip into a quarter squat, then jump explosively while driving both arms straight overhead to touch as high as possible.', 'Land softly and reset.'],
    cues: ['Drive the arms up as hard as the legs drive down — this is a whole-body extension, not just a jump with your arms up.', 'Touch the same spot every rep so improvement is visible.'],
    mistakes: ['Raising the arms slowly and only using leg drive; the overhead arm speed is the point of the exercise.'],
    progressions: ['med-ball-overhead-throw'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 3, reps: 5, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'vertical-jump',
    endPose: 'overhead-throw',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'med-ball-overhead-throw',
    name: 'Medicine Ball Overhead Throw',
    kind: 'exercise',
    qualities: { 'overhead-power': 1.0, 'trunk-anti-rotation': 0.4 },
    muscles: { 'deltoid-anterior': 0.7, 'rectus-abdominis': 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['med-ball'],
    surface: 'field',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand facing open space, holding a medicine ball overhead with both hands.'],
    execution: ['Arch slightly at the hips and shoulders to load, then throw the ball forward and down explosively, finishing in a slight forward fold.', 'Retrieve the ball and reset the stance before the next rep.'],
    cues: ['Whole body extends before the throw, then whips forward together.', 'Let the ball go early rather than holding on and slowing the throw.'],
    mistakes: ['Throwing only with the arms without loading the hips first.'],
    progressions: [],
    regressions: ['explosive-wall-reach-jump'],
    substitutes: ['explosive-wall-reach-jump'],
    defaultDose: { kind: 'reps', sets: 4, reps: 5, load: 'light' },
    restSeconds: 75,
    startPose: 'overhead-throw',
    endPose: 'trunk-flexion',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'pogo-hop',
    name: 'Pogo Hop',
    kind: 'exercise',
    qualities: { 'reactive-strength': 1.0, 'ankle-stiffness': 0.7 },
    muscles: { gastrocnemius: 0.9, soleus: 0.7, 'tibialis-anterior': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand tall, feet together.'],
    execution: ['Hop in place using mostly the ankles, keeping the knees almost straight.', 'Spend as little time on the ground as possible each contact.'],
    cues: ['Stiff ankle, quiet quick contacts — think of a bouncing ball, not a squat jump.', 'Minimal knee bend.'],
    mistakes: ['Using the knees and hips to jump instead of the ankles, which turns this into a different exercise entirely.'],
    progressions: ['single-leg-ankle-hop'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'contacts', sets: 3, contacts: 15, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'pogo',
    endPose: 'pogo',
    unilateralEligible: false,
    tempoEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Strength
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'trap-bar-deadlift',
    name: 'Trap-Bar Deadlift',
    kind: 'exercise',
    qualities: { 'lower-body-strength': 1.0, grip: 0.5, 'trunk-anti-rotation': 0.3 },
    muscles: { 'gluteus-maximus': 1.0, 'erector-spinae': 0.7, 'vastus-lateralis': 0.6 },
    equipment: ['trap-bar', 'weight-plate'],
    surface: 'gym',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Stand inside the trap bar, feet hip-width, shins close to the handles.'],
    execution: ['Hinge at the hips and bend the knees to grip the handles, chest up, back flat.', 'Drive through the floor to stand tall, hips and knees finishing together.', 'Lower under control by reversing the motion.'],
    cues: ['Push the floor away — think leg press, not back lift.', 'Keep the bar close to the body the whole way up.'],
    mistakes: ['Letting the hips shoot up first, turning the lift into a stiff-legged pull.'],
    progressions: [],
    regressions: [],
    substitutes: ['single-leg-rdl'],
    defaultDose: { kind: 'reps', sets: 3, reps: 6, load: 'moderate' },
    restSeconds: 120,
    startPose: 'hinge',
    endPose: 'hinge',
    equipmentChain: [
      { tier: 'trap-bar', label: 'trap bar', equipment: ['trap-bar', 'weight-plate'] },
      { tier: 'dumbbell', label: 'dumbbell', equipment: ['dumbbell'] },
      { tier: 'band', label: 'band', equipment: ['band'] },
      { tier: 'bodyweight', label: 'bodyweight squat', equipment: ['none'] },
    ],
    unilateralEligible: true,
    unilateralPosePattern: 'single-leg-rdl',
    unilateralStabilityQuality: 'single-leg-stability',
    tempoEligible: true,
  },
  {
    slug: 'goblet-squat',
    name: 'Goblet Squat',
    kind: 'exercise',
    qualities: { 'lower-body-strength': 1.0, 'hip-mobility': 0.4 },
    muscles: { 'vastus-lateralis': 0.9, 'gluteus-maximus': 0.8, 'rectus-femoris': 0.6 },
    equipment: ['dumbbell'],
    surface: 'gym',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Hold a dumbbell vertically at chest height with both hands.'],
    execution: ['Squat down, keeping the chest up and elbows brushing the inside of the knees at the bottom.', 'Drive back up through the whole foot.'],
    cues: ['Knees track over the toes, not caving in.', 'Sit down and back, not straight down.'],
    mistakes: ['Heels lifting off the floor at the bottom.'],
    progressions: ['barbell-back-squat'],
    regressions: ['bodyweight-squat'],
    substitutes: ['bodyweight-squat', 'trap-bar-deadlift'],
    defaultDose: { kind: 'reps', sets: 3, reps: 10, load: 'moderate' },
    restSeconds: 90,
    startPose: 'squat',
    endPose: 'squat',
    equipmentChain: [
      { tier: 'dumbbell', label: 'dumbbell', equipment: ['dumbbell'] },
      { tier: 'band', label: 'band-resisted', equipment: ['band'] },
      { tier: 'bodyweight', label: 'bodyweight', equipment: ['none'] },
    ],
    unilateralEligible: true,
    unilateralPosePattern: 'split-squat',
    unilateralStabilityQuality: 'single-leg-stability',
    tempoEligible: true,
  },
  {
    slug: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    kind: 'exercise',
    qualities: { 'lower-body-strength': 1.0, 'trunk-anti-rotation': 0.3 },
    muscles: { 'vastus-lateralis': 1.0, 'gluteus-maximus': 0.9, 'erector-spinae': 0.5 },
    equipment: ['barbell', 'rack'],
    surface: 'gym',
    minAge: 15,
    supervisionLevel: 'COACHED',
    setup: ['Set the bar in the rack at upper-chest height.', 'Step under the bar, position it across the upper back, and unrack with a confirmed spotter or safety pins set.'],
    execution: ['Squat down under control to at least parallel, keeping the chest up.', 'Drive back up through the whole foot.'],
    cues: ['Brace the trunk before descending — breathe in, brace, then squat.', 'Knees track in line with the toes.'],
    mistakes: ['Losing the neutral spine and rounding the lower back under load.'],
    progressions: [],
    regressions: ['goblet-squat'],
    substitutes: ['goblet-squat', 'trap-bar-deadlift'],
    defaultDose: { kind: 'reps', sets: 3, reps: 6, load: 'moderate, coached' },
    restSeconds: 150,
    startPose: 'squat',
    endPose: 'squat',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    kind: 'exercise',
    qualities: { 'lower-body-strength': 0.9, 'single-leg-stability': 0.7, 'hip-mobility': 0.3 },
    muscles: { 'vastus-lateralis': 0.9, 'gluteus-maximus': 0.8, 'gluteus-medius': 0.5 },
    equipment: ['bench'],
    surface: 'gym',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Stand two to three feet in front of a bench, rest the top of the rear foot on it.'],
    execution: ['Lower straight down until the front thigh is roughly parallel to the floor.', 'Drive back up through the front foot to standing.'],
    cues: ['Keep most of the weight in the front leg — the back foot is just for balance.', 'Torso stays fairly upright, not folding forward.'],
    mistakes: ['Letting the front knee drift far past the toes and the heel come up.'],
    progressions: [],
    regressions: ['split-squat'],
    substitutes: ['split-squat', 'goblet-squat'],
    defaultDose: { kind: 'reps', sets: 3, reps: 8, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'split-squat',
    endPose: 'split-squat',
    equipmentChain: [
      { tier: 'dumbbell', label: 'loaded', equipment: ['dumbbell', 'bench'] },
      { tier: 'bodyweight', label: 'bodyweight', equipment: ['bench'] },
    ],
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'split-squat',
    name: 'Split Squat',
    kind: 'exercise',
    qualities: { 'lower-body-strength': 0.6, 'single-leg-stability': 0.6 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand in a long split stance, both feet flat on the floor.'],
    execution: ['Lower straight down until the back knee lightly touches or hovers just above the floor.', 'Drive back up to the start.'],
    cues: ['Keep the torso upright throughout.', 'Front knee tracks in line with the foot.'],
    mistakes: ['Taking too short a stance, which crowds the front knee at the bottom.'],
    progressions: ['bulgarian-split-squat'],
    regressions: [],
    substitutes: ['bulgarian-split-squat'],
    defaultDose: { kind: 'reps', sets: 3, reps: 10, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'split-squat',
    endPose: 'split-squat',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    kind: 'exercise',
    qualities: { deceleration: 1.0, 'lower-body-strength': 0.4 },
    muscles: { 'biceps-femoris': 1.0, semitendinosus: 0.8, semimembranosus: 0.8 },
    equipment: ['partner'],
    surface: 'gym',
    minAge: 15,
    supervisionLevel: 'COACHED',
    setup: ['Kneel on a padded surface, ankles held firmly by a partner (or anchored under a low bar).'],
    execution: ['Lean forward from the knees as slowly as possible, resisting with the hamstrings the whole way.', 'Catch yourself with the hands at the bottom and push back up, or reset with the hands.'],
    cues: ['The entire value of the exercise is in slowing the descent — do not just let gravity take you down.', 'Keep the hips extended; do not bend at the waist.'],
    mistakes: ['Dropping quickly instead of controlling the lowering phase, which is the whole point of the exercise.'],
    progressions: [],
    regressions: ['single-leg-rdl'],
    substitutes: ['single-leg-rdl'],
    defaultDose: { kind: 'reps', sets: 3, reps: 6, load: 'bodyweight, coached' },
    restSeconds: 90,
    startPose: 'isometric-hold',
    endPose: 'trunk-flexion',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    kind: 'exercise',
    qualities: { 'lower-body-strength': 0.6, 'hip-mobility': 0.5 },
    muscles: { 'vastus-lateralis': 0.7, 'gluteus-maximus': 0.6 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand with feet shoulder-width, toes slightly out.'],
    execution: ['Squat down as low as comfortable while keeping the heels down and chest up.', 'Stand back up through the whole foot.'],
    cues: ['Knees track over the toes.', 'Keep the weight balanced through the middle of the foot.'],
    mistakes: ['Letting the knees collapse inward on the way up.'],
    progressions: ['goblet-squat'],
    regressions: [],
    substitutes: ['goblet-squat'],
    defaultDose: { kind: 'reps', sets: 3, reps: 15, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'squat',
    endPose: 'squat',
    unilateralEligible: true,
    unilateralPosePattern: 'split-squat',
    unilateralStabilityQuality: 'single-leg-stability',
    tempoEligible: true,
  },
  {
    slug: 'push-up',
    name: 'Push-Up',
    kind: 'exercise',
    qualities: { 'upper-body-push': 1.0, 'trunk-anti-rotation': 0.4 },
    muscles: { 'pectoralis-major': 0.9, 'triceps-brachii': 0.7, 'rectus-abdominis': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Hands slightly wider than shoulders, body in a straight line from head to heels.'],
    execution: ['Lower the chest to just above the floor, elbows at roughly 45 degrees from the torso.', 'Press back up to full arm extension.'],
    cues: ['Keep the hips in line — no sagging or piking.', 'Full lockout at the top.'],
    mistakes: ['Letting the hips sag, which turns the exercise into a lower-back stretch instead of a press.'],
    progressions: ['bench-press'],
    regressions: ['incline-push-up'],
    substitutes: ['bench-press'],
    defaultDose: { kind: 'reps', sets: 3, reps: 12, load: 'bodyweight' },
    restSeconds: 75,
    startPose: 'horizontal-push',
    endPose: 'horizontal-push',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'bench-press',
    name: 'Bench Press',
    kind: 'exercise',
    qualities: { 'upper-body-push': 1.0 },
    muscles: { 'pectoralis-major': 1.0, 'triceps-brachii': 0.7, 'deltoid-anterior': 0.5 },
    equipment: ['barbell', 'bench', 'rack'],
    surface: 'gym',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Lie on the bench, eyes under the bar, feet flat on the floor, shoulder blades pulled back and down.'],
    execution: ['Unrack and lower the bar under control to the chest.', 'Press back up to full arm extension.'],
    cues: ['Keep the shoulder blades pinned the whole rep — do not let them roll forward at the top.', 'Bar path is a slight arc, not straight up and down.'],
    mistakes: ['Bouncing the bar off the chest instead of controlling the descent.'],
    progressions: [],
    regressions: ['push-up'],
    substitutes: ['push-up'],
    defaultDose: { kind: 'reps', sets: 3, reps: 8, load: 'moderate' },
    restSeconds: 120,
    startPose: 'horizontal-push',
    endPose: 'horizontal-push',
    equipmentChain: [
      { tier: 'barbell', label: 'barbell', equipment: ['barbell', 'bench', 'rack'] },
      { tier: 'dumbbell', label: 'dumbbell', equipment: ['dumbbell', 'bench'] },
      { tier: 'band', label: 'band', equipment: ['band'] },
      { tier: 'bodyweight', label: 'push-up', equipment: ['none'] },
    ],
    unilateralEligible: true,
    unilateralPosePattern: 'horizontal-push',
    unilateralStabilityQuality: 'trunk-anti-rotation',
    tempoEligible: true,
  },
  {
    slug: 'incline-push-up',
    name: 'Incline Push-Up',
    kind: 'exercise',
    qualities: { 'upper-body-push': 0.6 },
    muscles: { 'pectoralis-major': 0.7, 'triceps-brachii': 0.5 },
    equipment: ['bench'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Hands on a bench or step, body in a straight line, feet on the floor.'],
    execution: ['Lower the chest to the edge of the bench.', 'Press back up to full extension.'],
    cues: ['Keep the hips in line with the shoulders and ankles.', 'The higher the incline, the easier the rep — pick a height that challenges the last few reps of the set.'],
    mistakes: ['Placing hands too low on the incline, taking away too much of the challenge.'],
    progressions: ['push-up'],
    regressions: [],
    substitutes: ['push-up'],
    defaultDose: { kind: 'reps', sets: 3, reps: 12, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'horizontal-push',
    endPose: 'horizontal-push',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'pull-up',
    name: 'Pull-Up',
    kind: 'exercise',
    qualities: { 'upper-body-pull': 1.0, grip: 0.5 },
    muscles: { 'latissimus-dorsi': 1.0, 'biceps-brachii': 0.7, 'trapezius-middle': 0.5 },
    equipment: ['pull-up-bar'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Hang from the bar with an overhand grip, slightly wider than shoulders.'],
    execution: ['Pull up until the chin clears the bar.', 'Lower back to a full hang under control.'],
    cues: ['Lead with the chest, not the chin.', 'Full extension at the bottom every rep.'],
    mistakes: ['Kipping or swinging to generate momentum instead of pulling strictly.'],
    progressions: [],
    regressions: ['band-assisted-pull-up'],
    substitutes: ['band-assisted-pull-up', 'inverted-row'],
    defaultDose: { kind: 'reps', sets: 3, reps: 6, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'vertical-pull',
    endPose: 'vertical-pull',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'band-assisted-pull-up',
    name: 'Band-Assisted Pull-Up',
    kind: 'exercise',
    qualities: { 'upper-body-pull': 0.6, grip: 0.4 },
    muscles: { 'latissimus-dorsi': 0.8, 'biceps-brachii': 0.5 },
    equipment: ['pull-up-bar', 'band'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Loop a resistance band over the bar and place a foot or knee in the loop.'],
    execution: ['Pull up until the chin clears the bar, letting the band assist.', 'Lower under control to a full hang.'],
    cues: ['Use the lightest band that still lets you complete every rep with good form.', 'Still lead with the chest, the same as an unassisted pull-up.'],
    mistakes: ['Using so much band assistance that the exercise stops training pulling strength at all.'],
    progressions: ['pull-up'],
    regressions: ['inverted-row'],
    substitutes: ['inverted-row'],
    defaultDose: { kind: 'reps', sets: 3, reps: 8, load: 'assisted' },
    restSeconds: 75,
    startPose: 'vertical-pull',
    endPose: 'vertical-pull',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'inverted-row',
    name: 'Inverted Row',
    kind: 'exercise',
    qualities: { 'upper-body-pull': 1.0, 'trunk-anti-rotation': 0.4 },
    muscles: { 'latissimus-dorsi': 0.9, 'trapezius-middle': 0.7, 'rhomboids': 0.6 },
    equipment: ['low-bar'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Set a bar at waist height (a squat rack bar, a sturdy table edge, or suspension straps all work). Lie underneath, gripping the bar, body straight, heels on the ground.'],
    execution: ['Pull the chest to the bar, keeping the body rigid from head to heels.', 'Lower back to full arm extension under control.'],
    cues: ['Squeeze the shoulder blades together at the top.', 'The more horizontal the body, the harder the row — raise the feet or lower the bar to add difficulty.'],
    mistakes: ['Letting the hips sag toward the floor instead of keeping a straight plank line.'],
    progressions: ['pull-up'],
    regressions: [],
    substitutes: ['pull-up', 'band-assisted-pull-up'],
    defaultDose: { kind: 'reps', sets: 3, reps: 10, load: 'bodyweight' },
    restSeconds: 75,
    startPose: 'horizontal-pull',
    endPose: 'horizontal-pull',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'prone-y-t-w-raise',
    name: 'Prone Y-T-W Raise',
    kind: 'exercise',
    qualities: { 'upper-body-pull': 0.5, 'shoulder-stability': 0.9 },
    muscles: { 'trapezius-lower': 0.9, 'trapezius-middle': 0.7, 'deltoid-posterior': 0.6, 'rhomboids': 0.6 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Lie face down, forehead supported, arms extended in front.'],
    execution: ['Raise the arms into a Y shape and hold briefly.', 'Lower, then raise into a T shape and hold.', 'Lower, then raise into a W shape (elbows bent, squeezing the shoulder blades) and hold.'],
    cues: ['Small range, strict control — this is about the shoulder blades, not how high the hands go.', 'Keep the neck relaxed, forehead down.'],
    mistakes: ['Shrugging the shoulders up toward the ears instead of drawing the blades down and together.'],
    progressions: ['band-pull-apart'],
    regressions: [],
    substitutes: ['band-pull-apart'],
    defaultDose: { kind: 'reps', sets: 3, reps: 8, load: 'bodyweight' },
    restSeconds: 45,
    startPose: 'horizontal-pull',
    endPose: 'horizontal-pull',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'band-pull-apart',
    name: 'Band Pull-Apart',
    kind: 'exercise',
    qualities: { 'upper-body-pull': 0.6, 'shoulder-stability': 0.7 },
    muscles: { 'trapezius-middle': 0.8, 'deltoid-posterior': 0.7, 'rhomboids': 0.6 },
    equipment: ['band'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Hold a light resistance band at shoulder height, arms extended in front, shoulder-width grip.'],
    execution: ['Pull the band apart by drawing the arms out to the sides, squeezing the shoulder blades together.', 'Return under control.'],
    cues: ['Keep the arms nearly straight throughout.', 'Lead with the shoulder blades, not the hands.'],
    mistakes: ['Bending the elbows to make the band easier, which shifts the work away from the upper back.'],
    progressions: [],
    regressions: ['prone-y-t-w-raise'],
    substitutes: ['prone-y-t-w-raise'],
    defaultDose: { kind: 'reps', sets: 3, reps: 15, load: 'light' },
    restSeconds: 45,
    startPose: 'horizontal-pull',
    endPose: 'horizontal-pull',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'plank-shoulder-tap',
    name: 'Plank Shoulder Tap',
    kind: 'exercise',
    qualities: { 'trunk-anti-rotation': 1.0, 'shoulder-stability': 0.4 },
    muscles: { 'rectus-abdominis': 0.8, 'obliques-external': 0.8, 'deltoid-anterior': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['High plank position, hands under shoulders, feet a little wider than hip-width for stability.'],
    execution: ['Tap the opposite shoulder with one hand while keeping the hips as still as possible.', 'Alternate sides.'],
    cues: ['The goal is stillness in the hips — the hand moving is almost incidental.', 'Keep a straight line from head to heels throughout.'],
    mistakes: ['Letting the hips rock side to side with each tap.'],
    progressions: ['pallof-press'],
    regressions: [],
    substitutes: ['pallof-press'],
    defaultDose: { kind: 'reps', sets: 3, reps: 16, load: 'bodyweight' },
    restSeconds: 45,
    startPose: 'anti-rotation-press',
    endPose: 'anti-rotation-press',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'pallof-press',
    name: 'Pallof Press',
    kind: 'exercise',
    qualities: { 'trunk-anti-rotation': 1.0 },
    muscles: { 'obliques-external': 0.9, 'rectus-abdominis': 0.6, 'obliques-internal': 0.6 },
    equipment: ['band'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Anchor a band at chest height, stand side-on, band held at the chest with both hands.'],
    execution: ['Press the band straight out in front without letting the torso rotate toward the anchor.', 'Return under control.'],
    cues: ['Resist the twist — the whole exercise is about NOT rotating.', 'Brace the trunk before pressing.'],
    mistakes: ['Letting the shoulders rotate toward the band on the press.'],
    progressions: [],
    regressions: ['plank-shoulder-tap'],
    substitutes: ['plank-shoulder-tap'],
    defaultDose: { kind: 'reps', sets: 3, reps: 10, load: 'moderate' },
    restSeconds: 60,
    startPose: 'anti-rotation-press',
    endPose: 'anti-rotation-press',
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: 'bear-crawl-hold',
    name: 'Bear Crawl Hold',
    kind: 'exercise',
    qualities: { grip: 0.6, 'trunk-anti-rotation': 0.6, 'shoulder-stability': 0.5 },
    muscles: { 'rectus-abdominis': 0.6, 'deltoid-anterior': 0.6, 'forearm-flexors': 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Hands and toes on the floor, knees hovering an inch above the ground, back flat.'],
    execution: ['Hold the position, weight distributed evenly through the hands.', 'For the crawl variation, move one hand and the opposite foot forward at a time.'],
    cues: ['Keep the back flat like a tabletop, not piked or sagging.', 'Spread the fingers wide for a stable base.'],
    mistakes: ['Letting the hips rise up, which takes the load off the shoulders and core.'],
    progressions: ['farmers-carry'],
    regressions: [],
    substitutes: ['plank-shoulder-tap'],
    defaultDose: { kind: 'time', sets: 3, seconds: 30, load: 'bodyweight' },
    restSeconds: 45,
    startPose: 'isometric-hold',
    endPose: 'isometric-hold',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'farmers-carry',
    name: "Farmer's Carry",
    kind: 'exercise',
    qualities: { grip: 1.0, 'trunk-anti-rotation': 0.5 },
    muscles: { 'forearm-flexors': 0.9, 'trapezius-upper': 0.5, 'rectus-abdominis': 0.4 },
    equipment: ['dumbbell'],
    surface: 'gym',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Pick up a heavy dumbbell or kettlebell in each hand, standing tall.'],
    execution: ['Walk a set distance keeping the shoulders back and the torso upright.', 'Set the weights down under control.'],
    cues: ['Do not let the shoulders round forward or the torso lean to one side.', 'Take normal, controlled steps.'],
    mistakes: ['Shrugging the shoulders up toward the ears instead of keeping them packed down.'],
    progressions: [],
    regressions: ['bear-crawl-hold'],
    substitutes: ['bear-crawl-hold'],
    defaultDose: { kind: 'distance', sets: 3, metres: 30, load: 'heavy' },
    restSeconds: 90,
    startPose: 'carry',
    endPose: 'carry',
    unilateralEligible: true,
    unilateralPosePattern: 'carry',
    unilateralStabilityQuality: 'trunk-anti-rotation',
    tempoEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Endurance
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'continuous-easy-run',
    name: 'Continuous Easy Run',
    kind: 'exercise',
    qualities: { 'aerobic-base': 1.0 },
    muscles: { 'biceps-femoris': 0.5, gastrocnemius: 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Choose a flat, safe route or a track.'],
    execution: ['Run at a conversational pace — able to speak in short sentences throughout.', 'Keep the effort steady rather than surging.'],
    cues: ['This should feel easy. If you cannot hold a conversation, slow down.', 'Breathing should stay relaxed and nasal for most of the run.'],
    mistakes: ['Running too fast, which turns an aerobic session into an anaerobic one and blunts the intended adaptation.'],
    progressions: ['tempo-run'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'time', sets: 1, seconds: 1800, load: 'bodyweight' },
    restSeconds: 0,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'hill-sprint-repeats',
    name: 'Hill Sprint Repeats',
    kind: 'exercise',
    qualities: { 'anaerobic-capacity': 1.0, acceleration: 0.5, 'lower-body-strength': 0.3 },
    muscles: { 'gluteus-maximus': 0.8, 'biceps-femoris': 0.6, gastrocnemius: 0.6 },
    equipment: ['none'],
    surface: 'field',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Find a moderate hill, 10-15 seconds of running length.'],
    execution: ['Sprint hard up the hill for the full length.', 'Walk back down for recovery.'],
    cues: ['Hard effort on the way up — this should feel genuinely difficult by the last few reps.', 'The downhill walk IS the rest interval; do not rush it.'],
    mistakes: ['Jogging back down instead of walking, which does not allow full recovery between efforts.'],
    progressions: [],
    regressions: ['continuous-easy-run'],
    substitutes: ['shuttle-repeat-sprints'],
    defaultDose: { kind: 'time', sets: 8, seconds: 12, load: 'bodyweight' },
    restSeconds: 90,
    startPose: 'sprint-start',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'shuttle-repeat-sprints',
    name: 'Repeat Shuttle Sprints',
    kind: 'exercise',
    qualities: { 'repeat-sprint': 1.0, 'anaerobic-capacity': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'biceps-femoris': 0.6, gastrocnemius: 0.5 },
    equipment: ['cones'],
    surface: 'court',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Set two cones 20 metres apart.'],
    execution: ['Sprint from one cone to the other and back.', 'Walk or jog lightly for the rest period, then repeat.'],
    cues: ['Aim for the same effort on the last rep as the first — that consistency is what repeat-sprint ability actually measures.', 'Touch the line fully with a foot on each turn; shortcuts undercount the distance.'],
    mistakes: ['Starting too fast on the first few reps and fading badly by the end.'],
    progressions: [],
    regressions: ['continuous-easy-run'],
    substitutes: ['hill-sprint-repeats'],
    defaultDose: { kind: 'time', sets: 10, seconds: 6, load: 'bodyweight' },
    restSeconds: 24,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'tempo-run',
    name: 'Tempo Run',
    kind: 'exercise',
    qualities: { 'aerobic-base': 0.8, 'anaerobic-capacity': 0.5 },
    muscles: { 'biceps-femoris': 0.6, gastrocnemius: 0.6, 'gluteus-maximus': 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Pick a route or track where a steady pace can be held.'],
    execution: ['Run at a "comfortably hard" pace — able to speak only in short phrases, not full sentences.', 'Hold that effort for the full duration.'],
    cues: ['This is not a sprint — it is a controlled, sustained hard effort.', 'A pace you can hold steady beats one that fades over the last third.'],
    mistakes: ['Starting at sprint pace and fading long before the set duration is up.'],
    progressions: [],
    regressions: ['continuous-easy-run'],
    substitutes: [],
    defaultDose: { kind: 'time', sets: 1, seconds: 900, load: 'bodyweight' },
    restSeconds: 0,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Control
  // ═══════════════════════════════════════════════════════════════════════

  {
    slug: 'single-leg-balance-reach',
    name: 'Single-Leg Balance Reach',
    kind: 'exercise',
    qualities: { 'single-leg-stability': 1.0, 'hip-mobility': 0.3 },
    muscles: { 'gluteus-medius': 0.8, 'foot-intrinsics': 0.5, 'gluteus-maximus': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand on one leg, knee soft.'],
    execution: ['Reach the free leg and opposite hand out to the front, then to the side, then behind, tapping the floor lightly each time if possible.', 'Return to centre between reaches.'],
    cues: ['Keep the standing knee stacked over the foot, not caving in.', 'Move slowly enough to stay in control throughout.'],
    mistakes: ['Rushing the reaches, which turns a stability drill into a balance-losing hop.'],
    progressions: ['single-leg-rdl'],
    regressions: [],
    substitutes: ['single-leg-rdl'],
    defaultDose: { kind: 'reps', sets: 3, reps: 6, load: 'bodyweight' },
    restSeconds: 45,
    startPose: 'single-leg-balance',
    endPose: 'single-leg-balance',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'single-leg-rdl',
    name: 'Single-Leg Romanian Deadlift',
    kind: 'exercise',
    qualities: { 'single-leg-stability': 1.0, 'hip-mobility': 0.5, 'lower-body-strength': 0.4 },
    muscles: { 'biceps-femoris': 0.8, 'gluteus-maximus': 0.8, 'gluteus-medius': 0.6 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand on one leg, slight bend in the standing knee.'],
    execution: ['Hinge forward at the hip, extending the free leg straight behind for balance, until the torso is roughly parallel to the floor.', 'Return to standing under control.'],
    cues: ['Keep the hips square to the floor — do not let them open up.', 'Think of the free leg and torso as a straight lever hinging at the hip.'],
    mistakes: ['Rounding the lower back instead of hinging cleanly from the hip.'],
    progressions: [],
    regressions: ['single-leg-balance-reach'],
    substitutes: ['single-leg-balance-reach', 'trap-bar-deadlift'],
    defaultDose: { kind: 'reps', sets: 3, reps: 8, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'single-leg-rdl',
    endPose: 'single-leg-rdl',
    equipmentChain: [
      { tier: 'dumbbell', label: 'loaded', equipment: ['dumbbell'] },
      { tier: 'bodyweight', label: 'bodyweight', equipment: ['none'] },
    ],
    unilateralEligible: false,
    tempoEligible: true,
  },
  {
    slug: '90-90-hip-switch',
    name: '90/90 Hip Switch',
    kind: 'exercise',
    qualities: { 'hip-mobility': 1.0 },
    muscles: { 'deep-hip-rotators': 0.8, 'adductors': 0.6, 'gluteus-medius': 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Sit on the floor with both knees bent at roughly 90 degrees, one in front and one out to the side.'],
    execution: ['Rotate both knees together to switch sides, keeping the chest tall throughout.', 'Control the movement in both directions.'],
    cues: ['Move slowly — this is a mobility drill, not a race.', 'Keep the chest up rather than leaning back to help the legs swing.'],
    mistakes: ['Using momentum and hands on the floor to fling the legs over instead of controlling the rotation.'],
    progressions: [],
    regressions: [],
    substitutes: ['mobility-flow-series'],
    defaultDose: { kind: 'reps', sets: 2, reps: 10, load: 'bodyweight' },
    restSeconds: 30,
    startPose: 'mobility-flow',
    endPose: 'mobility-flow',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'mobility-flow-series',
    name: 'Lower-Body Mobility Flow',
    kind: 'exercise',
    qualities: { 'hip-mobility': 0.8, 'ankle-stiffness': 0.3 },
    muscles: { 'iliopsoas': 0.6, 'adductors': 0.6, 'gastrocnemius': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Open floor space, no equipment.'],
    execution: ['Move through a sequence of a world\'s-greatest-stretch lunge, a deep squat hold, and a straight-leg forward fold, spending 20-30 seconds in each position.', 'Repeat the sequence on the other side where a position is one-sided.'],
    cues: ['Breathe into each position rather than bouncing.', 'Only go as deep as feels controlled, not painful.'],
    mistakes: ['Rushing through positions instead of settling into each one.'],
    progressions: [],
    regressions: [],
    substitutes: ['90-90-hip-switch'],
    defaultDose: { kind: 'time', sets: 1, seconds: 300, load: 'bodyweight' },
    restSeconds: 0,
    startPose: 'mobility-flow',
    endPose: 'mobility-flow',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'scapular-wall-slide',
    name: 'Scapular Wall Slide',
    kind: 'exercise',
    qualities: { 'shoulder-stability': 1.0 },
    muscles: { 'trapezius-lower': 0.8, 'serratus-anterior': 0.7, 'trapezius-middle': 0.5 },
    equipment: ['wall'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand with the back, head and arms against a wall, elbows and wrists touching the wall in a goalpost position.'],
    execution: ['Slide the arms up the wall as far as possible while keeping contact with the wall, then back down.', 'Reset to the starting goalpost position between reps.'],
    cues: ['Keep the lower back flat against the wall — do not arch to fake more range.', 'Contact stays continuous throughout.'],
    mistakes: ['Losing wall contact with the elbows partway up, which means the shoulder blades are not actually moving correctly.'],
    progressions: ['prone-y-t-w-raise'],
    regressions: [],
    substitutes: ['prone-y-t-w-raise'],
    defaultDose: { kind: 'reps', sets: 3, reps: 10, load: 'bodyweight' },
    restSeconds: 30,
    startPose: 'vertical-pull',
    endPose: 'vertical-push',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'single-leg-ankle-hop',
    name: 'Single-Leg Ankle Hop',
    kind: 'exercise',
    qualities: { 'ankle-stiffness': 1.0, 'single-leg-stability': 0.4 },
    muscles: { gastrocnemius: 0.9, soleus: 0.7, 'foot-intrinsics': 0.4 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Stand on one leg.'],
    execution: ['Hop in place on that leg using mostly the ankle, minimal knee bend, quick light contacts.', 'Switch legs once the set is complete.'],
    cues: ['Same stiff, quiet-contact feel as a pogo hop, just on one leg.', 'Keep the hands relaxed at the sides for balance rather than flailing.'],
    mistakes: ['Bending the knee heavily to help absorb each hop, which shifts the work off the ankle.'],
    progressions: [],
    regressions: ['pogo-hop'],
    substitutes: ['pogo-hop'],
    defaultDose: { kind: 'contacts', sets: 3, contacts: 10, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'pogo',
    endPose: 'pogo',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'drop-landing-stick',
    name: 'Drop Landing and Stick',
    kind: 'exercise',
    qualities: { 'landing-mechanics': 1.0, 'single-leg-stability': 0.3 },
    muscles: { 'vastus-lateralis': 0.8, 'gluteus-maximus': 0.7, 'biceps-femoris': 0.5 },
    equipment: ['box'],
    surface: 'gym',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Stand on a low box or step, 20-30cm high.'],
    execution: ['Step off (do not jump up) and land on both feet.', 'Absorb through the hips and knees and hold the landing still for two seconds.'],
    cues: ['Land quietly — a loud landing means too much force is going straight into the joints instead of being absorbed.', 'Knees track over the toes on landing, not caving in.'],
    mistakes: ['Landing stiff-legged instead of absorbing through a good depth of hip and knee bend.'],
    progressions: ['countermovement-jump'],
    regressions: [],
    substitutes: [],
    defaultDose: { kind: 'reps', sets: 3, reps: 5, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'landing',
    endPose: 'landing',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'shadow-cutting-drill',
    name: 'Shadow Cutting Drill',
    kind: 'exercise',
    qualities: { 'change-of-direction': 1.0, deceleration: 0.5 },
    muscles: { 'gluteus-medius': 0.8, 'vastus-lateralis': 0.7, 'adductors': 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 13,
    supervisionLevel: 'SELF',
    setup: ['Open space, no markers needed — the cuts are self-paced rather than fixed to a line.'],
    execution: ['Jog forward, then plant hard and cut 45 degrees to a new direction on your own call.', 'Vary the direction and number of steps between cuts so the pattern stays unpredictable.'],
    cues: ['Plant on a flexed, athletic ankle and knee, never a locked-out leg.', 'React and cut — do not pre-plan the pattern so far ahead that it stops being reactive.'],
    mistakes: ['Rounding every cut the same way instead of genuinely varying the angle and rhythm.'],
    progressions: ['5-10-5-shuttle'],
    regressions: [],
    substitutes: ['lateral-shuffle-cone-drill'],
    defaultDose: { kind: 'time', sets: 4, seconds: 20, load: 'bodyweight' },
    restSeconds: 60,
    startPose: 'cut',
    endPose: 'cut',
    unilateralEligible: false,
    tempoEligible: false,
  },
  {
    slug: 'in-place-suicide-sprints',
    name: 'Suicide Sprints (Self-Paced)',
    kind: 'exercise',
    qualities: { 'repeat-sprint': 1.0, 'anaerobic-capacity': 0.6 },
    muscles: { 'gluteus-maximus': 0.7, 'biceps-femoris': 0.6, gastrocnemius: 0.5 },
    equipment: ['none'],
    surface: 'anywhere',
    minAge: 14,
    supervisionLevel: 'SELF',
    setup: ['Pick any open stretch of ground at least 15 metres long — a sideline, a fence line, or just open field; no markers required.'],
    execution: ['Sprint out a set distance, turn, and sprint back to the start.', 'Walk for the rest period, then repeat, matching effort every rep.'],
    cues: ['Full turn and touch the ground or line at each end — do not round it off short.', 'Hold the same effort on the last rep as the first.'],
    mistakes: ['Fading badly on the later reps because the early ones were run too hard.'],
    progressions: [],
    regressions: [],
    substitutes: ['shuttle-repeat-sprints', 'hill-sprint-repeats'],
    defaultDose: { kind: 'time', sets: 8, seconds: 8, load: 'bodyweight' },
    restSeconds: 30,
    startPose: 'sprint-cycle',
    endPose: 'sprint-cycle',
    unilateralEligible: false,
    tempoEligible: false,
  },
];
